### ISSUE TITLE
[Feature Request] Track which classes provide access to each spell and display which character class provides each spell on the spellbook tab

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1012]
Originally in GitLab by @crash1115

Pain Point: A character with two spellcasting classes that use the same preparation mode (Always Prepared/Spells Known vs Prepared) has no way to easily distinguish which spells come from which class.

Current Workaround: Set all the spells from one class as Prepared, and all the spells from the other as Always Prepared, and let the color-coding some sheet modules provide do the work. This stops being a viable solution if you have domain spells which are always prepared, or have more than 2 casting classes.

Potential Solution: Add a "Source Class" field or something similar on the Spell item sheet, and display that field... Somewhere. Preference would be as a column in the Spellbook tab, but that's pretty crowded already.

**Comment by Zanderaf** [comment]
An extra column could be nice, could use it to track what advancement a spell came from, such as an advancement called "Mage Hand Ledgermian" that adds the mage hand cantrip to a characters spellbook would have the name of the advancement in that extra column, or just have a field in the Grant Items advancement type that automatically sets it.

_**Main example I could think of would be something like D&D Beyond.**_

![Capture](https://github.com/foundryvtt/dnd5e/assets/65571170/eb0466d8-460f-43c0-9fef-e8d237bc82ad)

**Comment by krbz999** [comment]
Spell lists are a different issue, but all that is lacking from this thread is the display of the origin class on the actor sheet, not just the spell sheet.

**Comment by Fyorl** [comment]
Putting the source class in the spell's subtitle seems like a reasonable solution. It might get a bit crowded with the limited uses in there as well though.
