### ISSUE TITLE
[Active Effects] Add functionality to specify the conditions under which an active effect is transfered from an item to an owning actor (i.e. when the item is equipped or attuned)

### ISSUE THREAD

**Issue by schultzcole** [foundryvtt/dnd5e#1020]
Currently, core Active Effects owned by an item have an option for "Transfer Effect to Actor", which applies the active effect to an actor when that item becomes owned by that actor.

It would also be useful to have a 5e specific setting which would determine whether the item must be "equipped" or "attuned" by the actor for the effect to transfer.

There could be multiple valid user experiences to expose this functionality.

Probably the simplest of these would be to have 3 checkboxes: "Transfer Effect to Actor", "Transfer Effect to Actor when equipped", and "Transfer Effect to Actor when attuned".

Another option would be to have a single "Transfer Effect to Actor" checkbox, then a drop down selector ("transfer condition") to determine the circumstances of the transfer, which could have possible values of "Always", "When Equipped", and "When Attuned".

The equipped or attuned state of the item could then toggle the "inactive" state of the effect on the actor.

**Comment by Fyorl** [comment]
This was handled differently via use of the `ActiveEffect#isSuppressed` property.
