### ISSUE TITLE
Item._getUsageUpdates() should handle more cases

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1023]
Originally in GitLab by @CarlosFdez

So currently, Better Rolls reimplements some of the consumption logic due to some pieces of missing functionality.
- If consumeQuantity is true and consumeUsage is true, then once an item reaches 0 quantity it will continue to have uses. An item reducing to zero quantity should also set the number of uses to zero.
- If consumeQuantity is true but consumeUsage is false, quantity is not consumed.

The second is less important (It is not likely to come up), but the first is necessary for any sort of quantity consumption logic that does not involve auto destroy, which is a feature that should probably be considered at some point.

**Comment by teroparvinen** [comment]
I will expand on this issue to note that `_getUsageUpdates` also does not support consuming a set number of uses.

WIRE, for example, contains an implementation of Lay on Hands that allows the player to set the healing done using a slider and several magic items in dnd consume a varying number of uses depending on which of its abilities is used, and this currently requires a custom implementation to either duplicate this method or to piggy back it with another processing layer.

**Comment by Fyorl** [comment]
Needs to be reframed in the wake of the consumption refactor.
