### ISSUE TITLE
Have a way of making spells hit in succession to different individual targets.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1067]
Originally in GitLab by @thingscouldgetdicey1

i dont know if this is a core issue or a 5e issue.

the issue i have is that if i want a spell like green flame blade to proc and make the damage go from one target to another theres no way currently to select targeting in succession so that a spell can do secondary damage to another target than the intial target. what i would like to see is a way of targeting with doing an order system. this would also be useful for things like magic missle and other spells that do damage in succesion. the idea would be if you enable a succession mode it would have a target indicator with a number of the order of how tokens take damage. or the ability to be able to do this for other module developers like midi qol. id like a space in the spells details that enables successive targeting with possibility for seperate damage values or to keep the same damage value. this would speed up the workflow of using spells like magic missle without having to use the spell slot tick box. or with green flame blade to accurately target the right creature/token with the correct secondary damage.

**Comment by Fyorl** [comment]
This is maybe adequately covered by activities, or perhaps will be covered by follow-on activities. I'm marking this as done, and any missing functionality can be re-raised as a more targeted issue.
