### ISSUE TITLE
Add a way for Feats and Class Abilities to make permanent modifications to an actor

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1068]
Originally in GitLab by @wildcat.jason

It would be nice to have a way for Feats and Class Features to make a permanent change to an actor when added to them, that doesn't use the active effects system.  My thought here is to actually modify the actors sheet when the feat or class ability is added, rather than having an active effect.  As feats and class features are basically permanent once added, you dont need the functionality that active effects provides, and also remove the performance impact of using active effects.

This would also provide 2 further benefits, in the rare case you would need to remove a feat or class feature, you would know what to remove (or the system can be built to support removing the changes that were applied).  And second it would remove the need to make manual modifications to the sheet when adding feats or class features.

**Comment by Fyorl** [comment]
I believe this request has been covered by the implementation of the Advancement system.

**Comment by MaxPat931** [comment]
Looks like this will be covered for Background and Class Items with https://github.com/foundryvtt/dnd5e/pull/2016 and https://github.com/foundryvtt/dnd5e/pull/2158 but neither of those mention adding Advancements to Feat item types (which would be necessary for setting up feats like Heavy Armored which gives +1 STR and prof in Heavy Armor)

**Comment by Zanderaf** [comment]
I thought that kind of would be covered with #1845
