### ISSUE TITLE
Additions to Actor proficiencies should automatically update current owned Items which should now be flagged as proficient.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1082]
Originally in GitLab by @denisPoifol

What happened:
If my character is equiped with a leather armor and its proficiency to light armors is not yet set, when setting it the armor is still marked as "not proficient"

What I expected to happen:
Ideally setting light armor proficiency to the character would make him proficient with any light armor he owns

Additional notes:

This is also true when :
- dealing with a weapon
- removing proficiency and the object was marked as proeficient

System version:
Foundry v0.7.9
D&D5e v1.2.4

**Comment by djinnstar** [comment]
I think I have a working commit that just needs refactoring, JSDoc annotations, etc. - should be ready to submit the PR in a day or so!

**Comment by arbron** [comment]
Based on discussion in the original pass at this, we decided that rather than storing proficiency on the items, we would automatically calculate it during `prepareData` while adding a `proficiencyMode` property that allows an item to be set to `"Automatic"`, `"Always Proficient"`, or `"Never Proficient"`.

This solution is currently blocked by #774

**Comment by djinnstar** [comment]
We might want a bit more flexibility depending on the final solution of #774. `“Automatic`, `“Always”`, and `“Never”` don’t allow the user to specify double/half proficiency, and it might be better to have `proficiencyMode` be a value from an enumeration, maybe something like `config.dnd5e.proficiencyValues.{expertise|half|full|none|auto}`. It would also give devs an easy way to modify the options and add something else (maybe like 1/3rd proficiency - nonsense in SRD RAW but maybe something a user might want to do).
