### ISSUE TITLE
a way to track and give bardic inspiration

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1132]
Originally in GitLab by @thingscouldgetdicey1

ideally id like a system wide fix to enable giving people die that they can roll. 

with bardic inspiration you are giving a player a die to roll and it has 10 minutes as to when it can be used. most of the time it is awarded during combat and 10 minutes can be a long time. so id like a way for players to firstly give the dice to someone from one of there uses of the feature and for it to track on a character sheet that they have the bardic inspiration available.  and for a player to indicated in a chat card upon use of bardic inspiration that it has been used so its contextualised towards the bardic inspiration die. 

currently bardic inspiration is written and imported into foundry as damage to attack a target. 

ideally id like a mechanism that would allow for rolls to subtract or add the bardic inspiration to them i.e spell attacks and saves for other module uses or for other modules to pull from this functionality so that for people like myself it can be factored into the roll via foundry and get the according results after and before a roll.

**Comment by Fyorl** [comment]
I think this is now achievable with enchantments and rider items.
