### ISSUE TITLE
Suggestion: Item damage rolls set option.flavor to the damage roll damage type of the item damage lines

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1146]
Originally in GitLab by @tposney

When rolling damage for an item there is no way to recover the damage type information from the roll result. 

For ad hoc rolls doing xd5[bludgeoning] will tag the flavor to the roll term.

If I have an item with two damage formula  
1d8 + @mod   bludgeoning
2d6          cold

It would be convenient (for me and probably no one else) if the roll terms were each tagged with the appropriate damage type as the flavor for the term
i.e. 1d8 DiceTerm - flavor bludgeoning
     +@mod NumericTerm - flavor bludgeoning
     2d6 DiceTerm - flavor cold

Ideally there would be a damage type that is attached to every damage roll term, but in lieu of that flavor makes a good proxy.

**Comment by Fyorl** [comment]
I think we want to align on #1818 for accomplishing this.
