### ISSUE TITLE
[Bug] Variables under Active Effects do not update upon editing

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1155]
Originally in GitLab by @MrVauxs

I wanted to keep the title short so to explain it fully, Active Effects used to revert back any edits an user might have done to the sheet if an active effect applied to the modified variable in question. 
For example, you have armor that grants you a total of 15 AC, and the user changes their AC to 17.
The AC immediately reverts back to 15 the moment the player clicks enter or otherwise accepts their modified value.
This used to happen, but currently the player instead gets a graphical glitch where their modified value is shown (17), but in reality the value itself is still the original (15).
This fixes itself on closing and reopening the sheet.

Tested on Foundry 0.8.6 and dnd5e 1.3.3. The first error in console appears upon editing and accepting the value. The second is upon closing the sheet.

![image](https://gitlab.com/foundrynet/dnd5e/uploads/374be11e2354317278f83b40a59bb414/image.png)

**Comment by Fyorl** [comment]
Editing values affected by an active effect is now disabled.
