### ISSUE TITLE
Effect bonuses to saving throws are combined as strings before being applied

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1157]
Originally in GitLab by @javalar

# Steps to reproduce:
1. Create a new effect on a character which adds +1 to saving throws (`data.bonuses.abilities.save`) and activate it.
2. Create a second effect on the same character which does the same and activate it.

# Expected behaviour:
Character has a +2 bonus to saving throws.

# Actual behaviour:
Character has +11 bonus to saving throws.

This is probably because the bonus numbers are saved as strings and added together (as strings) before adding to a number (where the string is implicitly cast to a number before being added).

**Comment by krbz999** [comment]
This was changed several versions ago now.
