### ISSUE TITLE
Enable for resource consumption in a feature to predefine the consumed target

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1185]
Originally in GitLab by @jobo93

It would be great to have the ability to predefine which attribute should be consumed with a feature. For example "consume":{"type":"attribute","target":"spells.spell1.value","amount":1}.
So the the manual editing part is not needed any more for features, which are consuming one specific attribute, when players gain that type of features.

**Comment by arbron** [comment]
Better defined here: #1856
