### ISSUE TITLE
Load Capacity in Kilo is not accurate

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1226]
Originally in GitLab by @flyli1973

Following the rules, Maximum load capacity should be equal to Strenght x 7.5.
Actually, with a Strenght equal to 17. Max weight should be 127.5 Kg and not 115.6

This has also an impact on Lightly and Heavily encumbered rules. 
Lightly = Strenght x 2.5
Heavily = Strenght x 5

I did the test with all module disable. 
Could you please correct this ?

Best regards

**Comment by Ciack** [comment]
Is there by any chance any news on this issue?

**Comment by Fyorl** [comment]
Leaving this open as it contains a lot of discussion, but it's the same issue as #1228 I believe, so they should both be solved in tandem.
