### ISSUE TITLE
Immediately evaluated inline rolls which occur within the context of an Actor Sheet (or owned Document sheet) should obtain that Actor's roll data object for the purposes of evaluation

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1238]
Originally in GitLab by @unsoluble1

(New ticket for this rather than resurrecting foundryvtt#4631)

Obtain and render rollData for *non-deferred* inline rolls, so that their full results may be displayed inline with text in places like Description fields, etc).

"The target makes a `[[1d20 + @abilities.dex.mod]]{Dexterity Check}`", for example.

**Comment by mhoerter** [comment]
Hello! Is this feature still planned? It always seemed peculiar that you can put [[/r @skills.ath.total]] into an item's description, and be able to click it and output the correct value to chat, but if you instead just type [[@skills.ath.total]] it shows as 0 in the item's description.
