### ISSUE TITLE
UI Change: Reorder dropdown for Equipment Usage

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1254]
Originally in GitLab by @sharkbruhaha

The dropdown for "Equipment Usage" starts with "None" this makes it immediately wipe out user input in corresponding fields.
The issue is that when inputting information and tabbing through fields, this is the first element so wipes out your work.

Request: Move "None" to the bottom of the list, so as to not impede tab workflows.

(this is both in the "Target" and "Range" rows)

**Comment by Fyorl** [comment]
This is either done or not applicable anymore, I'm not entirely sure. Closing it as N/A for now.
