### ISSUE TITLE
Spell Duration options are missing "Until Dispelled" and "Until Dispelled or Triggered"

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1258]
Originally in GitLab by @DrYoshiyahu

There are a dozen spells in the game that have a duration of "Until Dispelled" or "Until Dispelled or Triggered." These spells in the SRD compendium use "Permanent" instead, which is perhaps some form of compromise, even if strictly inaccurate.

If that is the case, and "Permanent" is supposed to replace the two of them, then might I suggest at least giving the option to input plain text as a duration, rather than users relying on the dropdown menu, for the duration purists out there.

**Comment by arbron** [comment]
#### Until Dispelled
- Arcane Lock
- Continual Flame
- Hallow
- Imprisonment
- Instant Summons
- Magic Jar
- Magic Mouth
- Programmed Illusion
- Sequester
- Simulacrum

#### Until Dispelled or Triggered
- Glyph of Warding
- Symbol
