### ISSUE TITLE
Implement the Variant Encumbrance rule from the SRD

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1276]
Originally in GitLab by @ben-barbour

From page 80 of the [SRD v5.1](http://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf).

It would also be great if we could alter the STR multipliers and maybe supply optional active effects for the thresholds, but that might be module territory.

**Comment by benbarbour** [comment]
I've started taking a stab at this. Right now it's just cosmetic changes: the weight bar in the inventory changes color and tooltips are added over the bar for each encumbrance level. I've got a couple of questions: 

1.Would it be appropriate to add active effects (or optional active effects) for the encumbrance levels. Should they actually reduce speed?
2. I probably need help choosing good colors, if color changes for the weight bar are desirable at all... I don't do a lot of UX/UI work.

I think that if there are no status effects (or at least color changes on the weight bar) then maybe this shouldn't be done in the system. It would be a whole system setting to turn on some tooltips over the three weight bar sections, and people might not even notice.

**Comment by aaclayton** [comment]
> Right now it's just cosmetic changes: the weight bar in the inventory changes color and tooltips are added over the bar for each encumbrance level. I've got a couple of questions:

I think that sounds like a good place to start.

> Would it be appropriate to add effects (or optional effects) for the encumbrance levels. Should they actually reduce speed? I don't think they can add disadvantage.

I think that's a good idea to explore, adding a status effect when the user is encumbered would be a good integration. Depending on the size of the change, it might be better to make that a follow-up MR to the cosmetic changes for simplicity of review and merge.

> Are color changes for the weight bar desirable, and if so, which colors?

I think color changes are a good idea but I would suggest two general tenets:

1. Make sure that information is not provided *only* using color, there needs to be some other indication also.
2. Make sure the color palette is not dramatically in contrast with the rest of the UI of the sheet. I'm not sure exactly which colors to suggest, but perhaps a light blue when unencumbered that translates towards a darker purplish-blue as you become more heavily encumbered? I'm not dead set on that and open to other choices. Regardless of which way we go it would be advisable to make those colors CSS variables so that modules can override the color palette with alternate choices.

**Comment by benbarbour** [comment]
Got a couple of questions about this.

1. Should I add colour and/or tooltips to the sheet when the variant rule is not in use? There are only two states in that case: "under carrying capacity" and "exceeding carrying capacity".
2. How should this variant rule interact with the Vehicle sheet, if at all? I don't think whatever rules it's based on are in the SRD, but please correct me if I'm wrong.

**Comment by benbarbour** [comment]
k, the current PR has everything but effects in it. I'll do those in another PR should this one be merged.
