### ISSUE TITLE
Create (Active) Status Effects for all Conditions

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1279]
Originally in GitLab by @akrigline

At the moment the default set of effects that come with Foundry Core does not completely cover the Conditions list of 5e. We should add the missing ones in `CONFIG.statusEffects`.

- [x] Blinded
- [ ] Charmed
- [x] Deafened
- [ ] Exhaustion
    - [ ] Level 1
    - [ ] Level 2
    - [ ] Level 3
    - [ ] Level 4
    - [ ] Level 5
    - [ ] Level 6 (Death)
- [x] Frightened
- [ ] Grappled
- [ ] Incapacitated
- [ ] Invisible
- [x] Paralyzed
- [ ] Petrified
- [x] Poisoned
- [x] Prone
- [x] Restrained
- [x] Stunned
- [x] Unconscious

Some additional status effects which would be extremely useful that are not strictly conditions:
- [ ] Concentrating

---

Additionally, it would be ideal if the effects conditions which can be automated through active effects are.

For example: Grappled, Paralyzed, Petrified, Prone, Restrained, Stunned, and Unconscious all set the creature's speed to 0, we can affect that like so:

| Attribute Key | Change Mode | Effect Value |
| -------- | -------- | -------- |
| `data.attributes.movement.walk`     | Override     | `0`     |
| `data.attributes.movement.fly`     | Override     | `0`     |
| `data.attributes.movement.swim`     | Override     | `0`     |
| `data.attributes.movement.burrow`     | Override     | `0`     |
| `data.attributes.movement.climb`     | Override     | `0`     |

**Comment by JPMeehan** [comment]
Found a neat collection of CC icons for dnd5e https://www.elderberry-inn.com/icons
