### ISSUE TITLE
Add a spell preparation mode for ritual only spells

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1280]
Originally in GitLab by @Pjb518

Certain characters have spells that can only be cast as rituals. Two examples are Warlocks with the Book of Ancient Secrets Invocation and characters with the Ritual Caster feat.

For ease of organisation, I suggest we add a "Ritual Book" or "Ritual Only" preparation mode so that these spells can be kept separate from any existing spellcasting sources the character currently possesses.

**Comment by JPMeehan** [comment]
One comment here: It would be nice if this could also handle the Wizard's spellbook, as that allows you to cast unprepared spells IFF they are rituals. It's possible the current features are sufficient.

**Comment by etiquettestartshere** [comment]
> @etiquettestartshere Can you comment on the original issue for this so I can assign it to you? (#1280)

#:wave:
