### ISSUE TITLE
Distinguish between prepared and unprepared cantrips on the core sheet

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1282]
Originally in GitLab by @Pjb518

Tasha's Cauldron of Everything introduced a new wizard feature called Cantrip Formulas. This feature allows wizards to change their known cantrips on a day by day basis.

It would be convenient for players to be able to leave all of their frequently chosen cantrips on their sheet, but there's currently no way to indicate which of these are prepared on a given day.

Now that this degree of cantrip preparation versatility exists in the game, I think we should support a visual indication of cantrip preparation on the core sheet. This feature already exists on 3rd party sheets, such as Tidy.

**Comment by MrBrentRogers** [comment]
yes, this would be super convenient! 
Especially for some 3rd party games where you have a number of cantrip live abilities that can be toggled on/off (Arcanis 5e Psion).
