### ISSUE TITLE
Improve visibility of active spellbook filters

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1310]
Originally in GitLab by @MaxPat931

The small line under the filter options can be difficult to see, or may not be pronounced enough to call attention that it is active. 
I would recommend additional visual indicators to inform users when a filter is active, such as bolding the text and/or highlighting the background area of that filter:

current
![image](https://gitlab.com/foundrynet/dnd5e/uploads/464dfb83fdb8ef3e46e063aa51f63b02/image.png)

Proposed
![image](https://gitlab.com/foundrynet/dnd5e/uploads/de456a35b6d8ea81c4c65b0dc502eda9/image.png)

slightly related to https://gitlab.com/foundrynet/dnd5e/-/issues/1281

**Comment by Fyorl** [comment]
Closing this for now. We won't be making UI changes to the legacy sheets, and the v2 sheets use different filter styles now.
