### ISSUE TITLE
Add more extensive configuration for initiative checks

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1316]
Originally in GitLab by @Pjb518

1.5.x introduces detailed configuration options for individual skills and ability check bonuses, but this release doesn't add the same options for initiative bonuses.

In a future release, I think we should add a similar configuration window for initiative, where players can set arbitrary initiative bonuses, including dice terms. Currently, only static bonuses can be added, and those bonuses cannot have flavour text. Attribute references also cannot be used in the modifier field.

Recent official releases have also indicated that WotC plans to use initiative proficiency as a mechanic going forward, so it's worth including proficiency level as part of this new configuration. See the Oath of the Watchers Paladin and Harengon race as examples.

**Comment by LiamFallon213** [comment]
I am working on the Init system right now, I will see if I can add this on to what I'm doing.
