### ISSUE TITLE
Add information about cantrips known on class items alongside spellcasting ability and spellcasting progression

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1341]
Originally in GitLab by @iaguastalli

Currently, `data.spellcasting.progression` can be tied up to `game.dnd5e.config.spellProgression` to calculate the slots available for each level (alongside the max spell level they can cast, infered from that same array), but there's no information about cantrips that I can find.

First idea that comes to mind would be adding another key on `{classItem}.data.spellcasting` named probably cantrips, that will have a 1-20 array similar to `game.dnd5e.config.spellProgression`, but containing only the number of cantrips per level.

I understand this can't be coalesced with the spellProgression matrix as the cantrip count per level is not consistent between classes (e.g. Bard lv1 having 2 cantrips, Cleric lv1 having 3 cantrips, and Sorcerer lv1 having 4 cantrips), but the full spell progression might be merged into the class, but I don't know where else this might be used and if it would make sense to shift all those usages to an eventual progression completely inside the class.

**Comment by Fyorl** [comment]
Handled by scale value advancements.
