### ISSUE TITLE
Support minimum roll values on skill checks

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1350]
Originally in GitLab by @MrPrimate

The Bard College of Eloquence has the feature Silver Tongue which allows:

> When you make a Charisma (Persuasion) or Charisma (Deception) check, you can treat a d20 roll of 9 or lower as a 10.

I would like to be able to set a "minimum value" for individual skills, possibly as part of the skill schema.

**Comment by arbron** [comment]
Minimums and maximums are now fully supported!
