### ISSUE TITLE
Assign Spells by Class

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1351]
Originally in GitLab by @danz5000

Might it be possible to assign spells to class, and thus assign spell attacks and DCs according to the class? That way we could organize how many spells we have according to which class, which class it's assigned to when multiclassing, and other quality of life improvements.

It would also allow us to differentiate having a Bloodwell Vial (applies only to sorcerer spells) vs. a Moon Sickle (applies only to druid spells) vs. a Wand of the Warmage (applies to all spell attacks).

**Comment by absymylyar** [comment]
I'm working on it now
