### ISSUE TITLE
Feature suggestion: Master Variant Item/Feature/Attack

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1360]
Originally in GitLab by @zarhog1

So much like we have the ability to change the master variant of a Token if they are linked i have a bit of a different idea lets add that feature to Items, Features, and attacks (IFO for short). The master variant would be kept in the compendium and you would be able to like them in there settings. once dose you may only change the details on the master variant in the compendium, and not the one which it is linked to, excluding the option to unlink. 

what would this do?
once linked any changed made to the master would automatically be made to the slaved / linked IFO.

why?
a lot of creatures, classes and players share exact copies of IFO, this means that data is being taken up by there copies, doing this would free up precious server space.

in addition making mass changes on large servers or even in games when you want to set everything up can be a pain say you want to mass change 1 IFO that is on 100 unique creates but the IFO is exactly the same normally that would take hours but by allowing us to have this feature it would take 1-2 mins at most since you only need to change the Master copy in the compendium.

This could also set the path for Automation in the future with reguards to imporing D&D beyond content and auto leveling using pre-set scematics. since the data would be pulled from the compendium it would make the leveling much easier, this also means that all the players would technicaly need is a compendium copy of a IFO for auto levelers to pull from and keep iot correct.

Extra?
un-linking the salve IFO would leave it un-dited in its previouse state allowing you to easily make a unique variant.

p.s. Sorry about the spelling Dyslexia

if you are confused about what im talking about im available to talk Zarhog1@gmail.com

**Comment by Fyorl** [comment]
Not something to be solved in the dnd5e system. I can see there is already a copy of this issue on the main repo under foundryvtt/foundryvtt#6193
