### ISSUE TITLE
[Feature] Automated conversion of PC sheet to/from NPC sheet

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1367]
Originally in GitLab by @Merudo

Frequent occurrences:

- A player takes over a NPC.
- A PC leaves the party, and becomes a NPC.
- A NPC becomes important to the story, and requires features not available to NPCs, such as [Death Saving Throws](https://gitlab.com/foundrynet/dnd5e/-/issues/456)

All of these require a PC sheet to be converted to a NPC sheet, or a NPC sheet to converted to PC sheet. At the moment, it is not possible to convert between the two types, and the new sheet must be rebuilt from scratch.

It would be great to have an option to transform a character sheet to the other type.

**Comment by Fyorl** [comment]
We have done some significant work to improve the experience for long-lived NPCs that might travel with the party. Their sheets support death saves, as well as having class levels. Transforming their actual Actor type would be very messy by comparison so I think we should consider this complete.
