### ISSUE TITLE
Suggestion: Rename "Prepared" spell filter to "Available", then change logic of the filter

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1390]
Originally in GitLab by @zjennings1

In the spellbook on the character sheet, I would propose changing the name of the "Prepared" filter to "Available", or "Able to Cast", or "Available to Cast" or similar. Then include the following in the filter:

- All cantrips
- All prepared spells (even if they don't have slots, so they can be upcast)
- All at-will spells for which the PC has uses remaining
- All pact magic spells for which the PC has slots (I have no experience with pact magic. There may be nuances I'm not aware of.)
- All innate spellcasting spells

A minor issue that brought me to this suggestion:

At-will spells don't show up in the "prepared" filter unless they are marked as prepared in the spell details.

**Comment by Fyorl** [comment]
Closing this in favour of #2905 as it has a bit more discussion.
