### ISSUE TITLE
Advancement Type: Ability Score Improvement

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#1403]
This advancement can be used to represent an ability score change performed by `race` or `background` (for support of D&D One content) and can be used to indicate at which levels a `class` grants an ability score improvement with optional feat support.

## Level Up Interface

For classes, first the player would be asked whether they wish to improve their ability scores or add a feat. Since feats are an optional rule, the feat option can potentially be disabled using a system setting. For races and backgrounds, they will be taken directly to the ASI interface.

If they choose to take the ASI, they will be shown a list of their current ability scores and given the option to distribute up to two points among them.

If they choose to take a feat, they will be presented with a drop area where they can place the new feat.

## Configuration

The `points` property is a number indicating how many points a player can allocate among their ability scores.

The `fixed` property is an object containing how many points are allocated to specific ability scores.

One or both of these properties must be set. The system will also support granting fixed to one score and still allocating points to another (aka you get a +2 to dexterity and one other point to allocate as you wish).

``` json
{
  "points": 2
  "fixed": null
}
```

```json
{
  "points": null,
  "fixed": {
    "dex": 2,
    "con": 1
  }
}
```

## Value

The value object contains a `selected` property indicated whether the player selected the ability score improvement (`"asi"`) or the feat (`"feat"`).

If they chose the ASI then there is an `improvements` object containing the keys of the ability scores they improved and a value with the amount they improved that score. This will include any changes made by fixed values because they might have been capped by the maximum for that score.

```javascript
{
  selected: "asi",
  improvements: {
    cha: 2
  }
```

If a feat is chosen, the object contains a `feat` property containing another object with the origin UUID of the feat and the ID on the actor. This structure intentionally mirrors the structure proposed for item grants (#1400) and choices (#1401) to hopefully be able to reuse some code.

```javascript
{
  selected: "feat",
  feat: {
    "hpLNiGq7y67d2EHA": "Compendium.dnd5e.classfeatures.Dop1RcU5UdhSVLYS"
  }
}
```

## Future Directions

A more advanced items type and compendium scanning system would allow for a list of feats to be presented to the player built automatically from the various compendiums available rather than require the user to drag an item in manually.

**Comment by kaelad02** [comment]
+1 on the compendium scanning option. The SRD only comes with one feat so relying on #2015 feature isn't very helpful. In fact, compendium scanning should be extended to that since we have the feature types and subtypes. Would make it really easy to include other fighting styles, eldritch invocations, etc. that aren't in the SRD without having to modify the SRD class feature to find them.
