### ISSUE TITLE
Character Sheet Formatting Issue

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1410]
Originally in GitLab by @voidstate

![image](https://gitlab.com/foundrynet/dnd5e/uploads/911163008f93e18b0cadbe8d4a4219fc/Screenshot_2022-01-18_at_23.18.36.png)

As shown in the screenshot, the slots on my players' character sheets have the fonts partly hidden.

Browser: Safari 15.2, OSX 12.1

**Comment by Fyorl** [comment]
Obsoleted by the v2 sheet design.
