### ISSUE TITLE
NPCs need custom resource pools for features such as the abjurer's Arcane Ward

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1434]
Originally in GitLab by @DrYoshiyahu

There's currently no good way to set up an NPC token's resource bars to keep track of a feature like Arcane Ward.

For those that don't know, the [abjurer](https://www.dndbeyond.com/monsters/abjurer)'s Arcane Ward is a pool of hit points that exist at all times and are separate from the creature's hit points and temporary hit points.

Ideally, this resource should be tracked on the NPC's token the same way their health is, since it will constantly be in flux, up and down, over the course of a fight. A player character would normally use custom resources for this kind of thing—a feature that NPCs need, for the exact same reason.

There are a number of ways one might think to try to make it work using the current options, but none of them are suitable for this use-case.

"Limited Uses" can't be edited from a token's resource bar, "Resource Consumption" must be tied to an existing attribute of the NPC, the hit points can't be increased beyond the creature's maximum hit points, and even if you were able to track temporary hit points with resource bars, it would clash with _actual_ temporary hit points, which should be tracked independently.

**Comment by Fyorl** [comment]
Item limited uses can now appear on token bars so this use case is well enough covered.
