### ISSUE TITLE
Lair Action init default value should be 20

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1443]
Originally in GitLab by @dleet

The default lair action init value for NPC actors should be set to 20, since that is typically what is used in 5e. The default value is currently 0.

**Comment by Fyorl** [comment]
Whether a creature has a lair action or not is controlled by the 'uses lair action' checkbox. We explicitly set a `placeholder` value of `20` for lair initiative but that is ignored as the default `template.json` value is `0`. Either it should be `null` in order for the placeholder to be visible, and we make sure the code treats `lair.value: true` + `lair.initiative: null` as `20`, or we set the default in `template.json` to `20`.
