### ISSUE TITLE
When polymorphing the Revert Transformation button has issues

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1463]
Originally in GitLab by @revilowaldow

# There are a few things going wrong:
- When a token is polymorphed, the revert transformation button does not immediately appear on the new sheet.
- The token sheet must be closed and reopened for it to appear.
- Once the polymorphed actor is reverted, reopening the sheet makes the revert transformation button appear again, and again, and again.
- Dragging the actor from the side bar also uses the wrong art assets in a range of scenarios related to polymorphing.
- All of these issues are visible in the video below which was recorded in a clean world.
- There are no console errors.

![image](https://gitlab.com/foundrynet/dnd5e/uploads/040cb6e8a5d972998f98552e8e78b691/Media1.mp4)

**Comment by Fyorl** [comment]
I believe this has been fixed as part of #1823. The actor image issue when dragging from the sidebar is a core foundry issue that is currently blocked: foundryvtt/foundryvtt#5896
