### ISSUE TITLE
Unnecessary System Data Migration if world has no settings (should use `systemVersion` from manifest)

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1470]
Originally in GitLab by @arcanistzed

I'm working on a world package for distribution and I am not including the `settings.db` with my package. I have noticed that there is always a migration whenever I install it despite it not needing one:
```js
const NEEDS_MIGRATION_VERSION = "1.5.6";
const currentVersion = "";
isNewerVersion(NEEDS_MIGRATION_VERSION, currentVersion) // returns true
```
A solution for this would be to provide a fallback for the current version from `game.world.data.systemVersion` so that it isn't an empty string.

**Comment by arcanistzed** [comment]
I think an easy and simple solution to this is that it would read the world flags if present and then fallback to the current behavior. I'll create a PR with what that could look like.

**Comment by arbron** [comment]
That is probably a good solution, but I think we’d want to reverse it and check the settings value first, and then the data value. That way once migrations have been applied they will update the saved settings value to ensure they aren’t applied a second time.
