### ISSUE TITLE
Add other tables from the SRD

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#1471]
There are a variety of roll tables mixed throughout the SRD that would be useful:

### Spells
- Confusion
- Reincarnate

### Items
- Armor of Resistance*
- Bag of Beans
- Gray/Rust/Tan Bags of Tricks
- Candle of Invocation*
- Carpet of Flying*
- Efreeti Bottle
- Feather Token*
- Horn of Valhalla*
- Iron Flask*
- Manual of Golems*
- Necklace of Prayer Beads*
- Potion of Resistance*
- Ring of Resistance*
- Robe of Useful Items*
- Sphere of Annihilation
- Wand of Wonder

\* *These items only used the roll tables on item creation by DMs, not on usage.*

### Others
- Four tables in the "Creating Sentient Magic Items" section

**Comment by kjolern** [comment]
Hi. 

Could I try and help with this issue ? 
Would you like them as ordinary roll tables or tied to the item ? 

Best regards
Kjolern

**Comment by arbron** [comment]
> Could I try and help with this issue ? Would you like them as ordinary roll tables or tied to the item ?

Great! I was thinking just adding a link in the item/spell descriptions to the tables the same way the `"Acolyte"` background links to its associated tables.

**Comment by kjolern** [comment]
It seems there is no feather token , but alle the different items the rolltable refers to.  Should I make a feather token item that links to to rolltable @arbron ?

**Comment by kjolern** [comment]
Is it ok if I add a Horn of valhalla and a feather token item @arbron  ? It seems the different variants exists, but not the plain one which I assume should be linked to the rolltable. Or should I just add the rolltable and let them be ?

**Comment by kjolern** [comment]
Do we work on branch 2.0.X now @arbron ?
