### ISSUE TITLE
[Feature Request]  Tag dice with damage type from formula field

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1495]
Originally in GitLab by @sharkbruhaha

Can we please have the dice in the chat cards get tagged with the damage type from their formula row (and include any addition on that die).

Currently it seems like these fields do nothing other than be printed at the top of the attack, ex: (Piercing, Fire) with no useful indication what is what.

![image](https://gitlab.com/foundrynet/dnd5e/uploads/cdcd6bc6312ac86a62cf1870daf679b8/unknown-20.png)

**Comment by sharkbruhaha** [comment]
(tagging for tracking after move to github)

**Comment by RossGosling** [comment]
Just expanding upon @sharkbruhaha's design, I think there's other subtle elements like the inclusion of modifiers, being able to see where a +1 or a +10 factored into a total and allowing you to garner a lot more information from the expanded view

| Parts Configuration |
| --- |
| ![image](https://user-images.githubusercontent.com/879127/208489707-de70f483-b0f0-4d63-8697-eea30314defc.png) |

| Roll Before | Roll After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/879127/208489745-65c3804c-d9d2-4339-87ae-d96b0b30bd8e.png) | ![image](https://user-images.githubusercontent.com/879127/208489758-08f99fed-9af5-4662-ba18-2bef44505ad7.png) |

---

Whether the example `+0` from `@mod` could also be tagged as such, `+0 (Modifier)`? I don't know how to visually represent that

| Roll After With Tag |
| --- |
| ![image](https://user-images.githubusercontent.com/879127/208490529-ca164558-e150-4b9f-9904-38d0ec5e2fcf.png) |

**Comment by sharkbruhaha** [comment]
Yes, tagging modifier and other elements that are derived or from other sources like After Effects like @RossGosling mentioned would be incredibly helpful especially when, seemingly, random zeros show up.
