### ISSUE TITLE
Allow formulas in range field on items

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1504]
Originally in GitLab by @sharkbruhaha

The range field is not taking `@scale`.
![image](https://gitlab.com/foundrynet/dnd5e/uploads/c6f6eb963061bc7ea6f3f215ebd2a814/image.png)

Also, not clear from the description on `Distance` if that is in fact going to be the proper one to use for the range field, as that is typically just a number (I've tried setting this as `Numeric` and still did not accept `@scale` in the field.
![image](https://gitlab.com/foundrynet/dnd5e/uploads/cc1b608590d585bebc69b56a73afab97/image.png)

**Comment by sharkbruhaha** [comment]
(tagging for tracking after move to github)

**Comment by sharkbruhaha** [comment]
bump on this?
