### ISSUE TITLE
Allow customization of dice sizes in scale value advancement

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1505]
Originally in GitLab by @sharkbruhaha

Please change the `Dice` Scalar Advancement from a dropdown to a numeric field.

Having this hard coded as a dropdown prevents the use of d100, but also larger non-physical dice numbers. Homebrew Wild Magic comes to mind immediately, but why limit it as well.

**Comment by arbron** [comment]
Rather than allowing this to be a completely free-form input, I have changed it to allow the list to be customized using a script:

```javascript
Hooks.on("init", () => {
  dnd5e.advancement.types.ScaleValueTypeDice.FACES.push(200);
}
```
