### ISSUE TITLE
Make it possible to change how items are being linked in the Advancement UI from ID based to Name based.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1509]
Originally in GitLab by @sharkbruhaha

Would be highly useful to be able to specify the link by name instead of ID, when we wish.

ex: `@Compendium[dnd5e.spells.Fireball]`
ibsread of always being `@Compendium[dnd5e.spells.<id_hash>]`

So that there is no worry about accidentally forgetting to import/export with the "maintain ID" setting checked.

**Comment by sharkbruhaha** [comment]
(tagging for tracking after move to github)
