### ISSUE TITLE
[Feature Request] Sort status effect icons by lexical effect name

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1510]
Originally in GitLab by @Blesmol

When clicking on a token to assign a status effect, there is no obvious order for the status effects, and the icons are not always helping that much when trying to find a specific status effect. Therefore, I would request to pick up the way this was solved in the PF2 game system, where the status effect icons are arranged in order of the name of the status effect. So the new order would probably be something like "Asleep", "Blessed", etc.

**Comment by krbz999** [comment]
Other than 'Dead' being placed at the front of the array of conditions, they are otherwise sorted alphabetically as of v3.0.0.
