### ISSUE TITLE
Die expressions in Check Bonus are not evaluated when an inline roll uses skills.XXX.total

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1511]
Originally in GitLab by @MaxPat931

When using a deferred inline roll such as `[[/r 1d20+@skills.per.total]]` if the skill has a numerical value in the Check Bonus field, it is included in the resulting roll, if the Check Bonus is a die value it is not included.

![image](https://gitlab.com/foundrynet/dnd5e/uploads/5cce728c06e24c66ec86008292d2bcaf/skillbonusdie.mp4)

**Comment by Fyorl** [comment]
I wonder if a custom skill enricher like the one proposed in #1865 would be a better solution at this point. Adding a `@skills.*.formula` would also work though.

**Comment by MaxPat931** [comment]
I do think the enrichers would be a more significant improvement to the system to have, and would definitely solve this use case

**Comment by MaxPat931** [comment]
we be resolved by #2500
