### ISSUE TITLE
Add tool category to tool sheet header rather than generic "Tool"

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#1532]
If a tool is selected within a certain category such as `"Musical Instrument"` or `"Artisans' Tools"`, that category should be displayed in the tool sheet header rather than the generic `"Tool"` that always displays now.

**Comment by kaelad02** [comment]
Are you referring to the item type that's in the upper-right corner of the item sheet?

![image](https://user-images.githubusercontent.com/19502084/174918723-3af9c0f9-61ac-4bdf-a5b8-941e3629c8b8.png)

If so, then changing that sounds like a bad idea to me. Other item types have subtypes (e.g. equipment and weapons) and they show their subtypes to the left of the Rarity.

![image](https://user-images.githubusercontent.com/19502084/174918795-0110dbf5-c5d3-4c18-8b31-07f89f2ecb0f.png)

Updating the tool sheet to show the tool type like the second screenshot makes sense to me. It'd be consistent with what some of the other item types look like.

**Comment by arbron** [comment]
This is the screenshot from the old MR created by @jeremyregnerus which I hope will eventually be recreated on GitHub:

![image](https://user-images.githubusercontent.com/19979839/175064302-4ec222b8-c01f-43aa-82dc-363cba2e82b9.png)
