### ISSUE TITLE
Feature request: Add Limited Uses to tools

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1537]
Originally in GitLab by @krbz999

Several tools, mostly musical instruments, have charges to expend on specific features. It would be good if these item types supported limited uses.

Examples:
- Pipes of Haunting (DMG)
- Horn of Silent Alarm (XGE)
- Instrument of Scribing (XGE)
- Pipes of the Sewers (DMG)

**Comment by LadyDefile** [comment]
I second this. My campaign uses a homebrew system for herbalism/poison crafting/alchemy where the kits have charges. As it is right now, we have to have a completely separate item in Consumables to have charges for the kit.

**Comment by guldelox** [comment]
It does seem odd that tools cannot have charges or limited uses.
