### ISSUE TITLE
[Feature Request] Add Roll button to inline roll links

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1546]
Originally in GitLab by @MaxPat931

Include a 'Roll' button at the end of inline roll links for Items and Rolltables

![image](https://gitlab.com/foundrynet/dnd5e/uploads/46f596ae7ee53ea415e15e2dd0cc0ab1/image.png)

This would allow a user to roll for an item from the item sidebar/compendium as if they were the owner which could be useful in keeping an actor's sheet more concise for things like a weapon that allows casting of spells, or a journal with links to multiple roll tables

In v10 when an actor's embedded items can also be linked, this will also allow for functionally linking their different attacks in a multiattack chat card

![image](https://gitlab.com/foundrynet/dnd5e/uploads/76f604af6ce21bc7ffa800168ef6dc0e/image.png)

**Comment by arbron** [comment]
Hey @MaxPat931, if you comment on this issue then I can assign it to you to keep track of who is working on it :)

**Comment by MaxPat931** [comment]
🙋‍♂️
