### ISSUE TITLE
Creating an active effect on an item shouldn't always check transfer to actor

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1552]
Originally in GitLab by @kaelad

When you create a new active effect on an item, the "transfer effect to actor" option is checked by default. When creating an effect on a spell, you don't want that checked and has caused some issues for people on the Discord.

When you create an effect on a spell, it's meant to transfer to the target of the spell when cast. You don't want it to transfer to the actor just by adding the spell to their spellbook. Also, seems kind of odd considering you don't actually equip spells.

There are two possible solutions that I thought of:

1. When creating a new effect on a spell, don't have that option checked by default. Spells can't be equipped anyways and effects there are meant to be transferred to the spell's target when cast.
2. When creating a new temporary effect on any item type, don't have that option checked by default. If the effect is temporary, then it's probably meant to transfer to a target when the item is used.

**Comment by Fyorl** [comment]
Sometimes the target of the spell is the caster themselves, so it is desirable to have the effect transfer to them. *Shield* is an example of such a spell that provides an AE that the caster can then toggle on and off on themselves. Even if that's not the case, for example, *Bless*, the AE that it provides is inactive and is intended to be dragged-and-dropped onto the spell targets when they are under its effects.

I might be misunderstanding the issue, but tentatively marking this as won't change for now.
