### ISSUE TITLE
Proficiency/Proficiency Die scaling is broken/linearly scaled for custom max level

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1573]
Originally in GitLab by @CrackJackFlood

If you have a custom maxlevel set the proficiency scaling is linear so a level 30 character gets 1d18 proficiency die for example. 

Preferably max level and proficiency should be easily customizable in the settings.

I have tried to find the hooks and references to change the proficiency scaling myself in the worldscript but have been unable to find it, pointer in the right direction would be much appreciated.

**Comment by arbron** [comment]
You can cap the proficiency for an individual character using an active effect targeting `system.attributes.prof`. Since there is not rules for proficiency dice above a certain level, our current solution seems as good as any.
