### ISSUE TITLE
Transform and revert breaks token flags

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1574]
Originally in GitLab by @DJ.Addi

**Description**

When transforming a token, the flags are entirely ignored. This causes missing module settings for the token.

When reverting the transformation, the flags are restored using a recursive, non-differential update. This causes odd states where any flags modified on the transformed token are now merged with the flags of the original token.

**Environment**

- System version: 1.6.1
- FoundryVTT version: 9.269 on Electron for Windows
- Modules enabled: Bar Brawl 1.6.0

**Expected behavior**

What I would expect is for the transformation to simply copy (and restore) the flags from the prototype non-recursively. The revert transformation method already does this for unlinked tokens, so I don't see why linked token data is merged rather than overwritten.

Alternatively, a hook for the revert could be introduced to allow modules to customize the behavior (which is already possible for the transformation itself).

**Steps to reproduce**

1. Install the Bar Brawl module.
2. Create two actors (one original, one for the transformation).
3. Open the Prototype Token configuration for both, go to the Resources tab and change add resources to make sure that they have different amounts of resources. Save both prototype tokens.
4. Drop the token of the original actor onto the scene.
5. Drop the transformation actor onto the original actor sheet, check "Transform all linked tokens?" and click "Wild Shape". Observe how the displayed bars don't match either configuration (there may be bars depending on the defaults).
6. Revert the transformation. Observe how the restored token now has a mix of the original data and the transformed token data.

**Comment by Fyorl** [comment]
Need to check if this was resolved as part of #1840
