### ISSUE TITLE
[Feature Request] Allows to have up more then 3 resource fields on actor sheets and add option to link a resource to specific item

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1577]
Originally in GitLab by @p4535992

In practice, the integration at the system level of these two modules:

- [5e-Sheet Resources Plus](https://github.com/ardittristan/5eSheet-resourcesPlus): Allows to have up more then 3 resource fields on actor sheets 
- [Link Item and Resource DnD5e](https://github.com/ElfFriend-DnD/foundryvtt-link-item-resource-5e): Adds the ability to link an item's charges or quantity to an actor's resource and thus keep the two always in sync.

**Comment by Rabulias** [comment]
With DND5E 3.X is this still a thing?

**Comment by Fyorl** [comment]
Obsoleted by the v2 sheet design.
