### ISSUE TITLE
[Feature Request] Spellbook overhaul (multiclass-friendly)

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1580]
Originally in GitLab by @Radstark

First of all, [here's an example](https://imgur.com/a/F9nMVrq). It's terrible but it should give an idea of what I'm trying to suggest.

So, the current spellbook isn't really suited for multiclassing spellcasters. It works great for single classes, but as soon as a wizard dips one level into bard, things start to feel not so great anymore.

Here's a list of things that IMO don't work well for multiclassing:
- There isn't a way to tell which class a spell comes from
- There's one default spellcasting stat, then the player has to choose the stat separately for each spell coming from a class that doesn't use that default stat
- The only way to tell the level of a Pact Magic spell is by opening its menu; it doesn't matter for a single class, but it does matter for a multiclass
- Spells coming from a spontaneous caster have the "Prepared" icon, which serves no purpose for a class that doesn't prepare their spells and could actually be confusing for the user

Here's a list of things that IMO would make a multiclass's life much easier:
- Split spells in separate groups, one for each class
- Show each class's spellcasting stat - it could be left editable from the spellbook or it could be locked instead, letting the user change it from the class's options
- Have the spell options window set its class of origin instead of its spellcasting stat, and let it use that class's spellcasting stat (this could go hand-in-hand with the above point)
- Have one section where all spell slots are found, maybe out of the scroll window so that it's always visible (this might be nice even for single classes)

This could also make it easier to have custom spellcasting or spell progression ([issue here](https://gitlab.com/foundrynet/dnd5e/-/issues/1575)), since the spell progression would be directly tied to a class.

What do you think? Is this possible at all or is it too gargantuan of a task for too little use? Could it be improved even more?

[EDIT 06/12/22] I've just remembered that there are cases where a class can have both prepared and spontaneous spells like for example the Paladin, who prepares its spells but casts its Oath spells spontaneously. There would be two possible ways to handle this:
- Leave the possibility to define whether a spell is prepared or always available for each individual spell.
- Have the possibility to bind a spell not only to a class, but also to a subclass, which would have its own spellcasting style.

I'd personally lean towards the second option, which would feel more in line with spells also being linkable to a race instead of a class as already suggested in [this issue](https://gitlab.com/foundrynet/dnd5e/-/issues/1568).

**Comment by Ikaguia** [comment]
One idea that could help, instead of putting each class/subclass sequentially one below the other, split a tab for each (possibly with the option to create custom tabs for spells from other sources)
Here's how we did it for sw5e (system based on dnd5e):
![image](https://user-images.githubusercontent.com/16377028/173622444-99aef15c-c5a6-4466-9a0d-b19722446a06.png)

**Comment by Radstark** [comment]
> One idea that could help, instead of putting each class/subclass sequentially one below the other, split a tab for each (possibly with the option to create custom tabs for spells from other sources) Here's how we did it for sw5e (system based on dnd5e): _snip_
I really like this approach! It appears to be basically more character sheets combined into one for the spellbook, which seems easier to do from a coding standpoint.

**Comment by arbron** [comment]
Some of this is duplicated by other issues, so I'm going to leave a reference to them here:
- Pre-parable spells by class: https://github.com/foundryvtt/dnd5e/issues/1021
- Spells associated with classes: https://github.com/foundryvtt/dnd5e/issues/1351

Once those are closed we can re-assess this issue and see if there are any further improvements required.

**Comment by arbron** [comment]
Only remaining issue that should probably be addressed is the the ability to filter on a specific class.
