### ISSUE TITLE
Unable to update - invalid manifest file

### ISSUE THREAD

**Issue by parallax78** [foundryvtt/dnd5e#1595]
![image](https://user-images.githubusercontent.com/7573430/173782276-44a0122b-d0fd-4bba-ad4d-9658b773ac1f.png)

Keep getting this error when trying to Update via foundry config menu.

**Comment by plutoneld** [comment]
I successfully updated from 1.6.1 to 1.6.2 just now
![image](https://user-images.githubusercontent.com/10401440/173821498-d0bb3673-8db2-4fc0-9bd3-fb87bec4fb66.png)

However, if i press update when 1.6.2 is installed, i get the same error as you. There's no newer version though.

**Comment by FaeyUmbrea** [comment]
Best course of action would be to make a hotfix release with proper URL setup for future updates and upload the manifest file to the old update location so legacy installations can smoothly update to the github release.
