### ISSUE TITLE
[Feature Request] add weapon, armor, tools proficency to details in the advancement class. 

### ISSUE THREAD

**Issue by Fridan99** [foundryvtt/dnd5e#1596]
With the new auto-scaling function of the classes, perhaps it is missing to add in details the proficiency in weapons, armors and tools ....

Well, a simple suggestion. 

:)

![track9](https://user-images.githubusercontent.com/86131373/173880179-73331d57-f6ad-4543-a218-f4853423524a.jpg)

**Comment by arbron** [comment]
That is already planned with #1405 

Its one of those suggestions that looks simple, but is something I've been working towards for over a year since I first created #1016 :O
