### ISSUE TITLE
Sheets are transparent and many icons have lost support

### ISSUE THREAD

**Issue by AnEnemyChampion** [foundryvtt/dnd5e#1598]
Updated from 1.6.2 to 1.6.3 today and all character sheets went transparent instead of the normal tan background. Many profile pictures have lost support, as have feature and spell icons, reverting back to the default icons or error image icons.

Edit: To clarify, this was tested on multiple worlds with and without modules.
Using Foundry v9 - build 269

Edit again: 
![image](https://user-images.githubusercontent.com/75521499/174217696-f607da03-1edb-41f4-a047-414080ec6cbe.png)
Error message shown due to the tokens folder no longer being present.

**Comment by unsoluble** [comment]
Your system install is corrupted or incomplete. Delete the /dnd5e folder entirely, from /systems in your userdata, then install the system again in Foundry Setup.

**Comment by AnEnemyChampion** [comment]
Did that just now and it resolved it. Thanks.
