### ISSUE TITLE
Metamagic class feature item has entity links.

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#1601]
![image](https://user-images.githubusercontent.com/50169243/174431728-176a7944-3928-4353-82b0-3950adb181cb.png)

Users are unable to drag Metamagic options from the feature onto the sheet.

**Comment by MaxPat931** [comment]
Looks like a few other items were affected
Class Features: Metamagic, Multiattack and Pact Boon
Classes: Druid (also the druid item on Aoth)
Items: Necklace of Fireballs, Staff of Charming, Brass Horn of Valhalla

Updated JSONs:
[Broken Links.zip](https://github.com/foundryvtt/dnd5e/files/8934339/Broken.Links.zip)
