### ISSUE TITLE
Make scale values available for active effects

### ISSUE THREAD

**Issue by Ikaguia** [foundryvtt/dnd5e#1605]
Move `_computeScaleValues` to `prepareBaseData`, thus allowing scale values to be used on active effects with the help of DAE

**Comment by Akallabeth13666** [comment]
Yea, need that one too as I would like to create new classes and some stats that scale with it :)
But it did not work, later on I learned on discord that this request exists 👍
![class](https://user-images.githubusercontent.com/95130435/177223165-10c5721f-40f9-4148-978e-a81aa32d15f9.JPG)
