### ISSUE TITLE
NPC weapons cannot be created as "not proficient" via API

### ISSUE THREAD

**Issue by TheGiddyLimit** [foundryvtt/dnd5e#1607]
- Foundry v9, dnd5e 1.6.2

Explicitly setting `data.proficient` works for player characters, but not for NPCs.

```js
(async () => {
	const actor = await Actor.create({
		name: "Repro",
		type: "npc",
	});
	await actor.createEmbeddedDocuments(
		"Item",
		[
			{
				name: "Weapon",
				type: "weapon",
				data: {
					proficient: false,
				},
			},
		],
	);
	actor.items.contents[0].sheet.render(true);
	console.log(actor.items.contents[0].data.data.proficient);
})();
```

Expected: `false`

Actual: `true`

**Comment by MaxPat931** [comment]
NPCs do not have Weapon or Armor proficiencies listed in their statblocks, and are therefore assumed to be proficient in whatever they have. The closest thing I can find to this in the rules is https://www.dndbeyond.com/sources/basic-rules/monsters#ArmorandWeaponSwaps

"You can upgrade or downgrade an NPC's armor, or add or switch weapons. Adjustments to Armor Class and damage can change an NPC's challenge rating."

So the closest you could get would be to put "-@prof" in the Attack Roll Bonus of the weapon

**Comment by TheGiddyLimit** [comment]
Or I can go into the NPC's sheet item and un-tick proficient. The system supports it; the API doesn't.
