### ISSUE TITLE
Add skill check as an action type

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/dnd5e#1609]
When setting up a feature or other item, there's a list of action types to choose from. One kind of d20 roll that seems to be missing is a skill check. For example, some monsters have the Mimicry ability that requires an Insight check to tell the sounds are imitations. It gets asked on the Discord server from time to time so I figured it's probably worth adding.

**Comment by webmaster94** [comment]
Yeah the ability to have it call for a skill check straight from the item would be very useful.
