### ISSUE TITLE
Incorporate Forgotten Adventures creature tokens packs 33, 34, and 35

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#1624]
- Pack 33: https://www.patreon.com/posts/creature-tokens-68483730
- Pack 34: https://www.patreon.com/posts/creature-tokens-68483902
- Pack 35: https://www.patreon.com/posts/creature-tokens-69830449

**Comment by Kulkodar** [comment]
i'll start to work on this.
