### ISSUE TITLE
Acid Splash Targets (Compendium Content)

### ISSUE THREAD

**Issue by Rabulias** [foundryvtt/dnd5e#1625]
The _acid splash_ cantrip allows you to target 1 or 2 creatures, but in the Spells (SRD) compendium, the Target field is set to only 1 creature. It should be set to 2 creatures. Thanks!

**Comment by kjolern** [comment]
Since the wording is :

> Choose one creature within range, or choose two creatures within range that are within 5 feet of each other. 

Would it not be proper to have one creature ? I mean there is a requirement for selecting two.

**Comment by Rabulias** [comment]
It becomes an issue when adding some automation modules that validate target rules. With the spell set to 1 target, it will not allow you to target two creatures:
![image](https://user-images.githubusercontent.com/13688060/189486326-aacb13f3-9112-44c8-84a6-839a7f8b299d.png)

**Comment by kjolern** [comment]
Then i understand the issue. Thank you for the clarification.
