### ISSUE TITLE
Change item deletion to a dialog on the character sheet.

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#1629]
It is much too easy to accidentally delete an item on the character sheet, given the size of the buttons and the controls being grouped with the Edit button which is used very frequently.
Changing the function on it to a confirmation dialog would go a long way, especially for users with bad eyesight (or fat fingers).
Also being able to shift-click to quick-delete would align well with core behavior of rolls.

**Comment by InnilToo** [comment]
This needs to be a thing, please let it be a thing. Too often happens that I delete something and don't even notice it.
