### ISSUE TITLE
Add option to roll initiative with advantage and disadvantage

### ISSUE THREAD

**Issue by IngeRasch** [foundryvtt/dnd5e#1632]
All in the title really, I would greatly appreciate it if the option to roll initiative with advantage and disadvantage could be added to this system.

**Comment by oestred** [comment]
following

**Comment by LiamFallon213** [comment]
I'll take a look into this

**Comment by Dumbhuman** [comment]
Just some examples of why this is needed:

- Any creature with at least one level of Exhaustion has disadvantage on all ability checks (which would include initiative rolls).
- Any creature with the Poisoned condition has disadvantage on all ability checks (which would include initiative rolls).
- 7th level Barbarians get the Feral Instinct feature which gives advantage on all initiative rolls.
- 7th level Warrior Sidekicks get the Battle Readiness feature which gives advantage on all initiative rolls.
- 10th level Artificers can use an infusion to create the Helm of Awareness magic item which gives advantage on all initiative rolls.
- 1st level Wild Magic Sorcerers get the Tides of Chaos feature which can give advantage on one ability check (which would include initiative rolls).
- 1st level Twilight Clerics get the Vigilant Blessing feature which gives one creature advantage on their next initiative roll.
- The 2nd level spell Enhance Ability can be used for the Cat's Grace effect which grants one creature advantage on all dexterity checks (which would include initiative rolls) for up to 1 hour duration.
- The 8th level spell Foresight grants advantage on all ability checks (which would include initiative rolls) for up to 8 hours.

**Comment by aaclayton** [comment]
Addressed in https://github.com/foundryvtt/dnd5e/pull/1994
