### ISSUE TITLE
Hit die type generalization

### ISSUE THREAD

**Issue by djinnstar** [foundryvtt/dnd5e#1634]
The selectable hit die types in class items are the hit die types from the SRD classes - d6, d8, d10, and d12. The restriction can be seen in the image below:

![image](https://user-images.githubusercontent.com/51678460/178358087-1a7db3f6-d127-46c6-a713-188ee1d31280.png)

The SRD rules don't actually restrict the hit die types to d6, d8, d10, and d12 - they just say that hit die type is inherited from class. 

Our system's existing restriction prevents homebrew classes from choosing their desired hit die types (see #1581 - where a class wants a d4 hit die). In principle, a class should also be able to have arbitrary integer hit die types, like d3 and d24601.

I propose that the hit die type in each class be represented by an integer rather than a string. This should add all of the flexibility we need.

This image represents a possible modified workflow in the class item sheet (the "d" is just to clarify the input to the user; the underlying rep is an integer):

![image](https://user-images.githubusercontent.com/51678460/178360010-2da2fab3-6e44-4651-876d-7426e8ae9038.png)

This process of hit die generalization would need some work:

- Changing the hit die type in class data from strings to integers
- Updating all related functions to expect integers instead
- Updating all packs to reflect this change
- Updating the class item template to expect non-empty integer input

...obviously this will take some time, and I'll start on it within a few days, but I'd love some feedback/opinions/suggestions!

**Comment by arbron** [comment]
I don't think we should make this change. The dropdown is much more usable, and you can still customize it by modifying `CONFIG.DND5E.hitDieTypes` without adding extra burden to normal users.

**Comment by djinnstar** [comment]
I feel like the dropdown's only slightly easier to use than a text input, whereas modifying `CONFIG.DND5E.hitDieTypes` requires its own module for the modification to persist after the Foundry app closes. The text input could even parse the text field inputs to accept both "d9" and "9" to make it easier to use. Ultimately up to you all though!

**Comment by Fyorl** [comment]
We can consider adding 'd4' to the list to support some homebrew. But I agree that the drop-down is nicer UX.
