### ISSUE TITLE
Skills in Non-PC character sheets aren't alphabetically sorted correctly

### ISSUE THREAD

**Issue by Fallayn** [foundryvtt/dnd5e#1635]
Skills in non-PC sheets are sorted too early, before localization is applied, which means they end up out of order e.g. in german.

Originally, this issue existed for PC sheets too, which I reported and was fixed: https://github.com/foundryvtt/dnd5e/issues/1070

Unfortunately, the issue still exists for non-PC sheets, so the fix needs to be applied there too :)

**Comment by arbron** [comment]
Not happening on the default NPC sheet in dnd5e.
