### ISSUE TITLE
Spell Scroll to Hit and Save DC corrections

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/dnd5e#1639]
The spell scrolls do not calculate the To Hit or Save DCs correctly, instead the To Hit is getting a bonus of what should be the flat value, and Save DCs are set to the owner's spell save DCs.
![image](https://user-images.githubusercontent.com/86370342/179316383-7d1691aa-a8e1-4848-99fc-c1b07eb2eff2.png)

Fixing the To Hit is as easy as adding `- @mod` in the Attack Roll Bonus field (where the flat attack bonus already exists).
![image](https://user-images.githubusercontent.com/86370342/179316936-9e99458c-508e-471a-af76-b182444c2ac2.png)

Fixing the Save DCs is probably a little more difficult, currently the saving throw info is generated from the spell's information, but sets the DC based on the spellcasting attribute, this should change to a Flat DC defined in the Spell Scroll, and only the Save Ability populated from the Spell item. Currently, setting the DC on the Spell Scroll item gets overwritten
![image](https://user-images.githubusercontent.com/86370342/179317030-e3c3b060-8e05-4cb4-8133-4eb44ce9c294.png)

**Comment by paulohdsc** [comment]
When you address this issue, please don't forget to update the `createScrollFromSpell()` method so that spell scrolls are created already with flat Save DC/Attack Bonus values.

Also, it would be nice if it was possible to indicate somewhere in item details that it has a flat Attack Bonus, so that it is not necessary to insert `-@mod` to the roll.

**Comment by Fyorl** [comment]
> Also, it would be nice if it was possible to indicate somewhere in item details that it has a flat Attack Bonus, so that it is not necessary to insert `-@mod` to the roll.

Probably not as part of fixing this bug but I've raised a separate issue for this request: #2026
