### ISSUE TITLE
Core setting "Scrolling Status Text" is ignored by _onUpdate in dnd5e.mjs

### ISSUE THREAD

**Issue by eclarke12** [foundryvtt/dnd5e#1645]
A check should be added here:
https://github.com/foundryvtt/dnd5e/blob/077da87dab22b9b50e234ff0ecc496408ceb0af8/dnd5e.mjs#L9719

Or here:
https://github.com/foundryvtt/dnd5e/blob/077da87dab22b9b50e234ff0ecc496408ceb0af8/dnd5e.mjs#L9731

**Comment by arbron** [comment]
That check is already being performed by core inside `createScrollingText`, so the system doesn't need to do anything.
