### ISSUE TITLE
Parry doesn't appear to prevent a hit when it should

### ISSUE THREAD

**Issue by haqa** [foundryvtt/dnd5e#1654]
On a couple of occasions in our last game NPCs parrying incomming hits that were only 1 above their AC still had the hit damage applied.

**Comment by unsoluble** [comment]
Hi again! Can you pop into the #dnd5e channel on the [Discord](https://discord.gg/foundryvtt) to hash this out? Again this is a module interaction; tickets here are solely for core system issues.

**Comment by haqa** [comment]
Looks like this is a conflict with Midi QOL, sorry. I'll close this.
