### ISSUE TITLE
dnd5e 1.7 typo

### ISSUE THREAD

**Issue by tposney** [foundryvtt/dnd5e#1657]
```js
  async _onSpellSlotOverride(event) {
    const span = event.currentTarget.parentElement;
    const level = span.dataset.level;
    const override = this.actor.systema.spells[level].override || span.dataset.slots;
```
const override = this.actor.**systema**.spells[level].override || span.dataset.slots;  
should be
const override = this.actor.**system**.spells[level].override || span.dataset.slots;

**Comment by arbron** [comment]
Already fixed in the current `v10-dev` branch.
