### ISSUE TITLE
dnd5e 1.7 damage scrolling text not working

### ISSUE THREAD

**Issue by tposney** [foundryvtt/dnd5e#1658]
It appears that dnd5e.mjs line(s) starting at 9730
```js
  _displayScrollingDamage(dhp)
  ```
  has not been updated for foundy 10's scrolling status text changes and throws an error with
```js
t.hud.createScrollingText
```
being undefined. If I change the call to 
```js
canvas.interface.createScrollingText(t.center, dhp.signedString(), {
 ```
it works

**Comment by arbron** [comment]
Resolved with #1656
