### ISSUE TITLE
`dropTarget is null` error when dragging & dropping class

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#1685]
Steps to Reproduce:
1. Increase level dropdown to higher level
2. Exit advancement window, canceling the process
3. Click and drag the class just changed, dropping back onto the same character sheet

**Comment by akrigline** [comment]
I'm not able to reproduce this in lastest `v10-dev` on core build 279.

**Comment by arbron** [comment]
Seems to have been fixed by a change in core. Good to see :).
