### ISSUE TITLE
Some pampering with the other formula field

### ISSUE THREAD

**Issue by Fridan99** [foundryvtt/dnd5e#1694]
I have contacted Tim Posney, for an improvement with midi-qol in the calculation of how dnd5e system treats the Other Formula. It seems that the Other Formula field (item.rollFormula), is separate from the normal damage fields (item.rollDamage), but it depends on the dnd5e system how that field is treated. 

It seems that since the Other Formula is not included, it is not possible to automate several things like DR, Resistances, Immunities, ..... and the Other Formula field itself lacks damage type (you can put [acid], [thunder], etc.. in brackets, but it does not really fulfill any effective function except aesthetics). 

I was wondering if this aspect could be revised in any way.

I post the link to the thread with Tim Posney, where he is going to try to work something for v10, but according to what he says, it also depends on the dnd5e system of how the Other Formula is processed. 

https://gitlab.com/tposney/midi-qol/-/issues/935

**Comment by arbron** [comment]
The issue is that the `"Other Formula"` field isn't a damage field, it is intended for other rolls like `"Confusion"` effects. It very specifically doesn't bring up the roll configuration window or support things like criticals or damage types.

**Comment by Fridan99** [comment]
Generally, as I have observed, most users use the other formula for damage that is rolled after a saving throw, such as the venom of spiders, poisonous snakes, and other creatures that have a dependent secondary damage, or even some items like the venom dagger, etc.....  Let's say that the other formula is a disaster box, for all that damage that is not always rolled.

**Comment by Fridan99** [comment]
Is it possible that the other formula could behave in a dual mode, or is it complicated?  

Example

Other formula (no damage "label"). Behave as it does now. 

Other formula (piercing, slashing, bludgeoning, fire, cold..... "label"). Behave as a damage field and follow the damage workflow.
