### ISSUE TITLE
Improve how boxed text is displayed throughout the rules

### ISSUE THREAD

**Issue by plutoneld** [foundryvtt/dnd5e#1695]
I've never liked how the boxed text was carried over from the SRD rules. I disregarded the use of `blockquote`, since i consider that style to be more of a "read aloud boxed text", and italics is not suited for some of the content. Most of the boxed text is therefor displayed between `hr` elements or with needlessly big headings, to set them apart from the surrounding text.

![image](https://user-images.githubusercontent.com/10401440/184110793-07a74683-c849-44dc-bad6-c1bc11e8a04c.png)

I think it would be nice if they were standardized, possibly while carrying out the Journal V2 revamp (https://github.com/foundryvtt/dnd5e/issues/1565), and improved upon. For reference
![image](https://user-images.githubusercontent.com/10401440/184112938-cd1c2689-e8ab-4764-a55f-1b0823299203.png)

I've compiled a list of Class items and Journal Entries where boxed text is displayed

### Druid
* "Sacred Plants and Wood"
* "Druids and the Gods"

### Paladin
* "Breaking your Oath"

### Warlock
* "Your Pact Boon"

### Wizard
* "Your Spellbook"

### Adventuring Gear
* "Equipment packs"

### Expenses
* "Self-Sufficiency"

### Using Each Ability
* "Hiding"

### The Order of Combat
* "Combat Step by Step"

### Movement and Position
* "Interacting with Objects Around You"

### Making an Attack
* "Contests in Combat"

### What is a Spell?
* "Casting in Armor"

### Casting a Spell
* "The Schools of Magic"

### Monsters
* "Modifying Creatures"
* "Armor, Weapon and Tool Proficiencies"
* "Grapple Rules for Monsters"

### Appendix PH-A: Conditions/Exhaustion
A bit of a special case since the whole Exhaustion box was broken out into a separate JE, for easy reference/linking. The entire Exhaustion JE should probably be boxed text and added as a page to Appendix PH-A JE.

**Comment by kjolern** [comment]
I could try and make this changes if you want ?
