### ISSUE TITLE
Unable to expand item summary

### ISSUE THREAD

**Issue by Terked** [foundryvtt/dnd5e#1700]
### What happened?

User is unable to expand any item, feature or spell summary when done through the actor sheet. 

Encountered in _DnD5e - Fifth Edition System 2.0.0-alpha2_ system

### What ways of accessing Foundry can you encounter this issue in?

- [ ] Native App (Electron)
- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Other

### Reproduction Steps

1. Open an actor sheet (can be adventurer or NPC)
2. Navigate to an item
3. Click on item to expand item summary
4. Observe nothing happening. Console error thrown
   **Expected**: Item summary expands

### What core version are you reporting this for?

V10 testing 3

### Relevant log output

```shell
dnd5e.mjs:11639 Uncaught TypeError: Cannot read properties of undefined (reading 'value')
    at ActorSheet5eNPC._onItemSummary (dnd5e.mjs:11639:69)
    at HTMLHeadingElement.<anonymous> (dnd5e.mjs:11215:67)
    at HTMLHeadingElement.dispatch (jquery.min.js:2:43064)
    at v.handle (jquery.min.js:2:41048)
_onItemSummary @ dnd5e.mjs:11639
(anonymous) @ dnd5e.mjs:11215
dispatch @ jquery.min.js:2
v.handle @ jquery.min.js:2
```

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by arbron** [comment]
Already fixed
