### ISSUE TITLE
Various SRD items were not properly converted to use core icons

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#1711]
I suspect there is not direct match between the icons they use and the ones in core. We will need to find a new icon, and then also update `icon-migration.json` & `spell-icon-migration.json` with these new matches to ensure that players' icons are able to be properly migrated.

Class Features:
- Bonus Cantrip (Druid)
- Invocation: Eldritch Spear

Items:
- Elven Chain
- Robe of Useful Items
- Robes
- Vestments

Monster Features:
- Air Form
- Angelic Weapons
- Charm
- Create Whirlwind
- Darkness Aura
- Death Throes
- Enlarge
- Fire Aura
- Keen Senses
- Lightning Storm
- Misty Escape
- Petrifying Breath
- Possession
- Reflective Carapace
- Rejuvenation
- Shimmering Shield
- Teleport
- Web Sense
- Whirlwind

Racial Features:
- Dragonborn
- Dwarf
- Elf
- Gnome
- Half-Elf
- Halfling
- Hellish Resistance
- High Elf
- Hill Dwarf
- Human
- Lightfoot Halfling
- Rock Gnome
- Tiefling

Spells:
- Instant Summons
- Tiny Hut

**Comment by arbron** [comment]
Also need to make sure we update the items in monsters & starter heroes.

**Comment by alaustin0** [comment]
Icon locations:

**Class Features**
Bonus Cantrip (Druid) - icons/magic/nature/vines-thorned-glow-green.webp
Invocation: Eldritch Spear - messed up for me, not sure which icon it's supposed to be.

**Items**
Elven Chain - icons/equipment/back/mantle-collared-green.webp
Robe of Useful Items - icons/equipment/back/mantle-collared-black.webp
Robes - icons/equipment/back/mantle-collared-black.webp
Vestments - icons/equipment/back/mantle-collared-black.webp

**Monster Features**
Air Form - icons/magic/control/debuff-energy-hold-levitate-yellow.webp
Angelic Weapons - icons/magic/fire/dagger-rune-enchant-flame-strong-blue-yellow.webp
Charm - icons/magic/air/wind-tornado-spiral-pink-purple.webp
Create Whirlwind - icons/magic/air/wind-tornado-cyclone-white.webp
Darkness Aura - icons/magic/perception/eye-ringed-glow-angry-small-red.webp
Death Throes - icons/magic/fire/explosion-fireball-large-red-orange.webp
Enlarge - icons/magic/control/energy-stream-link-large-blue.webp
Fire Aura - icons/magic/air/fog-gas-smoke-swirling-orange.webp
Keen Senses - icons/magic/perception/eye-ringed-glow-angry-large-teal.webp
Lightning Storm - icons/magic/lightning/bolts-forked-large-blue-yellow.webp
Misty Escape - icons/magic/air/fog-gas-smoke-swirling-gray.webp
Petrifying Breath - icons/magic/air/fog-gas-smoke-orange.webp
Possession - icons/magic/control/fear-fright-monster-grin-purple-blue.webp
Reflective Carapace - icons/magic/defensive/shield-barrier-flaming-pentagon-purple-orange.webp
Rejuvenation - icons/magic/control/debuff-energy-hold-levitate-green.webp
Shimmering Shield - icons/magic/light/explosion-star-large-blue-yellow.webp
Teleport - icons/magic/symbols/runes-star-pentagon-magenta.webp
Web Sense - icons/magic/control/debuff-chains-ropes-net-white.webp

**Racial Features**
Dragonborn - icons/magic/perception/eye-ringed-glow-angry-red.webp
Dwarf - icons/magic/defensive/shield-barrier-glowing-triangle-teal-purple.webp
Elf - icons/magic/nature/leaf-glow-maple-teal.webp
Gnome - icons/magic/fire/projectile-meteor-salvo-strong-purple-yellow.webp
Half-Elf - icons/magic/nature/leaf-glow-triple-teal.webp
Halfling - icons/magic/lightning/bolt-forked-large-teal.webp
Hellish Resistance - icons/magic/air/fog-gas-smoke-swirling-orange.webp
High Elf - icons/magic/nature/leaf-glow-maple-green.webp
Hill Dwarf - icons/magic/defensive/shield-barrier-glowing-triangle-magenta.webp
Human - icons/magic/light/explosion-star-large-orange.webp
Lightfoot Halfling - icons/magic/lightning/bolt-forked-teal.webp
Rock Gnome - icons/magic/fire/projectile-meteor-salvo-light-purple.webp
Tiefling - icons/magic/air/wind-tornado-cyclone-red-orange.webp

**Spells**
Instant Summons - icons/magic/symbols/runes-star-blue%20.webp
Tiny Hut -  icons/magic/symbols/runes-star-blue%20.webp

**Comment by akrigline** [comment]
Related but not exactly: Active Effect icons need migration support as well (Bless, Shield, for instance use the spell's icon)
#1739 and #1740 solve this

**Comment by arbron** [comment]
Strangely, all of the icons but two were properly set up in the icon migrations files, but were never applied to the items.
