### ISSUE TITLE
v10: Unable to edit ActiveEffects

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#1726]
Changes made to ActiveEffects do not save.

(FVTT V10 testing 5, dnd5e 2.0.0-alpha2)

Steps to reproduce:
- create effect on an actor sheet.
- edit it and attempt to change its icon, label, duration, or effects (changes).
- Hit 'Submit Changes'

**Comment by arbron** [comment]
This is a core bug: https://github.com/foundryvtt/foundryvtt/issues/7935
