### ISSUE TITLE
v10: Saving using the Trait selectors adds 'submit' as a value

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#1727]
To reproduce:
- Open a trait selector.
- Tick any number of options.
- Save.

(testing 5, dnd5e alpha3)

![image](https://user-images.githubusercontent.com/50169243/186702354-28cce68c-39c2-4c1b-b2fa-a5bdcad70269.png)

**Comment by arbron** [comment]
Related to a core issue: https://github.com/foundryvtt/foundryvtt/issues/7938

That said, is probably worth doing a quick fix here to clean up some of our forms.
