### ISSUE TITLE
Cannot add compendium items to rollable tables

### ISSUE THREAD

**Issue by djinnstar** [foundryvtt/dnd5e#1730]
### Details
dnd5e version: 2.0.0-alpha3
Foundry version: V10 testing 5 - Build 279
Reproducible w/o modules: Yes
Hosting: Self-hosted
Reproduction steps: Create a rollable table and try to add an item from a compendium to it. When you do, the item appears to be successfully added to the table, until `Update` is pressed, at which point the item is replaced with a null item. No errors are written to the console when this happens. This does not appear to happen for non-compendium, in-directory items. 

### Before pressing `Update`: 

![image](https://user-images.githubusercontent.com/51678460/186747200-f3cc6ebb-47c5-4aa1-92b0-256a14785953.png)

### After pressing `Update`:

![image](https://user-images.githubusercontent.com/51678460/186747228-536a0b40-65a5-4345-94df-9dcb825511f1.png)

### The chat result from rolling on the table:

![image](https://user-images.githubusercontent.com/51678460/186747287-041d0681-eb91-47c7-8a67-0ff02511e4a1.png)

I'm not sure how much I can try to solve the bug myself - the dnd5e code doesn't explicitly deal with tables, so this might instead be a general Foundry bug?

**Comment by arbron** [comment]
Can't reproduce myself, and it looks like you are trying to fetch the `"Acolyte"` from the `dnd5e.heroes` compendium where it doesn't exist. That actor is in the `dnd5e.monsters` compendium. Let me know if that was your issue or if something else is going on.

**Comment by djinnstar** [comment]
Weird - it looks like the source compendium name didn't transfer when dragging and dropping the `"Acolyte"` actor from `dnd5e.monsters`. Manually switching the compendium name after dragging and dropping resolves the issue, but this seems automatable, so perhaps we could automate the source compendium name transfer for QOL?
