### ISSUE TITLE
v2.0.0 alpha3: armor with 'Stealth Disadvantage' set to false cannot be used.

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#1743]
Add an Equipment-type item to an actor. Set it to be light/medium/heavy armor. Base item type does not matter.

Check and then uncheck "Imposes Stealth Disadvantage". Try to use the item, and you get an error.

If the box is checked, the item works fine.

**Comment by akrigline** [comment]
I just discovered this as well. You don't even need to uncheck it, if you have an existing character (e.g. from the starter heroes compendium) and then open then close the Armor item, it is no longer possible to "use" the item.

![image](https://user-images.githubusercontent.com/7644614/187032605-4c8f6747-d71a-4770-8b57-6366eeab6732.png)
