### ISSUE TITLE
v2.0.0 alpha3: Deprecation warning when attacking with weapons that expend ammo

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#1746]
![image](https://user-images.githubusercontent.com/50169243/187082519-eefdd9d1-2e78-4be5-a411-59c952e29a4a.png)

The relevant part I think is this:

![image](https://user-images.githubusercontent.com/50169243/187082556-0f418be4-0d92-4d54-ad12-dea0b61f75a2.png)

**Comment by arbron** [comment]
Resolved by #1745
