### ISSUE TITLE
Class/Subclass attempts an infinite merge after adding advancements

### ISSUE THREAD

**Issue by teberger** [foundryvtt/dnd5e#1753]
Happens on the latest release of the 2.0.0 alpha
![image](https://user-images.githubusercontent.com/4360083/187288917-da4ea2c5-b0c2-4902-88e1-7dc0185a9863.png)

Looks like some kind of recursion is happening when attempting to edit the description of a Class/Subclass item type. Prior to adding any 'Advancements' to the class, you can edit the description just fine. 
 
![image](https://user-images.githubusercontent.com/4360083/187285402-1813fa67-1c86-4365-a875-ae40485f55f1.png)

But after adding in any advancement (including HP), it looks like some kind of recursive merge is happening and the description's edit button becomes unresponsive. 

![image](https://user-images.githubusercontent.com/4360083/187285191-2dfaef92-276c-4a1a-aa4b-2f3f2385d60f.png)

![image](https://user-images.githubusercontent.com/4360083/187285250-ed8af72f-abc8-4d53-b99b-3c5e4f9bb7dc.png)

Steps to reproduce:

1. Create a Class or Subclass item and open the item
2. Click the 'Advancement' tab and add any advancement (Scale Value, Hit Points, and Grant Items all cause the issue)
3. Switch back to the 'Description' tab
4. Attempt to edit the description

**Comment by arbron** [comment]
This is a core bug that will be fixed in the next release: https://github.com/foundryvtt/foundryvtt/issues/7946
