### ISSUE TITLE
When applying damage via the chat log, only the first roll is used

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#1757]
If you produce a message with multiple rolls, like this (possible as of v10):
```
/r 1d4
/r 1d100
```
you cannot apply the d100 as damage. The first roll is always used.

To reproduce:
- Write the above snippet in chat or through a Chat macro and execute.
- Select a token.
- Right-click the second roll in the message, or anywhere on the chat message, and apply as damage.

**Comment by akrigline** [comment]
This particular syntax of `/r xxxx /r xxxx` wasn't possible in v9 it seems, so I expect this has to do with the multiple rolls per chat card changes in v10.

**Comment by itteerde** [comment]
not the same, but a fix/improvement should also cover
![image](https://user-images.githubusercontent.com/8367477/210012166-80467ce5-7cc7-44ba-ab45-3b980340bbc5.png)
where there is a total composite for different stuff (different lines in the roll formula) that should have their own right click or enable to right click for seperating them in order to handle them different after that with more clicks.

**Comment by itteerde** [comment]
It is also seemingly impossible to even create the separation by damage visually right now as even 
![image](https://user-images.githubusercontent.com/8367477/210189352-eaa2417c-a1cb-4d91-8824-9a02169aca7f.png)
leads to
![image](https://user-images.githubusercontent.com/8367477/210189361-6c362049-4adf-4ea5-99c4-4d620c5da5ed.png)
. A good solution would aggregate by damage type, and make those right-clickable.

**Comment by itteerde** [comment]
![image](https://user-images.githubusercontent.com/8367477/210189563-1e6dbb9a-bec5-47a7-a7db-997014cbf664.png)
gives
![image](https://user-images.githubusercontent.com/8367477/210189576-62241e10-5f3a-4d8e-8810-0fb4854f4341.png)
which would be playable if the partial results would be right-clickable. But aggregate by damage type would be better.

**Comment by itteerde** [comment]
long story short, the ChatMessage for rolls with different damage types should group aggregates by damage type and allow those parts to be right clicked to aplly them differently (for resistances, immunities and vulnerabilities).

**Comment by itteerde** [comment]
Another example is Spirit Shroud. As imported by DDB-Importer it has three damage formula rows, that currently end up in just one (in this case just wrong) roll. If those would be aggregates by type (no changes in the definition needed) it would be perfect for users assigning damage by right click -- one would just right-click the damage type chosen (by talking). I really believe making this better should have a pretty high priority.
