### ISSUE TITLE
Add consumable/pack list to config + add pack data to system

### ISSUE THREAD

**Issue by djinnstar** [foundryvtt/dnd5e#1764]
We have the weapon, equipment, and tool reps in config.mjs for #1058, but we don't have consumables (some classes add arrows) or equipment packs (many classes add explorer's packs, etc.).  We should add these categories to the config too, and we should have some in-game representation of packs - possibly as their own item type which expands out into other items, or possibly just as a direct representation in the config to reference. The item type option has the advantage of making it easy to add a whole pack's contents to a character when purchased outside of the class's starting equipment.

**Comment by arbron** [comment]
We definitely need a way to represent equipment packs, though I am not sure whether that should be a new type or if we should wait until we've properly implemented the `container` type and implement them as those.

**Comment by alexdiste** [comment]
Maybe you already speak about that and I am sorry in case, but new item type containers also means that will we have a way to manage backpack, pouch, handy harversack, bag of holding, quiver of ehlonna, etc? They will be a item that can contain other items (like in pf1 system)?

**Comment by djinnstar** [comment]
> We definitely need a way to represent equipment packs, though I am not sure whether that should be a new type or if we should wait until we've properly implemented the `container` type and implement them as those.

That's true! All equipment packs include either a backpack or a chest, so they could easily be just those items, renamed, with their contents added. In that case, this is blocked by #729.

> Maybe you already speak about that and I am sorry in case, but new item type containers also means that will we have a way to manage backpack, pouch, handy harversack, bag of holding, quiver of ehlonna, etc? They will be a item that can contain other items (like in pf1 system)?

No, this `container` type would be specific to DND5E since it implements DND5E's item templates - PF1 would need to implement its own type.
