### ISSUE TITLE
Macro Depreciation Warning - DataModel

### ISSUE THREAD

**Issue by Beerbill** [foundryvtt/dnd5e#1765]
Since v10, i get a warning when using the following in a macro:
```
const tokenD = canvas.tokens.controlled[0];
tokenD.document.update({light: newLight});
```

the warning is:
```
You are accessing the TokenDocument5e#data object which is no longer used.
Since V10 the Document class and its contained DataModel are merged into a combined data structure.
You should now reference keys which were previously contained within the data object directly.
```

I was unable to find any useful information on the matter, or even understand which is the new practice i should adopt when updating token light info or TokenDocument data. Can anyone shed some light on this?

**Comment by unsoluble** [comment]
Hi there! This repo is for tracking core Foundry _bugs_ in particular — you'll get the best assitance with this in the #macro-polo channel on the [Foundry Discord](https://discord.gg/foundryvtt).

**Comment by Beerbill** [comment]
Thank you
