### ISSUE TITLE
npc.js, entity.js 404 Not Found

### ISSUE THREAD

**Issue by KatiaSae** [foundryvtt/dnd5e#1798]
Foundry: 10.285
DnD5e: 2.0.2

Console errors on loading
systems/dnd5e/module/actor/sheets/npc.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)
systems/dnd5e/module/item/entity.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by arbron** [comment]
Any modules enabled? If so, check that they have updated for v10.

**Comment by KatiaSae** [comment]
I should have thought about that, sorry for not checking first. Yes, after some troubleshooting uninstalling modules it looks like LootsheetNPC5e is the issue.
