### ISSUE TITLE
Icon Missing

### ISSUE THREAD

**Issue by afolivieri** [foundryvtt/dnd5e#1805]
The only Icon present are SVG icons, all the others are gone and it badly broke some adventures

**Comment by MaxPat931** [comment]
This macro will migrate all of the icons within your **Unlocked** compendiums to the core icon paths


```
function migrateAllCompendiums(value, key, map) {
    if(!value.locked)
        game.dnd5e.migrations.migrateCompendium(value);
}

game.packs.forEach(migrateAllCompendiums);
```

**Comment by afolivieri** [comment]
Thanks M8, I'll test this ASAP

**Comment by afolivieri** [comment]
worked like a charm, Thanks m8!
