### ISSUE TITLE
The new compendium SRD rules window does not take account of compendium translations

### ISSUE THREAD

**Issue by riccisi** [foundryvtt/dnd5e#1809]
Hi, I'm the developer of the Babele module. The new custom window of the SRD Rules compendium expects English language content. This is a problem for those who use Babele with a translated compendium content. 
I recommend extracting the words 'Chapter' and 'Appendix' in keys that can be translated in order to make the code language independent.
![CleanShot 2022-09-12 at 10 27 45@2x](https://user-images.githubusercontent.com/6490765/189609769-30b8a0fd-82c8-439f-87a7-d5ac0cc5ae19.png)

Thanks.

**Comment by arbron** [comment]
My recommendation is that we store the chapter and appendix data in the flags on the journal entries to avoid potentially messy string parsing. This will avoid difficult situations like languages where the number or letter might come before the other words.
