### ISSUE TITLE
Explore Splitting Damage Rolls into their constituent parts with v10 chatMessage#rolls

### ISSUE THREAD

**Issue by akrigline** [foundryvtt/dnd5e#1818]
Core V10 allows `ChatMessage`s to have multiple `Roll` instances defined for one message.
We could leverage this with how Item Damage works, splitting the item's damage roll into many individual rolls instead of merging them all into one roll.

The perks of this are:
- Each Damage Roll's damage type could be displayed alongside it's individual subtotal, making it easier to handle monsters which are resistant or immune to some of an attack but not all of it (e.g. Flame Tongue Swords)
- It can open the door for more advanced configuration of Item damage grouping in the future, akin to how Roll Groups (and MRE before it) functions.

A quick and dirty demonstration of what I came up with after an hour or so of messing with v10's chat messages:
![image](https://user-images.githubusercontent.com/7644614/191160508-79199ae4-3a32-4a7b-8c06-69ac32290da1.png)

**Comment by RossGosling** [comment]
This encapsulates #1495, so might be worth closing that ticket, I'd just added some designs

My approach doesn't acknowledge the dialog but the output is the core
I think my design holding information within the expandable section may be neater?

I like the Situational Bonus and Extra Crit Damage being distinct as you've laid out!

---

Just expanding upon @sharkbruhaha's design, I think there's other subtle elements like the inclusion of modifiers, being able to see where a +1 or a +10 factored into a total and allowing you to garner a lot more information from the expanded view

| Parts Configuration |
| --- |
| ![image](https://user-images.githubusercontent.com/879127/208489707-de70f483-b0f0-4d63-8697-eea30314defc.png) |

| Roll Before | Roll After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/879127/208489745-65c3804c-d9d2-4339-87ae-d96b0b30bd8e.png) | ![image](https://user-images.githubusercontent.com/879127/208489758-08f99fed-9af5-4662-ba18-2bef44505ad7.png) |
