### ISSUE TITLE
Advancement Pre Requirements + Ability Score Improvement

### ISSUE THREAD

**Issue by caprichozow** [foundryvtt/dnd5e#1832]
Something else that could be added together with the features made by arbron on pull request #1627  

Are the option to better accommodate classes like the Warlock and it's Eldritch Invocations  since some of them require certain levels such as "Ascendant Step" which requires 9th level some that require a certain Pact Boon such as "Aspect of the Moon" which requires the "Pact of the Tome", some can even ask for a mix of both, they can also ask for cantrips (But it's just mostly if not only Eldritch Blast), so requirements of levels and features would be neat, cantrips/spells requirements would be a nice extra, definitely not something really needed tho.

And also have Ability Score Improvement feature built in, just like the Hit Points are built in

Sadly unlike arbron I can't really code so I can't actually contribute besides just giving a suggestion, but hopefully this also gets added :)

**Comment by YugoNumachi** [comment]
Actually, you can select another totem in this case, see the text:

_At 6th level, you gain a magical benefit based on the totem animal of your choice. You can choose the same animal you selected at 3rd level **or a different one._**

**Comment by MaxPat931** [comment]
It would be useful for Warlock Invocations, which can require a certain level in the class and/or a specific Pact Boon

**Comment by caprichozow** [comment]
> Actually, you can select another totem in this case, see the text:
> 
> _At 6th level, you gain a magical benefit based on the totem animal of your choice. You can choose the same animal you selected at 3rd level **or a different one.**_

That was my bad :p I said it mostly out of my memory after chatting about the it with MaxPat over Foundry's discord and also some other people, but yeah there are still certain features that require a certain level and some that require a certain other choice still, some that require certain levels such as "Ascendant Step" which requires 9th level some that require a certain Pact Boon such as "Aspect of the Moon" which requires the "Pact of the Tome", and some that even go as far as requiring a mix of both, Boon and Levels, some even ask for a specific cantrip (Most if not all of them ask only for Eldritch Blas tho), so the point still stands, just not an ideal example :d

**Comment by Zanderaf** [comment]
> It would be useful for Warlock Invocations, which can require a certain level in the class and/or a specific Pact Boon

Some also have requirements like Maddening Hex from XTE:
Prerequisites: 5th level; Hex spell or a warlock feature that curses.

Depending on the warlock subclass, it can also fulfill the prereq depending on how its set up.

**Comment by Fyorl** [comment]
At least level prerequisites are now covered, and the ASI advancement also exists now. Additional prerequisite requirements are covered by the linked issue.
