### ISSUE TITLE
Blank rarity type shows as `&Nbsp;`.

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#1850]
This seems to be new as of 10.287.

![image](https://user-images.githubusercontent.com/50169243/194446610-023f129c-85cd-4a6d-a949-fd02f8236e36.png)

**Comment by lucky-trill** [comment]
This issue seems to still be unresolved in the master.

**Comment by MaxPat931** [comment]
Similar issue also showing up in the Grant Items advancement type when you add a spell
![image](https://user-images.githubusercontent.com/86370342/200442677-6c5a43a9-ea4c-4ca4-a535-c4f46d1e44c5.png)

**Comment by arbron** [comment]
> This issue seems to still be unresolved in the master.

That’s because the fix is for the upcoming 2.1 release, which isn’t ready yet.

**Comment by Fyorl** [comment]
> Similar issue also showing up in the Grant Items advancement type when you add a spell

Already tracked: #1851
