### ISSUE TITLE
Remove `none` from various item fields

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#1857]
Several item fields ("Activation Cost", "Target", & "Range") include a blank value as well as a `"None"` value, both of which mean the same thing. This `none` value should be removed and any items that currently use it should be migrated to a blank value.

**Comment by Varriount** [comment]
Are you sure it shouldn't be the other way around? Remove `""` and display "None" in the UI?

**Comment by Fyorl** [comment]
For the vast majority of drop-downs in the UI where we want to represent 'no active choice made' or 'not applicable', we use a blank value. Jeff has identified a few places where have a blank option as well as a 'none' option, with no functional or semantic difference between the two. Removing the blank value and leaving 'none' would make these places inconsistent with the rest of the UI.

**Comment by Varriount** [comment]
I guess, my general argument is that the entire UI should use "none", rather than an empty selection, since it's more explicit to the user. I realize that would take an outsized amount of effort though.

**Comment by aaclayton** [comment]
Addressed <https://github.com/foundryvtt/dnd5e/issues/1857> and closed <https://github.com/foundryvtt/dnd5e/pull/1893/files> via <https://github.com/foundryvtt/dnd5e/commit/92c4b59fc1195ec438357b55cfbc05f4e4903c58>
