### ISSUE TITLE
Issue auto calculating within number fields. 

### ISSUE THREAD

**Issue by Umustalldie2** [foundryvtt/dnd5e#1861]
In the character sheet, there is an issue with auto calculation within the text fields involving numbers. The health, experience bar, currency, and other text fields like ammunitions. Before the recent update, you were able to highlight the text in these fields and use +/- integers to add or subtract automatically.

**Comment by LiamFallon213** [comment]
Hello, this is the same issue as #1806. I have a push request up with a fix #1860 as of a few minutes ago.
