### ISSUE TITLE
Add base ammunition types & allow configuring them on weapons

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#1866]
Currently, the only way to configure ammunition on a weapon is to have that item on your sheet and to select a specific type of ammo. This means that adding a crossbow to your sheet requires additional configuration in the item sheet before it can be used. Adding the ability to specify a base ammunition type that a weapon consumes would allow clearer and easier ammunition configuration.

```javascript
/**
 * The basic ammunition types in 5e.
 * @enum {string}
 */
DND5E.ammunitionIds = {
  arrow: "3c7JXOzsv55gqJS5",
  blowgunNeedle: "gBQ8xqTA5f8wP5iu",
  crossbowBolt: "SItCnYBqhzqBoaWG",
  slingBullet: "z9SbsMIBZzuhZOqT"
};
```

Weapons could be configured to specify what type of these ammunitions they consume. Then, when added to the sheet if ammunition consumption is set they will automatically attempt to associated themselves with the appropriate ammunition. The ammunition consumption dropdown could also be restricted to only ammo items with the same base type.

This might also benefit from adding an ammo dropdown to the inventory for any weapon that uses a specific ammo type, allowing to be easily selected without manually opening the item sheet. TidySheet5e implements a similar UI design:

<img width="264" alt="Screen Shot 2022-10-11 at 10 37 36" src="https://user-images.githubusercontent.com/19979839/195161350-d867c34a-b5c2-4fb7-88bb-cd7afbc6526c.png">

**Comment by Gib2024** [comment]
This!  You should not have to guess and fumble around why your equipped long bow attack rolls are not consuming arrows.  Finally after a few hours searching on the foundry reddit I found that you had to select the resource consumption type of arrows for my longbow after you add one to the inventory.  Why would this not be part of the SRD items programming?  Need this in ASAP!
