### ISSUE TITLE
Expand the Limited Uses Maximum field for better visibility

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/dnd5e#1867]
The Maximum Uses field is too small to view attribute references, if used
![image](https://user-images.githubusercontent.com/86370342/195163824-788e2e65-40a6-46ba-a0ae-a70b09b8908c.png)

Messing around in the Elements (I know nothing of css) changing `.dnd5e.sheet.item .details .form-group.uses-per input` to `{flex: 1;}` is a bit better 
![image](https://user-images.githubusercontent.com/86370342/195161941-3334d2fb-000a-4d51-9e42-b55564b9092e.png)

but it may be more desirable to differentiate the `text` Max Uses field from the `number` Available Uses and Resource Consumption fields also controlled by `.dnd5e.sheet.item .details .form-group.uses-per input` so that just this field can be expanded, leaving those a bit smaller
![image](https://user-images.githubusercontent.com/86370342/195163182-538281bb-48ac-4952-a0e3-d2bd98e93846.png)

**Comment by krbz999** [comment]
Just changing this line seems to get the desired result.
`.dnd5e.sheet.item .details .form-group.uses-per [name='system.uses.value']` (changing `input` to the name).
<https://github.com/foundryvtt/dnd5e/blob/master/dnd5e.css#L1620>

**Comment by arbron** [comment]
I have a PR I'm working on that does some other changes to these inputs, so I might throw this in with that one.
