### ISSUE TITLE
"&nbsp" value for rarity in loot item sheet

### ISSUE THREAD

**Issue by rwanoux** [foundryvtt/dnd5e#1875]
It seems that the code for a space is coded in the blank property of the selectOptions handlebarHelper. That result with the space code appearing for the first blank option
![unknown](https://user-images.githubusercontent.com/18176317/195894651-c8e0ee40-7b2b-463b-afff-67ea9f423846.png)

**Comment by Fyorl** [comment]
Duplicate of #1850
