### ISSUE TITLE
Unarmed Strike (Monk) Has No Activation Cost

### ISSUE THREAD

**Issue by Dialectikal** [foundryvtt/dnd5e#1884]
This is a small inconsistency that actually does have some impact with other modules.

Your Unarmed Strike (Monk) weapon that is listed under Class Features doesn't have an activation cost. This is inconsistent with the other weapons. Because of this difference, it doesn't show up for the Token Action HUD module, for instance.

**Comment by kjolern** [comment]
I added a pull request to change this into 1 action cost @Dialectikal

**Comment by arbron** [comment]
Already resolved for 2.1 by #1712
