### ISSUE TITLE
Visual Bug with item rarity drop down

### ISSUE THREAD

**Issue by MadManNBlueBox** [foundryvtt/dnd5e#1892]
As the tittle says there is a visual bug on the rarity drop down on an item.
![image](https://user-images.githubusercontent.com/84350572/197899293-8fc6d1d5-c35c-49bd-a801-4eacfb0acb87.png)
Where it should be blank its says `&Nbsp;`

**Comment by unsoluble** [comment]
Duplicate of #1850
