### ISSUE TITLE
Having Honor, Sanity, or a custom ability score enabled triggers an error when trying to load or view any actor in a locked compendium

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#1900]
To reproduce:
- enable Honor, Sanity, or add a small world script to add your own ability score.
- open the console and write this (or simply view an actor's sheet in a compendium):

```js
CONFIG.debug.hooks = true
game.packs.get("dnd5e.heroes").getDocuments()
```
Assuming you have the compendium locked, there is an attempt to update every actor with the new ability scores, triggering an error for each one.

**Comment by MotoMoto1234** [comment]
Having Midi-Qol installed with this bug, causes an endless loop error.  Enable Sanity on sheets, then drag a starter hero out onto the map, sometimes it takes the second actor to start the sequence of errors and its endless.
