### ISSUE TITLE
Suggestion: Make the "Show Players" "Show To: All Players" tick box to change Ownership Configuration on "All Players" section

### ISSUE THREAD

**Issue by InnilToo** [foundryvtt/dnd5e#1902]
On Journals, either on the whole Journal or each individual page, there is the 
![image](https://user-images.githubusercontent.com/33260912/198336656-cbdd57cf-0493-4f66-9702-98a23a9b6ed9.png)
a button that pops up a configuration window
![image](https://user-images.githubusercontent.com/33260912/198336763-fde53ad2-b2c8-4b4f-86c9-2f4b31405622.png)
where you can change ownership depending on which tick is ticked.
However, the "All Players" tick box edits the ownership on all players instead of just the "All Players" section on Ownership Configuration window
![image](https://user-images.githubusercontent.com/33260912/198337290-a2784c9a-ecce-4eca-9933-3a2932300c8a.png)
This is confusing because you can have "All Players: None" and each individual player might for example be and Observer, but then the Eye icon still looks like no one but the DM can actually see the journal page
![image](https://user-images.githubusercontent.com/33260912/198337707-467ac3b5-e7b0-4ba0-848a-f22e81e4b968.png)
Would be nice if the "All Players" tick box while showing the page to players would edit the "All Players" Ownership Configuration and not individual rights. (If specific players are selected, it would work exactly as now. Maybe some additional icons to discern who actually can see what would be nice.)

**Comment by arbron** [comment]
This configuration window is from a module, not core or the dnd5e system. So this request should be made to whichever module adds that window.

**Comment by unsoluble** [comment]
This is actually a core Foundry window; ticket should be moved to the other repo.

**Comment by InnilToo** [comment]
I tested it again, this time on a completely new world without any modules ever enabled to make sure it's a core feature, it is. I mixed up the system with Foundry itself as I never used any other system, my fault.

Made a new issue https://github.com/foundryvtt/foundryvtt/issues/8450
