### ISSUE TITLE
Add units to item weight

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#1909]
Currently all items are assumed to be weighed in pounds. This makes it difficult to represent large vehicle equipment that might weigh tons or to support a metric mode in the system. I propose converting weight into an object with a `units` parameter:

```javascript
weight: {
  value: 5,
  units: "lbs"
}
```

This would also require defining different weight units on config:

```javascript
DND5E.weightUnits = {
  lb: {
    label: "Pounds",
    abbreviation: "lb",
    conversion: 1
  },
  tn: {
    label: "Tons",
    abbreviation: "tn",
    conversion: 2000
  },
  kg: {
    label: "Kilograms",
    abbreviation: "kg",
    conversion: 2.2046
  },
  t: {
    label: "Tonnes",
    abbreviation: "t",
    conversion: 2204.6
  }
};
```

Calculating weight for character sheets would be a simple matter of multiplying the weight `value` by the conversion multiplier specified its unit's config.

**Comment by Skyl3lazer** [comment]
Absolutely insane that this was a breaking change with no backwards compatibility.
