### ISSUE TITLE
Disable grid snapping when placing ability templates onto gridless scenes

### ISSUE THREAD

**Issue by SethGallucci** [foundryvtt/dnd5e#1919]
Currently, when attempting to place an ability template onto a gridless scene, the template will snap to certain points as if a square grid is enabled.

- **Do the Rules as Written (RAW) support this feature? If so, provide some examples.**
    - Yes. The [v5.1 SRD](https://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf) makes no mention of playing on a grid. The only mention of playing on a grid appears in the PHB as a variant rule.
- **Is the missing feature in the System Reference Document? If not, it might still be supportable, but it is worth mentioning in the request.**
    - Playing without a grid is not explicitly mentioned in the [v5.1 SRD](https://media.wizards.com/2016/downloads/DND/SRD-OGL_V5.1.pdf). However, neither is playing on a grid.
- **Does this feature help a GM run a fifth edition game in Foundry VTT?**
    - Yes. GMs (and the players of such games) who do not use a grid, but still use battlemaps (like myself) are plagued by inaccurate ability template placement due to snapping being the default behavior, which is not modifiable via the dnd5e settings configuration menu.

**Comment by Fyorl** [comment]
Related to #1417
