### ISSUE TITLE
Osric rule set - Characters loose vision

### ISSUE THREAD

**Issue by BrotherZinfandel** [foundryvtt/dnd5e#1932]
In the Osric rule set...

Any adjustment to a character sheet causes all characters to loose their vision.

**Comment by Fyorl** [comment]
Is it possible this was posted to the wrong repo? The `dnd5e` system does not support an osric rule set.

**Comment by BrotherZinfandel** [comment]
Kim,

Thank you for your reply.  I am trying to help my DM who is the actual user
of the product.  I believe I may have submitted my Issue under the wrong
GitHub category.

Please close this ticket and I will try to locate the appropriate OSRIC
GitHub to log this under.

Thank you for your understanding.

**Comment by Fyorl** [comment]
No problem, thanks for following up.
