### ISSUE TITLE
Roll damage with flavour

### ISSUE THREAD

**Issue by TPNils** [foundryvtt/dnd5e#1956]
I have been looking into making an automation module where I want to take damage types into consideration. I wanted to reuse Item5e.rollDamage() but this seems to [omit the flavour texts](https://github.com/foundryvtt/dnd5e/blob/f2c7c99193f5c00d327e9fb515b3759919b86e91/module/documents/item.mjs#L1400), would it be possible to add those to the roll?

**Comment by RossGosling** [comment]
This seems like it may duplicate #1818 ?

**Comment by TPNils** [comment]
It's somewhat similar yes, though I would like it to also work when passing the option "without generating chat message"

**Comment by Fyorl** [comment]
Leaving this open to make sure that we implement #1818 such that damage parts are split into their own separate `Roll` instances (with flavour) at the `damageRoll` level, and not just at the level at which they are converted to the chat card.

**Comment by arbron** [comment]
Not sure when this got fixed, but it isn't a problem anymore
