### ISSUE TITLE
Spells start with empty school, but it automatically changes to "Abjuration" as soon as any change is made

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#1958]
`template.json` and `SpellData` both define spell school as blank by default, but the "Spell School" dropdown doesn't allow for a blank school. This results in the spell's school being changed to the first value in the school list (in this case, Abjuration) as soon as any other change is made to the spell.

Two possible solutions:
1. Set a default spell school in `template.json` & `SpellData` and update the school field to disallow blank values
2. Update the "Spell School" select to allow blank values

**Comment by krbz999** [comment]
Neither solution seem to have any drawbacks for the user experience, however (2) would allow a user to create a spell that does not belong to any school at all, which could be valuable.
