### ISSUE TITLE
Add space for creature type on player character sheet

### ISSUE THREAD

**Issue by Tepiltzin** [foundryvtt/dnd5e#1960]
Whilst most playable races are humanoid, there are an increasing number which are not: fairy, satyr, and centaur are fey, plasmoid are ooze, and autognomes are constructs.
NPCs have a space for this on their character sheet but playable characters do not.

**Comment by arbron** [comment]
This will certainly be coming when `race` is added as an item type.

**Comment by krbz999** [comment]
`system.details.type` should also be added to `character` type actors to hold this information, with an identical structure as NPCs, though without "swarm".
