### ISSUE TITLE
[BUG] Using "+X" to add currency overwrites instead of adds the specified amount

### ISSUE THREAD

**Issue by Boefjim** [foundryvtt/dnd5e#1968]
# Description
Removing any inventory currency with "-X" (for example entering "-5" will substract 5 from that currency) does work properly.
However, using "+X" overwrites the value with X instead of adding X to the current currency value.

# Steps
Start with 100 copper:
![image](https://user-images.githubusercontent.com/16748131/208305567-9abe3389-e823-4cf0-994d-bece2286085a.png)
Enter "-5"
![image](https://user-images.githubusercontent.com/16748131/208305583-69e703bb-3b0b-405b-9890-8dec0dbf9a6e.png)
Will end up in 95 copper
![image](https://user-images.githubusercontent.com/16748131/208305591-d8187361-0692-4ee5-95fc-b0d58dfc28be.png)
Enter "+5"
![image](https://user-images.githubusercontent.com/16748131/208305626-61f2fec8-d521-4e71-b545-31468bdafcb5.png)
Will end up with 5 copper (while it should've been back to 100 copper again)
![image](https://user-images.githubusercontent.com/16748131/208305639-abf88610-7301-4478-bdf5-987cf7b29e65.png)

**Comment by krbz999** [comment]
This is fixed in 2.1.0. :)

<https://github.com/foundryvtt/dnd5e/issues/1806>

**Comment by Boefjim** [comment]
> This is fixed in 2.1.0. :)
> 
> #1806

Ah glad to hear!
Is there any estimation on when that version will be published?
