### ISSUE TITLE
Compendiums "Items (SRD)" and "Spells (SRD) are no longer in alphabetical order

### ISSUE THREAD

**Issue by M0nk3yy** [foundryvtt/dnd5e#1969]
I mentiond this on Discord and @krbz999 pointed out they have a `sort` property set that is affecting their order in the compendium.

This would appear to be a bug/unintended as it prevents the compendiums being sorted alphabetically.

**Comment by kjolern** [comment]
Are the sort property supposed to be removed ? Or is there any system to what value they each should have ? 
I could help with this if you want.

**Comment by M0nk3yy** [comment]
Apparently it is usually removed when adding a document to a compendium, unless specifically setting that option to false when doing so.

**Comment by kjolern** [comment]
I have tried to address this in above mentioned pull request @M0nk3yy and @Fyorl .  Please let me know if something should be changed.

**Comment by aaclayton** [comment]
Given the sensitivity of ensuring these compendium changes are correct, I have implemented these changes myself in https://github.com/foundryvtt/dnd5e/commit/16c334a752ffc62a24d348ddb25ca04c63b6551b. Thank you @kjolern
