### ISSUE TITLE
Item Context Menu with option to duplicate/clone items, features, and spells

### ISSUE THREAD

**Issue by RossGosling** [foundryvtt/dnd5e#1970]
Pull Request #1971

---

Provides a new Context Menu on all items, features, spells, and effects across Characters, NPCs, Groups, and Vehicles.

This includes a tailored set of options with a new Duplicate, which simply clones your item, feature, spell, or effect.

Duplicate is not available for Backgrounds, Class, or Subclass after to some discussion in Discord.

---

<details><summary><b>Inventory Screenshots</b></summary>

Lacking the equip icon due to #1972 

  | Inventory (Character Sheet) |
  | --- |
  | ![image](https://user-images.githubusercontent.com/879127/209038209-116d4c3f-f4ea-4ae4-8be8-981830b6e0ec.png) |
  | ![image](https://user-images.githubusercontent.com/879127/209038319-58a30d76-ad19-4545-9d29-4b987f9ef669.png) |

</details>
<details><summary><b>Spellbook Screenshots</b></summary>

  | Spellbook (Character Sheet) |
  | --- |
  | ![image](https://user-images.githubusercontent.com/879127/209021425-9eaaa616-0345-4fb4-9032-6c0e4f044151.png) |
  | ![image](https://user-images.githubusercontent.com/879127/209021462-39ef180d-f44a-4470-b5ac-bfa225eb8d57.png) |
  
</details>
<details><summary><b>Feature Screenshots</b></summary>

  | Features (Character Sheet) |
  | --- |
  | ![image](https://user-images.githubusercontent.com/879127/209021544-a48e5025-8a03-4fcc-8e7c-5780f70d2811.png) |
  | ![image](https://user-images.githubusercontent.com/879127/209038397-410ba5a1-77cf-4808-af3c-555d195a580d.png) |

</details>
<details><summary><b>Effect Screenshots</b></summary>

  | Effects (Character Sheet) |
  | --- |
  | ![image](https://user-images.githubusercontent.com/879127/209038447-e4dea825-a694-4280-9761-33d260195543.png) |

</details>

**Comment by arbron** [comment]
While duplication functionality would certainly be helpful in certain situations, I don't think it warrants a whole new button to further clutter up the UI. This might be a good place to begin adding context menus to the inventory list. That is how I added the ability to duplicate advancements into the system: https://github.com/foundryvtt/dnd5e/pull/1588

**Comment by RossGosling** [comment]
Makes a lot of sense - I'll see about setting that up when I get a chance

**Comment by RossGosling** [comment]
@arbron I've reworked it into a context menu in a near-identical design to advancements

Group sheets are handled differently right now and I haven't supported them, are they getting an update soon? or just distinct and need accounting for?

**Comment by krbz999** [comment]
Regarding (2):
- Is it possible to leave the current buttons as is (equip, prepare, edit, delete) and have only Clone and all future additions in the context menu - or better yet, all buttons in the context menu but leaving the current 4 in their current location as well.

I feel like the idea of having them there in the first place is ideal since they should be readily available and are used often.

**Comment by RossGosling** [comment]
Can see the inclusion of all buttons being good for the context menu

I don't agree with Delete being necessary for quick-access, but I can leave it untouched to uphold the status quo

**Comment by RossGosling** [comment]
@krbz999 I've updated the description with screenshotting supporting Equip, Attune, and Prepare within the context menu
What do you think about the full "Equip Weapon" style, would just "Equip" be better?

Is there anything you think I may have missed?

Thanks!

**Comment by Varriount** [comment]
I think a better place to put such an item's context menu would be to the right of the item's entry, where all the other item manipulation buttons are. For example, using the ubiquitous "more options" icon:
![image](https://user-images.githubusercontent.com/524596/209249995-4cee291a-3ef3-49be-85f6-78ffe961703c.png)

**Comment by RossGosling** [comment]
Potential context menu layouts? with the current being "Left-Align, Small"

| Type | Example |
| --- | --- |
| Left-Align, Small | ![image](https://user-images.githubusercontent.com/879127/209339892-d43e8a16-7d42-4d08-bcc1-2a3774b0d728.png) |
| Left-Align, Full-width| ![image](https://user-images.githubusercontent.com/879127/209339931-85328e8a-fc94-4ed2-82c8-1bbc5f471b12.png) |
| Right-Align, Small | ![image](https://user-images.githubusercontent.com/879127/209339942-ebd8c6a2-e87c-4990-baab-18a86f66cdd6.png) |
| Right-Align, Full-width | ![image](https://user-images.githubusercontent.com/879127/209339951-f5a95d40-e2cc-4310-a88c-9386489ad51b.png) |

**Comment by krbz999** [comment]
The current seems perfectly fine in my opinion (better than the alternatives) and matches the context menu of Advancements.
