### ISSUE TITLE
Option to display wounded/bloodied state

### ISSUE THREAD

**Issue by itteerde** [foundryvtt/dnd5e#2010]
The DMG suggests in chapter 8 Running the Game to indicate when monsters drop below 50% health:

> Players often ask how hurt a monster looks. Don’t ever feel as though you need to reveal exact hit points, but if a monster is below half its hit point maximum, it’s fair to say that it has visible wounds and appears beaten down. You can describe a monster taken to half its hit points as bloodied, giving the players a sense of progress in a fight against a tough opponent, and helping them judge when to use their most powerful spells and abilities.

There should be an option to dispaly that without modules. A step further would be options to have that for players, and for players uncoscious at 0hp, too, for group playing without the PCs knowing each others values precisely, but still making the healers' job playable without extensive talking about the players' characters values.

**Comment by Larkinabout** [comment]
I don't know if this'll already be a thing with the recent Bloodied development, but I've found it useful for Bloodied to be added as a condition to allow it to be added as a Condition Immunity for some creatures. There are some epic monsters that I make immune to Bloodied so it doesn't give the game away or where I deem the monster wouldn't show signs of being Bloodied. It's a nice way to may it a bit more optional in some cases.
