### ISSUE TITLE
Set spells dropped onto NPCs with no spellcaster level to innate spellcasting

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#2024]
Right now all spells dropped onto NPCs start as prepared spells even if that NPC doesn't have any spellcaster levels. A lot of monsters, including most new official monsters, handle their spellcasting through "Innate Spellcasting" or some variant rather than giving the monster spellcaster levels. It would save a lot of time manually setting the casting mode on those spells if the system changed them to innate itself.

**Comment by krbz999** [comment]
It would also be nice if any leveled spells dropped onto a `character` sheet would be set as `pact`, either if the actor has Pact Magic as the spell progression of their main class or as the only spell progression.

**Comment by arbron** [comment]
It would also be a good improvement to be able to choose base on which section of the spell list you drop the spell into. So if you have both pact casting and leveled casting, it will turn into a pact spell if you drop it into the pact section and a regular prepared spell if you drop it into the leveled section.
