### ISSUE TITLE
Background field becomes uneditable at some point after editing it

### ISSUE THREAD

**Issue by jchunick** [foundryvtt/dnd5e#2034]
I am trying to edit a Background in the Background field on a character sheet using the **Default 5e Character Sheet** but that one field is uneditable on all four of my players' character sheets. Their Name, Race, Alignment, Ability Scores, etc. (you get the picture) are all still editable, but not the Background field. At some point it seems to get set from being editable to being uneditable, but I don't know what action/procedure or whatever causes this to happen or if it's a simple coding error.

**Comment by krbz999** [comment]
Troubleshooting steps are best taken on the Discord server, where you first asked this question.

**Comment by jchunick** [comment]
looks like this is as intended when the background is added under Features. Solution found.
