### ISSUE TITLE
HP validation breaks actors and scenes

### ISSUE THREAD

**Issue by dev7355608** [foundryvtt/dnd5e#2040]
https://github.com/foundryvtt/dnd5e/blob/9a81781990174eb0581f2135d0146cd74ea489cb/module/data/actor/templates/common.mjs#L46-L49

2.1.0 didn't include migration for this: pre 2.1.0 it was okay for `hp.min` to be greater than `hp.max`. Actors become invalid and unlinked tokens break the scene they're in.

Also the message should say: "HP minimum must be less than *or equal to* HP maximum".

**Comment by p4535992** [comment]
yea a simple solution is just to show the error:
```
if ( hp.min > hp.max ) {
   console.error("HP minimum must be less than or equal to HP maximum"); 
} 
```
or set runtime the value 0 ?
```
if ( hp.min > hp.max ) {
   console.error("HP minimum must be less than or equal to HP maximum, we set the curretn HP to 0"); 
   data.attributes.hp.min = 0;
} 
```
