### ISSUE TITLE
Show a warning notification when attempting to change an overridden armour calculation, or have the field be disabled with a tooltip

### ISSUE THREAD

**Issue by CDeenen** [foundryvtt/dnd5e#2041]
If 'Unarmored Defense' (from both Monk and Barbarian) from the 'Class Features (SRD)' is added to the character sheet, it is no longer possible to change the AC calculation to anything else.
'Unarmored Defense' should only be active if no armor is being worn, however, equipping armor does not change the AC, and it's not possible to change the AC calculation to 'Equipped Armor'.
I believe that the issue is that the 'Change Mode' of the item's effect is set to 'Override'. I believe that it should either not be set to 'Override', or it should automatically switch to 'Equipped Armor' if the user has equipped any.

Tested on Foundry v10.291 and 5e v2.1.1 and v2.0.2

**Comment by Fyorl** [comment]
There is no automation around Unarmored Defense. If the character should not benefit from Unarmored Defense, you should disable the Active Effect that is granting it. That will allow you to change the armour calculation.

**Comment by CDeenen** [comment]
The problem is that players are not able to disable the effect. It is a passive effect and because it's on their character sheet they cannot modify the effect. The best they can do is delete the feature from their character sheet, which, IMO, is not ideal.
This can be very confusing and frustrating. I had a player who tried to equip armor and couldn't figure out a way to get the AC to be calculated correctly. Having to remove a class feature is, IMO, not a reasonable solution. There already exist an easy way to change the AC calculation, wouldn't it be better to keep everything that changes the calculation in one spot?
Additionally, multiclassing into Barbarian and Monk gives you 2 different Unarmored Defenses, but the effects prevent the player from selecting the one they want to apply.

**Comment by Fyorl** [comment]
If the player owns the character, they should be able to disable the effect by clicking the 'disable effect' icon on the effect, like so:

https://user-images.githubusercontent.com/207433/212113539-763a3328-e380-413d-963f-f21e891347ec.mp4

Is that not working for you?

**Comment by CDeenen** [comment]
Ah, I was looking for a way to switch it off in the Features tab, switching it in the Effects tab does work.
But I still think it is unintuitive. Let's look at this from a (unexperienced) user's perspective in 2 cases, where the AC is either forced or not:

-Forced: A player equips armor, nothing changes. They might try clicking the AC value to manually edit it and the 'Configure Armor' icon appears, however, this will not allow them to change their AC, they can't even override it with a custom value. They might just give up and think it's bugged (which is what my player and I thought). Only if they know that effects are a thing, will they take a look at the Effects tab, and even there it isn't immediately obvious that the Unarmored Defense effect is the cause. And then they have to figure out how you can disable the effect.
-Not forced: Equiping armor just works. If they want to change it to Unarmored Defense, they might try clicking the AC value and notice the 'Configure Armor' option where they can select Unarmored Defense. And they're done.

Looking at those 2 situations, I don't see how overriding it with an effect is the best option.
This way requires a good understanding of how things on the character sheet interact. Although I've been using Foundry almost weekly since before its official release, the way I (and my players) use it doesn't require a good understanding of the character sheet. We use physical dice, my players use paper character sheets (or apps). The Foundry character sheet is mainly used for the DM to quickly check stats and track HP. So we only use it for the basics. And I know of many others who do it similary (especially people who use Foundry for in-person games). Changing something as basic as AC should always be easy. 

If you do want to keep the effect, maybe a notification should pop up when trying to edit it in the 'Configure Armor' screen saying something like "This has been overridden by 'Unarmored Defense', you can disable it in the Effects tab".

**Comment by Fyorl** [comment]
Agreed that using Active Effects for armour calculation is not ideal. This is a temporary solution to align with (some) users' expectations around features granted via the Advancement system.

I will reopen this and reframe it as an issue to provide a useful warning message when attempting to modify an overridden armour calculation as I must admit that it even caught me out when we were doing some testing for this release.

**Comment by arbron** [comment]
It might be valuable to look into a more widespread system for indicating on actor sheets when values are overridden by active effects. This has certainly been an issue that has caught people out elsewhere also.

**Comment by CDeenen** [comment]
I was just playing around with the effects, and I think there's a quick and easy solution: have it default to an inactive effect.
People who want to use it through the Effects tab can to that, others can just ignore it and use the 'Configure Armor' screen.

Notifications should still be a thing, though :). 
And you might want to expand it to anything that can be overridden, because there are probably similar situations for other things

**Comment by Fyorl** [comment]
> I was just playing around with the effects, and I think there's a quick and easy solution: have it default to an inactive effect.
People who want to use it through the Effects tab can do that, others can just ignore it and use the 'Configure Armor' screen.

Having it default to inactive would subvert those other users' expectations I was talking about. There is no right answer here, only preference.

**Comment by CDeenen** [comment]
The right answer would be to add automation to calculate the AC from equipped armor if any is equipped and Unarmored Defense is active. But I understand that this might not be a solution (in the short term?).

**Comment by arbron** [comment]
Add a second `unarmoredCalc` field to AC would allow us to define a second formula that would come into effect when the main calculation is set to `default` but no armor is equipped. It might also make sense to add a property to entries in `CONFIG.DND5E.armorClasses` to indicate which ones are considered unarmored formulas.

That said, the warning for overridden calculations would still be useful.
