### ISSUE TITLE
Canvas drawing failed

### ISSUE THREAD

**Issue by Geektasticdad** [foundryvtt/dnd5e#2042]
After I upgraded to 2.1.1 I get the following error on one of my scenes:
![chrome_fEeMd7zl6O](https://user-images.githubusercontent.com/73676044/211813642-f768f9e8-1ce8-420c-bc55-68cacf4467b7.png)

On the title scene I also get this error:
![chrome_LOHHbNboEb](https://user-images.githubusercontent.com/73676044/211815005-3f98658a-444a-4db0-9e36-034816616d3c.png)

I'm currently running Foundry VTT 10.291 on an Ubuntu 22.04 LTS server. I'm running the following modules:

- Active-Auras
- Character Actions List dnd5e
- Compact DnDBeyond 5e Character Sheet
- Compendium Folders
- D&D Beyond Importer
- Dice So Nice!
- Dice Tray
- Drag Ruler
- Dynamic effects using Active Effects
- Easy Target
- Encounter Statistics
- Foundry Community Tables
- FXMaster
- Give item to another player
- Iconizer
- Introduce Me
- Item Piles
- libWrapper
- Lordu's Custom Dice for Dice So Nice
- Magic Items
- Math.js
- Midi QOL
- Module Compatibility Checker
- Monk's Active Tile Triggers
- Monk's Enhanced Journal
- Monk's Little Details
- Monk's Scene Navigation
- Monk's TokenBar
- Monk's Wall Enhancement
- Multilevel Tokens
- Player Status
- Playerlist Status - Lib for View status on Playerlist
- PnP - Pointer and Pings!
- Roll Tracker
- socketlib
- Tabletop RPG Music
- Token Action HUD
- Tokenizer
- Torch
- Universal Battlemap Importer
- User Latency
- Whisper As

Module Compatibility Checker does not show any incompatibilities in these modules. 

I have rolled my setup back to a previous backup, so I'm not going to proceed with the new 5e game system until it's more stable, but I wanted to report this issue. Most of my scenes work fine, just this two scenes that won't load and I'm not sure how to track down the actor in reference.

**Comment by p4535992** [comment]
If you disable all modules do the scenes load correctly ? If you enable one module at a time and see if one of them is the cause of the error

**Comment by arbron** [comment]
Module Compatibility Tester is only for Foundry V10 compatibility, not system compatibility. You'll want to use Find The Culprit to figure out if any module is causing this.

You can also run this macro to auto-fix any invalid actors:
```js
for ( const id of game.actors.invalidDocumentIds ) {
  const actor = game.actors.getInvalid(id);
  ui.notifications.info(`Fixing actor ${actor.name}`);
  await actor.update(actor.toObject(), {diff: false})
}
foundry.utils.debouncedReload();
```

**Comment by Geektasticdad** [comment]
I ran found the culprit, disabled ALL modules, and ran @arbron's script ... still broken.

**Comment by Geektasticdad** [comment]
Is there a way to identify which actor wGdJFAwDtFcRMMvJ represents?

**Comment by unsoluble** [comment]
Could we get you to pop into the #dnd5e channel on the discord? Much better place for back-and-forth troubleshooting.

**Comment by Geektasticdad** [comment]
I found the actors.db file and narrowed the issue down to Actors created by the Item Piles module. When I removed all the Item Pile loot actors and tokens, then upgraded to 2.1.1, everything seems to be fine across the board.

**Comment by Geektasticdad** [comment]
I have no need to keep this open, the developers of Item Piles is not going to bother trying to fix it because I won't spend hours trying to reproduce it for them.

**Comment by Haxxer** [comment]
There's no need to be snarky :) I requested to get the error from your console with only item piles & dependencies enabled, as I cannot reproduce it myself. It's incredibly hard to fix something if you don't know what the cause is.

> I have no need to keep this open, the developers of Item Piles is not going to bother trying to fix it because I won't spend hours trying to reproduce it for them.
