### ISSUE TITLE
Token auto-sizing cannot be overridden

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/dnd5e#2049]
Originally reported by SageWendigo#3593 https://discord.com/channels/170995199584108546/956306859491471420/1059326121168085032

**ALL MODULES DISABLED?**  
True  
**OS, Hosting, Browser (if applicable):**  
Windows 10  
**Short Description of bug:**
 Actor scaled to size category in 5e system (gargantuan to 4x4) independent of token size (in terms of grid squares). Importing correctly sized compendium actor resets size to 4x4, and exporting correctly sized actor and then reimporting it resets the size to 4x4.  
**Simple steps to reproduce the bug:**  
Create an actor, specify non-standard grid-size, then export to compendium and import the actor.  
**Screenshots and/or console errors:**

![image](https://user-images.githubusercontent.com/207433/212166174-d0860399-2696-4ced-9f83-9266b627da42.png)

**Comment by Fyorl** [comment]
It should probably only auto-size if no size data is provided, or if it's the default (1x1).

**Comment by ShannonMcG** [comment]
+1 For this. 

**Use case:** As a gamemaster building a compendium of actors to run adventures, when I set the token size for an actor, then put the actor in a compendium for later use, I expect it to have the same size when I re-import the actor from the compendium.

**Comment by Fyorl** [comment]
This has been addressed with the resolution to #2228
