### ISSUE TITLE
Spells added to vehicle are not converted to scrolls

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2055]
For both types, one can programmatically add a `spell` type item to each actor type using a script.

When using the drag-and-drop method, only `group` creates a scroll instead, where `vehicle` simply adds a Spell under 'Cargo'.

**Comment by arbron** [comment]
We currently don't do any restriction on item types that are added programmatically, but adding spells to vehicles should definitely convert them to scrolls.
