### ISSUE TITLE
Can't use decimal for movement

### ISSUE THREAD

**Issue by dmizrahi** [foundryvtt/dnd5e#2058]
Hello,
Since the 2.1.x update, we can't use decimal for movement. The character sheet round up the value. It's annoying because Halfling for instance have a movement of 7.5m.
Thanks !

**Comment by dev7355608** [comment]
The movement speed fields should be noninteger with step size 0.1.
https://github.com/foundryvtt/dnd5e/blob/b28a8680290ca47675fa86c28f1ec28843a2ac6d/module/data/actor/templates/attributes.mjs#L30-L44
https://github.com/foundryvtt/dnd5e/blob/b28a8680290ca47675fa86c28f1ec28843a2ac6d/module/data/actor/group.mjs#L41-L49
