### ISSUE TITLE
Token Bar Attributes changed in 2.1.0

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/dnd5e#2069]
The available Attributes for Tokens changed in 2.1.0 making `attributes.ac.value` available, it was replaced by `attributes.ac.flat` which does not show a value on the token bar. Several other attributes seem to have changed as well, but this one is the attribute that has been mentioned the most in the discord

v2.0.3 and below
![image](https://user-images.githubusercontent.com/86370342/212984745-1dfeeada-a371-44c9-9a5c-a3a36429d96a.png)

v2.1.0
![image](https://user-images.githubusercontent.com/86370342/212985141-f4907990-ddae-469c-b727-418f1e5b4425.png)

**Comment by Fyorl** [comment]
This is a core issue: https://github.com/foundryvtt/foundryvtt/issues/8726
