### ISSUE TITLE
Setting "Critical Damage Maximize Dice" maximizes crit dice instead of base dice

### ISSUE THREAD

**Issue by Raccoomph** [foundryvtt/dnd5e#2078]
Causes issues with Brutal critical, since the additional dice are always maximized.

**Comment by arbron** [comment]
It seems to be only multiplying the base dice for me:

<img width="296" alt="Screenshot 2023-01-20 at 11 03 05" src="https://user-images.githubusercontent.com/19979839/213784371-cd53f6c0-8954-4099-b967-3be20219ca5b.png">

**Comment by Raccoomph** [comment]
<img width="470" alt="image" src="https://user-images.githubusercontent.com/122682880/213878335-54721870-ee9b-4888-985e-8cf5a4891e7b.png">

This is what it looks like for me.

With these options on:

<img width="371" alt="image" src="https://user-images.githubusercontent.com/122682880/213878365-152e4dac-ba03-4a64-8c8d-46d63a97eb8e.png">

<img width="406" alt="image" src="https://user-images.githubusercontent.com/122682880/213878386-5911cf78-e0d8-470e-909b-04ca2cab05b6.png">

**Comment by arbron** [comment]
And if you disable whatever rolling module you are using, does it work as expected. It looks like that might be a module issue not a 5e issue.
