### ISSUE TITLE
ESLint compatibility issues with Node 19

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#2091]
- The version of `eslint-plugin-jsdoc` that is set up in `package.json` doesn't support Node 19.
- `gulp-estlint7` has been deprecated and replaced by `gulp-eslint-new` to support future versions of `eslint`

**Comment by Fyorl** [comment]
Does `gulp-eslint-new` run correctly on Node 14 (the current minimum for v10)?

**Comment by Fyorl** [comment]
> It supports Node 14 but strangely not Node 15. I don’t know what is going on with that. If that’s an issue we can remove that change and stick with just the plug-in version bump which was the one causing the install issues in Node 19.

I can understand running an old LTS release, but it would be a bit strange to be running an old odd-numbered release. Still, if `gulp-eslint7` is only deprecated, lets just keep using that for now, and bump all our dependencies once dnd5e does a minimum v11 release.
