### ISSUE TITLE
Tooltips for Inline Rolls should display formula as written

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/dnd5e#2105]
Current tooltip
![image](https://user-images.githubusercontent.com/86370342/214442667-58556180-75b8-4c5e-ab22-92b59da00068.png)

Proposed tooltip:
![image](https://user-images.githubusercontent.com/86370342/214442612-45d17c5b-81c7-437d-a59f-daf5ed77b171.png)

**Comment by arbron** [comment]
Those are provided by core, so you should probably file that over the core repo.

**Comment by MaxPat931** [comment]
Moved 
https://github.com/foundryvtt/foundryvtt/issues/8810
