### ISSUE TITLE
Carpentry and Woodcarving tool icons are swapped

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/dnd5e#2106]
The icon for Carpentry Tools is a wood chisel, while the icon for Woodcarver's Tools is a saw. These should be swapped; Carpentry is for large things that would take a saw, while Woodcarving is for small things you'd whittle or otherwise finely manipulate.

**Comment by unsoluble** [comment]
This is the tiniest bug that I am 100% here for.

**Comment by M0nk3yy** [comment]
@JPMeehan The icons were chosen based on the descriptions provided in Xanathar's Guide to Everything.

> Carpenter's Tools:
> 
> Carpenter’s tools include a _**saw**_, a hammer, nails, a hatchet, a square, a ruler, an adze, a plane, and a **_chisel_**.
> 
> Woodcarver's Tools:
> 
> Woodcarver’s tools consist of a knife, a gouge, and a **_small saw_**.

They both contain a saw and one contains a chisel. Icons were selected accordingly.
