### ISSUE TITLE
Action Surge and Channel Divinity Advancement issue

### ISSUE THREAD

**Issue by bkvam** [foundryvtt/dnd5e#2112]
I'm getting the following message in a yellow banner at the top of the character sheet for fighters and clerics with releases 2.1.3 and 2.1.4:

The Maximum Uses formula withing Action Surge has references to missing data: @scale.fighter.action-surge.

The same thing is happening for Channel Divinity (Cleric).

I exported the data files and found an entry in the advancement object of the fighter class (items.fighter.system.advancement:
          {
            "_id": "sh0ih4vmnv6qsjwp",
            "type": "ScaleValue",
            "configuration": {
              "identifier": "action-surge",
              "type": "number",
              "scale": {
                "2": {
                  "value": 1
                },
                "17": {
                  "value": 2
                }
              },
              "distance": {
                "units": ""
              }
            },
            "value": {},
            "title": "Action Surge Uses"
          },
which looks like it did in the previous version of the file under 2.1.2.

Since this data is here, it seems that the code looking for these entries is looking in the wrong place.

I replaced the items with fresh ones from the compendium and still have the problem.

**Comment by arbron** [comment]
This is a module bug with DAE, not with the system. You’ll have to wait for the module to update or disable it in the meantime.
