### ISSUE TITLE
Allow setting of item range without activation cost

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#2116]
There are a number of passive features such as auras that need a range defined but are still classified as "Passive". Right now the only way to set their ranges is to set them to have an activation cost, set their range, and then remove the cost. The range field should be available regardless of whether and activation cost is selected.

**Comment by krbz999** [comment]
'Limited Uses' would also benefit from this, since a number of features simply act as a passive resource for other features (Channel Divinity, Sorcery Points).
