### ISSUE TITLE
Add information on additional formulas for Dice scale values

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#2129]
Currently dice scale values list and provide a copy button for the whole formula (`@scale.fighter.superiorityDice`) but not to the new formulas needed to access portions (`@scale.fighter.superiorityDice.number`, `@scale.fighter.superiorityDice.faces`, and `@scale.fighter.superiorityDice.die`) making those formulas difficult to discover.

**Comment by MaxPat931** [comment]
Could we get these documented in the wiki in the meantime? https://github.com/foundryvtt/dnd5e/wiki/User-Guide
