### ISSUE TITLE
Migrating from 2.0.3 to 2.1.4 deleted some actors

### ISSUE THREAD

**Issue by cs96and** [foundryvtt/dnd5e#2141]
I just upgraded from 2.0.3 to 2.1.4 and noticed some migration errors in the console log.  When I tried to look up the actors that it was complaining about they had been deleted.  Luckily I had a backup to revert to, so I could then look up the actors and discover what was wrong with them.

One of the actors was a PC that had the string `"insufficient"` as their current XP.  We do not use XP, so no idea how this string got there, but it seems a bit mean to completely delete the actor because of this.

All the rest were old NPCs that were imported from Roll20 years ago.  They had an armor type string (e.g. `"splint"` or `"leather armor"`) as their custom AC formula.  The actors weren't even using the custom formula (they were using "Natural Armor"), so again, I'm not sure why these actors were deleted completely.

**Comment by Fyorl** [comment]
The actors aren't actually deleted, they're just marked as invalid, so they're hidden from view but the data still exists. What's supposed to happen is that, if validation errors are detected, your world should flip to a permissive validation mode so that your actors are still visible, but there are evidently some classes of validation error for which that does not happen.

If you could zip up your world's `actors.db` and send it to us, that would help us understand what's happening.

**Comment by cs96and** [comment]
I've manually fixed the errors and upgraded to 2.1 now, so don't have the original actors.db to hand, and the post-migration db is now fine.

I do have a json export of one of the actors that had an issue  though (export was taken before the migration).  You can see the error in the `ac.formula`...

```json
      "ac": {
        "flat": 16,
        "calc": "natural",
        "formula": "studded leather",
        "min": 0
      },
```
[fvtt-Actor-boram.json.txt](https://github.com/foundryvtt/dnd5e/files/10547311/fvtt-Actor-boram.json.txt)

**Comment by cs96and** [comment]
I suppose another problem is that I only noticed these errors because I was watching the console.log.  I feel like foundry should have popped up a window after the migration with a list of errors, and an explanation that the actors were hidden, and how I could access them.

Also the error in the console log only output the actor id.  It would have been very helpful to see the actor names in the errors too.

**Comment by Fyorl** [comment]
> I suppose another problem is that I only noticed these errors because I was watching the console.log. I feel like foundry should have popped up a window after the migration with a list of errors, and an explanation that the actors were hidden, and how I could access them.
> 
> Also the error in the console log only output the actor id. It would have been very helpful to see the actor names in the errors too.

Thanks for following up. Improvements in validation logging, UI, and UX are coming in v11.

**Comment by somanyrobots** [comment]
just chiming in, looks like this happened in my game to. Not sure which version we upgrade from, but the "to" was 2.1.2. still figuring out the scope of the problem, but looks like a lot of actors silently went away :/

**Comment by MaxPat931** [comment]
Run this macro to fix the validation errors for those actors.
https://gist.github.com/dev7355608/66b3758ce30353c94d1c7be49f093f99

**Comment by somanyrobots** [comment]
a) that is _impressively_ quick!
b) unfortunately that script errors out
```
commons.js:4090 Uncaught (in promise) Error: undefined. NPCData Model Validation Errors
[NPCData.attributes]: Model Validation Errors
[NPCData.attributes.ac]: Model Validation Errors
[NPCData.attributes.ac.formula]: Roll.safeEval produced a non-numeric result from expression "natural armor"
[Detected 3 packages: system:dnd5e, advanced-macros, lib-wrapper]
```

**Comment by MaxPat931** [comment]
1. thanks ;)
2.  try with no modules enable
3. otherwise hop to the discord for assistance

**Comment by dev7355608** [comment]
Foundry 10.291 is required to successfully migrate invalid AC formulas (#2043).

**Comment by somanyrobots** [comment]
> Foundry 10.291 is required to successfully migrate invalid AC formulas (#2043).

aha, this fixes that error! fantastic, ty. it now fixed most of the missing actors, though there are errors on a few that manage to crash foundry. still, gets us good to go for tonight's session - will debug further later this week.
