### ISSUE TITLE
Add Resources to NPC character sheets (or even group and vehicle sheets too)

### ISSUE THREAD

**Issue by XardisSevenfold** [foundryvtt/dnd5e#2145]
I find myself needing to track an additional value for both PCs and NPCs, and needing it represented in a token bar, it's easily implemented via Resources on PC side, but there is no such option on the NPC side, or even on group or vehicle sheets. I can have it as a feature, but then editing it gets far more convoluted to do to every actor, on their initial setup, and dynamically in game. And then I cannot have it link back to a token bar.

**Comment by Zanderaf** [comment]
Would open up a lot of things like tracking Ki and Legendary resistances, and custom resources that a npc might use in a fight- I've just kind of been cobbling it together through Bar Brawl

**Comment by krbz999** [comment]
NPCs do have a few limited resources, one of them being legendary resistances.

![image](https://user-images.githubusercontent.com/50169243/216166321-f222b52f-887a-4aa0-bbac-c5fbbdcb5af3.png)

**Comment by XardisSevenfold** [comment]
That doesnt help in a situation where I need both my new mechanic and to use legendary resistance/action.

**Comment by Shayulghul** [comment]
Yeah, it would be nice to have resources on group actors.

**Comment by Rabulias** [comment]
In light of DND5E 3.X, is this still a thing?
