### ISSUE TITLE
Monsters (SRD) seems to have missing token and portrait images

### ISSUE THREAD

**Issue by DMSei** [foundryvtt/dnd5e#2149]
I tried to place down a Silver Dragon for my players the other day and there was no token or portrait for a silver dragon associated to the Monster stat block. Not a difficult to solve problem, mind you. Solved by grabbing one from a different source. It was however unfortunately not a top down version. I don't know if this is an issue, or if this is just not yet finished. If it is the latter, please let me know so I can delete this post.

**Comment by unsoluble** [comment]
Just hasn’t been completed yet.
