### ISSUE TITLE
[REVERSION Issue] Item usage field workflow is broken

### ISSUE THREAD

**Issue by sharkbruhaha** [foundryvtt/dnd5e#2163]
The item usage configuration workflow has reverted to a prior versions issue, but magnified by nearly every field.

The fields are no longer able to be tabbed through to configure an item as the default has reverted to the "none" setting preventing anything from being entered in the field till this is changed. This was fixed many versions ago in the "Target' line, but now not only is that issue back, but the Range line is also suffering from this issue.

Also, the Target line is inconcistent in its failure to let you configure the first two elements. The 2nd field's dropdown box fails to be set to "Feet", but all three of the other settings: "Miles", "Meters", and "Kilometers" blank out if you try to set prior to setting the 3rd field.

Hopefully this reversion can be fixed quickly, as it drastically impacts the time to create items and usability for people.

**Comment by arbron** [comment]
Intentional change and this workflow has already been changed for the upcoming 2.2.
