### ISSUE TITLE
Add character weight to details

### ISSUE THREAD

**Issue by rjbprime** [foundryvtt/dnd5e#2164]
To whom it may concern,

Is it possible to revert the ``details`` attributes of an actor, (more specifically ``details.weight``) for use in automation of trap calculations. Certain traps, such as Pressure Plates and Covered Pits, occasionally mention a minimum weight to trigger the trap, or mention things such as the weight of a kobold or similar size creatures do not trigger it.

Having the ``details.weight`` attribute on an actor allows easier automation of whether an actor's ``details.weight`` combined with their ``actor.system.attributes.encumbrance.value`` to trigger the trap, and all that entails.

Kindest regards.

**Comment by arbron** [comment]
These were never part of the system, they were added by the Tidy Sheet module.

**Comment by TyrasNistru** [comment]
Isn't it possible to incorportate it officially into the module?

**Comment by krbz999** [comment]
> Isn't it possible to incorportate it officially into the module?
> 
> I'm facing problems as well because of the system.details.maxPreparedSpells field that they decided to remove from there to a module-specific one. Problem is, a lot of modules used this property (such as the importer) and then it broke a lot of things...
> 
> Making them official would be an incentive to create a standard to be used by the modules, instead of making them harder to share across modules.

Then simply reference its new location. Module developers are no doubt aware that they are or were using a property added by another module.

There is a different, related issue here: https://github.com/foundryvtt/dnd5e/issues/1021

**Comment by TyrasNistru** [comment]
Why change a lot of modules in favor of changing only one?

> Module developers are no doubt aware that they are or were using a property added by another module, which should never have existed in that location.

Is it such a crime to have those properties under `details`?
