### ISSUE TITLE
Crewed/uncrewed toggle button on actions/equipment in vehicle sheets broken on 2.1.4

### ISSUE THREAD

**Issue by Gawdl3y** [foundryvtt/dnd5e#2166]
The button to toggle the crewed/uncrewed status of an action or equipment in vehicle sheets does not do anything. No errors are output into the console when clicking it. I have reproduced this on a totally vanilla setup with no modules active and a completely fresh world.

Repro steps:
1. Create a new vehicle actor
2. Add an action to it
3. Click the crewed status toggle button on the new action in the list

![image](https://user-images.githubusercontent.com/279900/217451265-2f60fefa-f10a-4466-8b40-f1bf39db92ca.png)

**Comment by krbz999** [comment]
Seems like `item.system.crewed` is not a property on items anymore whatsoever. And secondly, the HP of items cannot be edited from the sheet at all either.

**Comment by krbz999** [comment]
Also seems like `threshold` does not appear at all.

**Comment by arbron** [comment]
> Seems like `item.system.crewed` is not a property on items anymore whatsoever. And secondly, the HP of items cannot be edited from the sheet at all either.

Strangely enough `system.crewed` was never defined in `template.json`, so it got overlooked in the conversion to data models.
