### ISSUE TITLE
Move `equipped`, `attuned`, and `crewed` tracking to actor data

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#2167]
Currently items hold information on whether they are equipped, attuned, or crewed, but this information is only relevant as a relation between the actor and the item itself. It would make more sense and remove the need for most `_preCreate` modifications of item data if these pieces of data were instead tracked by the actor itself and then derived on the item.

**Comment by wonkoderverstaendige** [comment]
Would this set up having the item store information if (and how) attunement is required, instead of the [not required, required, attuned] options which do not separate the state from the requirement?
