### ISSUE TITLE
Standardize item system type format

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#2168]
Currently an item type is tracked in several ways depending on the type of item:
- **consumable**: `system.consumableType`
- **equipment**: `system.armor.type` (even if it isn't armor), `system.baseItem`
- **feat**: `system.type.value`, `system.type.subtype`
- **tool**: `system.toolType`, `system.baseItem`
- **weapon**: `system.weaponType`, `system.baseItem`

I propose migrating these values to a more standard format to match features:
```js
{
  system: {
    type: {
      value: "",
      subtype: "", // For features
      baseItem: "" // For equipment, tools, and weapons
    }
  }
}
```

This would make it easier to create indexes on these fields rather than needing to track a different indexed field for each item type.

**Comment by Ikaguia** [comment]
I believe I caught all the existing uses you mentioned, but was unsure on how to do migration; on my PR it is done just via dataModel migration

**Comment by Ikaguia** [comment]
@arbron I would suggest altering the name of the property from `system.type` and `system.type.subtype` to `system.category` and `system.type.subcategory`, since that would make it less likely to be confused with the item's `type` property.

**Comment by Ikaguia** [comment]
@arbron sorry to ping you a second time, but what is your opinion on the suggestion above?

**Comment by Ikaguia** [comment]
About the compendium migration, should that be done as a separate issue or... ?

**Comment by Fyorl** [comment]
> About the compendium migration, should that be done as a separate issue or... ?

Best to wait for the changes planned in #2665 first.
