### ISSUE TITLE
Spell to scroll conversion is missing original text

### ISSUE THREAD

**Issue by BrotherSharper** [foundryvtt/dnd5e#2181]
Normally, when a spell is dragged in the ineventory tab, it will turn into a spell scroll.
However, as of the latest 2.1.4 version (or even earlier) only the description of srcolls in general is added instead of having original text + scroll description text.

![image](https://user-images.githubusercontent.com/41280723/218241769-e815ff60-c287-468b-9678-b6b2c4eae858.png)

**Comment by krbz999** [comment]
Seems that something changed and now the system doesn't like that we use `"description.value"` instead of `description: {value`.
