### ISSUE TITLE
Class Sheet Journal sets dropped classes as both class and archetype

### ISSUE THREAD

**Issue by Ikaguia** [foundryvtt/dnd5e#2194]
There is no `break` at the end of the switch case statement, thus classes are treated as both class and archetype.
https://github.com/foundryvtt/dnd5e/blob/4de2d2aabb078f0d18a26ea2d94a754ba8d99510/module/applications/journal/class-sheet.mjs#L440

**Comment by krbz999** [comment]
Duplicate issue: https://github.com/foundryvtt/dnd5e/issues/2124
Fixed here: https://github.com/foundryvtt/dnd5e/pull/2126
