### ISSUE TITLE
Class not progress properly when I have a backpack

### ISSUE THREAD

**Issue by jdeon** [foundryvtt/dnd5e#2209]
When the character sheet have a backpack, they're an error in the progression of the class.
When you add a level, it has error on the container resulting with the partial update of new feature. For example, the max hp field didn't update.

**Comment by arbron** [comment]
Is this with all modules disabled? Can you post a screenshot of the error message in the console (F12)?

**Comment by jdeon** [comment]
Yes, all module were disabled.
There was no error in console but find exception in #updateData method with bag currency. It still don't update the hp max but I don't find the backpack item in updateData anymore.
I try to recreate it, with heroes compodium, I succeed when I created it with module but not when I create without.

 Perhaps a module have malformed some data. I'm going to investigated more.
