### ISSUE TITLE
Add ability to specify ability score required for multiclassing into a class

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#2212]
Classes generally have a minimum value that a certain ability score (or multiple in some classes) must meet in order to to multiclass with it. This information should be available in the class in some way (though not enforced with core dnd5e). This would also be able to be displayed on the class summary journal sheet in a multiclassing section.

**Comment by Zanderaf** [comment]
An option to ignore multiclass stat requirements would also be nice to have.

**Comment by Zarhog** [comment]
Hello, I would also like to request this feature. as there are modals in the works that would benefit greatly from this feature.
