### ISSUE TITLE
Advancement Type: Size

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#2220]
This advancement type allows a race to set a character's ~~type, movement, senses, and~~ size.

## Level Up Interface

~~This interface will display the values for the race being added.~~ If the race offers a choice of size, that option will be presented.

## Configuration

~~The `type`, `movement`, and `senses` object are the same as are presented in actor data, and are `null` if they are not set (e.g. Humans don't get darkvision, so `senses` will be `null` for them).~~

The `size` property is an set of size choices.

```javascript
{
  "size": ["med"]
}
```

## Value

Stores the size choice selected as well as the former value of any other properties that were replaced so they can be accurately reversed.

**Comment by ccjmk** [comment]
I find the name Race Properties slightly deceiving as some classes also set movement or senses, but I am at a loss with suggesting a better name. Character Properties sounds a little too generic to me, swinging too far on the opposite direction..

**Comment by kaelad02** [comment]
If you're still taking name suggestions, maybe Racial Traits since the feature sounds similar to #1405

**Comment by emwhalen** [comment]
Perhaps what you're discussing is Body Properties or Physical Properties. I have no strong feelings about it.
