### ISSUE TITLE
DnD5e mod

### ISSUE THREAD

**Issue by Dalkan75** [foundryvtt/dnd5e#2225]
hello, 
I use a modified XP table, I usually modify the XP string dedicated to players. 
Before I used the forge as a server, but since I use a dedicated server, i must have a json file for upload.
My question: Can you help me how to turn post-edit zip file (or folder) into json file? 
What procedure can I do? Any app?
Thank you

Roberto

PS: sorry for my bad english

**Comment by unsoluble** [comment]
Please join us on the [Discord](https://discord.gg/foundryvtt) for general use questions like this. :)

**Comment by Dalkan75** [comment]
I joined Discord and reposted the problem (which I fear will be ignored), but in the meantime I'm waiting for someone to answer my question.

**Comment by Dalkan75** [comment]
i fixed it with a .js file in the world folder and a script referencing it.
