### ISSUE TITLE
Skills defaulting ability to Dexterity

### ISSUE THREAD

**Issue by elizeuangelo** [foundryvtt/dnd5e#2227]
When I try to create an NPC and I pass only the data regarding the skill proficiency, it always defaults the skill ability to "Dexterity".

`Actor.create({name:'teste',type: 'npc','system.skills.his.value':1})`

![image](https://user-images.githubusercontent.com/56921633/222513681-a615eb31-ca6a-4b26-8f1d-098fef82e5c0.png)

This didn't happened in earlier versions?

**Comment by arbron** [comment]
I'll have to give this a test, but I believe that should be fixed by this PR: https://github.com/foundryvtt/dnd5e/pull/2179

**Comment by Fyorl** [comment]
Related to #1933 
Should be fixed by #2388
