### ISSUE TITLE
Improvements for Attuned Item visibility, bonus to hit with spells, and amount of prepared / known spells a character can have.

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/dnd5e#2235]
Not sure if this is already posted anywhere but a few suggestions:

- Maybe updating how the spells tab looks like in the character sheet, adding in a +x to hit with spells.
- Adding in an indicator on how many spells a character can prepare / know.
- Adding in an indicator to show how many items you are currently attuned to / can attune to in the inventory tab.

**Comment by Fyorl** [comment]
That last bullet point is covered by #1309 but I will mark this as a feature request for the first two. In general though, please split up issues separately.

**Comment by arbron** [comment]
First and third issue have been solved (#1309 and the sheet redesign), second point is a duplicate of https://github.com/foundryvtt/dnd5e/issues/1021 but I'll leave this open for now for reference.

**Comment by Zanderaf** [comment]
I think everything in this issue might be already solved with the recent 4.0 updates iirc.
