### ISSUE TITLE
Template drawPreview failing silently when failing validation

### ISSUE THREAD

**Issue by rikmarais** [foundryvtt/dnd5e#2250]
From `items.mjs` `use` function, when a measured template is placed when the template dimensions exceed the scene dimensions, `drawPreview` validation fails silently with an error. 
`Uncaught Error: Model Validation Error: Invalid MeasuredTemplate distance which exceeds maximum dimensions for the Scene`

However, the error gets caught in the calling `use` function and not logged. This can lead to users believing that the actors or abilities are somehow broken when testing out abilities. A console log or UI notification would be helpful for avoiding confusion.

```js
	// Initiate measured template creation
    let templates;
    if ( config.createMeasuredTemplate ) {
      try {
        templates = await (dnd5e.canvas.AbilityTemplate.fromItem(item))?.drawPreview();
      } catch(err) {}
    }
```
![image](https://user-images.githubusercontent.com/34374883/227594527-61c2f241-42ce-41ea-9ff0-a49c17dd0a0f.png)

To replicate, try to place a lightning bolt template for the Archmage on the `Foundry Virtual Tabletop` base scene (see included json exports for scene and actor)

[archmage and scene.zip](https://github.com/foundryvtt/dnd5e/files/11064773/archmage.and.scene.zip)

**Comment by Fyorl** [comment]
Seems that this particular piece of Measured Template validation is no longer needed or used (in v11 at least), but I have made changes to not swallow the error message when template creation fails.
