### ISSUE TITLE
Initiative duplication in combat tracker

### ISSUE THREAD

**Issue by archeresky** [foundryvtt/dnd5e#2255]
Not sure whether it's core foundry behaviour or dnd5e, but I was pointed in v10-feedback that it might be more of a dnd5e issue.

When you make an encounter on a separate scene not being viewed by a player, it's still possible to roll initiative from that player's sheet, despite them not having any active encounters on their currently active scene. If you had toggled combat state before on their token that is on the scene where the encounter is taking place, their initiative will be duplicated instead of being updated on the already existing tracker entry like below. In short, you will have separate initiative entries from the sheet and the token.

![image](https://user-images.githubusercontent.com/73297245/229292710-91bd5a47-3186-4137-803e-c46395139926.png)

Tested on Foundry 10.291 and dnd5e 2.1.5

**Comment by Fyorl** [comment]
Seems likely this is a core bug, but I will tag it for investigation.

**Comment by Sinled** [comment]
Also have this problem, it's really annoying

**Comment by Fyorl** [comment]
I wasn't able to reproduce this when I investigated; it may well have been a core bug that has since been fixed.

**Comment by archeresky** [comment]
Did you test on v10 or v11? If on v11, it might’ve been a core bug then, haven’t had the chance to test stuff on v11 yet.
