### ISSUE TITLE
Error in 5/10/5 hex distance measurement

### ISSUE THREAD

**Issue by caewok** [foundryvtt/dnd5e#2256]
Foundry: v10.291
dnd5e: v2.1.5
Browser: Version 112.0.5615.49 (arm64)
browserclient OS: macOS 13.3
Running Foundry on NodeJS locally
No modules running.

Measuring 5/10/5 diagonals using `canvas.grid.measureDistance` or the ruler gives erroneous measurements on hex maps. 

Example:
Place two tokens at sufficient distance to require at least two diagonal moves to get from one to another. Measure using ruler or alternatively:

```js
A = _token.center(); // {x: 2425.6217782649105, y: 2590}
B = _token.center(); // {x: 2970.6217782649105, y: 2905}
canvas.grid.measureDistance(A, B, { gridSpaces: true }) // Returns 30 but should be 35 using 5/10/5 rules
```

**Comment by Fyorl** [comment]
I would have thought 5/10/5 rule would not apply to hex grids. The passage in the DMG where it talks about this rule does not specify, but it does say this:

> count every square as 5 feet, even if you’re moving diagonally. Though this is fast in play, it breaks the laws of geometry and is inaccurate over long distances.

This is not true for hex grids though. Moving diagonally on a hex grid does not break any laws of geometry and is not inaccurate over long distances, so the rationale for implementing such a rule is not there. In fact, this is one of the advantages of using a hex grid in the first place: diagonals require no special treatment.

So, it seems like the correct behaviour to not apply the 5/10/5 rule to hex grids.
