### ISSUE TITLE
'1dc' roll terms erroneously mapped to '1d2' in item derivedDamage labels

### ISSUE THREAD

**Issue by jmmerchant** [foundryvtt/dnd5e#2281]
This is purely a cosmetic issue and doesn't affect rolling.  If you add one or more '1dc' terms in the damage formula for an item, the 'derivedDamage' labels shown in the description tab of that item will instead contain '1d2' (or 'nd2' for n terms).  This is incorrect as '1dc' is equivalent to '1d2 - 1' and not '1d2' despite having two faces.

Anyway, this happens with zero enabled modules, v. 2.1.5 of the dnd5e system, and v. 10.291 of Foundry.

![1dc](https://github.com/foundryvtt/dnd5e/assets/17532914/4f976378-60bd-49d8-b753-9405a89c01fe)
![1d2](https://github.com/foundryvtt/dnd5e/assets/17532914/92f3e8d5-abe6-4adf-a1e4-3b79dcc70e56)
![labels](https://github.com/foundryvtt/dnd5e/assets/17532914/2187439a-c21d-4dc3-912a-d031389ba219)

**Comment by Hoppyhob** [comment]
I can work on this one.
