### ISSUE TITLE
[Bug]: Token Bar Attributes no longer have max for spells.pact.value and other spell slot value attributes

### ISSUE THREAD

**Issue by tmcnulty14** [foundryvtt/dnd5e#2284]
### Summary
Up until a few weeks ago, I was using the 'spells.pact.value' attribute to display pact magic slots as a resource bar on the token for my Warlock character. Recently, this stopped working, and a bar is no longer displayed when I select that attribute. In the token configuration dialogue, the 'Bar 2 Data' fields no longer show a maximum value for this attribute, which is probably why the bar is not being rendered.

### Reproduction Steps
1. Launch a FoundryVTT DnD5e world with all modules disabled.
2. Create a new player character actor.
3. Give them one level in Warlock.
4. Configure their token.
5. Set **Bar 2 Attribute** to **spells.pact.value**.
6. Check the **Bar 2 Data**, then save the configuration.

### Expected / Previous Behavior
- The **Bar 2 Data** fields for **spells.pact.value** would be populated with **1** / **1**.
- The token would display a blue resource bar representing the bar data.

### Observed / Current Behavior
- The **Bar 2 Data** fields for **spells.pact.value** are populated with **1** / **___** (there is no maximum in the data).
- The token does not display a blue resource bar.

#### Token Configuration
![Token Data Bug (No Mods)](https://github.com/foundryvtt/dnd5e/assets/9556787/f714d637-f881-4773-9414-6f27fffc4dc4)
There is no maximum shown for the spells.pact.value attribute
#### Token Hovering
![image](https://github.com/foundryvtt/dnd5e/assets/9556787/3ee4420a-4753-4003-8366-a17cc1bb8290)
There is no resource bar displayed for the spells.pact.value attribute

### Additional Observations
I confirmed that the same issue applies to other spellcasting classes and other levels of spell slot- a bar for **spells.spell1.value** on a sorcerer also displayed a value with no maximum, and there was no resource bar rendered on the token.

### Hosting Info
This was observed on two different self-hosted Foundry servers (mine and a friend's), each of which is being run from a personal PC running Windows 10.

**Comment by lykaios** [comment]
@Fyorl hey mate. I'd like to work on this ticket if you think its managable for a javascript n00b (I do most of my dev in scala). Ping me and let me know (Count on discord)

**Comment by Fyorl** [comment]
> @Fyorl hey mate. I'd like to work on this ticket if you think its managable for a javascript n00b (I do most of my dev in scala). Ping me and let me know (Count on discord)

I'd expect it would be very manageable. I think all that's needed is to add `spells.pact` as a `bar` attribute in `_configureTrackableAttributes` (`dnd5e.mjs`). Let me know how you get on.

**Comment by lykaios** [comment]
Any timeline for the milestone? I'd look at this next week :)

**Comment by Fyorl** [comment]
> Any timeline for the milestone? I'd look at this next week :)

No timeline at the moment

**Comment by AdamJDyer** [comment]
As of some recent change, it seems that these spell attributes don't appear under the list of attributes at all. Following the same reproduction procedures on my end doesn't even show the spell slots as an attribute choice for the token at all. I'm really missing this functionality.

**Comment by lykaios** [comment]
Sorry, little behind at the moment. Will look at this tomorrow.

**Comment by lykaios** [comment]
Still behind @Fyorl ; if there is no rush you can leave it assigned to me. Otherwise may be worth handing off to someone else.

**Comment by AdamJDyer** [comment]
Non-pact spell slots are still not appearing under the resource selection for tokens.
