### ISSUE TITLE
Add ability to perform Choices Swapping on advancement

### ISSUE THREAD

**Issue by InnilToo** [foundryvtt/dnd5e#2299]
**Use case:** Eldritch Invocation which warlock can swap on level up.

**Problem:** As Choices are remembered on the class item, changes to the sheet aren't reflected. So if more Choices are allowed on higher levels and an item feature that's been chosen is no longer present on the sheet, the advancement still thinks the Choice is valid.

**Workaround:** Using Modify Choices is a valid way to swap features instead of directly deleting and dragging a new one onto the sheet. But it requires going through a whole level of advancement.

**Feature request:** Please add an option to easily swap features that are gained from level advancement.

**Comment by krbz999** [comment]
It would likewise be good to be able to set a required class level for each of the options.
