### ISSUE TITLE
Monsters (SRD) Compendium is Missing Available Forgotten Adventures Token Art for Several Entries

### ISSUE THREAD

**Issue by Dumbhuman** [foundryvtt/dnd5e#2303]
Here is a list of entries currently missing available token art, followed by the relevant Forgotten Adventures Token Pack number where the art can be found:

Androsphinx - Token Pack 38
*Avatar of Death - The Reaper from Token Pack 3 could work, but you should definitely ask Stryxin first.*
Barbed Devil - Token Pack 17
Bronze Dragon Wyrmling - Token Pack 20
Cloud Giant - Token Pack 37
Copper Dragon Wyrmling - Token Pack 20
Drow - Token Pack 5
Erinyes - Token Pack 23
Ettin - Token Pack 38
Flesh Golem - Token Pack 38
Gold Dragon Wyrmling - Token Pack 20
Half-Red Dragon Veteran - Token Pack 37
Hill Giant - Token Pack 39
Ogre Zombie - Token Pack 39
Shambling Mound - Token Pack 37
Solar - Token Pack 37
Swarm of Poisonous Snakes - Token Pack 29
Treant - Token Pack 39
Triceratops - Token Pack 29
Weretiger - Token Pack 16
Wyvern - Token Pack 38
Young Blue Dragon - Token Pack 37
Young Brass Dragon - Token Pack 39
Young Copper Dragon - Token Pack 38

It seems packs 37, 38, and 39 are missing altogether, so I'm linking to #1834 for those.  I didn't see an issue to implement Token Pack 20, yet somehow the Silver Dragon Wyrmling is included from that pack while other Wyrmlings are not.  I don't immediately see a pattern for the handful of other entries that are missing art.

**Comment by MaxPat931** [comment]
Of the list above, these are the ones that do not have tokens in the `tokens/` folder
- [ ] Avatar of Death - The Reaper from Token Pack 3 could work, but you should definitely ask Stryxin first.
- [ ] Bronze Dragon Wyrmling - Token Pack 20
- [ ] Copper Dragon Wyrmling - Token Pack 20
- [ ] Drow - Token Pack 5
- [ ] Erinyes - Token Pack 23
- [ ] Gold Dragon Wyrmling - Token Pack 20
- [ ] Swarm of Poisonous Snakes - Token Pack 29
- [ ] Triceratops - Token Pack 29

I believe the rest can be added to the [ TokenArt.json ](https://github.com/foundryvtt/dnd5e/blob/master/json/fa-token-mapping.json) file as such:

```json
 		"11ILTQZseA756DJV":{
			"actor":"systems/dnd5e/tokens/humanoid/HalfRedDragonVeteran.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/humanoid/HalfRedDragonVeteran.webp",
					"scaleX":1,
					"scaleY":1
				},
			}
		},
		"3pb9wQk9Gv8HDdDh":{
			"actor":"systems/dnd5e/tokens/dragon/YoungCopperDragon.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/dragon/YoungCopperDragon.webp",
					"scaleX":1,
					"scaleY":1
				},
			}
		},
		"6hx8dkMlO4NMgrAh":{
			"actor":"systems/dnd5e/tokens/plant/Treant.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/plant/Treant.webp",
					"scaleX":1,
					"scaleY":1
				},
			}
		},
		"HUDTvQR9WK52EL35":{
			"actor":"systems/dnd5e/tokens/dragon/YoungBlueDragon.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/dragon/YoungBlueDragon.webp",
					"scaleX":2,
					"scaleY":2
				},
			}
		},
		"JVPUxyH9W6x8hkAL":{
			"actor":"systems/dnd5e/tokens/fiend/Barbed.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/fiend/Barbed.webp",
					"scaleX":1,
					"scaleY":1
				},
			}
		},
		"LkODz6SeNnJ2k3HL":{
			"actor":"systems/dnd5e/tokens/giant/CloudGiant.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/giant/CloudGiant.webp",
					"scaleX":1.66,
					"scaleY":1.66
				},
			}
		},
		"Mz628zPPdQIehP2l":{
			"actor":"systems/dnd5e/tokens/giant/HillGiant.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/giant/HillGiant.webp",
					"scaleX":1.66,
					"scaleY":1.66
				},
			}
		},
		"MzPtBNpUGcO1t7n7":{
			"actor":"systems/dnd5e/tokens/construct/FleshGolem.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/construct/FleshGolem.webp",
					"scaleX":1,
					"scaleY":1
				},
			}
		},
		"NUtOFw1BMUOWeYVZ":{
			"actor":"systems/dnd5e/tokens/celestial/Solar.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/celestial/Solar.webp",
					"scaleX":2,
					"scaleY":2
				},
			}
		},
		"a2mSW1D4T4UDeyjX":{
			"actor":"systems/dnd5e/tokens/plant/ShamblingMound.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/plant/ShamblingMound.webp",
					"scaleX":1,
					"scaleY":1
				},
			}
		},
		"i6Z6sWEKqIvR7wk5":{
			"actor":"systems/dnd5e/tokens/monstrosity/Androsphinx.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/monstrosity/Androsphinx.webp",
					"scaleX":1,
					"scaleY":1
				},
			}
		},
		"ibwiHsfHZcnJG2Nj":{
			"actor":"systems/dnd5e/tokens/giant/Ettin.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/giant/Ettin.webp",
					"scaleX":1.5,
					"scaleY":1.5
				},
			}
		},
		"ljX813KGVeVOMXv5":{
			"actor":"systems/dnd5e/tokens/dragon/Wyvern.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/dragon/Wyvern.webp",
					"scaleX":2,
					"scaleY":2
				},
			}
		},
		"q12uaw3n6blp5jAD":{
			"actor":"systems/dnd5e/tokens/humanoid/Weretiger.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/humanoid/Weretiger.webp",
					"scaleX":1,
					"scaleY":1
				},
			}
		},
		"tQo7eo0mpIgIw6XB":{
			"actor":"systems/dnd5e/tokens/undead/OgreZombie.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/undead/OgreZombie.webp",
					"scaleX":1,
					"scaleY":1
				},
			}
		},
		"wsuQWV0Gpi2lBuNE":{
			"actor":"systems/dnd5e/tokens/dragon/YoungBrassDragon.webp",
			"token":{
				"texture":{
					"src":"systems/dnd5e/tokens/dragon/YoungBrassDragon.webp",
					"scaleX":2,
					"scaleY":2
				},
			}
		},
```

**Comment by mattexdee** [comment]
Added the missing token files and updated the mapping for all of the creatures other than Avatar of Death (which we'll wait for an official token for). Closed by this commit: https://github.com/foundryvtt/dnd5e/commit/754b23e0b23a63b1593098021e1d841914b218b1. This commit adds or correctly maps an additional 23 creatures.
