### ISSUE TITLE
Tool Item - Tool Proficiency field

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/dnd5e#2305]
The Tool Proficiency field in a Tool Item has no effect on the roll, the proficiency bonus is governed by the Actor's Tool Proficiency traits
I think that when a Tool item is placed on an actor the field should be set by the Actor's traits, but anything set in that Item should take precedence over the Actor's traits. 

![image](https://github.com/foundryvtt/dnd5e/assets/86370342/1322c759-1020-4836-8de7-d0d74d8c648a)

**Comment by Fyorl** [comment]
I think this might already be handled/fixed by #2143 but it's a bug otherwise.
