### ISSUE TITLE
Charge Recovery Multiplied by 7

### ISSUE THREAD

**Issue by ghost** [foundryvtt/dnd5e#2323]
The charge recovery via the Recovery Formula always gives 7 times the charges it is supposed to.
1 becomes 7, 1d4+1 becomes 7d4+7, etc.
Tested with no modules, and in a different world (where the problem did not exist, so it seems to be only this world of mine with this issue)

**Comment by krbz999** [comment]
You have 'Gritty Realism' turned on.
