### ISSUE TITLE
Split out target definitions to separate shape from target type

### ISSUE THREAD

**Issue by tposney** [foundryvtt/dnd5e#2331]
There are quite a few spells that have target definitions of the form allies within 30 ft, creatures within 20 ft etc.

Within midi-qol I represented that with a target specification of 30 ft creature/ally/etc. With the latest release it is impossible to set that combination in the target specification anymore.

What is the intended way to represent such target specifications? The current Area targeting requires the placement of a template which these sorts of target definitions don't require, or if a template is intended I'm not aware of any way to anchor it to the caster.

Any guidance would be gratefully received.

**Comment by MrPrimate** [comment]
Same question, different module.

**Comment by krbz999** [comment]
I don't believe this has ever been intended to be displayed through the item details, but through the item description. The UI rework was done because labels such as '30 foot creature' is nonsensical (#1858). One aura spell in the SRD compendium backs this up with a range of 'self' and a target of '30 feet radius'.

**Comment by MotoMoto1234** [comment]
How would you display turn undead in 2.2.x core?  Cause it really does look weird in 2.2.x.  There is a very distinct difference between a template radius and all creatures within 30ft.  One includes the casters width.

**Comment by MotoMoto1234** [comment]
A template is not going to cut it unless we edit them all away from raw and add in the 5ft...to 15ft depending on the casters size.

**Comment by tposney** [comment]
I think target "30 foot creature" is a natural expression of creatures within 30 feet of the caster.

In any event I'm looking for clarification from the dnd5e team about how they intend to represent such things so I can align with their intent.

**Comment by arbron** [comment]
I feel like this is a core place where our data structure isn’t quite up to snuff. It seems like we should have one field that defines target type (sphere, cone, line, radius, target, space) and a second field defining who it affects (all creatures, all creatures & objects, only allies, only enemies). Right now things like a cone that only targets enemies or a space that only targets allies (like healing spirit) aren’t possible.

**Comment by MotoMoto1234** [comment]
There is also a few weird ones like the Slow Spell and Mass Cure Wounds, where they are templates that don't target everything in them, they have a target count limit.

**Comment by thatlonelybugbear** [comment]
> I feel like this is a core place where our data structure isn’t quite up to snuff. It seems like we should have one field that defines target type (sphere, cone, line, radius, target, space) and a second field defining who it affects (all creatures, all creatures & objects, only allies, only enemies). Right now things like a cone that only targets enemies or a space that only targets allies (like healing spirit) aren’t possible.

Has there been any more discussion about the way that might get implemented? 
Knowing if/how that might be added would help modules better plan ahead on how to utilise any such additions or work arounds.
