### ISSUE TITLE
Updating an unlinked token's item causes actor preparation to fail

### ISSUE THREAD

**Issue by tposney** [foundryvtt/dnd5e#2334]
dnd2.2.1, foundry v11.300, no modules loaded running on chrome in windows, hosted on node.js

I created a blank world with no modules enabled, dragged a monster (giant spider) from the monsters compendium to a scene.
To reproduce
Edit its bite attack and change any field (in this case I chose finesse). 

The update fails with ``data preparation failed``, ``cannot read properties of null (reading system)``.
It seems that after the update item.actor is null and the subsequent item preparation fails.

This remains until the world is reloaded.

I think, but cannot definitely confirm, that this did not occur in foundry v11 299.

I don't know if this is a foundry issue or a dnd5e issue.

**Comment by Fyorl** [comment]
It's a core bug. One of these I think: foundryvtt/foundryvtt#9563 or foundryvtt/foundryvtt#9565

**Comment by tposney** [comment]
I was just about to add that in - confirmed it does not occur in 11.299.
Should I close this?
