### ISSUE TITLE
Consolidate Background, Race, and Class/Subclass into a single Row

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/dnd5e#2342]
To stop the features tab in the character sheet from just being a vertical mess of features that don't efficiently use the space, what about changing the layout slightly for the time being with the upcoming Race Items in 2.3 and make the features tab a little more presentable.

_**Image Photoshopped by MaxPat**_
![image](https://github.com/foundryvtt/dnd5e/assets/65571170/14e184f2-614c-4911-a2a5-52fcf246dae6)

It would save a fair bit of room on the character sheet by allowing the basics of the character, ie the Class, Race, and Background to be all next to each other in a single row, alleviating the need to have a "tall" character sheet.

**_From MaxPat on Discord:_**
_"one thing is that Class and Subclass are grouped, so they take up 2 lines, while background and race are 1 line, maybe a 50% split for Class & Subclass, and Race & Background?"_

I do agree with Max on this but dont exactly know how to format the split to make it look nice, especially if some subclasses have longer names, for instance Path of the Ancestral Guardian.

**Comment by MaxPat931** [comment]
Yea I think the 1/3 split does make the sections too compact, and with multiclassing, that Classes section would bloat the others, so I think having the Race and Backgrounds split a section up top (as a character is unlikely to have more than one of these item types - although I know there was talk in the Race Item issue to allow for multiple race items), then the Classes have their own section where the Class and Subclass items are side-by-side would be a better layout

![FeatureTab](https://github.com/foundryvtt/dnd5e/assets/86370342/14cf295f-8ebf-4069-a2b7-1bd51ae5d97d)

**Comment by krbz999** [comment]
Alternatively, introducing subtabs in the Features tab could leverage the feature subtypes introduced in 2.1.0. One tab for class features, one tab for the rest.

**Comment by Zanderaf** [comment]
I think the tabs thing might sound the best- especially if you put any background features into there as well, or atleast, like the 1 background feature you get but races do sometimes give a few features as well when they dont give out spells or spell-like abilities.
