### ISSUE TITLE
Compendium Content: Base Weapon/Equipment/Tool not set on weapons/armor/tools in Starter Heroes and Monsters

### ISSUE THREAD

**Issue by Rabulias** [foundryvtt/dnd5e#2348]
A number of items owned by the Starter Heroes and Monsters do not have their Base Type set.

For example, Akra's Light Crossbow, Krusk's Chain Mail, the Skeleton's Shortbow, or the Knight's Plate Armor (which is actually mis-set as Light Armor in Equipment Type).

The same items in the Items (SRD) compendium look to be correct, so maybe there is a way to re-sync the items there to the inventories of the Starter Heroes and Monsters?

This notably affects automatic ammo usage with automation modules.

**Comment by Fyorl** [comment]
Related: #1338
