### ISSUE TITLE
[Request] Add subtypes for poisons, Injury, Inhaled, Contact, Injested

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/dnd5e#2352]
Maybe add in a subtype for poisons that would denote them as a certain type of application?

**Comment by krbz999** [comment]
Ideally in my mind `consumable`-type items would get the same treatment as `feat`-type items have been given, with both system type and subtype ('class feature' and 'eldritch invocation' for example). There's a clear use case for denoting ammunition subtype as well.
