### ISSUE TITLE
After updating an item, its weight and price vanishes

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2357]
Repro: open actor sheet. Click "Equip" icon. See weight and price vanish.

Only happens when done through the actor sheet (seemingly).

https://github.com/foundryvtt/dnd5e/assets/50169243/d217959c-1023-49f5-bdb2-019d3be09a26

**Comment by thatlonelybugbear** [comment]
Recovery formula was/is still another field that is plagued by this in v2.2.2

If you update an item that has a Recovery Formula defined, an update sets the field to `''`

**Comment by Fyorl** [comment]
Please raise a separate issue rather than commenting on an already closed one.
