### ISSUE TITLE
If an Item that has a formula set in Resource recovery is updated, the update sets the field to `""`

### ISSUE THREAD

**Issue by thatlonelybugbear** [foundryvtt/dnd5e#2362]
Related to the now closed <https://github.com/foundryvtt/dnd5e/issues/2357>

**Comment by krbz999** [comment]
Took some digging, but it turns out that all updates are passed through `migrateData` (why?) in `character.mjs` (and then to `#migrateUses`), and then when `uses.recovery` is not present in the update, it gets set to `""`.
