### ISSUE TITLE
Cannot read properties of undefined (reading 'toolIds')

### ISSUE THREAD

**Issue by matthewbstroud** [foundryvtt/dnd5e#2369]
CONST.DND5E.toolIds is undefined, I believe is this just a typo and should be **CONFIG**.DND5E.toolIds

![image](https://github.com/foundryvtt/dnd5e/assets/17620888/a77d4268-f9dd-4e22-a959-969bc25178c4)

![image](https://github.com/foundryvtt/dnd5e/assets/17620888/f07c413a-09b4-4369-a292-c545b4a2e42d)

foundry v10.291
dnd5e   v2.2.2

**Comment by Fyorl** [comment]
Already fixed here: <https://github.com/foundryvtt/dnd5e/commit/2b07cc2ad9d869dbf000731bb2d0274ebacdfc47>

**Comment by matthewbstroud** [comment]
Is there a workaround for this?
