### ISSUE TITLE
multiple calls to prepareData accumulate active effect changes

### ISSUE THREAD

**Issue by tposney** [foundryvtt/dnd5e#2370]
foundry 11.305, dnd2.2.2 no modules active.

When an active effect adds to a field, e.g. system.abilities.str.value add 1, multiple calls to actor.prepareData() will cause the effect to accumulate, e.g. str.value -> 11 -> 12 -> 13 etc.

I'm unsure if this is intended but is certainly a change in behaviour. 
I'm also unsure if this is a dnd5e or a foundry v11 issue, but the tests I did were with dnd5e so adding it here.

**Comment by Fyorl** [comment]
Seems to no longer be an issue at least in 11.315 and 2.4.0.
