### ISSUE TITLE
Scrolling Status Text animations should be suppressed when the triggering token is toggled hidden

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/dnd5e#2382]
(Moved from https://github.com/foundryvtt/foundryvtt/issues/9833)

Scrolling Status Text animations are visible to all players with line of sight to the token, even if the token has been toggled hidden with the Toggle Visibility State control. The text animations ought to be suppressed in that case.

This behaviour is present in both 10.303 and 11.306

### Reproduction Steps

1. Be in a game system that supports Scrolling Status Text
2. Enable Scrolling Status Text
3. Put a token within a Player's vision polygon
4. Toggle Visibility State on the token, making it hidden from the Player
5. Change a value on the token that triggers a Scrolling Status Text animation
6. View from the Player's login that the text animation is visible

### Bug Checklist

- [X] The issue occurs while all Modules are disabled

**Comment by krbz999** [comment]
Are you seeing scrolling text on invisible tokens for conditions being toggled on or off or only damage numbers? I am not seeing the former, but slapped in a fix in #2383 for damage numbers specifically.

**Comment by unsoluble** [comment]
Only tested with HP changes, so perhaps that's all that needs to be hit.
