### ISSUE TITLE
Ring of Protection active effect only grants +1 AC but not +1 to all saving throws

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#2384]
_Pardon the brevity of this report, writing it while mid-session_

From the Items (SRD) compendium pack, system version `2.2.2`

![image](https://github.com/foundryvtt/dnd5e/assets/2468703/7ec5a26f-08b9-4064-9851-c57fdbd833b0)

**Comment by krbz999** [comment]
Related: #797

**Comment by Fyorl** [comment]
I think this is adequately covered by the list in #797, but it seems that issue got lost in the Compendium Active Effects milestone, which never ended up happening. I will tentatively re-target it to 2.3 and see if we can make some headway there.

**Comment by aaclayton** [comment]
No problem with that, but a perspective is that it's worse to have an item already in the compendium with an active effect that is *wrong* than items in the compendium that simply do not have effects yet. As such, my 2c is that this is more of a *bug* than a missing feature.

In this case, the Ring of Protection already has an Active Effect configured, but that Active Effect is incorrect.

**Comment by Fyorl** [comment]
Yes, that's fair enough. The amount of effort to implement the entire batch is quite small so I'll make sure it's prioritisted.
