### ISSUE TITLE
Model Validation Error when creating vehicles on a fresh world

### ISSUE THREAD

**Issue by Ikaguia** [foundryvtt/dnd5e#2397]
![image](https://github.com/foundryvtt/dnd5e/assets/16377028/978c30b6-d907-47fd-a914-05ef27ece01f)
`details.source` is declared as a required field here:
https://github.com/foundryvtt/dnd5e/blob/797d0bc700ee9c9b1567b6c4e53de1e1f671dbc8/module/data/actor/vehicle.mjs#L102
but is not present in `template.json`.

**Comment by Fyorl** [comment]
Not able to reproduce this on 11.306 with the following:
```js
Actor.implementation.create({ name: 'foo', type: 'vehicle' });
```
Is this a v10-only issue maybe? Or are there some additional reproduction steps that you can provide?

**Comment by Ikaguia** [comment]
Could be a v10-only issue, it also does seem to only happen in a freshly created world for some reason.

Repro steps would be:
- Create a fresh world
-  Attempt to create a vehicle actor
![image](https://github.com/foundryvtt/dnd5e/assets/16377028/f10434f2-21de-47ac-b536-30c7ca19c0b4)

**Comment by Fyorl** [comment]
Worth mentioning that the v10 version you have there is not the latest v10 release. Can you try updating to the latest (303), and see if that resolves the issue? If so, we will need to make sure we bump the minimum version in the `system.json` to `10.303`.

**Comment by Ikaguia** [comment]
That does indeed seem to fix it, though it still seems like adjusting `template.json` would be the correct solution.

**Comment by Fyorl** [comment]
Now that we have implemented system data models, the `template.json` is largely redundant, and we plan to mostly truncate it in a future update, see #2388
