### ISSUE TITLE
Dropping an item onto an actor resets `system.proficient` to `null` ('automatic')

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2418]
Seems unneeded when we can now select 'Automatic', and negates the ability to create an item any actor is always (or never?) proficient with regardless of their weapon proficiencies.

There is the issue, however, that no proficiencies were migrated to 'Automatic', so users would then have to fix these themselves.

```diff
  /**
   * Reset certain pieces of data stored on items when they are dropped onto the actor.
   * @param {object} itemData    The item data requested for creation. **Will be mutated.**
   */
  _onDropResetData(itemData) {
    if ( !itemData.system ) return;
-    ["equipped", "proficient", "prepared"].forEach(k => delete itemData.system[k]);
+    ["equipped", "prepared"].forEach(k => delete itemData.system[k]);
    if ( "attunement" in itemData.system ) {
      itemData.system.attunement = Math.min(itemData.system.attunement, CONFIG.DND5E.attunementTypes.REQUIRED);
    }
  }
  ```

**Comment by Fyorl** [comment]
I think we would also need to update the SRD items since they're all set to 'Not Proficient' currently.

**Comment by Ikaguia** [comment]
> Bumping this to 2.4. It's difficult to do a migration since we can't guess the intent of the proficiency setting for items inside world compendia. Did the user intend for the item to be 'not proficient' explicitly, or did they just leave it as the default? If we don't do a migration then users will suddenly find that items dropped from their compendium packs are marked as 'not proficient', and I'd rather not spring that surprising behaviour as part of a bugfix release.

How about, for now, changing it to automatic only if no actual change would happen. I.E: if it's marked as not proficient and the actor does not have proficiency, or it's marked as proficient and the actor has proficiency
