### ISSUE TITLE
Booming blade Greenflame blade

### ISSUE THREAD

**Issue by Quinn-Aetherwood** [foundryvtt/dnd5e#2435]
Proficiency bonus is not being added to attacks when using BB or GFB once a weapon is requested for selection. Instead it is only using the base attribute, DEX, STR, ETC.

**Comment by krbz999** [comment]
Neither Booming Blade nor Green-Flame Blade are SRD items included with the system. You seem to be describing behavior from a module.

**Comment by thatlonelybugbear** [comment]
Well it's related to https://github.com/foundryvtt/dnd5e/issues/2420 probably and it seems that it will be resolved soonish ™️
