### ISSUE TITLE
Ability scores that are at their maximum can be edited in an ASI

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2441]
Dunno if we want to prevent editing them, but given that the "-" and "+" buttons are disabled I assume so.

Additionally, if the value is deleted, the entire advancement flow needs to be redone as the number becomes `NaN`.

One fix is to just give it the `readonly` property, same as if it had a `fixed` addition.

**Comment by Hoppyhob** [comment]
I can work on this one.
