### ISSUE TITLE
Item Choice Advancements don't Accept Drops from Players

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/dnd5e#2457]
As a player trying to drop an item into an Item Choice advancement with Accept Drops on silently fails

https://github.com/foundryvtt/dnd5e/assets/86370342/51d7d439-f2bb-45ed-994b-7a038a47c65e

(semi related but tested as a DM dropping an item of the wrong type specified in the advancement gives an Undefined type error instead of the specified type)
![image](https://github.com/foundryvtt/dnd5e/assets/86370342/4607ed82-7546-4ac3-a042-a130605e7ecb)

**Comment by MaxPat931** [comment]
This also affects a Player dragging and dropping a feat onto an ASI advancement

**Comment by krbz999** [comment]
Wouldn't be surprised if the 'undefined' error is fixed as part of #2485.
