### ISSUE TITLE
Allow multiple methods of recovery for uses and more input possibilities for recovery.

### ISSUE THREAD

**Issue by DreamingHero1997** [foundryvtt/dnd5e#2464]
Having the ability to input a formula or value for uses recovered makes a lot of sense, especially since a lot of magical items use non-standard recovery, currently modules can facilitate this but I feel like this should be a core feature.
Allowing multiple methods of recovery for uses would be nice for features/items that recover for example X amount of uses on a short rest and all uses on a long rest.

**Comment by Fyorl** [comment]
Recovering X or a short rest and all on a long rest seems quite common in the playtest, so we will at least need a solution for that if those features end up being published as-is. Thank you for raising this.
