### ISSUE TITLE
Weapons with ammunition not taking in account ammunition damage when only damage is rolled.

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/dnd5e#2472]
I'm not sure if its intended or not, but when using something such as a longbow with with +1 arrows:
- Clicking the item and sending it into chat with the attack / damage options and selecting attack to make a roll, and then damage consumes the ammo and applies the damage bonuses from the ammunition accordingly.

However, if you send the item to chat and only hit damage and skip the ammo consumption, it only rolls the base longbow's damage. Is the damage linked to the consumed ammo / this whole process intentional?

**Comment by Fyorl** [comment]
Probably not intentional, no. Maybe a technical limitation, not sure. I'll mark this as a bug since I think if a weapon is using explicitly using ammunition then the ammunition properties should always apply when rolling damage.

**Comment by krbz999** [comment]
The code adds a reference to the `_ammo` in the attack roll, then removes that reference when creating the damage roll.

It is also the attack roll that consumes ammo, not the damage roll.
