### ISSUE TITLE
[2.3.1] Error when creating an effect on an NPC

### ISSUE THREAD

**Issue by FalconPilot** [foundryvtt/dnd5e#2477]
Since the last update and Foundry V11, it seems like effects are broken on NPCs :( It's impossible to create them either manually, or by drag & dropping them. It still works with player-character actors.

My wild guess would be that the activeEffect refactor of Foundry V11 may be the culprit. Here's the console error:
```
foundry.js:753 TypeError: An error occurred while rendering ActorSheet5eNPC 196. Cannot create property 'icon' on string '+1'
```

It only started happening with Foundry V11 stable, it was perfectly functional in V10 stable

EDIT: I made some digging, and it seems like it only appears when drag & dropping an item with an activeEffect first. Exclusively creating manual activeEffects on an NPC seems to work just fine.

Also, the consequences can be quite dire, as it can actually lock the sheet from opening due to console errors!

**Comment by krbz999** [comment]
This seems likely to be because of the effect itself being misconfigured. For example if you make an effect with the configuration
```
system.abilities.str | Override | +1
```
(which should have been `system.abilities.str.value`), then that actor's entire Strength object is a string instead, and the actor sheet will be unable to render.

**Comment by FalconPilot** [comment]
> This seems likely to be because of the effect itself being misconfigured. For example if you make an effect with the configuration
> 
> ```
> system.abilities.str | Override | +1
> ```
> 
> (which should have been `system.abilities.str.value`), then that actor's entire Strength object is a string instead, and the actor sheet will be unable to render.

I see, that makes sense! So I tried using just a `1` instead, but it seems like the error just got changed🤔

`foundry.js:753 TypeError: An error occurred while rendering ActorSheet5eNPC 74. Cannot create property 'icon' on number '1'`

Somehow, it seems like typecasting behaves weirdly for NPCs specifically (and only NPCs)
