### ISSUE TITLE
Consumable items' Resource Consumption middle field is lost when observed while detached from an actor.

### ISSUE THREAD

**Issue by FrankIsAtank** [foundryvtt/dnd5e#2480]
FoundryVTT V 11 Stable 306
DnD5e 2.3.1

To reproduce :
1. Create a player character actor.
2. Add a Consumable item to the actor.
3. Give the new item these properties :
- Activation Cost : Action
- Resource Consumption 1 'resources.primary.value' Attribute
4. Drag-and-drop the new item from the actor's inventory tab to the Items panel on the right side.
5. Delete the new item from the actor's inventory.
7. Open new item from the Items panel.
8. Open the new item's Details tab. Notice the Resource Consumption's drop down list's current value is now empty and its list is now empty.
9. Drag-and-drop the new item from the Items panel back to the actor's inventory. Notice the item's drop down list is not restored.

Alternatively, repeat the process but skip steps 7 and 8. Now, notice the item's drop down list is not cleared as it was never inspected while detached from an actor.

Expected behaviour :
The drop down list should allow for it's current value to be preserved even when the present value is not an element it its list. Perhaps a drop down list is not the right widget for this application.

As a bonus, it would be nice to be able to write any value in this field, even if it isn't in the list. This would allow for consumable objects to be defined without having to attach them to an actor first.

**Comment by arbron** [comment]
Related to #1856
