### ISSUE TITLE
Non-Pact Spell Slots are not an option for Token Resource Bars

### ISSUE THREAD

**Issue by AdamJDyer** [foundryvtt/dnd5e#2483]
### Summary
Until a recent update, I was using the 'spells.spell1.value' attribute (and so on for higher spell slot levels) to display spell slots as a resource bar on the tokens for my player characters. Unfortunately, I do not know exactly when this stopped working. Currently, those attributes (non-pact spell slots) are not options for selection. Pact slots are still an option for unknown reasons.

Older tokens that had previously been configured with spell slot bars still display their bars, and those bars still update with changes in the character sheet. When the player uses a spell slot, the token bar still displays the updates. Copies of these tokens (made by copy/pasting) also continue to function correctly. However, any attempt to save new configurations of the token, including simply changing the token name, causes the bars to disappear. There seems to be no way to re-select those spell slots as an attribute for the resource bar. Upon inspecting the previously-configured tokens, the bars that correspond to spell slots only show "None (remove)" as an option instead of what they are currently connected to. 

It seems that the attribute connection to the resource bar itself is still working, but it can't be saved as a new configuration for any token for some reason. This is preventing new tokens from being configured with those resource bars, and it is removing those resource bars from any previously-configured tokens that are saved anew.

### Reproduction Steps
Launch a FoundryVTT DnD5e world with all modules disabled (Foundry version 11.309, D&D5e version 2.3.1)
Create a new player character actor.
Give them one level in any spellcasting class, such as wizard.
Configure their token.

### Expected / Previous Behavior
The resource bar should have options for either "spells.spell1" or "spells.spell1.value".

### Observed / Current Behavior
There is no option for spell slots except for pact spell slots.

### Screenshots
**New Tokens (no mods active):**
![DND Spell Slot Token Resource Bug](https://github.com/foundryvtt/dnd5e/assets/15099970/0191345d-3eae-4b9f-b5c5-5ff9184c082a)
**Previously-Configured Tokens (this screenshot shows some active mods):**
![DND Spell Slot Token Resource Bug 2](https://github.com/foundryvtt/dnd5e/assets/15099970/03d9414d-7d26-4b10-b6a4-a7008533d196)

**Comment by Fyorl** [comment]
We manually curate the list of available token resources now and it was deemed that spell slots were not really a useful resource to display on tokens. Pact slots make sense since they're the only spell slots the Warlock has, so they're quite similar to a class resource. We could add them back in though.

**Comment by AdamJDyer** [comment]
Ah, thank you then. I find them very useful, especially in combination with the Bar Brawl mod that lets me put multiple bars on the same level.

**Comment by krbz999** [comment]
This was added in v3.
