### ISSUE TITLE
Missing pixie?

### ISSUE THREAD

**Issue by f4hy** [foundryvtt/dnd5e#2484]
I am pretty sure pixies are part of the SRD, but they seem to be missing from here. Is this just that no one has added them or are they not actually part of the SRD?

**Comment by unsoluble** [comment]
Pixie is [not in the SRD](https://media.wizards.com/2023/downloads/dnd/SRD_CC_v5.1.pdf)

**Comment by f4hy** [comment]
Weirdly pixies are mentioned in the SRD as an example of something from the feywild when it first mentions the feywild... but ya they are not actually there. Will close this.
