### ISSUE TITLE
[Feature Request] Optional firearms proficiencies

### ISSUE THREAD

**Issue by Janner3D** [foundryvtt/dnd5e#2489]
It would be nice to make firearms an available option for proficiencies. One of my players is an artificer, and they use firearms frequently. Here's a list of all the currently available types of firearms in D&D I've found so far.

![image](https://github.com/foundryvtt/dnd5e/assets/35965176/dcd1f00e-0a6e-4ce2-b870-e5b892463bbb)

**Comment by Zanderaf** [comment]
From what I remember, the Exandria items aren't SRD, theyre from a Critical Role supplement to D&D Beyond

**Comment by Janner3D** [comment]
> From what I remember, the Exandria items aren't SRD, theyre from a Critical Role supplement to D&D Beyond
 Ah, right. In that instance, perhaps just the non-exandrian ones.

**Comment by Janner3D** [comment]
> We should be able to add the DMG ones without trouble since they're just labels.

Sounds good to me!

**Comment by Fyorl** [comment]
Duplicate of #1327
