### ISSUE TITLE
[Feature Request] NPC Resources

### ISSUE THREAD

**Issue by Tookie03** [foundryvtt/dnd5e#2491]
Converting an NPC character sheet into a PC character sheet due to resource management constraints has proven to be a frustrating experience, primarily because I'm unable to create multiple distinct, unlinked characters simultaneously without causing something to error/break. 

![image](https://github.com/foundryvtt/dnd5e/assets/107572957/022f0836-df56-4d48-b74c-693fbe1bb65e)
(Example of PC's Resources shown above.)

The introduction of a manageable NPC resource system would significantly enhance NPC creation.

**Comment by Fyorl** [comment]
> primarily because I'm unable to create multiple distinct, unlinked characters simultaneously without causing something to error/break.

Please raise any issues you encounter with this. As far as I'm aware there are no issues in the system or core software related to the bulk creation of unlinked tokens.
