### ISSUE TITLE
Add price in the `item-properties`

### ISSUE THREAD

**Issue by InnilToo** [foundryvtt/dnd5e#2501]
**Use case:** Having all useful information in one place makes running a game always smoother. No having to open another window (item edit in this case) is always welcomed and can prevent accidental edits.

**Problem:** Items already display a lot of useful information if you "roll them out" so why not add more if there is room?

**Feature request:** Add price in the `item-properties`.

![image](https://github.com/foundryvtt/dnd5e/assets/33260912/e6e5247e-c5ee-4b67-ba52-377bae98a1cf)

**Comment by krbz999** [comment]
This would be especially useful on loot.

**Comment by Fyorl** [comment]
Prices are available as a column on actor sheets now, and in the item tooltip, and we also include price in loot item tags.
