### ISSUE TITLE
[Feature] Add option to switch all types of items to the tinyMCE editor

### ISSUE THREAD

**Issue by SLinxTheFox** [foundryvtt/dnd5e#2507]
tinyMCE has a lot more features than prosemirror and i have to go to journals to make many things just so i can copy paste them into features or spells or subclasses. I'd love if i could just use the MCE editor in items aswell as journals

**Comment by Fyorl** [comment]
TinyMCE is being sunset in the core software, so we have no plans to offer a way to switch to it in the dnd5e system. For any features that you feel are missing from the ProseMirror editor, it would be helpful if you could raise them against the main software so we can evaluate the feasibility of including them.
