### ISSUE TITLE
Feature Request: Support for Common / Exotic language differentiation and language subtypes.

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/dnd5e#2528]
A rework to the way the language proficiency tab is set would be nice to maybe have in the future, with something like a way to tell apart common and exotic languages such as dwarvish and abyssal like the SRD states.

Also, Primordial has different dialects or "sublanguage" like terran, ignan, etc. that would maybe be valid to put as sub-things of primordial.

Not sure if I got the point across, hoping other people can chime in since it was talked about in the D&D5e channel on the discord.

**Comment by arbron** [comment]
The system supports languages subtypes now if you wanted to add them using a world script:

<img width="252" alt="Screenshot 2023-10-27 at 09 58 44" src="https://github.com/foundryvtt/dnd5e/assets/19979839/a2bb38ee-42dc-46e9-a5f2-fc6810ad29e9">
<img width="420" alt="Screenshot 2023-10-27 at 09 58 51" src="https://github.com/foundryvtt/dnd5e/assets/19979839/b754e56e-b29e-4775-8990-b29a0cfee7e9">
<img width="335" alt="Screenshot 2023-10-27 at 09 59 05" src="https://github.com/foundryvtt/dnd5e/assets/19979839/dd8d2ecf-727e-4eba-8a92-2c1efc1cda2e">

So all this would take would be a bit of reorganization of the configuration and can be done by a world script at the moment (though that doesn't mean we shouldn't add them to the system).

**Comment by krbz999** [comment]
Might make sense to do something similar for damage types. It would provide an easy way to temporarily grant resistance to 'all physical damage' for example, via an effect.
