### ISSUE TITLE
(2.4) Damage enrichers throw an error if the formula is missing

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2566]

**Comment by arbron** [comment]
For me damage enrichers without formulas just don't enrich, but I'm not seeing an error:

<img width="261" alt="Screenshot 2023-11-08 at 14 13 18" src="https://github.com/foundryvtt/dnd5e/assets/19979839/d34357c8-0394-4c69-9b69-915e4c0ec6dc">

**Comment by krbz999** [comment]
Seems like it needs `average=true` to cause an error; `[[/damage average=true]]`

**Comment by arbron** [comment]
> Seems like it needs `average=true` to cause an error; `[[/damage average=true]]`

Yep, that would do it.

> Notably, `[[/damage fire]]` and `[[/damage average=false]]` do enrich. Should they?

Probably not :).
