### ISSUE TITLE
Add 'blank' damage enricher

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2568]
Basically extending the damage enricher so you can leave it blank, such as just `[[/damage]]`, which would then retrieve from the item's damage formulas rather than any written input.

Would also be helpful if the item itself is passed to the roll hook.

**Comment by arbron** [comment]
This is probably a direction for a future version when we also add a To Hit enricher to aid with creating item descriptions.

**Comment by arbron** [comment]
I'm going to say we need to support multiple damage types for this first so we don't get failed outputs, so blocked by https://github.com/foundryvtt/dnd5e/issues/3357
