### ISSUE TITLE
Cannot import certain spellcasting features from SRD compendium

### ISSUE THREAD

**Issue by BeesEggsToast** [foundryvtt/dnd5e#2574]
"Cannot read properties of undefined (reading '0')"

Every time I try to import these spellcasting features I get this error for Bard, Cleric, and Druid. It also happens when I try to add the class to an actor.

**Comment by unsoluble** [comment]
This is a symptom of having updated to v11 without first fully uninstalling v10. If you do a full uninstall/reinstall now, this will be resolved.
