### ISSUE TITLE
Cannot drag advancements from a class in the Classes SRD compendium as a player

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/dnd5e#2590]
Steps to reproduce:

1. create a new Actor of the "character" type
2. create a new Class directly on the actor
3. give Owner permission to the actor to a player
4. login as the player
5. edit the class and switch to the Advancement tab
6. click on the locked icon to change to Configuration Enabled
7. open the Classes SRD compendium pack and then one of the classes (I tested with Druid but I don't think it matters)
8. switch to the Advancement tab and try and drag/drop one of the advancements (I used the 4th-level ASI) from the SRD class to the class on the actor

After following the steps, I cannot drag any of the advancements from the SRD actor to the sidebar actor. If I try the same steps when logged in as the GM, it works. Normally when I drag something I see what I dragged attached to the cursor to indicate that I started dragging something. I don't even see that when logged in as a player.

**Comment by kaelad02** [comment]
I tested w/ Foundry 11.313 and dnd5e 2.3.1

**Comment by arbron** [comment]
Probably because the default `canDrag` method checks to see if the item is editable.
