### ISSUE TITLE
Allow for a flat attack bonus on an item, which ignores all modifiers except any value placed in `system.attackBonus`

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2591]
Spell scrolls as well as spells from magic items have a flat modifier that does not incorporate the user's proficiency bonus or ability scores in any way but simply have, e.g., a +7 to hit. Same as we have a way to set a flat saving throw DC, we should more easily be able to set a flat attack bonus.

A current workaround is to add an attack bonus of `7 - @prof` in the `system.attackBonus` field and then also set `system.ability` to `none`, where a simple checkbox next to the attack bonus field would make this much simpler and more intuitive.

**Comment by kaelad02** [comment]
This was already done in #2026

**Comment by krbz999** [comment]
> This was already done in #2026

Partially, but proficiency still applies.

**Comment by kaelad02** [comment]
So far I only used it on vehicles and their attacks, which are flat attacks. Do we actually need a separate property for it or should we just change the behavior of the `none` ability modifier to not include proficiency? I can't see why you'd want to apply proficiency but not an ability score, TBH.

**Comment by krbz999** [comment]
> So far I only used it on vehicles and their attacks, which are flat attacks. Do we actually need a separate property for it or should we just change the behavior of the `none` ability modifier to not include proficiency? I can't see why you'd want to apply proficiency but not an ability score, TBH.

This was considered, but since that input determines the ability, it makes less intuitive sense to have it affect proficiency.

**Comment by kaelad02** [comment]
What if it was renamed from None to Flat, like it is in the saving throw? That would be more obvious
![image](https://github.com/foundryvtt/dnd5e/assets/19502084/3f45a775-f2ff-4125-a7f4-d660d23d9cbf)
