### ISSUE TITLE
[2.4] New Race Item and migration for Player characters

### ISSUE THREAD

**Issue by thatlonelybugbear** [foundryvtt/dnd5e#2594]
I would suggest a migration script to at least add the current data held in `actor.system.details.race` to a newly created Race Item `actor.system.details.type.custom`.

If that is not preferable, at least when adding a New Race Item to already created player actors, do not default the field's `type.value` to `New Race` as the user will inevitably lose whatever was in that field.

**Comment by krbz999** [comment]
Sounds logical to take the old "custom" field in the sheet and move it to a new race item's `type.custom` value, but only when created *through* the sheet, not if one drops an existing Race item onto the sheet.

**Comment by thatlonelybugbear** [comment]
Not sure about what's the best solution here, but as it is, I think it will lead to some unneeded grief... 🤷 

Especially since an older player's actor will have the Creature Type populated as `Humanoid` without the config cog to change it, if no Race Item is added 
![image](https://github.com/foundryvtt/dnd5e/assets/7237090/ec6aa2e5-102b-43da-8d43-cc77107abbbb)

**Comment by Fyorl** [comment]
> I would suggest a migration script to at least add the current data held in `actor.system.details.race` to a newly created Race Item `actor.system.details.type.custom`.

The current value is not lost when loading into 2.4 for the first time, so there is no need for a migration. Users can opt-into the new race item at their convenience, and can continue to use the plain text field otherwise. This is consistent with how we handled backgrounds.

> If that is not preferable, at least when adding a New Race Item to already created player actors, do not default the field's `type.value` to `New Race` as the user will inevitably lose whatever was in that field.

Presumably they can remember their character's race and adjust the name of the newly-created race item accordingly. I do not think this is too much to ask.

> Especially since an older player's actor will have the Creature Type populated as `Humanoid` without the config cog to change it, if no Race Item is added

Characters did not have a creature type on their sheet previously so there is nothing lost here. Humanoid is a sensible default for the vast majority of player characters and races available in the game. Only very few races have non-humanoid creature types.

**Comment by MaxPat931** [comment]
> Sounds logical to take the old "custom" field in the sheet and move it to a new race item's `type.custom` value, but only when created _through_ the sheet, not if one drops an existing Race item onto the sheet.

I think it would make a little more sense to put the old "custom" field as the new Race Item's name, if creating the Race on the sheet. It would be a minor thing for some users, but I think would be a better experience overall.

![image](https://github.com/foundryvtt/dnd5e/assets/86370342/83d236fe-bcef-4545-9988-7808050b68de)
![image](https://github.com/foundryvtt/dnd5e/assets/86370342/e8d6f838-2b0a-48c5-9718-be814f254d5f)

**Comment by kaelad02** [comment]
I remember asking for the same thing when Backgrounds were introduced and it wasn't done. If it was, could have avoid having the background on the sheet being either a text box you can type in or just showing the background item's name. Always thought it was odd there was still a legacy `background` String field with the new Background item
