### ISSUE TITLE
Add 2.4.0 Wiki documentation for adding languages & language children via script

### ISSUE THREAD

**Issue by etiquettestartshere** [foundryvtt/dnd5e#2598]
With 2.4.0, the way to add languages (and language children like [this](https://github.com/foundryvtt/dnd5e/issues/2528)) has changed slightly. Full disclosure: I did not understand why the old way worked. Here is a working way.

**Credit:** with help from Zhell

To add a language not part of the **Standard** or **Exotic Languages**, or to add a language under the **Standard Languages** (or **Exotic**) umbrella, you can use
```js
Hooks.once("init", () => {
    CONFIG.DND5E.languages.coolspeech = "Cool Speech";
    CONFIG.DND5E.languages.standard.children.supercommon = "Super Common Language";
    CONFIG.DND5E.languages.standard.children.megacommon = "Mega Common Language";
});
```
```diff
-  CONFIG.DND5E.languages.standard.children
+  CONFIG.DND5E.languages.exotic.children
```    
And to add languages with children to any existing language family such as **Standard** or **Exotic Languages**, you can use this. Note: it didn't work with init (`Error: Localization keys must be provided for pre-localizing when target is an object.`). However, Zhell indicated it may work on setup, and it did.
```js
Hooks.once("setup", () => {
    CONFIG.DND5E.languages.standard.children.highgibberish = {
        label: "High Gibberish",
        children: {
            gibberish: "Gibberish"
        }
    },
    CONFIG.DND5E.languages.standard.children.oldnonsense = {
        label: "Old Nonsense",
        children: {
            nonsense: "Nonsense"
        }
    }
});
```
Lastly, to delete languages, add the correct path in respect to children, like
```js
Hooks.once("init", function () {
    delete CONFIG.DND5E.languages.standard.children.dwarvish;
    delete CONFIG.DND5E.languages.standard.children.elvish;
    delete CONFIG.DND5E.languages.standard.children.giant;
    delete CONFIG.DND5E.languages.standard.children.gnomish;
    delete CONFIG.DND5E.languages.exotic.children.primordial.children.aquan;
});
```
The result
![languages](https://github.com/foundryvtt/dnd5e/assets/148253744/a2c8c710-8150-451e-ab3e-dc2fd7dbc20c)

*edits: 1) merged the first two examples, 2) added missing ;*

**Comment by MaxPat931** [comment]
This can be closed
