### ISSUE TITLE
cant open actor sheet

### ISSUE THREAD

**Issue by R0TEAM** [foundryvtt/dnd5e#2602]
The error :

foundry.js:753 TypeError: An error occurred while rendering ActorSheet5eCharacter 95. Cannot read properties of undefined (reading 'label')
[Detected 1 package: system:dnd5e]
    at ActorSheet5eCharacter.getData (character-sheet.mjs:42:43)
    at async ActorSheet5eCharacter._render (foundry.js:5812:18)
    at async ActorSheet5eCharacter._render (foundry.js:6532:5)

**Comment by thatlonelybugbear** [comment]
FYI, this is an issue with a module and not the System (probably DAE).

**Comment by R0TEAM** [comment]
YES - you was right ;)
disabling DAE and i can open the actor sheets again :D

**Comment by Quidam2k** [comment]
Glad you haven't deleted this yet, as it's what told me which mod was at issue, getting me back in the game, though without DAE, which is problematic. 

Don't suppose @R0TEAM figured out what the combination was? 

Apologies if this sort of thread necromancy is frowned upon.

**Comment by MaxPat931** [comment]
Troubleshooting would be better done in the discord, and TPosney has his own for DAE/MidiQOL
Make a backup, make sure your modules are up to date (I believe the latest DAE requires the latest version of Foundry, v11.315), and see if that fixes things for you.
