### ISSUE TITLE
Rolling back to 2.3.1

### ISSUE THREAD

**Issue by Quinn-Aetherwood** [foundryvtt/dnd5e#2604]
I'm trying to roll back to 2.3.1 from 2.4 as its  breaking my modules. I have tried to download the manifest link but the one provided (which says 2.3.1) Just downloads 2.4

![image](https://github.com/foundryvtt/dnd5e/assets/127997499/63f0ae50-976d-476a-8d9f-03d7337fdd66)

**Comment by MaxPat931** [comment]
This manifest will download 2.3.1 https://github.com/foundryvtt/dnd5e/releases/download/release-2.3.1/system.json
I'd recommend heading to the discord to help troubleshoot this.

**Comment by Quinn-Aetherwood** [comment]
I tried the link but it  came up with invalid URL

**Comment by MaxPat931** [comment]
Uninstall the DnD system, then click the Install System button and paste the URL in the bottom, it will then install 2.3.1
![image](https://github.com/foundryvtt/dnd5e/assets/86370342/23ab19ca-8110-4303-a5ee-e44d92d61eac)

You will need to then restore your world from your backup made before launching it with 2.4.0

**Comment by Quinn-Aetherwood** [comment]
Huh... If click install it will instantly install 2.4, i don't get an option to add a link to the manifest url.

**Comment by MaxPat931** [comment]
Head to the Discord to troubleshoot.
