### ISSUE TITLE
[BUG] Item rolls aren't showing up on character seet

### ISSUE THREAD

**Issue by austinmorales-dev** [foundryvtt/dnd5e#2608]
DnD5e Version: 2.4.0
Foundry VTT Version: 11 build 315

When creating a new world with the 5e system, I don't get the option to roll for attack or damage from an item:
![image](https://github.com/foundryvtt/dnd5e/assets/57203473/8c170075-9110-493a-ad1f-41f307e2c13f)

This started happening ~10 minutes before this post was made, and I disabled all modules + created a new world and it is reproducing the same behavior.

**Comment by krbz999** [comment]
There has never been attack/damage buttons in the expanded item on the character sheet. This has been a module you were using.
