### ISSUE TITLE
Remove "Unidentified Description" from Spell Items

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/dnd5e#2610]
I think that spells do benefit from having the Description and Chat Description, but I dont think that the Unidentified Description makes sense for this Item type. Is the Multi-editor All or Nothing?

![image](https://github.com/foundryvtt/dnd5e/assets/86370342/c2dfce4e-6d65-4815-b0ad-cbca01e3cfc4)

**Comment by krbz999** [comment]
Tools, loot, and containers also have 'Unidentified description' but do not have an identified property to toggle. For these item types, the description should either be removed, or the toggle added.

Features should have the unidentified description removed.

**Comment by MaxPat931** [comment]
For Tools, Loot, and Containers I would vote for adding the Identified toggle, as each category can have magical items that require Identification.

**Comment by MaxPat931** [comment]
This can be closed, the Unidentified description has been removed from the Spell items, and the Tools, Loot, and Containers have added the Identification toggle
