### ISSUE TITLE
Cannot consume 0 ammunition

### ISSUE THREAD

**Issue by MangoFVTT** [foundryvtt/dnd5e#2616]
When using an item in dnd5e 2.4.0, you cannot set the resource consumption amount to 0, because it will always default back to 1, due to line 1092 in item.mjs (under `_handleConsumeResource`):

`let amount = usageConfig.resourceAmount ? usageConfig.resourceAmount : (consume.amount || 1);`

This is specifically a problem for items that use ammo, because it means that an item cannot get the benefits of ammo (such as the + to hit and the extra damage) without expending a use of the ammo item, which seems like a lessening of flexibility from previous versions for no reason. Since `usageConfig` is also hardcoded when entering this function for ammo, there doesn't seem to be a way to change the `usageConfig.resourceAmount `externally either.

**Comment by krbz999** [comment]
You get the benefit of ammo on damage rolls as long as the ammo item exists.
You get the benefit of ammo on attack rolls when able to consume one piece of ammo.

The logic was changed in 2.4.

**Comment by MangoFVTT** [comment]
@krbz999 Yes that's the issue, the logic change means that any time you roll the attack it consumes one piece of ammo, regardless of whether or not you set the consume amount to 0. I expect that if the consume amount is set to 0, it consumes 0, while still granting the benefits of the ammo.
