### ISSUE TITLE
Some added languages are not sorted alphabetically

### ISSUE THREAD

**Issue by etiquettestartshere** [foundryvtt/dnd5e#2624]
Some languages added with a script (maybe only languages **_other_** than **Standard Languages**) are not displayed alphabetically on the character sheet despite being sorted that way in the console. One example below, including how they are added: 
 
![image](https://github.com/foundryvtt/dnd5e/assets/148253744/348237d8-7824-4230-80c9-131482818f73)
![image](https://github.com/foundryvtt/dnd5e/assets/148253744/8f1c0d59-fc0b-4c02-b292-058c11d97715)

```js
class HomebrewManager {
  static init() {
    foundry.utils.mergeObject(CONFIG.DND5E.languages.exotic.children, {
      netherese: "Netherese",
      scro: "Scro"
    });
  };
}
Hooks.once("init", HomebrewManager.init);    
```
Additionally, Thieves' Cant is above Druidic (though this one may be intentional, I'm not sure). However, all default and added languages under the Standard umbrella, including those with children, are sorted in proper alphabetical order.

**Comment by arbron** [comment]
Just a little bug with preparing trait lists. The ordering of Thieves' Cant & Druidic is wrong because the keys are `cant` and `druidic`, so I put them in that order rather than translated order :).

**Comment by JPMeehan** [comment]
Chrome's console will auto sort things alphabetically, which is why you're seeing that discrepancy

**Comment by arbron** [comment]
> Chrome's console will auto sort things alphabetically, which is why you're seeing that discrepancy. I'm not sure there's a clean way of re sorting the keys of a non-array object in JS without fully re-instantiating it.

Already fixed! We've got sorting built in to the `SelectChoices` object which those are, so it was simply a matter of marking those as needing to be sorted.
