### ISSUE TITLE
[SRD] Advancements for certain classes / subclasses still add features possible through advancements

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/dnd5e#2631]
With the arrival of Trait & Item Choice Advancements, some classes have redundant features that only really clog up and clutter the character sheet.

### Classes
Bard:
- Expertise Feature (Redundant via Trait Advancement)
- Magical Secrets (Redundant via Item Choice Advancement)

**Druid:**
- Drudic Feature (Redundant via Trait Advancement)

**Fighter:**
- Fighting Style Feature (Redundant via Item Choice Advancement)

**Paladin:**
- Fighting Style Feature (Redundant via Item Choice Advancement)

**Ranger:**
- Fighting Style Feature (Redundant via Item Choice Advancement)

**Rogue:**
- Theives' Cant Feature (Redundant via Trait Advancement)
- Expertise Feature (Redundant via Trait Advancement)
- Slipper Mind Feature (Wisdom Save Prof Gained)

**Sorcerer:**
- Metamagic Feature (Redundant via Item Choice Advancement)

**Warlock:**
- Eldritch Invocation Feature (I wouldn't say redundant as the feature itself has a chart of what levels and requirements the invocations have, but the Item Choice Advancement is there too)
- Pact Boon Feature (Redundant via Item Choice Advancement)
- Mystic Arcanum Feature (Redundant via Item Choice Advancement)

### Subclasses
**Champion Fighter:**
- Fighting Style Feature (Redundant via Item Choice Advancement)

**Circle of the Land Druid**
- Cantrip Choice (Redundant via Item Choice Advancement)

**Lore Bard:**
- Bonus Proficiencies (Redundant via Trait Advancement)
- Additional Magical Secrets (Redundant via Item Choice Advancement)

**Hunter Ranger:**
- Hunter's Prey Feature (Redundant via Item Choice Advancement)
- Defensive Tactics Feature (Redundant via Item Choice Advancement)
- Multiattack Feature (Redundant via Item Choice Advancement)
- Superior Hunter's Defense Feature (Redundant via Item Choice Advancement)

**Life Domain Cleric**
- Bonus Proficiencies (Redundant via Trait Advancement)

**Comment by kaelad02** [comment]
I'd change the classes/subclasses to switch to these new advancements but **do not** remove the features themselves yet. Existing characters that use the current classes will still look for these features in the SRD compendiums and removing them now will cause errors. We'll probably have to treat them as deprecated, so we stop referring to them but leave them in for a few versions before removing them.

**Comment by Zanderaf** [comment]
Got it!

**Comment by Fyorl** [comment]
Advancements are not intended as a replacement for class features, they are just the way that we implement certain class features in the system. It's important that characters retain a full list of the features they have. Firstly, so that they can keep track of where everything comes from and, more importantly, because having certain features with specific names is important in game terms.

The most obvious example of that is the Spellcasting feature, numerous other game rules interact with it. Similarly the Extra Attack feature. In the playtest we also saw that some feats had the 'Fighting Style' feature as a prerequisite (though I think those have been scrapped now), and the Expertise feature also had some significance at some point also.

**Comment by krbz999** [comment]
A lot of features currently hold effects that were temporary substitutes until this advancement type (like 'Druidic'), those effects should at least be moved into proper advancements, even if the feature itself remains.

**Comment by Fyorl** [comment]
> A lot of features currently hold effects that were temporary substitutes until this advancement type (like 'Druidic'), those effects should at least be moved into proper advancements, even if the feature itself remains.

Yes, those placeholder AEs should absolutely be removed. Can you raise a separate issue to track that?
