### ISSUE TITLE
Trait upgrades don't let you upgrade a proficiency chosen in the same dialog.

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/dnd5e#2632]
I have a homebrew race who has a feature that grants a tool proficiency, and a separate feature that grants expertise in a tool proficiency of the player's choice. It's structured this way so you can use the expertise on a tool proficiency automatically granted by a class, e.g. thieves' tools. 

Unfortunately, the current dialog does *not* recognize the initial tool proficiency as a valid option for a later tool expertise upgrade.

Data wise, this would probably require tracking dialog choices and feeding them back into the display of each step of the advancement dialog.

**Comment by JPMeehan** [comment]
While feats are not implemented as advances, the choice structure is identical to the Skill Expert feat from Tasha's, which has proficiency and expertise as separate choices that can be combined but are not mandatory to do so.

**Comment by arbron** [comment]
The system does currently support this, but it being prevented by another bug: https://github.com/foundryvtt/dnd5e/issues/2596

**Comment by JPMeehan** [comment]
Ah, feel free to mark as duplicate or otherwise handle as you prefer.
