### ISSUE TITLE
Remove Advancement on Race deletion doesnt remove tool proficiency box [2.4.0]

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/dnd5e#2637]
When you try to remove a race that grants a tool proficiency it doesn't remove the box from the tool proficiency list.

Tested it in a newly made world with no modules. made a player actor and added the hill dwarf race. deleted it and had it remove all advancements

Before the deletion (just for show)
![image](https://github.com/foundryvtt/dnd5e/assets/86924581/f0ffdeae-f9ec-416f-8ce6-5edb20126a80)

After deletion, brewers supplies is set to not be proficient, but in the large proficiency list it is proficient?
![image](https://github.com/foundryvtt/dnd5e/assets/86924581/5f4b3b71-3ee4-479a-9d33-5fda1c27d822)

**Comment by arbron** [comment]
This is intended behavior so it doesn't delete the associated ability or bonuses included with the tools. It also remains if you use the circle to unset proficiency.

**Comment by flyingsquad** [comment]
Arbron didn't point this out explicitly, so I will.

When you delete the race/background/etc. it **unchecks** the proficiency for the tool. It does leave the tool on the character sheet, but the character is **not** proficient, even though the tool is still listed.

These light gray widgets are very subtle, and it's easy to miss them.
