### ISSUE TITLE
"Trait is not defined" preventing Tool checks from being enriched

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/dnd5e#2639]
![image](https://github.com/foundryvtt/dnd5e/assets/86370342/d2e74cbe-c63a-4132-ab44-15b0b43ba6f7)

https://github.com/foundryvtt/dnd5e/blob/afe245632ddd40c350d4c44dda223525e1c029bb/module/enrichers.mjs#L139C32-L139C37

**Comment by arbron** [comment]
Can't reproduce this issue, `Trait` is properly imported into that file.
