### ISSUE TITLE
Custom traits

### ISSUE THREAD

**Issue by Lunchboxmaster777** [foundryvtt/dnd5e#2651]
Is there a way to expand upon custom proficiencies in the new trait system?
For instance firearms for Artificers, or a completely homebrew language, proficiency, or damage type?

I know there is already a module for custom attributes and skills found here:
https://github.com/misthero/dnd5e-custom-skills

but is there any plans on being able to add in your own straight from the DnD system?

**Comment by Zanderaf** [comment]
Worldscripts are the typical way of doing it, if you join the discord, theres a few people who can help you

**Comment by MaxPat931** [comment]
There is also a guide with examples here on the wiki - https://github.com/foundryvtt/dnd5e/wiki/Modifying-Your-Game-with-Scripts

**Comment by Lunchboxmaster777** [comment]
Oh I didn't know World Scripts were a thing, thank you guys so much for showing me where I can do that.
That answers my question.
