### ISSUE TITLE
Organized SRD compendium content into folders

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#2666]
We currently have a script that organizes our compendium source files for certain types into folders, so I figured that would be a good starting point for planning the final organization. If we think this is a good way to go I can quickly turn the backend script into a macro to organize items, monsters, and spells quickly.

**Backend Organization:**
- `items`
  - `ammo`
  - `backpack`
  - `equipment`
  - `food`
  - `loot`
  - `poison`
  - `potion`
  - `rod`
  - `scroll`
  - `tool`
  - `trinket`
  - `wand`
  - `weapon`
- `monsters`
  - `abberation`
  - `beast`
  - etc.
- `spells`
  - `cantrip`
  - `level-1` through `level-9`

Other proposed changes is merging class features into the classes compendium and organizing those:
- `classes`
  - `barbarian`
    - Barbarian item
    - Path of Something item
    - `barbarian features`
      - Rage
      - etc.
    - `path of something features`
      - etc.
  - `bard`
    - Bard item
    - `bard features`
      - Bardic Inspiration
      - etc.
 - `races`
   - `dragonborn`
     - Dragonborn race item
     - `dragonborn features`
       - Breath weapon
       - etc.

**Comment by MaxPat931** [comment]
Perhaps there could be an option in the Settings to folder/refolder some of the compendiums? MrPrimate offers this for the DDB muncher as there are people that want their compendiums sorted in certain ways, and their way is obviously the _right way_ 😉

The options he provides are:
Monsters: Types, CR, or Alphabetical
Spells: Spell Level or Spell School
Items: Type, Rarity

**Comment by arbron** [comment]
> Perhaps there could be an option in the Settings to folder/refolder some of the compendiums? MrPrimate offers this for the DDB muncher as there are people that want their compendiums sorted in certain ways, and their way is obviously the _right way_ 😉

That seems like it is something better handled by a proper compendium browser, which is a much more involved change than just adding folders to the SRD compendiums.
