### ISSUE TITLE
Feature Request: Add Race to NPCs

### ISSUE THREAD

**Issue by mnoreke** [foundryvtt/dnd5e#2668]
The various books from DnD contain many humanoids that are "any race". Having the ability to add a race to them would simplify creating unique variants that contain the racial modifiers, such as darkvision and resistances.

**Comment by Zanderaf** [comment]
Normally you would just add the Subtype in like "Human" or "Elf" when selecting the creature type.

**Comment by mnoreke** [comment]
> Normally you would just add the Subtype in like "Human" or "Elf" when selecting the creature type.

This doesn't add in Darkvision or resistances though.

**Comment by revilowaldow** [comment]
Page 282 of the DMG contains mechanical benefits to confer on NPCs when they are a specified race.

As an example the first row of the large table suggests:

| Aarakocra | +2 Dex, +2 Wis |Dive Attack: talon attack action, speed 20 ft., fly 50 ft., speaks Auran |

This would be the appropriate data to implement to support this feature request.

**Comment by revilowaldow** [comment]
Note that data support for NPC races as defined in the DMG has not been added, only support for the NPC sheet type to use the race structure. If similar rules are found in the 2024 DMG release is it expected that they be added to that product.

**Comment by arbron** [comment]
> Note that data support for NPC races as defined in the DMG has not been added, only support for the NPC sheet type to use the race structure. If similar rules are found in the 2024 DMG release is it expected that they be added to that product.

Hmm, what is currently missing? Cause you can create a Race just like for players and give it an Ability Score Improvement advancement to change the NPC ability scores and Item Grant Advancement to give it features listed in that table.

We'll probably need to add a bit of handling for Senses and Movement.

**Comment by revilowaldow** [comment]
> > Note that data support for NPC races as defined in the DMG has not been added, only support for the NPC sheet type to use the race structure. If similar rules are found in the 2024 DMG release is it expected that they be added to that product.
> 
> Hmm, what is currently missing? Cause you can create a Race just like for players and give it an Ability Score Improvement advancement to change the NPC ability scores and Item Grant Advancement to give it features listed in that table.
> 
> We'll probably need to add a bit of handling for Senses and Movement.

Sorry, what I mean is, you can now manually give it those features.
But it would be good to have a compendium of NPC-races that reflects those tables you can add to any NPC you want without having to create them, or without using PC-races on NPCs.
I think the right way to do that is to implement whatever is in the new DMG when it releases, I just didn't want that to get lost.

**Comment by Zanderaf** [comment]
I mean, I think the part in the DMG kinda meant that say, a tiefling bandit-

it would have the same things as the player race no?

**Comment by revilowaldow** [comment]
Some of them use PHB inspired features, but the majority do not. Almost all of them, PHB reference or not, also refer to some typical NPC trait such as "ambusher" or "pack tactics", in addition to other mechanical adjustments.

What you do at your own table is always up to you, but the System is aiming to reflect the default game rules. And the DMG recommends the information in the table to build NPCs from scratch.

**Comment by arbron** [comment]
> Sorry, what I mean is, you can now manually give it those features. But it would be good to have a compendium of NPC-races, that reflects the table, which you could add to any NPC you want without having to create the table content again and again, or without using PC-races on NPCs, which is unintended by the game even though the system now allows it. I think the right way to do that is to implement whatever is in the new DMG when it releases, which may be as part of a premium module, I just didn't want that to get lost.

Certainly if something similar is in the new DMG it will be included with that. For now the system data should support building those in the same way as PC races are built.
