### ISSUE TITLE
Inventory Items with long names don't wrap neatly

### ISSUE THREAD

**Issue by revilowaldow** [foundryvtt/dnd5e#2674]
Title and the picture say it all.

![Screenshot 2023-12-17 at 13 08 36](https://github.com/foundryvtt/dnd5e/assets/52298102/caba0558-ad4b-495c-a542-41980d12eefe)

![Screenshot 2023-12-17 at 13 10 33](https://github.com/foundryvtt/dnd5e/assets/52298102/60eac2f2-c485-4475-82b1-b92eb0fd8935)

**Comment by arbron** [comment]
Resolved on the new character sheets
