### ISSUE TITLE
Gold Gained from background

### ISSUE THREAD

**Issue by etoy22** [foundryvtt/dnd5e#2675]
Hi i would really like it if i could give gold in background

**Comment by Zanderaf** [comment]
Most likely going to be bumped into a Starting Equipment Advancement option, along with actual equipment like "small knife" or other misc items you may get.

**Comment by etoy22** [comment]
I have already successfully done things for Starting Equipment using the choice option and grant option. However gold is the only thing that i couldn't add.

**Comment by arbron** [comment]
Can now be handled by adding a container with gold inside, since most backgrounds say something like "A pouch with 20 gp".
