### ISSUE TITLE
Setting to round-up when doing "apply half damage"

### ISSUE THREAD

**Issue by ThiefMaster** [foundryvtt/dnd5e#2683]
Some DMs prefer to always round up instead of rounding down when someone takes half damage. It would be nice to have a setting to configure whether "apply half damage" should round up or down to make this button useful in campaigns where you round up.

**Comment by Fyorl** [comment]
These sorts of house rules are the domain of modules, I think. We expose an appropriate `dnd5e.applyDamage` hook that could be used for this.
