### ISSUE TITLE
Feature Request: Expose a way to modify the `MeasuredTemplate when created from an Item

### ISSUE THREAD

**Issue by caewok** [foundryvtt/dnd5e#2684]
When casting a spell, like _fireball_, dnd5e runs through a series of steps to link the item (e.g., the _fireball_ spell) to the template. But it is very difficult for modules to modify the template that is created at that point.

In `item.mjs`, this line of code is particularly problematic:
```js
templates = await (dnd5e.canvas.AbilityTemplate.fromItem(item))?.drawPreview();
```

There is not, as far as I can tell, a straightforward way to modify the created template prior to its preview being drawn. I could not find anywhere that `AbilityTemplate` is exposed, so I don't think I can use libWrapper. There are hooks before and after this step, which are nice, but they are all either too early or too late. I need to take information from the item and use it to modify the template parameters. (My current workaround is to hook the `MeasuredTemplate` drawing, but that is not great because it is overinclusive and because I don't really care about the template drawing per se, I care about getting information from the item upon template creation.)

So, my request is to add something to let modules modify the template upon creation. Something like:
```js
const template = dnd5e.canvas.AbilityTemplate.fromItem(item);
Hooks.call("dnd5e.itemTemplateCreation," template, item, options);
await template.drawPreview();
```

**Comment by arbron** [comment]
That is a good idea.

I will say, you can patch `AbilityTemplate` using exactly the path you used there `dnd5e.canvas.AbilityTemplate`.

**Comment by caewok** [comment]
Good to know. I was trying to figure out if that class was exposed.
