### ISSUE TITLE
Adding subraces

### ISSUE THREAD

**Issue by TurGoose** [foundryvtt/dnd5e#2691]
Similar to how subclasses work, or some other way to implement such mechanics as transformations in grim hollow. In older versions of the system we did this through a second background or race, but now there is a limit to only one race and backgroun.

**Comment by Zanderaf** [comment]
There was a discussion for this, but the approach the system took was just building each subrace as its full race, IE for example,

Instead of a Elf Race + High Elf Subrace, its just a High Elf Race, a Wood Elf Race, etc

**Comment by TurGoose** [comment]
Transformations it's template on your race, what evolves with character level and story. Here are some examples: Lich, Vampire, Lycanthrope, Seraph and Fiend. Everything is described on Grim Hollow: The Campaign Guide page 30.

I can, of course, just add advancements manually, but it's a little different.

**Comment by MaxPat931** [comment]
You can transfer Advancements from one item to another by dragging and dropping, perhaps this could help your setup a bit, but of course there are some things to consider, such as scale value references and things.  
But you could create Human, Dwarf, etc, and Lich, Vampire etc races/backgrounds, and then transfer the advancements on an actor once they choose/gain one.  
This video uses Classes, but the process is the same

https://github.com/foundryvtt/dnd5e/assets/86370342/b93a192c-4b8b-4e58-b40d-8e56edb982f9

**Comment by TurGoose** [comment]
> You can transfer Advancements from one item to another by dragging and dropping, perhaps this could help your setup a bit, but of course there are some things to consider, such as scale value references and things. But you could create Human, Dwarf, etc, and Lich, Vampire etc races/backgrounds, and then transfer the advancements on an actor once they choose/gain one. This video uses Classes, but the process is the same
> 
>  BarbFighterGestalt.mp4

This is what I said, either add it manually or combine it with another. I started talking about subraces because this will make it possible to implement quite a lot of things in the end.
Still, I hope this option will be added in the future.

**Comment by arbron** [comment]
I don't think the system will add it, but with v11 you can now add your own item types using module subtypes. If someone wanted to create a new module that adds a `transformation` type (or whatever you want it to be called) it would certainly be possible.

**Comment by webmaster94** [comment]
I don't understand the restrictiveness here. I asked a similar question with being able to handle multiple backgrounds. You seem to really be locking down the ability for homebrew with these changes. For example, any homebrew that splits race into something like Heritage and Culture, including D&D itself coming up this year will now have to create a separate item for every possible combination? I honestly just don't understand the thinking. If we can put any subclass on any class, why can't we have the same functionality for races?
