### ISSUE TITLE
Starter Hero Riswyn has Creature Type undefined (dwarf)

### ISSUE THREAD

**Issue by etiquettestartshere** [foundryvtt/dnd5e#2693]
One of the Starter Heroes, "Riswynn (Dwarf Rogue)", has an undefined (dwarf) Creature Type (should be Humanoid (dwarf)).

![image](https://github.com/foundryvtt/dnd5e/assets/148253744/8b611f0a-dc89-4976-a9a2-4e51497d21c9)

**Comment by luccavp12** [comment]
I'll try to look into this!

**Comment by luccavp12** [comment]
Where is this bug occurring for you?

**Comment by arbron** [comment]
I can see this on the current release:

<img width="402" alt="Screenshot 2023-12-29 at 16 13 58" src="https://github.com/foundryvtt/dnd5e/assets/19979839/6643338f-f9e1-473e-ab0b-122bbebb848e">

**Comment by luccavp12** [comment]
@arbron so I found that under packs/heroes.db it just looks like the parameters of Riswynn are messed up. 
Here is Riswynn: 
![image](https://github.com/foundryvtt/dnd5e/assets/20866887/2be685c7-782e-4708-9c45-190db0906c97)

Here is Biero who looks fine:
![image](https://github.com/foundryvtt/dnd5e/assets/20866887/26d71845-99c7-404b-bda5-e575dca65985)

What do you think about this?

**Comment by arbron** [comment]
> What do you think about this?

Just didn't get properly added during the conversion process. Just add `humanoid` to `value` and it should be fixed.

**Comment by luccavp12** [comment]
Ok I will try that shortly.

**Comment by luccavp12** [comment]
> > What do you think about this?
> 
> Just didn't get properly added during the conversion process. Just add `humanoid` to `value` and it should be fixed.

Hey @arbron I'm having trouble getting the change to show up in my local version. What else do you have to do besides rebuilding the DBs?

**Comment by arbron** [comment]
> Hey @arbron I'm having trouble getting the change to show up in my local version. What else do you have to do besides rebuilding the DBs?

Are you running on v11? The current DB build tools build to the old v10 file format, which Foundry converts automatically if no v11 databases are found.

In order to get your changes to appear you have to first delete the v11 database folders (so delete `packs/heroes/` folder but leave `packs/heroes.db`) and then Foundry will re-convert next time you launch your world.

The tooling will be fixed soon so you won't have to do this in the future :).

**Comment by luccavp12** [comment]
@arbron Thank you! Also just for clarity, is there any way to fix the actor once it has been imported into a world? Or is that just something for the user to fix?

**Comment by krbz999** [comment]
That would be easier for users to fix than for the system to write a script.

**Comment by luccavp12** [comment]
Alright ty @krbz999
