### ISSUE TITLE
Incorrect calculation of AC when there are several enchantments

### ISSUE THREAD

**Issue by Zyertdox** [foundryvtt/dnd5e#2696]
I have 2 enchantments, from breastplate and from shield. 
Expected: AC should be 14 + 2 + 2 + 2 = 20.
Actual: AC is 14 + 2 + '22' = 38
Before 2.4.1 (or 2.4) everything was ok.
![image](https://github.com/foundryvtt/dnd5e/assets/7522793/407a158f-57b4-4f97-921b-bb900d42a21c)

**Comment by krbz999** [comment]
This is expected with how you have set up the effects. What you are seeing is string concatenation where '2' and '2' becomes '22'. The specific attribute, `system.attributes.ac.bonus`, was changed from integer-only to a string in 2.4.0 to allow for using roll data like `@abilities.wis.mod`; if you change the effect values to '+2' instead you should be seeing the correct total.
