### ISSUE TITLE
Direct calls of `getRollData` in Actor5e to the system model

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2698]
Currently we just skip over `group` actor specifically in `Actor5e`, but this fails for any other actor types added by modules.

If `getRollData` instead returned `system.getRollData` each added actor type could change behaviour any way it pleases.

Currently a new actor type is forced to have `system.attributes.prof`, otherwise they cannot even render owned items' sheets.

In fact, a whole slew of methods fail if an added actor type does not have `system.attributes`.

**Comment by JPMeehan** [comment]
Would appreciate this for sure, it's blocking me using items in my knw-actors module.
