### ISSUE TITLE
Setting a Custom Type on NPC programmatically does not take effect immediately

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/dnd5e#2706]
Setting an NPC's Type to Custom Type via a macro does set the field but does not take effect on the sheet until the field is acknowledged and the Type Config is saved.

[CustomType.webm](https://github.com/foundryvtt/dnd5e/assets/86370342/af6930b3-52b0-44aa-8292-ad0ca12c60f4)

**Comment by krbz999** [comment]
You would also have to set `system.details.type.value` to `"custom"`.

**Comment by MaxPat931** [comment]
D'oh
Thank you.
