### ISSUE TITLE
Character sheet missing fields for Characteristics

### ISSUE THREAD

**Issue by mnoreke** [foundryvtt/dnd5e#2732]
The character sheet is missing the following section from the character sheet that exist on DnDBeyond. This causes an issue when using other modules, such as TidySheet and DnDImporter.

The fields on DnDBeyond:
![image](https://github.com/foundryvtt/dnd5e/assets/5225366/3e41e665-f48b-4d93-9eaa-bff0f3612a5c)

DnDImporter converts them to text in the Appearance field:
![image](https://github.com/foundryvtt/dnd5e/assets/5225366/b86b3a97-b915-4fbc-80bc-a32a61e8ef05)

TidySheet adds a section for them, which doesn't pick up the data:
![image](https://github.com/foundryvtt/dnd5e/assets/5225366/2bee9799-51d5-4c19-8bac-ef749d647ec6)

Having a single spot that all modules can access this data would be preferable.

**Comment by Fyorl** [comment]
This is available now in the new sheet.
