### ISSUE TITLE
Level scaling on spells does not add static bonuses for every level

### ISSUE THREAD

**Issue by Adam-Osmani** [foundryvtt/dnd5e#2739]
When adding a static amount to the level scaling of a spell, that bonus is only added once regardless of how much the level of the spell is increased.

![image](https://github.com/foundryvtt/dnd5e/assets/90919907/a73a4e32-6f55-4e8e-80bd-2f4eb7a8ddba)

As we can see in the image above, the +3 is only added once for a third level spell, while it should be added twice as the spell is two levels above its base level.

![image](https://github.com/foundryvtt/dnd5e/assets/90919907/4c350835-fd9e-4ddc-88a3-5b0a33fbbb6f)

The same effect is seen when referring to a modifier.

**Comment by arbron** [comment]
Static bonuses don't increase as spells level up, only the dice do. As healing word states there "the healing increases by 1d4 for each slot level above 1st", so you only add a new 1d4.

**Comment by krbz999** [comment]
While true for this spell, there are spells that deal additional damage not involving a die roll as they are upcast (Armor of Agathys).

Having to write `5 * @item.level` in a damage formula and disable the scaling instead of just writing '5' in the scaling field seems like a bug to me.
