### ISSUE TITLE
Updated to 3.0.0, Character Sheets cannot open now for me (GM).

### ISSUE THREAD

**Issue by aceluck101** [foundryvtt/dnd5e#2762]
Just updated to new version, can't open my players character sheet's. I can open the NPC sheet, but it doesn't show the Armor Class or the Modifier & Saving Throw bonuses on them

**Comment by wolfb3ard** [comment]
Encountered this issue as well. The console log states:

`TypeError: An error occurred while rendering ActorSheet5eCharacter2 167. attributes.encumbrance is undefined
[Detected 1 package: system:dnd5e]`

However I can't open the character sheet to define encumbrance. This applies to any encumbrance option defined in config as well

**Comment by unsoluble** [comment]
Please disable all modules until you've verified that they've been updated to be compatible with the new release.

**Comment by wolfb3ard** [comment]
Yep, disabled all modules and reactivated one by one. It looks like it's libWrapper that's the culprit for me. Will wait until other modules have updated before moving over

**Comment by arbron** [comment]
> Yep, disabled all modules and reactivated one by one. It looks like it's libWrapper that's the culprit for me. Will wait until other modules have updated before moving over

Probably not libwrapper, but a module that relies on it. If you figure out what module it actually is you might want to mention it on their repo so it can be fixed and you can keep playing :)

**Comment by Hyodorio** [comment]
Worked for me when I disabled Dynamic Active Effects if that's of any use.

**Comment by SpaceYeti1** [comment]
Verified error occurs when libwrapper is active.

**Comment by aceluck101** [comment]
> Worked for me when I disabled Dynamic Active Effects if that's of any use.
Did this on my own, also worked for me. Probably the culprit, or one of em

**Comment by posiedengrave** [comment]
> Worked for me when I disabled Dynamic Active Effects if that's of any use.

This worked for me, thanks!

**Comment by abelph** [comment]
> Worked for me when I disabled Dynamic Active Effects if that's of any use.

I can also confirm that DAE is the problem. That was the only module I had to disable to get the sheets working again.

**Comment by ohmusama** [comment]
Ready Set Roll also seems to be broken. Rolls do not work with it active.

**Comment by unsoluble** [comment]
Folks we don't need to know about all the modules that don't work. :)

**Comment by DanielSims1** [comment]
I still have this issue with zero modules enabled

**Comment by unsoluble** [comment]
Please head over to the Foundry discord (and the #dnd5e channel) for general troubleshooting.
