### ISSUE TITLE
Character sheet won't load if an class images are `null`

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#2766]
![Screenshot_2024-01-31_170010](https://github.com/foundryvtt/dnd5e/assets/19979839/eb77cb2e-6bab-4844-8b2d-c76c34429d65)

**Comment by posiedengrave** [comment]
Having this same issue, I see it's closed, but what was the solution?

**Comment by posiedengrave** [comment]
> > Having this same issue, I see it's closed, but what was the solution?
> 
> Fix should be coming out in an update tomorrow, but for now you can create a script macro to fix it:
> 
> ```js
> game.actors.getName("CHARACTER NAME").items.filter(i => i.img === null).forEach(i => i.update({"img": "icons/svg/mystery-man.svg"}));
> ```
> 
> Just replace `CHARACTER NAME` with your actor's name and run that as a script macro and it should fix the issue.

Thank you! Helped me out of a weird spot in the meantime
