### ISSUE TITLE
Spells with limited uses do not show these anywhere on the actor sheet

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2773]

**Comment by Fyorl** [comment]
There's probably space at the 750px width breakpoint to fit a limited uses column.

**Comment by itteerde** [comment]
I consider this important. This should be 3.1 imho. With some races, maybe class warlock, some magic initiate, this can be a long list -- before using Spell Items with uses for Magical Items.

**Comment by Zanderaf** [comment]
Yea, 2nd'ing this for things like Mystic Arcanums for warlocks, being able to see whether or not you have used em at a moment's notice

**Comment by itteerde** [comment]
> Yea, 2nd'ing this for things like Mystic Arcanums for warlocks, being able to see whether or not you have used em at a moment's notice

which is why I wrote Warlock

```js
Hooks.on("renderActorSheet5eCharacter2", (app, [html]) => {
  if (!app.document.testUserPermission(game.user, CONST.DOCUMENT_OWNERSHIP_LEVELS.OBSERVER)) return;
  const spellTab = html.querySelector(".items-list.spells-list").querySelectorAll(".item-list");
  for (const list of spellTab) {
    const spells = list.querySelectorAll(".item");
    for (const spell of spells) {
      const item = app.document.items.get(spell.dataset.itemId);
      const uses = item.system.uses;
      if (uses.max > 0 && uses.per) {
        const per = (uses.per === "lr" || uses.per === "sr") ? uses.per : "";
        const newHTML = `
          <div class="item-detail item-range item-casts">
            <span class="value">${uses.value}/${uses.max}</span>
            <span class="unit">${per}</span>
          </div>
        `;
        spell.querySelector(".item-school").insertAdjacentHTML("beforebegin", newHTML);
      };
    };
  };
});
```
for the time being, (thanks alakshana)
https://discord.com/channels/170995199584108546/670336046164213761/1212157516608184361

**Comment by krbz999** [comment]
> Also, given that displaying the formula will break the UI a lot of times anyways (many formulas are just to long), there would be the real estate imho.

I agree that Uses should take priority over the 'Formula' column. 'Formula' is not very useful for spells in general, since their damage most often scales.
