### ISSUE TITLE
Dynamic Token Rings incorrectly scale with the token scale.

### ISSUE THREAD

**Issue by cs96and** [foundryvtt/dnd5e#2775]
If the token has a scale set, then the dynamic ring also scales.  This doesn't look correct, as it makes the token look like it takes up more squares on the grid than it actually does.  E.g. see the Balor from the SRD that has a scale of 2.5 by default...

![image](https://github.com/foundryvtt/dnd5e/assets/898086/d053865e-2d89-4c90-be2d-7dffaf82afcc)

As far as the Wizard is concerned, it looks like he can't get any closer to the Balor because he is now touching the ring, but he can actually move another square to the right.

The dynamic ring should scale to the grid size of the creature by default, rather than the token scale.

**Comment by arbron** [comment]
This is the reason for the `flags.dnd5e.tokenRing.scaleCorrection`, which will be getting a UI in the next release (https://github.com/foundryvtt/dnd5e/issues/2765).

**Comment by cs96and** [comment]
Thanks for exposing that setting.  Should the default value of that setting be the grid scale, rather than the token scale though?

**Comment by cs96and** [comment]
Copy/pasting a comment I made on #2776...

If you were playing with physical minis, then the base of a Balor mini would take up 3x3 grid spaces, but the mini itself may extend over this area. The dynamic token rings should do the same (this is more a discussion for https://github.com/foundryvtt/dnd5e/issues/2775 though).
