### ISSUE TITLE
Large Dynamic Rings hide the disposition hover box

### ISSUE THREAD

**Issue by cs96and** [foundryvtt/dnd5e#2776]
If you have a large dynamic ring, then you can no longer see the disposition hover box (friendly, neutral, hostile)...

![image](https://github.com/foundryvtt/dnd5e/assets/898086/6440fe03-514e-444b-a1a4-74b306b31fc1)

You can see my mouse cursor in the image, but the hover box is not displayed.  If I scale down the token, then the box reappears...

![image](https://github.com/foundryvtt/dnd5e/assets/898086/c0e905f2-02c9-4c1d-be65-d6786f3afefa)

**Comment by Fyorl** [comment]
Likely solved with foundryvtt/foundryvtt#8043 or #2765

**Comment by Fyorl** [comment]
As far as I'm aware, having the token ring scale with the token is the intended behaviour, and the `scaleCorrection` flag is the mechanism by which this can be adjusted according to the user's needs.

**Comment by Fyorl** [comment]
No longer a dnd5e issue as it uses the core dynamic token ring API. I believe this particular issue is resolved by the various grid fit mode improvements.
