### ISSUE TITLE
Deprecations refer to D&D 2.5+

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/dnd5e#2778]
SpellData#components has a deprecation warning since "D&D 2.5", a now-false version number. I'm sure there's others.

**Comment by arbron** [comment]
It says `3.0` in the code:

```javascript
    foundry.utils.logCompatibilityWarning(
      "The `system.components` property has been deprecated in favor of a standardized `system.properties` property.",
      { since: "DnD5e 3.0", until: "DnD5e 3.2", once: true }
    );
```

Where are you seeing this?

**Comment by JPMeehan** [comment]
My bad, I was on an earlier commit (was trying to figure out all the changes for updating my modules) and clearly missed the commit that updated the message.
