### ISSUE TITLE
Add setting for defining default Compendiums when clicking Add X

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/dnd5e#2780]
Add an option to define which compendiums should be opened when clicking Add Race/Add Background/etc so that users can default to their own personal compendiums if they want

**Comment by schultzcole** [comment]
> The current implementation is just a stopgap really. The goal we are heading towards is a compendium browser that aggregates all available options from all sources. So Clicking 'add race' will bring up the compendium browser filtered by all races.

Do you know if there is an issue open for this? I'd be willing to take a stab at it for 3.1 if no one has claimed it yet.

**Comment by Fyorl** [comment]
It's a fairly significant undertaking that probably requires a bit of design work before getting started. We can definitely start with an issue and some proposals/mockups for how it should work though.

**Comment by schultzcole** [comment]
Cool, if you have specific thoughts about how to approach it feel free to write that up, otherwise I'll take a stab at a design proposal tomorrow.
