### ISSUE TITLE
Users lack permissions to update containers nested within their sheets

### ISSUE THREAD

**Issue by Sorellia** [foundryvtt/dnd5e#2782]
As the GM, it's obviously possible to move items to a container and from one to an actor's inventory, but as a player, you do not count as the owner of any container on your sheet, so you cannot in any way move items to or from them.

I'm _guessing_ that this isn't intended behaviour, and I came to the permissions conclusion based on the fact that even whilst on a sheet owned by the player, they cannot edit items on the container while GM users can.

**Comment by arbron** [comment]
Need to override `_canDragStart` & `_canDragDrop` on container sheets.
