### ISSUE TITLE
[3.0.0] Prototype Sheet indicator

### ISSUE THREAD

**Issue by Mushie1** [foundryvtt/dnd5e#2784]
With the new 3.0 character sheet, the only way to know that you are on the "Prototype Sheet" compared to the "token" sheet is by hovering on the symbol at the top and look for the tool tip.  

It would be great if this symbol changed depending on what sheet you are on (or have the words) so users can quickly check they are editing the correct sheet
![image](https://github.com/foundryvtt/dnd5e/assets/77275833/dd8b9e79-12a3-420e-8d44-36a1e374b91e)

**Comment by Mushie1** [comment]
Thanks for updating this, but it looks like the update only works with NPC's and not Player sheets
![image](https://github.com/user-attachments/assets/89d63a85-a743-42ed-a9a6-72e1b27d5b0d)

**Comment by MaxPat931** [comment]
It seems to be tied to being an Unlinked Token rather than PC/NPC

Changing Akra to an unlinked token:
![image](https://github.com/user-attachments/assets/2e36b6e0-9144-4561-be1b-e9ce96b42303)
