### ISSUE TITLE
Empty speed tooltip displays if actor has no movement

### ISSUE THREAD

**Issue by tombomb** [foundryvtt/dnd5e#2786]
not sure whats in the box or whats triggering it, just saw it and thought i would post it. blank sheet with nothing setup on it in a new world 

![image](https://github.com/foundryvtt/dnd5e/assets/544509/43cba0fe-c88e-4fb7-8a5b-300b7d5a4f21)

**Comment by arbron** [comment]
What browser are you using? The tooltip appears over the HP bar for me.

**Comment by arbron** [comment]
Yeah, looks like it just because you didn't have any speed. We should probably not show the tooltip if no speed is on the actor.
