### ISSUE TITLE
New Char sheet portrait overlaps border

### ISSUE THREAD

**Issue by Wokeye27** [foundryvtt/dnd5e#2790]
It appears the portrait in the new char sheet overlaps the frame, so portraits can be partially obscured 
![image](https://github.com/foundryvtt/dnd5e/assets/77101610/cdffef39-ebd8-4cd1-b623-37f7bbccceb3)

**Comment by Fyorl** [comment]
This is intentional to give a 'full card art' effect for more traditional portrait styles, like the following:

![image](https://github.com/foundryvtt/dnd5e/assets/207433/d54dc703-ab07-4210-850c-89cbe3091099)

It will not work equally well with all styles of portrait I'm afraid.
