### ISSUE TITLE
new char sheet: classification of items incorrect and possibly uneditable?

### ISSUE THREAD

**Issue by Wokeye27** [foundryvtt/dnd5e#2791]
Hi, 
Great work on the character sheet. I had a look at the items lists, two issues arose:
1) some items appear to be in the wrong classification eg Bedroll is loot, tinderbox and lanterns are consumables
2) it does not appear that I can change the classification on these or any other items, so homebrew items may appear in odd lists.

It would also be great to have an 'Armor' (or Armour lol) classification for armour, or perhaps 'wearable/worn' category of equipment?

**Comment by Fyorl** [comment]
The categorisation of items is controlled by the item's `type`. It can't be changed (via the UI) once it has been set. You'll find the exact same limitation on the legacy sheet.

At the moment there is a toggle on the search bar, it looks like this: 
![image](https://github.com/foundryvtt/dnd5e/assets/207433/f80415fb-e71b-4395-9cee-0437bc9f4cb4)

It can be used to toggle between grouped or ungrouped. And you can use the sort toggle to the left of that button to change from alphabetical to manual sorting and arrange things how you prefer. It's possible we could add some additional grouping modes in the future.

**Comment by Wokeye27** [comment]
Thanks.  
Being able to edit the item 'type' would be sensational if possible, would work for homebrew items esp well and allow us to quickly fix little weird categories when they arise (like bedroll being loot).   I guess the alternative is to delete the compendium entry, re-create?

**Comment by Fyorl** [comment]
Closing this for now. It can be re-raised as separate issues for compendium content that has the wrong item type and/or specific requests for different grouping or additional categories.
