### ISSUE TITLE
New Char sheet: Draconic resilience not listed as such in AC tooltip

### ISSUE THREAD

**Issue by Wokeye27** [foundryvtt/dnd5e#2793]
Low priority, but I noticed my character with draconic resilience had the AC bonus added, but it was listed as 'none'.  This was the same for another character with unarmored defence (monk).  
![image](https://github.com/foundryvtt/dnd5e/assets/77101610/51581ca3-67ea-47c2-9747-54efa76df60d)

**Comment by arbron** [comment]
Draconic resilience doesn't add a bonus, it changes the AC calculation (that's the `13 Base` on the first line). Not sure what the `+2 None` is coming from, you might need to check your effects.
