### ISSUE TITLE
Encumbrance Pips Not Quite Matching Encumbrance Effects

### ISSUE THREAD

**Issue by Larkinabout** [foundryvtt/dnd5e#2796]
With Variant Encumbrance enabled, the encumbrance bar and pips on the 3.0 character sheet do not appear to match up with when the Encumbered and Heavily Encumbered effects are applied.

Here the character has the Encumbered effect, but the first pip is slightly further along:
![image](https://github.com/foundryvtt/dnd5e/assets/105953297/dd1f83bd-7905-4c17-b3ed-7e8b06ee1664)

Likewise, this is when the Heavily Encumbered effect is applied:
![image](https://github.com/foundryvtt/dnd5e/assets/105953297/b61a6f4e-0070-4bc3-90b3-b778bdbc1c6f)

No modules are enabled.

**Comment by Larkinabout** [comment]
Pips and bar percentage are both set to 50% here:
![image](https://github.com/foundryvtt/dnd5e/assets/105953297/0e5d9dbe-eefb-4039-b710-b5f6e55490fa)

I believe the pip is slightly off-centre due to the arrow icon being inset 50% to its left side. The bar also appears to be off-centred to the left however, possibly due to subtracting the border with from the bar percentage.

**Comment by Fyorl** [comment]
There is actually a 2 or 3 pixel 'border' on the right of the bar itself that is actually part of the bar. You can see it more clearly on the HP and HD bars. It's quite dark so it looks like it's part of the track, which might be confusing things here. We could potentially just remove this styling from the encumbrance bar if it proves too confusing.

**Comment by Larkinabout** [comment]
Yeah, it almost looks like the side of the bar has a 3D effect, which is giving me the impression of the bar being short. Maybe either remove or bring the colour up a bit. Looks like the arrow still needs a slight adjustment, so it's spot on with the bar's bordered end.
