### ISSUE TITLE
[Feature Request] Split damage based on type

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/dnd5e#2799]
At the moment when you roll for damage the total gets combined to 1 number, however this is not always ideal when two damage types are meant to behave different from one another. To give two examples: the Ice Knife spell and the Giant Spider's Bite attack.
Ice Knife deals both piercing damage and cold damage, but the piercing is only if the target is hit, while the cold damage is only on a failed saving throw.
The Giant Spider's Bite attack deals piercing damage on a hit, but on a hit also forces a saving throw causing poison damage on a failed save, or half on a successful one.

To get back to the point, it would be nice if you could have an option to split the damage cards into sections for each damage type, so that people can quickly apply only the damage they are meant to take.

**Comment by arbron** [comment]
This will probably be something we handled when we do this: https://github.com/foundryvtt/dnd5e/issues/1964
