### ISSUE TITLE
Inventory not showing

### ISSUE THREAD

**Issue by noah-ruhland** [foundryvtt/dnd5e#2806]
After migrating with the new D&D 5e 3.0 the default Sheet does not show the inventory or Features properly anymore. 
This is the Inventory in the _"Legacy 5e Character Sheet"_ : 
![grafik](https://github.com/foundryvtt/dnd5e/assets/65781079/1b92cbcb-4e67-43ef-8591-abdce94241db)

And this is the Feature Page but the same applies for the inventory of the same character in the _"Default 5e Character Sheet"_: 
![grafik](https://github.com/foundryvtt/dnd5e/assets/65781079/f7d7555c-0a81-4367-9853-b6308e5c38e4)

It does not seem to be deleted, but it is not showing anymore. This Bug appears even after turning all modules off.

**Comment by arbron** [comment]
On the legacy sheet you are showing the Inventory tab, but on the new sheet you are in the Features tab. Does this happen when both are on the same tab?

**Comment by noah-ruhland** [comment]
Tried it out today and the bug is gone. Thanks for the help though
