### ISSUE TITLE
Player character sheets not opening.

### ISSUE THREAD

**Issue by gallantghost** [foundryvtt/dnd5e#2813]
PC sheets from before the update – as well as any newly created ones – will not open. Is this an issue with contesting modules? NPCs and monster sheets open, however.

**Comment by vinnie2k** [comment]
Disable a few modules and see which one conflicts. Worked for me.

**Comment by Windyplains** [comment]
If you have the **DFreds Convenient Effects** mod, that is one mod that is blocking the character sheets from loading.

**Comment by bradroeger** [comment]
Dynamic effects using Active Effects (DAE) seems to be another

**Comment by gallantghost** [comment]
Thanks, those helped. Still have one sheet not opening, but I'll just have to play with turning off more modules.

**Comment by Kelindor1974** [comment]
I have the same issue. Disabled the mentioned modules, and 7/8 Pc's are accessible. The 8th , a Fairy Druid , nothing. removed from board , pulled in from the characters folder. nothing. The hud works , but can not access new or old sheet. 
Any other moduels that have been flagged ?

**Comment by unsoluble** [comment]
Please join us on the discord (in the #dnd5e channel) for troubleshooting. This really isn’t the best place for that. :)
