### ISSUE TITLE
Player Inventories are not showing up on the V3.0 Sheet when using SteamDeckOS, on Firefox. 

### ISSUE THREAD

**Issue by VuraDMDoe** [foundryvtt/dnd5e#2814]
**Issue:** Upon logging into foundry using Firefox on the KDE5 Plasma desktop mode for steam deck, players inventory does not show up on the inventory tab, nor do their features. If one switches to the legacy sheet, everything shows up without issue. 

I'm bringing up this issue, even though it seems very niche, because it may affect more Linux Distro players in the future. None of my players are linux users, however, I could see a vast majority of folks being that. This issue isn't replicatable on Windows Architecture devices. It affects both GM view and Player view.

Hope this report amongst 1000+ isn't taking up too much of your time.  Your team does great work.

-Vura

**Comment by VuraDMDoe** [comment]
> What version of Firefox is it?

117.0.1 (64-Bit). Version from September 12th, 2023. I could attempt updating it at some point later this week if that would help potentially solve the issue.

Thanks Fyo!

**Comment by Fyorl** [comment]
> > What version of Firefox is it?
> 
> 117.0.1 (64-Bit). Version from September 12th, 2023. I could attempt updating it at some point later this week if that would help potentially solve the issue.
> 
> Thanks Fyo!

Unfortunately I believe at least version 121 is required, for the CSS `:has` selector: https://caniuse.com/?search=has

Hopefully your distro has that version available.
