### ISSUE TITLE
Remove `-subject` fallback for inferring token ring subjects

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#2819]
Causing a bunch of unnecessary 404 errors for people who have only one token artwork.

**Comment by CS-Birb** [comment]
The hint for the Subject path still references this now-removed behaviour: [en.json#L1422](https://github.com/foundryvtt/dnd5e/blob/3.0.x/lang/en.json#L1422)

**Comment by hadook** [comment]
This issue should be re-opened. The token configuration window still shows a hint for this behaviour, as if it was available.
![image](https://github.com/foundryvtt/dnd5e/assets/18307813/85b671f9-9906-4493-bd38-79cb32ba2bc1)
