### ISSUE TITLE
feature suggestion: toggle for default pause icon or fancy dnd5e pause icon

### ISSUE THREAD

**Issue by Freeze023** [foundryvtt/dnd5e#2833]
As the creator of Alternative Pause Icon my module currently doesn't function anymore as the added class makes the CSS of dnd5e of higher specificity meaning personalized pause icon + text is no longer possible using my module (while keeping the module general for any system). So it would be lovely if there was a toggle in the system settings where you can disable this extra CSS.

I know a lot of folks like to personalize this pause message. So i hope this suggestion is entertained.

**Comment by arbron** [comment]
Can't you just increase the specificity of your CSS a bit? Shouldn't stop it from working on other systems.

```css
#pause#pause {
  /* changes */
}
```

**Comment by Freeze023** [comment]
the problem is the css of dnd5e is higher specificity because of selecting the added dnd5e2 class. I cant add that class by default as it would break it for other systems. But if it is a big problem to add a toggle to the system, I will find a way around it.

**Comment by Freeze023** [comment]
Fixed on my end.
