### ISSUE TITLE
_enrichChatCard assumes message-sender exists

### ISSUE THREAD

**Issue by Larkinabout** [foundryvtt/dnd5e#2835]
As an example, my module [Change Log](https://github.com/Larkinabout/fvtt-change-log/) has an option to remove the `message-sender` from the chat message using Foundry's `renderChatMessage` hook. This is for the purpose of reducing the chat card when the sender info isn't important. 
![image](https://github.com/foundryvtt/dnd5e/assets/105953297/1311938f-a769-464f-870a-94deb56bf1ed)

However, dnd5e 3.0.0's `_enrichChatCard` subsequently assumes the content of the chat message, specifically that `message-sender` exists.

It's possible that other modules would wish to modify the chat message using `renderChatMessage` rather than dnd5e's own hook where the module is intended to be system-agonistic, therefore I'd request that the system handles for missing content.

**Comment by arbron** [comment]
@Larkinabout  A fix for this has been merged, but you might want to check out the new `dnd5e.chatMessage` hook which is called after the system's changes have been made, so you can modify the messages without issue.

**Comment by Larkinabout** [comment]
Many thanks. Yeah, noticed the hook, however because the module doesn't just support the dnd5e system I figured it was much simpler this way than writing code specifically for a different hook just for dnd5e's handling. At least for this particular issue. Thanks again.
