### ISSUE TITLE
`CONFIG`-provided baseItem additions trigger deprecation warning

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/dnd5e#2850]
Modules and world scripts that add to the `baseItem` setups, for example code like
```js
CUSTOM_CONFIG.DND5E.weaponIds = {
  musket: 'chaosos-5e-content.non-srd-equipment.EOvFbYS53yCdLvip',
  pistol: 'chaosos-5e-content.non-srd-equipment.oslEAx5D7nPzG9G3',
};
foundry.utils.mergeObject(CONFIG, CUSTOM_CONFIG);
```
trigger the deprecation warnings around the migrated type fields. This is because the select dropdowns in `ItemSheet5e#getData` pull from the un-migrated `index` for each item linked, and without unlocking the compendium and updating those item's entry in the database you run into the deprecation warning.

**Comment by JPMeehan** [comment]
I don't know if there's a solution but it's annoying to fix.

**Comment by arbron** [comment]
The proper fix for this is to migrate your compendiums. Due to the fact that this is an in-memory migration, you'll have to use two commands to complete it:

```javascript
const compendium = game.packs.get("chaosos-5e-content.non-srd-equipment");
dnd5e.migrations.migrateCompendium(compendium);
// Make sure the migration is fully complete and successful before running the next command, otherwise you may lose data
dnd5e.migrations.refreshcompendium(compendium);
```

**Comment by JPMeehan** [comment]
Typo in the command - it's `refreshCompendium` with a capital C
