### ISSUE TITLE
Actions not displayed on actions tab of PC sheet in v3

### ISSUE THREAD

**Issue by seanwilliams1964** [foundryvtt/dnd5e#2851]
We just upgraded to v3 today and a few things cropped up:

1. The Actions tab on the PC sheet is not fully displayed. It merely shows 'ions'. 
2. AC is not calculating correctly (Scale (AC 14) + Shield (+2) + DEX (+2) = 18, but it is at 16)
3. Damage is not auto-decremented on and attack. I have to open the opponent form to manually adjust it.

Not MAJOR, but definitely an impediment to combat. But I LOVE the new layout. 

![2024-02-03_0-22-25](https://github.com/foundryvtt/dnd5e/assets/1427618/f1e44719-92e7-4d50-a0bb-54c4e17cb758)
![2024-02-03_0-23-55](https://github.com/foundryvtt/dnd5e/assets/1427618/42ab0e27-1969-4814-9d7f-7e2fc8fb4e9f)

**Comment by arbron** [comment]
Actions tab is from a module, not the system.
