### ISSUE TITLE
Add option to favorite items from the item context menu

### ISSUE THREAD

**Issue by schultzcole** [foundryvtt/dnd5e#2853]
I think it'd be useful to be able to favorite an item from the item context menu on the character sheet. In my brief testing of 3.0 I've noticed that dragging and dropping items to the favorite section is pretty annoying on a track pad, so the option to use a context menu instead would be appreciated.

I'm happy to do the implementation, though I have one architectural question: it seems to me that a reasonable approach would be to add `addFavorite` and `removeFavorite` methods to `CharacterData` and call those from `ActorSheet5eCharacter2` for the existing drag/drop workflow and from `InventoryElement` for the new context menu workflow. Does that sound like a good approach?

**Comment by arbron** [comment]
Sounds like a good solution.
