### ISSUE TITLE
Add theme picker interface for changing between light, dark, and other themes

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#2864]
- Auto (changes between light/dark mode depending on OS settings)
- Light
- Dark
- Colorblindness (might make sense as a separate system setting so it can apply to light and dark mode)

This will also support user-definable themes defined in CSS (any HTML changes would have to be handled by separate sheet modules).

**Comment by schultzcole** [comment]
Just adding to the wishlist here, it might be useful or nice to be able to apply multiple themes at once (light + colorblind, dark + colorblind, etc.), but have a way to denote that certain themes are mutually exclusive (light and dark are mutually exclusive, but not exclusive with colorblind, for instance).

This would allow for useful combinations of themes (potentially provided by modules or core dnd5e).
