### ISSUE TITLE
Add context menus to class and subclass items on new sheet

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/dnd5e#2867]
On the new sheet that 3.0 introduced, I am unable to edit the class or subclass items. It doesn't seem to matter whether I'm in Play or Edit mode. With all the other items in the Features tab, I can right-click on them or use the new vertical ellipsis to edit them. With the class and subclass items, it appears that all I can do is delete them in Edit mode by clicking on the icon.

**Comment by arbron** [comment]
If you click on them in play mode it will open the class/subclass sheets, but we should probably also add context menus to those.

**Comment by kaelad02** [comment]
Clicking on an item on those tabs typically "use" the item so I didn't think to do that. That works in play mode but doing that in edit mode deletes the item. I didn't see a way to edit the class when the sheet is in edit mode.
