### ISSUE TITLE
Unable to delete items/spells that are at the bottom of the character sheet at its default size

### ISSUE THREAD

**Issue by CeaneC** [foundryvtt/dnd5e#2876]
When a feature, inventory item, or spell is at the very bottom of the character sheet, the context menu descends outside the window, making the lower buttons unclickable.

![image](https://github.com/foundryvtt/dnd5e/assets/43473593/845c9376-67bc-4188-bf63-491340ccdcdb)

This can be avoided by resizing the character sheet to be smaller vertically, but on a 1080p monitor the sheet takes up the entire window height by default.

Running Foundry build 11.315, D&D5e version 3.0.1

**Comment by LadyDefile** [comment]
I searched for this by "context menu" that's why i didn't find it and created a duplicate. My bad, lol.
