### ISSUE TITLE
NPCs lost AC, Modifiers and are unable to roll Skill Checks

### ISSUE THREAD

**Issue by HilmarLoft** [foundryvtt/dnd5e#2878]
Got the recent update and suddenly noticed that my NPCs now all suffer from the same issue. None of them have their ACs any more, their Skill Checks cannot be rolled anymore and all of their attack, skill and proficiency modifiers no longer apply to anything. The image should help illustrate this (and the nat1 helps illustrate my feelings on this issue)

![DndBug_01](https://github.com/foundryvtt/dnd5e/assets/158787404/a08966f1-bdd1-4e60-be3b-5fc4f67f8a1a)

Anyone know if this is a common issue?

**Comment by krbz999** [comment]
how about with all modules disabled

**Comment by HilmarLoft** [comment]
Ah yeah that seems to have fixed the issue. Now I just have to figure out which one of the mods is poisoning the well.

Thank you!
