### ISSUE TITLE
player effects page leaks unidentified items

### ISSUE THREAD

**Issue by jtracey** [foundryvtt/dnd5e#2885]
If a player is given an unidentified item with effects, the item's name and effects are masked in the Inventory page of their character sheet, but are all completely visible in the effects page.

**Comment by Fyorl** [comment]
The relationship between attuning and identifying needs more work. There are also (very rarely) items that confer magical properties on wielders while they are not attuned, and there's no way to distinguish at the moment. That will probably have to wait for the work on activities. For now, hiding effects of unidentified items probably gets us most of the way there and is consistent with the item sheet.
