### ISSUE TITLE
The SRD Flame Tongue weapons should have an additional damage formula for the 2d6 fire, not in the "Other" field

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2902]

**Comment by MaxPat931** [comment]
The flame tongue technically has to be activated to apply the bonus fire damage, but since it's a BA to activate and there's no restriction on how often you can do so, attacking with a flame tongue without fire damage is probably the exception

**Comment by Fyorl** [comment]
Ultimately we need a way to distinguish between individual properties of an item that require attunement to be in effect, and those that don't. I think activities solve this fairly neatly though, so it's probably best to wait for those rather than attempting to implement some interim solution in the meantime.

**Comment by krbz999** [comment]
> There are a few examples of a need for that damage to be in the Other field.

Damage should never be in 'Other' because it is (1) not a damage roll, (2) does not have a damage type, and (3) cannot crit.

**Comment by thatlonelybugbear** [comment]
(True, so the need for opt in damage formulas is even greater then.

With customizable options to allow crit or not and attach any subset of these formulas to saving throws being present on the item)

**Comment by krbz999** [comment]
This could be solved by dividing the damage parts into sections of rolls and providing additional damage buttons, one for each section, with each part being able to be in none, one, or several of these sections. Or roll groups, if you will.

**Comment by thatlonelybugbear** [comment]
Personally I would prefer to predetermine how the Item will work from the Item Sheet and refrain from adding even more buttons in the chatmessage, at least saving some space. 

Preference would be something like:
If the Item is attuned/identified, system updates the "attunement-linked" damage formulas to add them in.
If the Item has a save, system updates the "save-linked" damage formulas to add them in (including different damage multipliers depending on fail/success and by default not crit these ones per RAW IIRC)

But I think we might have strayed a bit off topic... 😅

**Comment by krbz999** [comment]
The flame tongue weapons should be updated with correct Activities. Currently the fire damage is in a Utility activity.
