### ISSUE TITLE
Fix descriptive note on Savage Attacks (or add an Active Effect to the feature instead)

### ISSUE THREAD

**Issue by unsoluble** [foundryvtt/dnd5e#2913]
The SRD `Savage Attacks` feature currently says to "Enable this feature in the Special Traits section of the character sheet", but there is no longer a named "Savage Attacks" feature in there.

This should _either_ be changed to read "Add 1 to the Melee Critical Damage Dice field in the Special Traits section of the character sheet", _or_ an Active Effect should be added to this feature item that targets `flags.dnd5e.meleeCriticalDamageDice` (and adds `1`).

![CleanShot 2024-02-04 at 21 23 17](https://github.com/foundryvtt/dnd5e/assets/801582/a5d80094-491e-49e5-9361-08b003d9e615)

**Comment by krbz999** [comment]
_Insert witty comment here._
