### ISSUE TITLE
Campaign upgrade from system version 2 to 3 consumes >2 MB of JS heap memory per second

### ISSUE THREAD

**Issue by jyurkiw** [foundryvtt/dnd5e#2914]
Steps to Reproduce:

1. Create a campaign in system version less than 3, Foundry version 10.
2. Import several thousand items from content compendiums.
3. Upgrade Foundry to version 11.
4. Upgrade 5e system to 3.
5. Load into the campaign in Chrome.
6. Open chrome dev tools.
7. Go to "Memory" tab.
8. Turn on profiling.
9. Observe memory consumption rate.

The memory consumption rate of a campaign update when moving from system version 2 to 3 is unreasonable. 2 MB per second bricks campaigns with a lot of imported content because Chrome limits JS to 1 GB of memory per tab. So if the update takes more than ~500 seconds the tab will crash and the process must start over from the beginning.

**Comment by Fyorl** [comment]
For items and actors we perform the updates one-at-a-time, so it's unclear why the browser would be holding onto that memory and not garbage collecting it.

**Comment by specificJyurkiw** [comment]
Maybe there's a dangling reference being generated somewhere for every item during the update process? Because you can manually execute garbage collection in the memory tab of the dev tools and clicking it does nothing.
