### ISSUE TITLE
Item charges as a Resource replacement [Suggestion]

### ISSUE THREAD

**Issue by LadyDefile** [foundryvtt/dnd5e#2915]
I know the aim is to move away from the Resource system on the legacy sheets. In that case, could we please get an option to set item charges? Optional setting, obviously, but it would be a good replacement for the Resource system.

In my case, my campaign has a cooking system with a component pouch (DMInspo's Cooking System). The component pouch holds 5 charges by default, then getting more pouches allows you to increase how many charges you have. Currently, we are using the old resource system but I've found there is no recourse in the new sheet. When a new character picked up the system, I had to return them to the legacy sheet, modify the resource there, then come back.

It's not world-ending because, obviously, it's just a quick change back and forth between sheets but if the goal is switch to using items instead, there needs to be a way to set charges on items.

**Comment by arbron** [comment]
I'm unclear on what you mean, there are charges on items. Not containers specifically, but pretty much all other items can have a certain number of uses that can be consumed by the item and modified by activating other items if required.

**Comment by LadyDefile** [comment]
You know, you're right and I'm kinda dumb. LOL. I swear I looked EVERYWHERE yesterday and couldn't find it. I think it's because I was looking at the wrong item types or something. So, ignore me, I guess?
Though I would like to see charges as an option to customize on tools.

**Comment by MaxPat931** [comment]
I think this could make the case for adding Scale Values to Feature Items (or a new item type?)
In their example, they may have set Resource 1 to "Cooking Charges", with some items using the resource as a consumption target, and each Component Pouch added to the actor's inventory could have used an active effect to increase `resources.primary.max` by 5, easily adjusting the total number of available Cooking Charges.  
Moving to Item Charges means that you cannot modify the number of charges with active effects, and they will need to adjust their "Cooking Charges" item manually as they gain/lose component pouches, as using charges on each individual Component Pouch would be undesirable for items consuming Cooking Charges.
If Scale Values could be added to Features, then we can set the maximum charges to `@scale.item-name.scale-name` and modify that with AEs as needed.
