### ISSUE TITLE
If an active effect modifies a dice scale value or any of its specific properties (.number or .faces) by appending a string, the remaining properties are completely lost

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2918]
For example, if you have a scale value `@scale.steve.dice`, and an active effect with `system.scale.steve.dice.faces | Add | min2`, then you can no longer refer to its number, i.e., `@scale.steve.dice.number`. It seems like the full derived scale value on the actor is replaced with just a string.

Note: numbers work fine, this seems to only be an issue with strings such as `min2` or `r<3`, etc.

**Comment by Fyorl** [comment]
I wasn't even aware that these fields were targetable by active effects. I'll tentatively mark it as a bug, but it seems like it could be tricky to resolve.

**Comment by krbz999** [comment]
To be able to modify (dice) scale values is an intended feature and was implemented here: https://github.com/foundryvtt/dnd5e/pull/2011
