### ISSUE TITLE
Formula data in attack bonuses do not work on ammunition

### ISSUE THREAD

**Issue by FalconPilot** [foundryvtt/dnd5e#2920]
I was fiddling around trying to setup a custom ammunition in my campaign, trying to hack my way around making the "Magic Stone" cantrip work as-is without having to fiddle with the ammo or duplicate my player's weapon 😄 So I used the following process to make it as simple as possible:
`@mod - @abilities.dex.mod`
But then I was greeted with the following error: 
![image](https://github.com/foundryvtt/dnd5e/assets/9877634/afb61b4f-e182-4502-bb04-c9a95ddab485)
So, I thought that maybe using `@mod` could be the culprit for some reason, so I tried expanding it into `@abilities.wis.mod`
![image](https://github.com/foundryvtt/dnd5e/assets/9877634/e8b6b759-4371-4633-97c5-9806c23f8adb)
No luck yet... I made a bunch more tests, including *only* adding a single attribute in the attack bonus to check if making calculations was an issue in this specific scenario, but it was still refusing to work :(

I checked to see if the "summary" bulletpoints on the left were perhaps glitching (which would have given me a clue), but... the equation was actually calculating the bonus correctly!
![image](https://github.com/foundryvtt/dnd5e/assets/9877634/076f8d22-b64c-468d-8f4b-79fc49e9ed6c)
So my conclusion was, "If the computation on the item's card is correct, it means the equation is supposedly parsed as it should, so could it be a bug from one of the latest releases?"

I made one last test, which is to put the same equation onto a weapon, NOT onto a piece of ammunition. And it worked!

So if my testing is correct, interpolation equations do not work on attack rolls for ammunition exclusively - it still works on weapons though

EDIT: I forgot to mention, but of course the bug was replicated on a fresh table with no module, Foundry v11 Build 315 and DnD5 3.0.1

**Comment by Fyorl** [comment]
I guess we're not evaluating ammo bonuses against the weapon's `rollData`? I think we do add ammo bonuses to weapon attack and damage rolls so this seems like a bug.
