### ISSUE TITLE
[3.0.1] Gold Award Bug

### ISSUE THREAD

**Issue by Mushie1** [foundryvtt/dnd5e#2923]
If you manually type in XP and gold into the party award, only the XP gets split to the party, and only if the XP is added to the box above the "award" symbol.  
If the XP is written in the popup with the gold, then nothing gets sent to the players (refer image)
If you use the /award in a journal the gold and xp gets sent to the party and then that is distributed to the party correctly

(No modules, fresh world, v11.315, dnd5e 3.0.1, local hosting)
![image](https://github.com/foundryvtt/dnd5e/assets/77275833/580acd60-c148-4357-b1d9-7cc77d4b2e19)

**Comment by arbron** [comment]
This is actually a bug with XP awarded from containers: https://github.com/foundryvtt/dnd5e/issues/2924

**Comment by Mushie1** [comment]
I noticed that issue #2924 has been marked as completed, but you still cant add gold or XP directly to the popout box and have it split to the party, so I dont think this issue is related to that one.

**Comment by arbron** [comment]
The intention is always that awards from groups would be capped by the contents of the group. So the current behavior is considered working as intended.

**Comment by Mushie1** [comment]
I am still confused.  
If you click "Award group", the box pops up with fields that you can add currency and xp to.  If you type an amount in these fields, they are not split to the group.

If these fields are not intended to be edited, then shouldn't they be non selectable and just shown as info?

**Comment by krbz999** [comment]
> The intention is always that awards from groups would be capped by the contents of the group. So the current behavior is considered working as intended.

Then it should be capped in the dialog as well.

**Comment by Fyorl** [comment]
> Then it should be capped in the dialog as well.

It could be, but we don't cap the inputs in the currency transfer dialog either, which works the same way. So for now, the behaviour is consistent.

> If these fields are not intended to be edited, then shouldn't they be non selectable and just shown as info?

Less likely for XP, but for currency it's entirely possible you don't want to transfer all the currency, just some of it. That's why it's editable.

The group award feature remains for distributing awards existing in the group actor itself. For ad-hoc awards you can use the `/award` command.

**Comment by schultzcole** [comment]
I think it'd be valuable and certainly more discoverable to have a "Distribute From Group" checkbox in the award modal when awarding from a party. When the checkbox is enabled, the amount that gets distributed comes from the actor, while if it is unchecked, it is distributed ad hoc like the `/award` command.
