### ISSUE TITLE
Filigree SVG missing styling

### ISSUE THREAD

**Issue by nesbittj** [foundryvtt/dnd5e#2932]
Congratulation on V3, very exciting.

FiligreeBoxElement SVGs are missing some styling.

Firefox ESR, Debian, Foundry v11, NodeJs v20

![Screenshot 2024-02-06 at 08-01-48 Foundry Virtual Tabletop](https://github.com/foundryvtt/dnd5e/assets/5427558/703bb547-abec-4098-b54d-81f0d16d5041)

Fixed by converting to traditional CSS

https://github.com/foundryvtt/dnd5e/blob/3.0.x/module/applications/components/filigree-box.mjs#L76

```diff
diff --git a/module/applications/components/filigree-box.mjs b/module/applications/components/filigree-box.mjs
index 6c746d646..16349c3ce 100644
--- a/module/applications/components/filigree-box.mjs
+++ b/module/applications/components/filigree-box.mjs
@@ -72,17 +72,16 @@ export default class FiligreeBoxElement extends HTMLElement {
           position: absolute;
           fill: var(--filigree-border-color, var(--dnd5e-color-gold));
           z-index: -1;
-  
-          &.top, &.bottom { height: 30px; }
-          &.top { top: 0; }
-          &.bottom { bottom: 0; scale: 1 -1; }
-  
-          &.left, &.right { width: 25px; }
-          &.left { left: 0; }
-          &.right { right: 0; scale: -1 1; }
-  
-          &.bottom.right { scale: -1 -1; }
         }
+        .filigree.top, .filigree.bottom { height: 30px; }
+        .filigree.top { top: 0; }
+        .filigree.bottom { bottom: 0; scale: 1 -1; }
+
+        .filigree.left, .filigree.right { width: 25px; }
+        .filigree.left { left: 0; }
+        .filigree.right { right: 0; scale: -1 1; }
+
+        .filigree.bottom.right { scale: -1 -1; }
         .filigree.block {
           inline-size: calc(100% - 50px);
           inset-inline: 25px;
```

& nesting selector is still very new. It should be supported by most browsers, but apparently not mine :)

https://developer.mozilla.org/en-US/docs/Web/CSS/Nesting_selector#browser_compatibility
https://caniuse.com/css-nesting

Latest available version at time of writing Firefox ESR 115.7.0
https://www.mozilla.org/en-US/firefox/all/#product-desktop-esr
https://packages.debian.org/bookworm/firefox-esr

I'm sure this use case represent a very small cross section of the user base.
But the change is simple, and will improve cross browser support.

**Comment by Fyorl** [comment]
We also use the `:has` selector in several places, which requires at least Firefox 121. So even if this were resolved, I'm afraid you will face issues elsewhere.

**Comment by nesbittj** [comment]
Ah, very good point. I had worked around it locally and didn't realise that that was because of my strange browser too.
I'll end this fool's errand. closing.
Thank you for all the work.

**Comment by GraithTiger** [comment]
@nesbittj Not reopening, but a temporary workaround for Firefox ESR is to set both `layout.css.nesting.enabled` and `layout.css.has-selector.enabled` to true in about:config.
