### ISSUE TITLE
AE duration is not only changed on Round change on the AE on the Actor but also on the Spell Item

### ISSUE THREAD

**Issue by itteerde** [foundryvtt/dnd5e#2935]
3.0.1 see comments, because the 3.0 change to AE transferrals the SRD Bless (guess more?) Spell Item needs to be changed.

AE duration is not only changed on Round change on the AE on the Actor but also on the Spell Item

All modules deactivated, dropped Bless from SRD Compendium to be sure to not have corrupted data.

**Comment by etiquettestartshere** [comment]
As far as I can tell, this means that the timers for effects are useless once an effect expires once. I could find no way to reset the timer aside from getting a new copy of the spell. I believe in 2.4 that this could be accomplished by deleting the effect from the actor and dragging it back from the spell, but now it seems when I delete the bless effect from the actor, it is removed from the spell also. Would love to be proven wrong 😅.

**Comment by krbz999** [comment]
> but now it seems when I delete the bless effect from the actor, it is removed from the spell also. Would love to be proven wrong 😅.

If an effect is set to transfer, then in v3 you will see it on the actor despite it being on the item. Hence what you were deleting was likely the effect on the item.

**Comment by itteerde** [comment]
> If an effect is set to transfer, then in v3 you will see it on the actor despite it being on the item. Hence what you were deleting was likely the effect on the item. 

Yes. But that still leads to what he wrote. Currently as the duration on the Item goes down, not just on the AE on the Actor, one would have to drop a new Spell Item for every casting or reset the duration on the Spell Item.

**Comment by etiquettestartshere** [comment]
> If an effect is set to transfer, then in v3 you will see it on the actor despite it being on the item. Hence what you were deleting was likely the effect on the item.

Ah, okay, I can confirm checking Effect Suspended and unchecking Apply Effect to Actor works much better: I can apply the effect from the chat card, it ticks down, then I can delete it and reapply from the chat card. However this is only possible if I modify Bless. Maybe SRD items that should be applied in this way should have Apply Effect to Actor unticked by default.

**Comment by itteerde** [comment]
ah, true. So this is not a code bug, but compendium

**Comment by Fyorl** [comment]
We wanted to preserve the 'old way' of toggling spell effects, whereby if you cast the Shield spell, for example, you would toggle on the AE in your own effects tab. A caster could cast Bless on themselves, and might prefer to toggle it in this way, so we left Bless as `transfer: true`. It's possible that we need to move entirely to applying spell AEs via the chat card though. I think we need to create fresh effects if we want to appropriately track duration and expire them, and track things like concentration.

**Comment by schultzcole** [comment]
To clarify, if we go with @Fyorl's suggestion, we'd do this?

- Spell effects should not have `transfer: true` by default or in the SRD compendium (unless simply _having_ the spell gives some effect. Which would be weird, but supported I guess).
- When applying a spell effect from the chat card, we create a new effect on the actor, regardless of whether that actor owns the spell the effect came from (unless the actor already has an effect with the same origin).
- In #2881 we made it so that if you re-apply the effect from the chat card to an actor that already has the effect, it will disable the effect. Would it be better to completely remove the effect from the actor rather than just disabling it?

**Comment by Fyorl** [comment]
> Spell effects should not have `transfer: true` by default or in the SRD compendium (unless simply _having_ the spell gives some effect. Which would be weird, but supported I guess).

Yes. We also need to change the logic for what effects appear in the effects tray. There's a conditional branch that will sometimes show effects with `transfer: true`. We would not need that anymore.

> When applying a spell effect from the chat card, we create a new effect on the actor, regardless of whether that actor owns the spell the effect came from (unless the actor already has an effect with the same origin).
> 
> In [[#2770] Toggle effect on actor if it already exists #2881](https://github.com/foundryvtt/dnd5e/pull/2881) we made it so that if you re-apply the effect from the chat card to an actor that already has the effect, it will disable the effect. Would it be better to completely remove the effect from the actor rather than just disabling it?

I think if you try to apply an AE to an Actor that already has it, it should probably just do nothing. I don't think toggling something off/deleting it would be the expected outcome of an *apply* operation. There is some existing logic that would toggle it *on* if it finds an existing AE that is disabled. But assuming we do the first point, such AEs would not naturally exist anymore.

**Comment by schultzcole** [comment]
Yeah, sounds reasonable to me.

**Comment by thatlonelybugbear** [comment]
> I think if you try to apply an AE to an Actor that already has it, it should probably just do nothing. I don't think toggling something off/deleting it would be the expected outcome of an _apply_ operation. There is some existing logic that would toggle it _on_ if it finds an existing AE that is disabled. But assuming we do the first point, such AEs would not naturally exist anymore.


As a couple of messages before you mentioned something about properly tracking duration, in this context, applying on an Actor an already existing effect, it should at least "renew" it for expiration reasons.

**Comment by Fyorl** [comment]
> As a couple of messages before you mentioned something about properly tracking duration, in this context, applying on an Actor an already existing effect, it should at least "renew" it for expiration reasons.

Yeah that makes sense.

**Comment by schultzcole** [comment]
Should we/can we make any attempt in a migration to reset the duration on spell effects? Or just tell people to re-add the spell if the duration is messed up?

**Comment by Fyorl** [comment]
> Should we/can we make any attempt in a migration to reset the duration on spell effects? Or just tell people to re-add the spell if the duration is messed up?

We would want to avoid resetting the durations on AEs in an active combat. Maybe we can check for an existing `Combat` instance. I'm not sure how reliable that would be.

**Comment by itteerde** [comment]
One the Spell Item I'd think resetting would be correct even in combat. If it is transferred to Actor, the copy is different. That should not be reset. If resetting is worth it, a good heuristic being possible, but still a heuristic as there is no link to the compendium, extreme case would be a table using a Spell's version keeping the name but having changed the duration intentionally.
