### ISSUE TITLE
[Linux] Debian - NodeJS v18 or LTS or Latest - Latest FoundryVTT zip package -  Sheets glitches - No inventory items seen - Firefox issues

### ISSUE THREAD

**Issue by tdockx** [foundryvtt/dnd5e#2936]
Hi there,

Thanks for the wonderful work.
I am running foundryVTT on a debian 12 using the recommended node version and settings.

I have several glitches, mainly the inventory tab of actors (players) not being processed. Bag containers are ok, but individual items are not listed. (Although I see the weights being added correctly).

I tried the client version on Debian and I see no issues, I have made a complete from scratch reinstallation of the server (node.js) version, I have the problem on the sheets. 

Do you have any idea where that could come from?
I greatly appreciate your help.

With version 3.0.0 or version 3.0.1. No add-ons / extra modules.

**Comment by Fyorl** [comment]
What browser are you using? And what version is it?

**Comment by tdockx** [comment]
Hello @Fyorl,

I did not even think of it — thank you very much.

Using : Mozilla Firefox 115.7.0esr - it is glitching on the inventory

When using : Google Chrome (unstable) 123.0.6272.2-1 - it works perfectly.

Such a shame for Firefox not rendering it properly, though. 
Thanks for the help again.

Not sure if I close the issue or if that is something that could be fixed via "support for Firefox", I let you guys decide, I am happy with whatever path you choose.

Cheers.

**Comment by arbron** [comment]
> Not sure if I close the issue or if that is something that could be fixed via "support for Firefox", I let you guys decide, I am happy with whatever path you choose.

It is because of the version of Firefox you are running (don't worry, I use Firefox and was reviewing all the sheet design stuff from that browser). The new sheets use `:has` selector and nesting in CSS which were added fairly recently, so you'll need a newer version of Firefox.

**Comment by tdockx** [comment]
Thank you very much @arbron for your reply. 

I'll see for the incoming updates related to Firefox itself and I am closing this issue.

Keep up the amazing work 🙏
