### ISSUE TITLE
Feature Request: Display numeric value of weight of items in a container

### ISSUE THREAD

**Issue by flyingsquad** [foundryvtt/dnd5e#2937]
Containers do not display the numeric value of the weight of their contents, only the blue bar at the bottom of the window shows the relative fullness of the container.

It would be nice if the actual weight was displayed, similar to the way the weight is displayed for the character's encumbrance, just to the left of the containers in the inventory tab of the character sheet.

**Comment by Kharmans** [comment]
And in top of that, I think would be nice to have an option to not exceed the total weight of the container.
