### ISSUE TITLE
`Trait.getBaseitem` fails and prevents sheet rendering if compendium associated with item no longer exists

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2946]
As an example, add the slightly modified uuid of an item to `CONFIG.DND5E.shieldIds`, then disable whatever module contains the compendium with that item (but does not contain the code), then try to open the sheet of an Equipment-type item.

![image](https://github.com/foundryvtt/dnd5e/assets/50169243/72f46f94-7c61-4f48-a096-0d867d40de77)

**Comment by arbron** [comment]
Specifically this is an issue if the compendium where the item exists no longer exists.
