### ISSUE TITLE
The caption of an embedded journal entry page using the `@Embed` enricher can only be empty if it consists of nothing but white-space characters

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2951]
![image](https://github.com/foundryvtt/dnd5e/assets/50169243/a3d17a4d-2fca-419f-a143-7b62a4c3b207)

**Comment by Fyorl** [comment]
If you don't want a caption, use the `caption=false` option. See foundryvtt/foundryvtt#10262 for details on `@Embed` options.

**Comment by MaxPat931** [comment]
This is true of all enrichers as far as I can tell 
![image](https://github.com/foundryvtt/dnd5e/assets/86370342/ca0acc7a-208e-48ec-a7d9-89418e48352d)

**Comment by MaxPat931** [comment]
looks like using `&#8302;` or `&ZeroWidthSpace;` in the html editor can give you an empty caption without a space
![image](https://github.com/foundryvtt/dnd5e/assets/86370342/ff70755e-e414-46df-91c6-c55368c03a68)
