### ISSUE TITLE
New Character Sheets Not Loading Properly

### ISSUE THREAD

**Issue by GCSmith-07** [foundryvtt/dnd5e#2953]
I updated my campaign world, got this error with character sheets not displaying with the new character sheet style. Created a test world with no modules enabled and the sheets still look like this:
<img width="960" alt="image" src="https://github.com/foundryvtt/dnd5e/assets/100705086/8e7b05f8-3298-4896-90ad-bfa727b9d02f">

**Hosting Details**
Oracle Cloud VM 
- Ampere CPU 4 OCPU
- 4gbps Bandwidth
- 18GB RAM
- Linux: Canonical Ubuntu 22.04

**Comment by unsoluble** [comment]
Do a Control-F5 to clear your browser cache.

**Comment by GCSmith-07** [comment]
That fixed it. Thanks
