### ISSUE TITLE
Allow for pushing objects, not just strings, in the `parts` option of `Item5e#rollDamage`

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2958]
Currently it means associating a part with a damage type means having `parts: ["1d8[lightning]"]`, while it would be nicer and more flexible to be able to push `parts: [{parts: "1d8", type: "lightning"}]`.

**Comment by arbron** [comment]
What we need to do is add the ability to pass `options.rollConfigs` into `rollDamage`, and have that be combined with the existing configs present similar to how we used to do that with parts.
