### ISSUE TITLE
Middle Click to edit Item from sheet

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/dnd5e#2964]
Add the ability to middle click on an any item on the character sheet to edit it.
Anything to save one click :)

**Comment by Fyorl** [comment]
Middle-click is reserved for locking tooltips, which are likely to appear if you are hovering over an item in the first place.

**Comment by MaxPat931** [comment]
Ahh right, forgot that will work when you middle click the item, not just when middle clicking the tooltip like it is now
