### ISSUE TITLE
Option for old Expanding Descriptions in place of Tooltips

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/dnd5e#2967]
While the tooltips are real nice, they are kind of hard to read / manage a bit. Would it be at all possible to maybe add some functionality back to the expanding item descriptions to the character sheets?

**Comment by Fyorl** [comment]
We cannot possibly accommodate every user's individual UI preferences in the sheet. Its implementation would become unmanageable. Modules and alternative sheet implementations exist for this purpose.

**Comment by Fyorl** [comment]
We'll be adding these to the NPC sheet since tooltips are not an ideal UX for DMs to have all the information they need displayed at a glance. And since the design work is being done already for the NPC sheet, these might as well be shared with the character sheet also.
