### ISSUE TITLE
Properly handle more than 8 abilities on the PC sheet

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#2969]
Currently the layout of abilities gets really weird if more than eight are added. While not common, it is something we support so we should make some effort to rendering them properly.

<img width="528" alt="Screenshot 2024-02-08 at 09 52 00" src="https://github.com/foundryvtt/dnd5e/assets/19979839/67a0cda2-ebd9-40db-8336-21cf32e1ee31">

**Comment by Fyorl** [comment]
I disagree. We support configuring lots of things via the API in order to not block homebrew, but we cannot be expected to accommodate every permutation of every possibility in our sheet designs. 8 ability scores in more than enough in my opinion.
