### ISSUE TITLE
Token ring flashing too quickly in succession makes the flashed color permanent

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#2975]
```js
token.document.flashRing({dhp: -50})
await new Promise(r => setTimeout(r, 150));
token.document.flashRing({dhp: -50})
```

**Comment by krbz999** [comment]
For the artists out there, healing + damage = yellow.

**Comment by arbron** [comment]
I suspect this is because the `flashColor` method grabs the starting color from the token ring's data, rather than from the flag, resulting in it having the wrong value to return to if it is called while another flash is already in progress.
