### ISSUE TITLE
It is not currently possible to add a detection mode to a Prototype Token using the UI

### ISSUE THREAD

**Issue by mattexdee** [foundryvtt/dnd5e#2980]
In 3.0.1 (I haven't tested in 3.0.0) it's not possible to add a detection mode to a prototype token in the UI but it is still possible to do in the code. This did work in 2.4.1 at least.

There are no console errors or warnings.

**Comment by unsoluble** [comment]
(Dupe of #2963)

**Comment by mattexdee** [comment]
D'oh. Closing as duplicate.
