### ISSUE TITLE
Use a different icon to indicate a spell is 'always prepared'

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/dnd5e#2992]
The new sheets currently show no indication of this, which is an issue as it looks like the preparation state can be toggled off when it can't. Previously it used to show as red, but we should use a different icon entirely for accessibility.

**Comment by schultzcole** [comment]
Yeah, I think different icons for "always prepared", "prepared", and "not prepared" would be best for accessibility. Maybe also an icon for "known/inherent"?

**Comment by etiquettestartshere** [comment]
I'll throw in my own personal little wish to this one: make the attunement icon different from any of the above.
