### ISSUE TITLE
Render Darkvision as Greyscale

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#30]
https://discordapp.com/channels/170995199584108546/517504137403826177/517513141551366165

Have a “toggle grayscale” for the player vision, so it can better represent Darkvision (D&D). Ideally, though, players with Darkvision enabled would have a separate vision circle for dim and dark parts of the map.

**Comment by kjolern** [comment]
Could this be closed due to the release of version 10 ? https://foundryvtt.com/releases/10.283.
@arbron @aaclayton

**Comment by aaclayton** [comment]
I think we can close this in favor of the issue #1166 that was opened.
