### ISSUE TITLE
Activating core context menu after system context menu causes it to not render

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#3000]
Clicking multiple system context menus in a row works properly, and the same with clicking multiple core context menus in a row, but if a core context menu is invoke when a system context menu is still open nothing renders until you completely dismiss any context menus.

**Comment by arbron** [comment]
This is caused by `ContextMenu5e` setting absolute positioning directly on the container element, which the context menu system reuses when opening subsequent menus. Since core's` ContextMenu` doesn't do anything to clear those, they remain when it recalculates its position.

**Comment by arbron** [comment]
Not sure there is a way to fix this cleanly at the moment. The best way to handle it would be to remove those extra styles during the close event, but `onClose` is never called when a context menu closes because another opens.

**Comment by Fyorl** [comment]
I don't know if using a `MutationObserver` would count as solving it 'cleanly'. Otherwise maybe we just chalk this one up to 'works better in v12', like locked tooltips?

**Comment by arbron** [comment]
> I don't know if using a `MutationObserver` would count as solving it 'cleanly'. Otherwise maybe we just chalk this one up to 'works better in v12', like locked tooltips?

Its a bit of an edge case, so I'm not sure how important it is to go above and beyond to solve it immediately. I've filed a core issue about the `onClose` callback regardless: https://github.com/foundryvtt/foundryvtt/issues/10555
