### ISSUE TITLE
Token vison discovers Fog of War for all Tokens at once

### ISSUE THREAD

**Issue by ehlord** [foundryvtt/dnd5e#3003]
Hey there,

If I enable Vision on multiple Tokens and one of them unveils Fog of War, it is unveiled for all of the Tokens, even if they are behind walls and technically cant see the area at all.

Is there a way to turn this off or fix it?

**Comment by unsoluble** [comment]
This is a core Foundry behaviour, not specific to dnd5e, and is working as intended — fog state is stored _per user_, not per token.
