### ISSUE TITLE
Details lost in update/migration

### ISSUE THREAD

**Issue by Liviu50** [foundryvtt/dnd5e#3008]
So while i made the update and then migrated the campaign i had...i just found out that the background for many characters and npc that i put in biography so i could easily check it got deleted completely, and not only from character sheets but even NPC which in theory does not get any sort of modification got all info lost.
Any idea why or how to fix that?
Since i cannot log into the campaign with an older version, which i would be happy to know a method, to copy paste all the info before switching i will lose a LOT of backstory made for many npc and characters...
any solution or future update to prevent this while migrating?

**Comment by arbron** [comment]
Before you upgraded, were you using the standard DnD5e sheets or a variant (Tidy Sheet, etc)?

Was the information lost entered in the standard biography field or something else?

Did you make a backup using Foundry's built-in backup feature before upgrading?

**Comment by Liviu50** [comment]
So i made a backup of the campaign since it is automatic (well it asks you) every time you start a campaign with a different version. so i do have a  copy from before but i dunno how that will help...unless i install an older version or something.
As far as sheets, i had some npc using the standard one, some using tidy 5e and most char sheets were tidy 5e...but not all.
yet all of them (npc included) had their biography deleted as soon as the new version took over...and yes i used the standard biography, no extra mods or special fields.
Hope this helps.

**Comment by arbron** [comment]
You can install an older version of the system to launch your backup.

We didn't do anything with character biographies in this release that might result in them being deleted, and I haven't heard that from anyone else. You might just want to try reverting to your backup and then upgrading again to 3.0 to see if the same thing happens.

**Comment by Liviu50** [comment]
well i would agree with you if the thing would happen only with the tidy5e sheets but also normals ones got same issue.
Sadly i can't reinstall right now things as a lower version to test that, feel free to close the ticket if you think its pointless, its just an issue i encountered and thought to share :).
thanks for your time and answers in the meanwhile!
