### ISSUE TITLE
Level Up - Spell Choice missing

### ISSUE THREAD

**Issue by HariboHUN** [foundryvtt/dnd5e#3009]
Hi!

I did not see that anyone else mentioned this. After the 3.0.1 update when a caster levels up, there is no pop up to learn new spells. It needs to be imported separately. 
This is only for those casters that learns X spells/lvl up. Clerics or Druids are okay, they get the pop up to populate the spellbook.

**Comment by arbron** [comment]
This is a feature from a module, not the system.
