### ISSUE TITLE
[BUG] Identifying no-magical items shouldn't be required

### ISSUE THREAD

**Issue by ZeroXNoxus** [foundryvtt/dnd5e#3013]
Identifying items should only be required when the item is considered magical. I was confused while editing a common item (a handaxe) and only seeing "Unidentified Name" in the editing window. I feel like this identifying concealment should only occur when the item is magical. In addition, a person with the "Game Master" role should be excluded from this hidden details, as well.
![image](https://github.com/foundryvtt/dnd5e/assets/29397572/83e9978d-0584-46ef-b884-eb12f07372f7)

**Comment by Fyorl** [comment]
Items are identified by default, so it's not clear why you're seeing this handaxe marked as unidentified. Did it come from the SRD compendium?

**Comment by ZeroXNoxus** [comment]
I have identified the problem; my item was from 2.1.4 and seems to have caused this issue.

**Comment by Fyorl** [comment]
> I have identified the problem; my item was from 2.1.4 and seems to have caused this issue.

Thanks for following-up
