### ISSUE TITLE
Provide an actor method `rollConcentration`, with associated `dnd5e.preRollConcentration` and `dnd5e.rollConcentration` hooks

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3033]
Related to #3028.

**Comment by kaelad02** [comment]
Please make sure the `dnd5e.preRollConcentration` hook is called before the roll dialog is shown. This wasn't done with initiative and... well made things difficult for modules to really change things.

**Comment by krbz999** [comment]
> Please make sure the `dnd5e.preRollConcentration` hook is called before the roll dialog is shown. This wasn't done with initiative and... well made things difficult for modules to really change things.

I swear it on my life.
