### ISSUE TITLE
Provide damage and healing hooks for when an actor is updated

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3035]
Related to #3028.

The hooks that currently best serve to track when and if an actor receives damage (provided by the system) are found in the `applyDamage` method. However this does not account for the times a user may simply apply damage (or healing) directly through the character sheet, or via a direct update.

It would be good to track the differences in current hit points and call an appropriate hook, which may likely be required regardless to determine the DC of a saving throw to maintain concentration.

**Comment by theripper93** [comment]
Seconding this - i have an homebrew automation module which applies grave injuries based on the damage taken and the damage type - having this information in the hook will be very helpful as well

**Comment by Fyorl** [comment]
Is this not already covered by the generic `preUpdateActor` and `updateActor` hooks?

**Comment by krbz999** [comment]
It is, yes.

The request is for the system to leverage those two methods and `call` its own hook, rather than many modules doing the same work, instead being able to latch onto a single hook provided by the system.
