### ISSUE TITLE
When using an item that requires concentration, supply appropriate context in the `AbilityUseDialog` for if, when, and why its use would end or replace concentration

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3037]
Related to #3028.

Circumstances in which an item may affect concentration include:
- It requires concentration, but you are not concentrating; using the item *will initiate* concentration.
- It requires concentration, but you are concentrating on a different item; using the item *will replace* concentration.
- It requires concentration, but you are concentrating on the same item at a different level; the user should be warned that concentration will end *unless* they cast the spell at the same level.

**Comment by Fyorl** [comment]
> It requires concentration, but you are concentrating on the same item at a different level; the user should be warned that concentration will end _unless_ they cast the spell at the same level.

Could you clarify this? It's not a rule I'm aware of.

**Comment by krbz999** [comment]
> > It requires concentration, but you are concentrating on the same item at a different level; the user should be warned that concentration will end _unless_ they cast the spell at the same level.
> 
> Could you clarify this? It's not a rule I'm aware of.

Any concentration spell being cast would end previous concentration. When the second item is the same item, it may be worthwhile considering not breaking concentration if it gets cast at the same level.

So to clarify, this is not a rule, but a convenience feature. In case a user may want to simply re-display the item, let's say they forgot to pop out the message for example.

**Comment by krbz999** [comment]
Agreed
