### ISSUE TITLE
Provide various methods to manually prompt for saving throws to maintain concentration

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3039]
Related to #3028.

According to official rules, a GM can request a saving throw to maintain concentration for reasons other than a character taking damage, such as being tossed around on a ship at sea, etc.

Some nice-to-haves:

- [x] The character sheet should display a button to roll concentration without being prompted.
- [x] A way to request with an inline roll or chat command (with a DC).
- [x] Relevant API methods.
- [x] Enrichers.

**Comment by Fyorl** [comment]
Some of these are done, the rest will have to wait for 3.1.1 or 3.2
