### ISSUE TITLE
Reenable Classes on NPC Sheets for 3.0.0+

### ISSUE THREAD

**Issue by TlMcook** [foundryvtt/dnd5e#3041]
The 3.0.0 update disabled the ability for npc sheets to gain player classes, however sidekick classes (from Tasha's) are placed onto npc's.

**Comment by krbz999** [comment]
This sounds like a module rather than something the system is doing. Non-character type actors have never been allowed to hold `class` items.

**Comment by JPMeehan** [comment]
This _does_ raise the question of what the correct process for the (Official!) sidekick classes should be, given that they're supposed to be layered on top of NPC stat blocks.

**Comment by Fyorl** [comment]
Closing this as not planned because classes were never allowed on NPCs, so this must have been some module behaviour. Sidekick implementations can be its own issue, and may very well involve adding `class` items to NPCs.

**Comment by revilowaldow** [comment]
https://github.com/foundryvtt/dnd5e/issues/3149 ...
