### ISSUE TITLE
[feature request] Have generic UI support for new spellslot and resource types

### ISSUE THREAD

**Issue by rapus95** [foundryvtt/dnd5e#3053]
This approach wants to be powerful enough that a non-scripting user could reimplement the current spell slot variants (leveled and pact magic) within that generic system. So he can make his own MagicSlots. This post was entirely rewritten to make it easier to grasp the idea.

# Generic Idea: item-subtype "resource" #
I imagine a solution that is centered around a new item subtype for resources (as there are subtypes for weapons, features, classes, races, spells etc) which is basically "resource name + charges + advancement + consumption strategy + point-level-value".

- Resource name: The name of the resource (for example Ki)
- charges: the amount one currently has
- advancement: how the amount changes over multiple class levels
- consumption strategy: whether you can consume multiple charges at once
- point-level-value: how much "level" n charges provide (5th level slot -> 5, Ki -> n, Wand -> baselevel+n)

Then, use that point-level-value in the scaling formula of spells and features/abilities.

Also, add a default spellcasting resource field (similar to the default spellcasting stat)

Going that way there won't be any difference between built-in spell slot types and custom spell slot/resource types. aka first level support for custom resources. 

# Upcasting: "On cast, pick any resource from that pool of resource items" #
Thinking about the upcasting-mechanic for spell slots, we'd recreate that option in two steps.
1) We create resource groups. These are logical groups listing all applicable resource items (by reference, not as a container). For usage, put that resource group (or a list of them) into the "item uses"-field of the spell or feature. And on spell casting/feature activation, show all resources that belong to that group (or any of the given groups) on the resource consumption drop down. Technically, there'll be no "up(casting)" anymore (since there are no relations between different resource items aside of eventually being grouped together) and you just "pick any of these resources to cast from".
2) The effect of upcasting will be recreated by multiplying the point-level-value of the selected resource with the number of charges you wanted to consume and using the result in the scaling formula.

This separation also allows for easy and arbitrary combination of item charge casting, spell slot casting and resource casting for each individual spell/feature. Like being able to cast from 5 Ki points exactly the same as from one 5th level slot or a single wand charge.

# UI generalization: Have tabs selectively show items that consume certain resources #
One could filter abilities+features+spells by their configured resource consumption. So the Spells tab could just be a tab that's configured to show anything that consumes a resource that belongs to the selected spellcasting resource.

# Examples: Current Slot Systems Recreated #
### Leveled Slots: Resource Group Usage ###
Leveled Spell Slots would become a Resource group consisting of 10 Resource items. Cantrip-level, first level, 2nd level and so on each with the caster level dependent amount of max uses which recharge at long rest. (That can already be built with the current item system).
The spellcasting resource would be set to the resource group and thus the spells/abilities tab would show anything that consumes resources from that resource group.

### Pact Magic: Resource Item Usage ###
A warlock would instead have a single pact magic resource item. Having its own on-short-rest recharge and level based advancement.
The spellcasting resource would be set to the pact magic item and thus the spells/abilities tab would be configured to show anything that consumes uses from the pact magic resource item.

### Monk's Ki: "Til now"-Resource Item Approach ###
A monk would get a resource item for Ki, that's exactly how it is right now.
The spellcasting resource would be set to the ki resource item and thus the spells/abilities tab would be configured to show anything that consumes uses from the Ki resource item.

### Mixed Resources: Adaptability ###
An elemental monk which gets spell slots from somewhere could additionally get the spell slot resource group.
Then we would create a new resource group consisting of the spellslot group and the ki resource item.
The spellcasting resource would be set to that newly created group and thus all spells/abilities that consume either of those resources would show up on the spells/abilities tab, ready to consume either resource.

**Comment by krbz999** [comment]
Gotta say this idea is pretty difficult to follow, but what I am gathering is...

- resources, and what an item (or just spells) can consume as a resource is not extensive enough.
- it is not possible to extend the spellcasting system. (That isn't true, you can define your own spellcasting progressions.)
- spellcasting (particularly upcasting) should be rewritten from the ground up.

What exactly would this solve?

**Comment by Zanderaf** [comment]
I feel like Im having a hard time understanding too-

The everything's an item part I dont exactly understand at all. I don't see why spell slots would need to be rewritten to become items unless this is a train of thought with the old "Resources" system that the character sheet had that was bounced in favor of any item being able to be well, a "resource".

Maybe for scaling stuff like a Paladin's divine smite? Bladesinger's 5 x spell slot level damage reduction? Theres going to / already are ways to do that IIRC

**Comment by rapus95** [comment]
@krbz999 @Zanderaf I've rewritten and structured the post, hopefully making it easier to grasp the idea.

**Comment by Zanderaf** [comment]
Once again, this feels like something that Spell Point implementation + a world script can manage- along with the work being done to handle something like Radiant Monk's Burning Hand & Paladin Smite consumption.

**Comment by Fyorl** [comment]
I think the design makes sense, but it's too large of an overhaul to the underlying systems without more tangible benefits and clear use-cases outside of re-implementing systems that already work.
