### ISSUE TITLE
Polymorph/WIldshape/Appearance Only function not working correctly

### ISSUE THREAD

**Issue by darthlunga** [foundryvtt/dnd5e#3055]
I am testing the new DnD5E locally. **Foundry v11 Build 315, DnD5E 3.0.2, no modules running**. 

Polymorph/Wildshape/Appearance Only not working correctly. It does transform the actor's sheet and token size but does not change the token image in the scene. I have tried it without Dynamic Token Ring enabled, issue persists. Clip attached for reference.

https://github.com/foundryvtt/dnd5e/assets/87379787/4c3d5afc-9ec5-4f00-841b-1b12ab7161b8

**Comment by arbron** [comment]
As best I can tell this is because the token ring subject artwork isn't being swapped when the swap occurs.
