### ISSUE TITLE
Roll command errors when using multiplication or division

### ISSUE THREAD

**Issue by wkurzius** [foundryvtt/dnd5e#3065]
Using a `/roll` command involving multiplication or division results in an error. For example, `/roll 1d6 * 5` yields

```
Uncaught (in promise) Error: Roll.safeEval produced a non-numeric result from expression " * 5"
    safeEval foundry.js:10437
    simplifyRollFormula simplify-roll-formula.mjs:42
    _enrichRollTooltip chat-message.mjs:251
    _enrichChatCard chat-message.mjs:233
    _enrichChatCard chat-message.mjs:232
    getHTML chat-message.mjs:58
```

Made sure to test in a fresh world with no modules enabled. Also tested in a fresh world with pf2 system, but got no errors. Putting parentheses around the roll avoids the issue.

**Comment by Hoppyhob** [comment]
I can work on this.
