### ISSUE TITLE
[Feature Request] Auto reduce damage for Heavy Armor Master

### ISSUE THREAD

**Issue by sapost** [foundryvtt/dnd5e#3085]
When applying damage to tokens, the 5e system automatically takes into account any damage immunities or resistances. However, it does not account for the -3 damage reduction for bludgeoning/piercing/slashing from the [Heavy Armor Master](https://www.dndbeyond.com/sources/phb/customization-options#HeavyArmorMaster) feat. Heavy Armor Master is a relatively unusual situation for DR, but for characters that have that feat, the damage reduction comes up _a lot_.

This request seeks to add a special calculation where:

- If a token (usually a player character) has the Heavy Armor Master feat
- And the source of damage is a weapon attack that deals bludgeoning, piercing, or slashing damage
- And that damage is applied to that token
- Then the damage applied is reduced by 3

The alternative is that players must manually edit their health by 3 each time they receive qualifying damage. It's a functional workaround, but extremely tedious.

**Comment by Fyorl** [comment]
Covered by damage modification.
