### ISSUE TITLE
'Stealth disadvantage' shows as a tag on equipment if ticked and unavailable

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3098]
- make equipment item on an actor.
- make it armor / shield.
- tick 'Stealth Disadvantage'.
- see tooltip in inventory has tag for Stealth Disadvantage.
- make it clothing.
- notice that Stealth Disadv is no longer a valid option (should it be?).
- see tooltip still has tag for Stealth Disadvantage regardless.

Would simplify things if this was just a property for any 'equipment' regardless of being armor or shield. It's easy to imagine a trinket or clothing that grants disadvantage on stealth.

**Comment by Hoppyhob** [comment]
I can work on this.
