### ISSUE TITLE
[Feature Request] Container Sheets with similar design to Player Inventory and option to make party containers

### ISSUE THREAD

**Issue by SirAron111** [foundryvtt/dnd5e#3100]
Is it possible to make the Container Sheets have a similar design as the Player Inventory and add a search and sorting options. It would make it so much more friendly to manage and visually more appealing.

Also, an option to make party containers would be great. For example, if the party has a Carriage or a Bag of Holding that everyone frequently access, being able to make lets say a proxy character sheet accessible by everyone via a linked container item in their inventory like the backpack manager module once did would be great.

**Comment by arbron** [comment]
Eventually all sheets will be getting a redesign that includes the improved inventory sorting, grouping, and filtering system.

There is already group actors that can store items to act as a party container, or vehicle actors if they are storing their items in vehicles.

**Comment by AustinTiger** [comment]
I second @SirAron111's request.

The group actor is a great start.  It would be nice to be able to add custom categories for improved organization.  One of the uses would be able to have PCs names as separate categories.  The usage model is to maintain a full list of party inventory and see what's available and which PC has different items.  My party uses D&D Beyond and currently have to maintain a spreadsheet to track who has what.  Integrating into Foundry Vtt would provide a lot of value.

A huge first step would be to integrate the Category capability that the module Inventory+ provided but is no longer maintained nor work with 3.0.

A further enhancement would be to have a Container that multiple Actor's sheets could link to and show as a Container in their Actor sheet.  This would avoid the need for a user to stay within their PC's sheet and not have to go find the group actor to open.

Thanks for all the great work and listening to this request.
