### ISSUE TITLE
[FEATURE] Allow locking item tooltips cards with right-click

### ISSUE THREAD

**Issue by lipehique** [foundryvtt/dnd5e#3112]
Right now, core behavior allows to somehow lock an item tooltip into place by pressing middle mouse button on the icon of the item. Clicking on the name or in the tooltip itself can work, but often does not.

There are plans to expand locking to allow for key rebinding, but it is not very intuitive for a function as basic as reading item descriptions to require knowledge about additional keyboard shortcuts (which, for some items, will be absolutely required).

With how the system already differentiates between pressing the icon or the item's name, there is the possibility of using one of them as trigger to the locking behavior. Pressing the icon (or the name) would lock the tooltip into place, and pressing the name (or the icon) would output the item to chat.

![image](https://github.com/foundryvtt/dnd5e/assets/159858551/2b511efd-37f4-47ed-844f-6ac955370dac)

Default behavior could be the tooltip is locked until you press the icon (or the name) again, even if you drag the mouse far away.

It then mimicks old sheet behavior, while keeping the modernized tooltips.

While at that, clicking the icon (or the name) to lock the tooltip could skip tooltip intro animation. Right now, there is a noticeable 1 second (at minimum) delay between hovering an item and the tooltip appearing, which does not happen when tooltip appears after hovering another item. This delay is noticeable on actual play. If the delay is intended, then clicking should skip it.

**Comment by Fyorl** [comment]
Tooltip locking is a core API feature. It works the same across all tooltips, anywhere. There are issues with this feature's discoverability, certainly, which could be improved either in the system or in the core software. Regardless, once a user knows how to lock tooltips, it always works the same way in every context. I'm not convinced that adding a specialised tooltip locking mechanism that only works in one place (the inventory) would be an improvement.

There are some issues with the core tooltip locking behaviour that mean that this feature is not working as smoothly as intended. I think it's worth re-evaluating feedback on tooltip locking once those issues are addressed.

**Comment by Fyorl** [comment]
We've since moved to v12 which fixes any lingering issues with tooltip behaviour, made the locking feature more discoverable, and we have added the ability to expand items in-row. Any additional requests for improvements should be re-raised in the context of the current state of tooltip behaviour.
