### ISSUE TITLE
TokenConfig5e#_prepareResourceLabels doesn't play well with module subtypes

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/dnd5e#3128]
My module K&W Actors, which uses module subtypes to add warfare units to D&D 5e, is disrupted by the way that the system overrides the display of the token bars. I can't even reliably use the native render hook to fix things, as that is called during _render and TokenConfig5e adds significant asynchronous code to _after_ those hook calls - it's a pure race condition and I'm probably going to lose it.

Reference issue: https://github.com/JPMeehan/knw-actors/issues/18

**Comment by Fyorl** [comment]
Is it possible that some/all of these issues might be addressed by #3115? Or is it completely unrelated?

**Comment by Fyorl** [comment]
The PR in question was merged in 3.1 so marking this as resolved.
