### ISSUE TITLE
Some Spells needs more complicated Scaling formula

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#313]
Originally in GitLab by @ariakas81

Spells like Spiritual Weapon, Flame Blade scale by 1dX for every two slot levels above their basic level.
Right now they can't scale properly with the available choices.![image](https://gitlab.com/foundrynet/dnd5e/uploads/d5e956881a38b6b1558a4ebaf11651a1/Cattura.JPG)

**Comment by Fyorl** [comment]
A lot of these use cases are handled by per-damage-part scaling, as well as the improved scaling functionality available in activities, so I am marking this as done for now to allow for more targeted issues to be raised for any remaining use cases.
