### ISSUE TITLE
The visual indicator for a die that has 'exploded' sometimes gets misplaced in the chat message

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3130]
Repro steps:

Notice that the explosion indicator is missing from some of the dice and placed at the item's name.

![image](https://github.com/foundryvtt/dnd5e/assets/50169243/568e2c50-8d86-4fa3-80f9-41048be1b0db)

**Comment by Hoppyhob** [comment]
I can work on this.
