### ISSUE TITLE
[Feature Request] Magical Weapon Property as AE Flag

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/dnd5e#3143]
At the moment when you cast a spell like Magic Weapon you have to manually make the weapon magical, it would be nice if you can set it as a flag that whatever weapon you use is considered magical for the sake of overcoming resistances.
I know the spell only effects one specific weapon, but with such a flag you can at least make the +1 and magic property as a toggleable effect for ease of use.

**Comment by arbron** [comment]
Just to be clear, you are suggesting a flag on the actor that would make all weapons they wield magical with an additional +1 to attacks and damage?

**Comment by maxobremer** [comment]
Correct. Reason being I don't see an easy way to activate such a thing on a per weapon basis with an active effect and this seems to be the easiest way. 
In addition if you have the buff on a weapon, it's reasonable to assume you will use that weapon for most of that combat encounter anyway.

**Comment by Fyorl** [comment]
This might be better handled by the Enchantments proposal #3305
