### ISSUE TITLE
Add magical bonus to weapons & armor

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#3147]
Currently turning a weapon into a `+1` version involves adding `1` to the "Attack Bonus" field and ` + 1` to the first damage part. This doesn't give any indication that the value in those fields is from the magical part of the weapon and not something else. This comes into play for weapons that require attunement, which shouldn't confer the magical bonus unless they are actually attuned. It is also an issue if we ever implement something like an anti-magic field, which should prevent the magical bonuses from being used.

A new "Magical Bonus" field on the weapon, possible only displayed when the "Magical" property is checked, should allow us to add these bonuses to attack and damage automatically as long as the proper conditions are met.

**Comment by thatlonelybugbear** [comment]
The attunement part for the Magic bonus to attack/damage is not a prerequisite in some cases. There are some weapons that are magical and confer their base bonuses to attack/damage to the wielder while not attuned and other abilities when attuned.
Hammer of Thunderbolts is one such example

**Comment by krbz999** [comment]
> The attunement part for the Magic bonus to attack/damage is not a prerequisite in some cases. There are some weapons that are magical and confer their base bonuses to attack/damage to the wielder while not attuned and other abilities when attuned. Hammer of Thunderbolts is one such example

"Hazirawn" is another special case. The attack bonus is +1, but +2 if attuned, and the damage bonus is +1d6 or +2d6 if attuned.

**Comment by arbron** [comment]
> The attunement part for the Magic bonus to attack/damage is not a prerequisite in some cases. There are some weapons that are magical and confer their base bonuses to attack/damage to the wielder while not attuned and other abilities when attuned. Hammer of Thunderbolts is one such example

The general rule is that for any item that requires attunement must be attuned in order to get any of its magical effects, that includes the +1 to attack and damage. So for the Hammer of Thunderbolts, you wouldn't get the +1 to attack or damage if you aren't attuned.

> "Hazirawn" is another special case. The attack bonus is +1, but +2 if attuned, and the damage bonus is +1d6 or +2d6 if attuned.

That is a special case. In that instance I imagine it would be implemented with a static +1 in the attack bonus & first damage field like we use currently, and a +1 in the new magical bonus field.

For the extra necrotic damage, I think that will have to wait until the activities system which will have more control over what damage parts are added under certain conditions.
