### ISSUE TITLE
Link directly to the wiki from the package page

### ISSUE THREAD

**Issue by etiquettestartshere** [foundryvtt/dnd5e#3151]
Many users may not think to check the Project Url for further documentation, or even know that github can have wikis (or even know what github is). Currently (as far as I can see), the package page links to CONTRIBUTING.md, but does not link to the [wiki](https://github.com/foundryvtt/dnd5e/wiki), which contains tons of information that new users will want to know.

**Comment by Fyorl** [comment]
The wiki is linked in the sidebar:

![image](https://github.com/foundryvtt/dnd5e/assets/207433/fdaad94f-cd20-4373-aa11-b02e6eb4918c)

There's no reason it couldn't be linked on the package page though.
