### ISSUE TITLE
Option to show the attack result (AC check) to players

### ISSUE THREAD

**Issue by pbasov** [foundryvtt/dnd5e#3156]
Right now only DM can see the AC check card that is automatically created after the attack hits or doesn't.
![image](https://github.com/foundryvtt/dnd5e/assets/5103674/6fb7b360-7ce5-49b5-8b1e-0577bfb54902)

For DMs that play "in the open" (and my players instantly remember the AC after the first hit lands anyway) it would be nice to have an option to display this card to players as well.
That would considerably speed up the combat, since players won't have to wait for the DM to say "it hits" to make a damage roll.

**Comment by ItsDrafty** [comment]
Additionally, it might be nice if it would show that it hits for the player, but maybe not the exact AC of the creature. It still keeps some element of mystery but speeds up play.
