### ISSUE TITLE
Damage calculation like dividing and multiplying is not working correctly

### ISSUE THREAD

**Issue by RcwynnDM** [foundryvtt/dnd5e#3158]
In my game I have percentage based damage sometimes for players.  At the moment when damage is calculated it will have the results being correct, but the damage calculated where you would normally see the dice roll done would just be the number being added.

![Screenshot 2024-02-29 104217](https://github.com/foundryvtt/dnd5e/assets/157905306/c222f44e-1e3b-444c-8e22-c14ab55e4712)
![Screenshot 2024-02-29 104252](https://github.com/foundryvtt/dnd5e/assets/157905306/d050236f-df3f-4f63-bb90-20d0382569f5)

**Comment by tposney** [comment]
Until fixed you can put the expression
```5 * 2.5``` inside parenthesis ```(5 * 2.5)``` and it will work, the display won't be great but it will be correct

**Comment by Fyorl** [comment]
I understand this was resolved by #3271 but please re-open if not.
