### ISSUE TITLE
[3.0.3 Bug] Numbered Journal headings 

### ISSUE THREAD

**Issue by Mushie1** [foundryvtt/dnd5e#3161]
If you create journal headings with just a number (not really a common thing a user would do)
It makes all the headings change position in the chapter list, and number 1 disappear.
For example, if you create a monster list and have them sorted by CR.
This is a fresh world with no modules, locally hosted. 
v11.315, DnD5e 3.0.3

![image](https://github.com/foundryvtt/dnd5e/assets/77275833/654206eb-626d-42de-bdc1-203028ea4662)

**Comment by arbron** [comment]
Looks like a core bug, you should file it over the core tracker rather than here: https://github.com/foundryvtt/foundryvtt/issues
