### ISSUE TITLE
/save Enrichers don't accept variables

### ISSUE THREAD

**Issue by LadyDefile** [foundryvtt/dnd5e#3162]
So, the new enrichers work awesome. Love being able to do something like `[[/save wis 15]]`. The problem I've got is that I can't use variables for it. For example, if the saving throw is based on `@attributes.spelldc` you have to write `[[/save wis]] of [[@attributes.spelldc]]`.
I tried using `[[/save wis @attributes.spelldc]]` and `[[/save wis (@attributes.spelldc)]]` but neither worked. I think it would be great if it would work with that.

**Comment by arbron** [comment]
You have to use dc=@attributes.spelldc

**Comment by LadyDefile** [comment]
In that case, ignore me. I didn't notice that in documentation anywhere but good to know it exists already!
