### ISSUE TITLE
Spell damage should always include the magical property for overcoming resistances

### ISSUE THREAD

**Issue by asherett** [foundryvtt/dnd5e#3163]
**Description**
When the damage resistance feature is enabled through a module (e.g. Ready Set Roll) Piercing/Slashing/Bludgeoning damage done by spells is halved by resistance to non-magical physical attacks.

**Steps to Reproduce**
This bug is currently only reproducible with a module that utilizes the damage resistance calculations in dnd5e 3.0.3, e.g. Ready Set Roll for 5e; but it _is_ a bug with the current (3.0.3) ddn5e system and not with the module.

Create or load in an NPC with resistance to physical attacks, countered by "magical":
![image](https://github.com/foundryvtt/dnd5e/assets/76103282/7b0e3e9d-eb57-47e2-b5ea-fac2627fe9af)

Do damage with a spell that does physical damage to this actor (example: Blade Barrier)
Observe that the system (incorrectly) halves the damage

**Versions**
Ready Set Roll for 5e: [3.0.9]
dnd5e: [3.0.3]
Foundry: [11.315]

**Other Modules**
Tested with no other modules running.

**Note/context**: Do note that the Resistances sheet that I screenshoted above (core dnd5e v3.0.3) is a simplification. It only calls out weapon properties that will bypass damage resistance. Creatures in 5e don't have simply "resistance to slashing damage" - the wording most commonly used in the Monster Manual is "Bludgeoning, Piercing, and Slashing from Nonmagical Attacks" - so clearly they have no resistance to bludgeoning, piercing or slashing damage caused by non-attacks (such as falling, or spells with saving throws), regardless or them being magical or not. And a spell with an attack roll is clearly also a "magical" attack, even if it's not a weapon attack.

When this feature (damage resistance calculation) is turned on, damage from a spell, regardless of type, probably should be treated as magical. So I submit this issue to help you be aware of the nuances/issues when you develop this system fully.

I personally have only become aware of the issue, module devs Zhell and MangoFVTT can probably be contacted if there are questions about how their modules use the current dnd5e system.

**Comment by arbron** [comment]
Specifically the issue is that other item types have a `"magical"` property that they pass along with damage, but since all spells are magical it doesn't need that property. We should be automatically adding the `mgc` property to all damage done by spells.

**Comment by MangoFVTT** [comment]
@arbron something to note is that simply adding `mgc` wouldn't cut it, because that would still prevent spells from bypassing physical resistances if the bypass is set to only "silvered" or "adamantine". The Physical Bypasses should apply only to weapons, not to spells, for the calculation to work correctly.

**Comment by asherett** [comment]
From the 5e Monster Manual introduction under the heading "Vulnerabilities, Resistances, and Immunities" (emphasis mine):

> Particular creatures are even resistant or immune to damage from non-magical attacks (**a magical attack is an attack delivered by a spell, a magic item, or another magical source**).

As far as I know the particular "bypasses" aren't specifically detailed or defined in the rules beyond this. The most common style of of course "bludgeoning, piercing, and slashing damage from nonmagical weapons", but it's only the monster creator's imagination that sets the limit. I've seen "resistance to damage from attacks made without advantage" from some 3rd party creators.

**Comment by arbron** [comment]
> @arbron something to note is that simply adding `mgc` wouldn't cut it, because that would still prevent spells from bypassing physical resistances if the bypass is set to only "silvered" or "adamantine" (and not "magical"). The Physical Bypasses should apply only to weapons, not to spells, for the calculation to work correctly, if my understanding of the rules of 5E is correct anyway.

The wording used in official stat blocks is `"bludgeoning, piercing, and slashing from nonmagical attacks"` or `"slashing from nonmagical attacks that aren't silvered"`. The use of `"nonmagical attacks"` rather than `"nonmagical weapons"` indicates that this applies to all attacks, not just weapon attacks.

Now this is a bit of a moot point because all the stat blocks I could find include `nonmagical` in the list, but if you had one that said `slashing from attacks that aren't silvered` that would mean it would get resistance to spells that do slashing damage.
