### ISSUE TITLE
Can't view character sheet tabs in 3.0 interface

### ISSUE THREAD

**Issue by aSemy** [foundryvtt/dnd5e#3171]
In version 2.x I could view a character's inventory, features, spellbook, effects, biography by clicking on the tabs and viewing the infromation.

![image](https://github.com/foundryvtt/dnd5e/assets/897017/9b6d0be8-3d9a-42a8-9df8-2c2b21871958)

In version 3.0.3 the tabs aren't visible on the character sheet, so I can't see the same information.

![image](https://github.com/foundryvtt/dnd5e/assets/897017/7c7a90c9-1bc7-43ca-90a1-46c77df4a949)

**Comment by SlamHammerfist** [comment]
The tabs are on the right of the character sheet
![image](https://github.com/foundryvtt/dnd5e/assets/68779916/b01860ee-b9e6-4675-9e46-3284a9bf6f02)
