### ISSUE TITLE
Draconic Sorcerer HP Increase feature not applying its effect on character sheet

### ISSUE THREAD

**Issue by victorhsantiago** [foundryvtt/dnd5e#3174]
Hi! 

The feature that increases Draconic Sorcerer max hit point is not applied in the character sheet, but it's possible to see the effect in player token. Additionally, it's not possible to heal the character above the max hp in the character sheet.

![image](https://github.com/foundryvtt/dnd5e/assets/39136619/66472795-ff37-41b2-90de-676ef1581b82)

**Comment by krbz999** [comment]
The 'Draconic Resilience' feature in the 'Class & Subclass Features' compendium contains an effect that only sets the AC calculation of the actor to the 'Draconic' one, which is correct.

The HP bonus (1 per sorcerer level) should be entered in the HP config:
![image](https://github.com/foundryvtt/dnd5e/assets/50169243/12883b1f-0d6f-410d-bf5e-ada54d8e03a5)

If this is an import from DDB, then it is not an issue with the system (and the `#dnd5e` channel on the discord server is always a better place to troubleshoot.)
