### ISSUE TITLE
Invalid size prevents actor sheet from rendering

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3180]
Repro:
- have no race
- make effect that *overrides* actor size (`system.traits.size`) to "huge"
- sheet can no longer re-render.

**Comment by arbron** [comment]
Hmm, not able to reproduce that myself. I created an actor without a race and an AE targeting size and it continues to work fine. Tested on both `3.0.4` and `3.1.0`.

<img width="591" alt="Screenshot 2024-03-04 at 09 25 14" src="https://github.com/foundryvtt/dnd5e/assets/19979839/d85a57ec-264f-4004-b0b9-f5a1f2796927">

**Comment by krbz999** [comment]
Yeah seems I was a bit too quick and didn't notice the effect was set to 'add' instead of override turning the property into `"medhuge"`.

So, different issue: invalid actor size prevents the sheet from rendering.
