### ISSUE TITLE
Incorrect legendary action on SRD Adult White Dragon

### ISSUE THREAD

**Issue by Mythano** [foundryvtt/dnd5e#3195]
The Adult White Dragon in the SRD has a wing attack (legendary action), that is incorrect.   It looks to be a tail attack with the name changed.  Attached screenshot to show. 
DnD5e version: 3.0.3  (though my playworld is stil on 2.4.1 and it's incorrect there also)

![image](https://github.com/foundryvtt/dnd5e/assets/89128830/7ebee061-4c4e-4762-be08-77a65d74c95a)

**Comment by luccavp12** [comment]
fixed in #3252
