### ISSUE TITLE
[Bug] Transferring effect from a chat card doesn't work if the item doesn't exist anymore

### ISSUE THREAD

**Issue by FalconPilot** [foundryvtt/dnd5e#3215]
I found a bug when trying to transfer an effect from a chat card: if the item doesn't exist anymore when transferring the effect, it logs an error message. I replicated the issue with a Potion of Hill giant strength to which I just added an effect:
![image](https://github.com/foundryvtt/dnd5e/assets/9877634/955018bf-62ff-4fb8-afce-33f617dde05b)
![image](https://github.com/foundryvtt/dnd5e/assets/9877634/db4b8817-8601-4859-9ef5-96537dd77ac1)
My hypothesis (without reading source code) is that the effect may be fetched directly from the actual object, but since it doesn't exist anymore, it just errors out. I don't know what could be a fix for it, but if it helps I could delve into it and try to figure something out 😄

I thought it would be an edgecase at first, but the potion of hill giant strength actually is a good example of that: a player may just have one potion, drink it, and want to apply the effect on his character (since it has a temporary effect attached to it). However, if the player consumes the potion, then the potion won't exist anymore.

Just over my head, perhaps there could be a possibility of a fallback using "static effect data" transferred to the chat card using hidden inputs somehow? It's a bit less sexy than dynamically fetching the Effect data, but as a fallback it could at least enable a whole new potential of effect-application

**Comment by krbz999** [comment]
> My hypothesis (without reading source code) is that the effect may be fetched directly from the actual object, but since it doesn't exist anymore, it just errors out.

You're correct. It's been coincidentally fixed already in #3172.

**Comment by FalconPilot** [comment]
> > My hypothesis (without reading source code) is that the effect may be fetched directly from the actual object, but since it doesn't exist anymore, it just errors out.
> 
> You're correct. It's been coincidentally fixed already in #3172.

Oh, perfect then! :D I'll close the issue since it's already fixed. Cheers! 🍻
