### ISSUE TITLE
Wand, Rod, and Trap should be equipment subtypes, not consumable subtypes

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3223]

**Comment by JPMeehan** [comment]
Wand is a consumable because it can be destroyed on use

**Comment by krbz999** [comment]
> Wand is a consumable because it can be destroyed on use

This is not correct. A wand is not a consumable because it is not destroyed when it expends its last charge. A wand, in many cases, is destroyed if it rolls a 1 on a d20 (after expending its last charge). The current implementation results in a user either having to:
- use a wand, expending the last charge, the wand is immediately destroyed, and they have to roll a d20 and grab a new wand if it didn't roll a 1.
- use a wand, expending the last charge, unchecking the Destroy property (*so it might as well not be a consumable!*), and then rolling a d20, removing the wand from their inventory if it rolled a 1.

**Comment by krbz999** [comment]
Also *horseshoes* should not be consumable items either.
