### ISSUE TITLE
[Bug] using the last consumables with an active effect and a 1/1 destroy on empty charge, makes the effect unusable

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/dnd5e#3224]
When you have a consumable that gives you an effect and the consumable gets destroyed on use the effect becomes unusable on the chat card if you use the last one of that consumable in your inventory.
1) example this potion:
![image](https://github.com/foundryvtt/dnd5e/assets/86924581/fa4d0b04-2605-4895-8c0f-bf32c83d5204)

2) use it.
![image](https://github.com/foundryvtt/dnd5e/assets/86924581/602bf5b3-77ea-400a-b006-df789956894b)

3) try to apply the effect and get an error
![image](https://github.com/foundryvtt/dnd5e/assets/86924581/ac1703b4-a233-465d-a5c5-577e9dab960c)
![image](https://github.com/foundryvtt/dnd5e/assets/86924581/88f4c5a7-54ff-4a85-9de2-f629d8359f31)

I'm assuming the active effect data is not stored on the chat card, meaning once the item is destroyed it doesn't know where to look. his is probably gonna be a problem in the future as with the milestone [Compendium Active Effects](https://github.com/foundryvtt/dnd5e/milestone/37) Im gonna assume there are gonna be a lot of standard items with active effects (like a Potion of Hill Giant Strength, which you could drink or feed to an ally)

Foundry vtt: 11 build 315
DnD5e: 3.0.4
modules: none

**Comment by arbron** [comment]
Already resolved by https://github.com/foundryvtt/dnd5e/pull/3172
