### ISSUE TITLE
[BUG] The flag ` flags.core.sourceId` is no more been passed to the `preCreateItem` or `createItem` hooks

### ISSUE THREAD

**Issue by p4535992** [foundryvtt/dnd5e#3229]
**Core Version:** 11.315
**System: dnd5e** 3.0.4 (Atropos) 
**Modules:**
forien-copy-environment v2.2.0 (Blair McMillan, Forien)

When dragging an item from a compendium to an actor how do I retrieve the original uuid of the compendium in the `preCreateItem` or `createItem` hook ? I can't find anymore the property in the flags.core.sourceId.

I confirmed with no active modules is the dnd5e system on pf2e everything is working fine.

**Macro Example:**
```
Hooks.on("preCreateItem", async (item, data, options, userId) => {
  console.warn("TEST |"); // Check the item.flags property
  const actorEntity = item.actor;
  if (!actorEntity) {
    return;
  }
});

```
Add some images for a better context
![test_source_5_with_dnd5e](https://i.imgur.com/3vY9A8f.png)

On pf2e everything seem fine

![test_source_4_with_pf2e](https://i.imgur.com/wsmBkin.png)

**Comment by arbron** [comment]
I cannot reproduce this result. Here is my testing code:

```javascript
Hooks.on("preCreateItem", (item, data) => {
  console.log(foundry.utils.deepClone(item.flags?.core));
  // Result: Object { sourceId: "Compendium.dnd5e.items.Item.paqlMjggWkBIAeCe" }
});

Hooks.on("createItem", item => {
  console.log(foundry.utils.deepClone(item.flags?.core));
  // Result: Object { sourceId: "Compendium.dnd5e.items.Item.paqlMjggWkBIAeCe" }
});
```

Tested this on `11.315` & `3.0.4` in the following ways:
- "Import" button from compendium
- Dragging from compendium to items sidebar
- Dragging from compendium to actor sheet (new and legacy)
- Dragging from compendium to container sheet

All produced the same result containing the `sourceId`. Is there anything else that might help narrow down this issue?

**Comment by p4535992** [comment]
It's strange i can replicate in a world but not in another ??? i'll close this for now . Ty for your time
