### ISSUE TITLE
Yes, you can now drag backgrounds but you can't correct them

### ISSUE THREAD

**Issue by Slagmoth** [foundryvtt/dnd5e#3234]
I dragged a background onto a sheet the other day and then realized I dragged the wrong one... I promptly deleted that background but when I tried to drop the next one it said you can only have one background on a character.

**Comment by arbron** [comment]
In my testing deleting the background and adding another one works fine, so I'm wondering if there is some bad data on the sheet.

- Can you re-produce this issue with a new actor?
- Is the background you dragged on the first one?
- Is this an old character that previously used two backgrounds before the restriction was added?
- If you switch back to the legacy sheet, is there still a background on the actor?
- If you go into the console (F12) and type `game.actors.getName("<your actor's name>").itemTypes.background` what do you see?

**Comment by Slagmoth** [comment]
Yeah, I can't reproduce it now... it may have been a module that has since been updated as well causing issues... however advancement for backgrounds is apparently non-functional. Not sure if that is just not implemented yet or not though.

**Comment by Slagmoth** [comment]
I am noticing that there is are some UI updating issues here and there though. I tried re-adding my advancement to the background and it didn't show until I closed and reopened it... noticing that in a lot of places.
