### ISSUE TITLE
Dynamic Rings push an error and break.

### ISSUE THREAD

**Issue by Brimcon** [foundryvtt/dnd5e#3254]
Foundry Version 11.315
D&D 5e 3.0.4
No Modules enabled.
Chrome version 122.0.6261.129 (Official Build)

With Dynamic ring enabled on a token (Enabled by default in the Phandelver & Below Adventure) targetting a new token flashes blue once, and never again. Going into the F12 console prints this error upon selecting the token as a target again.

```
TypeError: attribute.from.mix is not a function
    at #updateAttribute (foundry.js:31446:62)
    at #animateFrame (foundry.js:31415:67)
    at animation.fn (foundry.js:31310:55)
    at nn.emit (index.js:89:1)
    at Dt.update (index.js:89:1)
    at Dt._tick (index.js:89:1)
```
    
![image](https://github.com/foundryvtt/dnd5e/assets/7198283/25e5c97e-0ab4-4708-b5ad-1ba6ccfd0df9)

Error continues even upon attacking the token and dealing damage, filling the console log up with errors.

**Comment by arbron** [comment]
Is this just a single token or all of them? I suspect it is the result of bad color data on the token. Can you open the token config for an affected token, copy the UUID, type this into console (replacing the placeholder with the token's UUID): `(await fromUuid("UUID")).flags.dnd5e`, and let me know what it says?

**Comment by Brimcon** [comment]
Its all tokens generated from Phandelver that I've tested (Bugbear, Goblin, Giant Poisonus Snake, Klarg)
```
Uncaught TypeError: Cannot read properties of null (reading 'flags')
    at <anonymous>:1:38
```

Is what I get.
