### ISSUE TITLE
Weight calculations broke for Metric

### ISSUE THREAD

**Issue by LozoTrioxide** [foundryvtt/dnd5e#3257]
If 'Use metric weight units' is set to on it breaks the encumbrance calculations
![Screenshot 2024-03-15 220246](https://github.com/foundryvtt/dnd5e/assets/50601395/61830ede-b4a1-4e9b-bb41-0962e7c64f6e)
This is with it on ^
![Screenshot 2024-03-15 220414](https://github.com/foundryvtt/dnd5e/assets/50601395/2ace28fb-3794-4864-ae46-c7c7d2d1bbbb)
This is when its off ^

Not sure what else to put here

**Comment by LozoTrioxide** [comment]
If metric is on, instead of doing the weght calculation Strength * 11 it does Strength * 6.8

**Comment by alexdiste** [comment]
str*6.8 is wrong, in metric system is lb/2, so it should be str*7.5

**Comment by Padhiver** [comment]
That's right, and we talk about it here:  : https://github.com/foundryvtt/dnd5e/issues/1228
