### ISSUE TITLE
Add Healing enricher

### ISSUE THREAD

**Issue by Bradeck** [foundryvtt/dnd5e#3260]
As of v3.0.4, you can't use an enricher for healing as you can for damage.
[[/damage 2d8+2 healing]] or [[/damage 2d8+2 heal]] don't get parsed and so don't appear like a roll in the journals.

At the moment we have to use the [[/r 2d8+2#Healing]]{2d8 +2 Healing}

**Comment by arbron** [comment]
I'd propose supporting `[[/healing 1d6]]` & `[[/healing 1d4 temp]]` formats.

**Comment by JPMeehan** [comment]
Yeah this would be really nice for my artificer's Eldritch Canon
