### ISSUE TITLE
New character sheet tab UI is confusing

### ISSUE THREAD

**Issue by iamthehorker** [foundryvtt/dnd5e#3262]
I appreciate the work that has gone into the new dnd system, but there is now a usability issue. Character sheet tabs (inventory, spellbook, etc) only display an icon until highlighted by your cursor. My players can never remember which tab is which without seeing its name and honestly neither can I. It would greatly benefit usability if the character sheet tabs always had their names displayed alongside the icons. The character sheet prior to the WotC partnership always had tab names on display.

Thank you.

**Comment by Fyorl** [comment]
Using icons only is an incredibly common design pattern seen not just in core foundry (the sidebar tabs, the scene controls), but also in countless other pieces of software. I think the usability concerns here are overstated.
