### ISSUE TITLE
Add spell components back to chat cards

### ISSUE THREAD

**Issue by MotoMoto1234** [foundryvtt/dnd5e#3269]
In other iterations of the dnd5e system, when you casted a spell the VSM was clearly shown in the card, but in 3.0 you have to go to the character sheet to see it, if a spell has a material component that is displayed, but no Verbal or Somatic.  

![image](https://github.com/foundryvtt/dnd5e/assets/116308065/ad38bc90-20a6-4922-8e06-ceb41459f817)

![image](https://github.com/foundryvtt/dnd5e/assets/116308065/de91fcb1-1258-4a25-9a84-004726c10e4b)

**Comment by Fyorl** [comment]
I think this is just an oversight

**Comment by arbron** [comment]
Two options for displaying these:

<img width="295" alt="Screenshot 2024-03-25 at 11 26 36" src="https://github.com/foundryvtt/dnd5e/assets/19979839/af7f5917-a001-4244-b5cf-9c08398a1ff6">
<img width="297" alt="Screenshot 2024-03-25 at 11 26 40" src="https://github.com/foundryvtt/dnd5e/assets/19979839/9d7a410d-0085-411d-b7ec-5f3c5711f061">

**Comment by MotoMoto1234** [comment]
I personally always called it Verbal, but I think some places may actually use Vocal fyi.
