### ISSUE TITLE
Bug - HP Attributes Do not work on Vehicle or NPC Sheets but PC Sheets

### ISSUE THREAD

**Issue by XXDarrienX** [foundryvtt/dnd5e#3276]
The system.attributes.hp.bonuses.overall on an active effect placed on a Vehicle, NPC does nothing, only when placed on a player sheet does it work.

Foundry - 11.315
D&D5E 3.04
No Active Modules for testing

![image](https://github.com/foundryvtt/dnd5e/assets/28017703/f9e37143-d883-441b-a629-9ec74699a78b)
![image](https://github.com/foundryvtt/dnd5e/assets/28017703/7d165384-6705-4124-bdd6-286c8c0a3b4a)
![image](https://github.com/foundryvtt/dnd5e/assets/28017703/948da656-e82d-40fb-a9db-66c88632959d)

**Comment by arbron** [comment]
That is because NPCs and Vehicles have static max values, so you would use `system.attributes.hp.max` rather than the bonuses. PCs have those bonuses because they need to take class HP into account.

**Comment by XXDarrienX** [comment]
Nevermind I was incorrect tested again and it seems to work
