### ISSUE TITLE
Magical bonus to AC applies regardless of the item being magical

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3297]
When 'Magical' is toggled off, the AC bonus should not be applying, but it do be doing that.

repro:
- make shield
- give +2 ac
- make magical
- give 2 magical bonus
- equip it
- gain +4 AC on actor
- toggle magical off on shield
- still have +4 AC

**Comment by krbz999** [comment]
Same applies to weapons' attack and damage bonuses.

**Comment by JPMeehan** [comment]
How are you defining a "magical bonus"?
