### ISSUE TITLE
Containers breaking older item compendiums (missing from index)

### ISSUE THREAD

**Issue by sneat** [foundryvtt/dnd5e#3299]
FoundryVTT Version 11.315
DND5e Version 3.1.0

Opening or editing (e.g. moving the compendium between folders) triggers the following error:

```
foundry.js:753 TypeError: An error occurred while rendering ItemCompendium5e 36. Cannot read properties of undefined (reading 'container')
    at ItemCompendium5e._render (item-compendium.mjs:18:34)
```

The item itself in the collection seems to have been correctly migrated (and has `item.system.container = null`) but the response from the server for `.getIndex()` excludes the `system` field entirely (which then throws the error).

I came across this in a private module, but you can see it in v4.0.0 of https://github.com/PwQt/magic-items-2 when you open the compendium.

First two images shows the item (after running `.getDocuments()` on the pack) containing the `system` field and `system.container: null` values.
![image](https://github.com/foundryvtt/dnd5e/assets/293277/f8b4efc1-499e-49a1-875f-40b7bcbd8759)
![image](https://github.com/foundryvtt/dnd5e/assets/293277/7a248c1d-3882-4e86-864f-c2ea322012b1)

The third image shows the index returned from the server not having the `system` nor the `system.container` fields.
![image](https://github.com/foundryvtt/dnd5e/assets/293277/51a6d2ea-16f1-4152-a866-52f55e419dd8)

The impact of this error is that it prevents module logic flow inside the private module. Most people won't notice it (because the compendium still opens and can be accessed).

**Comment by PwQt** [comment]
Maybe it can help, but I've got this issue reported, as for Magic Items, the problem seems to be that when the module was migrating from Foundry v9 to Foundry v10, this migration wasn't properly done -> it's asking to fetch `system` when I had `data` as the column.

I did tests locally and it should be fixed for that.

![obraz](https://github.com/foundryvtt/dnd5e/assets/12457218/7443c859-8daa-4345-a636-1fcad7e1a545)

**Comment by krbz999** [comment]
The `getIndex` method doesn't perform any migrations whatsoever, meaning it can pull old or even invalid data. So documents that are still stored using `data` won't have a `system` property whatsoever.

This does mean such a document also won't be stored with any *new* data, such as `system.container`, so probably an easy fix until v11 support is dropped (which is gonna be a while).
