### ISSUE TITLE
Don't show the concentration warning when casting a spell that doesn't require concentration

### ISSUE THREAD

**Issue by CeaneC** [foundryvtt/dnd5e#3301]
When concentrating on a spell, casting a spell that doesn't require concentration should not warn the user that they cannot maintain concentration on more effects.

Example: Akra is concentrating on Bless.
![image](https://github.com/foundryvtt/dnd5e/assets/43473593/f56ffbd4-da86-42f2-8bbb-99e3fe51ee47)

Attempting to cast Cure Wounds warns the user that they cannot maintain concentration on more effects. Cure Wounds doesn't require concentration, so this warning is irrelevant.
![image](https://github.com/foundryvtt/dnd5e/assets/43473593/7ac0f6ae-4ad7-49ce-b910-dfbb85275d74)

Running D&D5e 3.1.0 with no modules enabled.

**Comment by krbz999** [comment]
My greatest wish would be the chance to nuke the `AbilityUseDialog` to oblivion in a major milestone.
