### ISSUE TITLE
Since 3.1, Concentration no longer works

### ISSUE THREAD

**Issue by Melkyor** [foundryvtt/dnd5e#3316]
Hi,
There is an issue since updating DND5e to version 3.1: Concentration no longer applies.

FYI: Foundry VTT 11.315; DND5e 3.1 / All my modules are up to date

- If I leave Concentration tracking enabled, spells with Concentration no longer cast.
- If I deactivate Concentration tracking and let Midi-QoL manage the Concentration automation, the spell is cast but the Concentration no longer applies. It worked fine before the update.
- If I deactivate the management of Concentration in Midi-QoL, the spell is cast but Concentration still does not apply.

**1. DND5e Concentration tracking ON + Midi-QoL Concentration Automation ON:**
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
     at ActiveEffect5e.createConcentrationEffectData (active-effect.mjs:426:31)
     at Actor5e.beginConcentrating (actor.mjs:1112:33)
     at Item5e.use (item.mjs:1028:39)
     at async Item5e.doItemUse (itemhandling.js:551:16)
     at async 🎁CONFIG.Item.documentClass.prototype.use#monks-combat-details (monks-combat-details.js:135:30)

**2. DND5e Concentration tracking OFF + Midi-QoL Concentration Automation ON:**
midi-qol | performState | Workflow Detect Magic VJ1LFKkWZDKzpfUc Workflow Actor.eIzoz0uzr9KdXRRr.Item.iM15O6ZGrQMcCskD Error: Invalid status ID "concentrating" provided to ActiveEffect.fromStatusEffect
     at ActiveEffect5e.fromStatusEffect (active-effect.mjs:63:26)
     at addConcentrationEffect (utils.js:2494:55)
     at addConcentration (utils.js:2472:8)
     at Workflow.WorkflowState_RollFinished (workflow.js:1392:10)
     at async Workflow.performState (workflow.js:476:21)

**3. DND5e Concentration tracking OFF + Midi-QoL Concentration Automation OFF:**
No error but no Concentration either.

I would add that I really love Foundry VTT but practically every DND5e update breaks the work of many developers AND the work of many DMs who have to spend hours and hours fixing everything.
It becomes painful and totally dissuasive!

Please learn to work together for the benefit of all.

**Comment by JPMeehan** [comment]
This seems to be a bug with MIDI rather than with the system.

**Comment by unsoluble** [comment]
For future reference, all tickets filed on this repo should be against a no-modules environment. 

> Please learn to work together for the benefit of all.

Also this comment completely disregards the efforts our (mostly volunteer) system devs take in order to improve the system with as little adverse ecosystem effects as possible.

**Comment by Melkyor** [comment]
> This seems to be a bug with MIDI rather than with the system.

This is surely true.
However, Concentration automation with Midi-QoL worked very well before the DND5e update.
There is surely a correlation between the two.

---

> Also this comment completely disregards the efforts our (mostly volunteer) system devs take in order to improve the system with as little adverse ecosystem effects as possible.

Foundry would certainly not be as popular without the immense work of all the module developers, most of them volunteers. And all of these modules couldn't exist without software as solid as Foundry and a system as well designed as DND5e.
On the other hand, it is clear how fragile this whole system is that regularly, system updates force many developers to rework, always on a voluntary basis, their modules AND also force many DMs to have to spend hours and hours to try to solve problems.

This is exactly what it means: learn to work together for the benefit of all.

**Comment by unsoluble** [comment]
Nobody is forced to update _anything_ on the platform. If you’d like to continue this conversation, please head over to the Foundry discord.

**Comment by Melkyor** [comment]
> It becomes painful and totally dissuasive!

Yes, that's exactly what I meant in my first message: It becomes painful and totally dissuasive!

Now I'm here to try to solve a problem.
THANKS

**Comment by Melkyor** [comment]
> Nobody is forced to update _anything_ on the platform. If you’d like to continue this conversation, please head over to the Foundry discord.

Yes, that's exactly what I meant in my first message: It becomes painful and totally dissuasive!

Now I'm here to try to solve a problem.
THANKS
