### ISSUE TITLE
Allow items to consume their "Quantity" without being considered ammunition. (Javelins, grenades, etc.)

### ISSUE THREAD

**Issue by guldelox** [foundryvtt/dnd5e#3317]
Currently there is no way to create a consumable weapon such as a javelin or grenade. There are many situations where a player may have a small collection of single-use weapons such as these, but there is currently no native way to create such an item.

It is possible to simulate this behavior by giving a weapon "charges" but this does not affect the quantity (and therefore weight) of the item being used. The presumed way of creating a consumable weapon would be by creating a Consumable with itself as the ammunition, but this causes the strange behavior of rolling the damage formula twice, since the system seems to consider the damage roll of a piece of ammunition to be included with the item that fired it (like a bow and arrow).

Currently the best way around this seems to be to create a weapon called "Throw" and set various consumables as its ammunition, but this is clunky and not ideal, requiring players to open up the Details of the item and change the ammo themselves.

Suggested feature: EITHER add "Item Quantity" to the Resource Consumption dropdown for items/weapons/etc. that simply decrements the quantity of the item its assigned to, without any additional functionality OR add "Thrown" to the Consumable Type dropdown with similar behavior.

**Comment by TremendoDude** [comment]
I struggled with this somewhat myself, but found out how to do it based on the way other consumables in the SRD compendium work. It's a bit unintuitive, but it is very possible to make an item like this work, similar to the way Potions of Healing work in the SRD:

**How to make a single use consumable that depletes itself on use (like a grenade):**
1. Create your consumable (Optional: Set the Consumable Type to trinket or whatever best fits your vision)
2. Set your desired Activation Cost
3. Under Limited Uses, select Charges, and set the desired number of charges (usually 1 for a single-use consumable)
4. Check the box that says Destroy on Empty.
![image](https://github.com/foundryvtt/dnd5e/assets/2471365/72f5a730-39e6-4e4c-b50a-4f5bb4410597)

When you use the item, if Uses Prompt is checked, it will allow you to expend a use of the item. When the charges are all used up, it will destroy one item from the stack (freeing up weight) and refill the charges with the next item in the stack. On the last usage of the item, it will warn you that it's the last one before using it, and will delete the item from your inventory once it's used. (Make sure to keep a backup of the item sheet in your Items page or a Compendium.)

**Comment by JPMeehan** [comment]
Seems like "Resource Consumption" should support "Self" as an option, as a more idiomatic way to configure weapons. Or just always include the weapon itself as an Ammunition option.

**Comment by guldelox** [comment]
> I struggled with this somewhat myself, but found out how to do it based on the way other consumables in the SRD compendium work. It's a bit unintuitive, but it is very possible to make an item like this work, similar to the way Potions of Healing work in the SRD:
> 
> **How to make a single use consumable that depletes itself on use (like a grenade):**

That is _wacky_, but does work! Thank you!

Though I do think a more of a self-evident way to configure thrown expendable weapons is called for.

**Comment by guldelox** [comment]
Is a more self-evident way of doing this being considered?
