### ISSUE TITLE
[BUG] Changing sheet via sheet settings not possible

### ISSUE THREAD

**Issue by ZeroXNoxus** [foundryvtt/dnd5e#3318]
Changing the actor sheet via the sheet setting in the dragable header will not change the sheet configuration. It just loads the v2 sheet and the setting to e.g. Legacy Sheet is not saved:

Current Settings:
![image](https://github.com/foundryvtt/dnd5e/assets/29397572/ba63504b-0ae4-4621-9d43-294e9ec64705)

Attempted Change:
![image](https://github.com/foundryvtt/dnd5e/assets/29397572/7d06925b-8d60-43f4-8f58-534afdea7af5)

Result Settings after save:
![image](https://github.com/foundryvtt/dnd5e/assets/29397572/d777ed71-a38e-46e4-bdfe-0564ddfe0862)

The only change applied to these settings is via the Game Configurations. This issue seems to only apply when the v2 sheet is currently set for the to-be changed sheet.

**Comment by arbron** [comment]
How about with no modules, quick testing myself allowed it to be changed so it may be one of your module interfering.

**Comment by ZeroXNoxus** [comment]
I have looked into this and found that "Monk's Enhanced Journals" seems to cause this issue. I will direct this issue towards the creator of this issue.

I was hesitant to test this disabling all modules and possibly messing up the settings for my 80* modules.
