### ISSUE TITLE
[FEATURE] Would it be possible to include a pointer option?

### ISSUE THREAD

**Issue by ZeroXNoxus** [foundryvtt/dnd5e#3327]
While a ping can be sent to all players by clicking and holding the canvas, a pointer following the cursor seems to be missing from the core functionality. It would be really helpful if you could simply hold a button (e.g. "X") on the keyboard and then show a pointer icon to all players to make them aware of a certain location, draw a non-permanent path, etc. 

Could this be implemented by the system or should this be handled by FoundryVTT itself?

**Comment by unsoluble** [comment]
This is already a core Foundry feature — Display Mouse Pointer, in the permission config.

**Comment by ZeroXNoxus** [comment]
These are mostly obnoxious and insufficient. We opt to not use them as they are too small at best or distracting at worst. Toggling a more prominent pointer that has higher visiblity is a missing feature. Many people I have played with are wondering why this isn't implemented yet and I can't blame them. The Mouse Pointer is barely visible when a larger map is shown.

**Comment by unsoluble** [comment]
In the case of a core feature being inadequate for your needs, you’ll need to turn to modules.

**Comment by ZeroXNoxus** [comment]
Useability isn't a priority, I suppose. Well, I'll try my luck in the FVTT core Git, thanks for your opinion, though.
