### ISSUE TITLE
Healing & healing temporary immunity no longer selectable on character sheet

### ISSUE THREAD

**Issue by Fayghost** [foundryvtt/dnd5e#3333]
![image](https://github.com/foundryvtt/dnd5e/assets/14824185/a2d09c85-1196-410d-aba5-7335901c1580)
In previous versions this option existed since foundry 3.0 it's been missing. You can still select it for DAE but it now does nothing.

![image](https://github.com/foundryvtt/dnd5e/assets/14824185/cec8d5bc-74e2-4ea5-8839-03cc221555f9)

**Comment by krbz999** [comment]
They have never been selectable in those configuration menus. You had a module doing that.

**Comment by Fayghost** [comment]
Would you happen to know which one?
