### ISSUE TITLE
Chat Card Optimization: Remove seperate d20 modifier div

### ISSUE THREAD

**Issue by ZeroXNoxus** [foundryvtt/dnd5e#3334]
The additional div only displaying the modifier added to the d20 roll seems unnecessary, especially when compared to the damage roll and the way those modifiers are displayed:
![image](https://github.com/foundryvtt/dnd5e/assets/29397572/ae7d9fb2-09e9-4975-b027-37781d7c163f)

**Comment by thatlonelybugbear** [comment]
That is a MidiQOL chat message for merged cards.

**Comment by ZeroXNoxus** [comment]
Oh, my bad!

**Comment by ZeroXNoxus** [comment]
The issue is also present in the default chat cards for attack rolls:
![image](https://github.com/foundryvtt/dnd5e/assets/29397572/c70eef3d-ca93-4657-acef-31e5a22e261c)

**Comment by unsoluble** [comment]
The whole point of the expanded card is to clearly show the breakdown of where the total comes from. Pretty sure this is an intentional design choice.

**Comment by thatlonelybugbear** [comment]
Indeed it seems so. I just wanted to clarify that cause it would create some confusion, as the card shown was not the default.
MidiQOL will follow the core system's display of rolls.

**Comment by ZeroXNoxus** [comment]
> The whole point of the expanded card is to clearly show the breakdown of where the total comes from. Pretty sure this is an intentional design choice.

It seems counter intuitive to style it differently for attack and damage rolls. The attack roll's additional div kinda explodes the chat messages (which are quiet large as is)

**Comment by krbz999** [comment]
You want to see different breakdowns for attack and damage rolls.

For damage rolls you likely don't care about the modifier, you just want to see how much was fire and how much was slashing. For attack rolls, you ... well, tbh, you never really care about anything but the total, but if you do decide to expand the chat message to see the breakdown, it's probably because you want to see what die rolled what, and what the total modifier is.

So it makes sense to split an attack roll of "1d20 + 1 + 1d4 + 3" as the d20, the d4, and the +4.

**Comment by ZeroXNoxus** [comment]
I understand this approach, but we have more than enough space to display 5-6 dice results in a single row and the background image is enough to differentiate the dice used in the attack roll.

For me the current solution uses tons of uneccessary whitespace that makes looking at chat cards bothersome where it really shouldn't be. As the chat cards require rework anyway (regarding their size) this should be reworked as well.

**Comment by Fyorl** [comment]
Attack roll constants don't necessarily have information on which 'group' they belong to like damage roll constants do. Loose constants are grouped at the bottom.
