### ISSUE TITLE
Add new "free casting" option for spells

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#3341]
A common pattern that has been used frequently in new content is spells being granted that can be cast once per rest for free at their base level and also cast using a player's spell slots. Currently this pattern is done in one of two ways:

1) Adding a limited uses to the spell, allowing the casting limit to be tracked. This has the disadvantage of requiring the player to uncheck "Consume Uses" every time they want to cast it using normal slots, or uncheck "Consume Slot" if they want to use the free use.
2) Creating two versions of the spell, in in "Innate Spellcasting" with the limited uses and one in normal spellcasting. This is more usable, but the player has to maintain those two copies and there is no mechanism within advancement to easily grant them both at the same time.

This can be resolved by add a checkbox indicating that the limited uses represent "Free Castings" of the spell. When this checkbox is checked and the spell is cast, the ability use dialog will have the ability to easily toggle between either casting at base level and using the free use or using a spell slot. If all the free castings are spent, then it will simply default to using a spell slot.

It should be possible for the spell configuration within `ItemGrantAdvancement` and `ItemChoiceAdvancement` to set this flag just like it sets limited uses so these spells can easily be given to players.

**Comment by TremendoDude** [comment]
Leaning in with support, though I'd honestly be satisfied if it kept the same system as it does now, but, if there's available uses, check on Consume Available Uses and check other stuff (like Spell Slots) off by default. I just want to be able to conveniently use Uses for free-casting stuff before using other resources like Spell Slots or Sorcery Points.
![image](https://github.com/foundryvtt/dnd5e/assets/2471365/1795da90-6669-4f43-8f0c-5492230e0293)

**Comment by LukasPrism** [comment]
Although in the above scenario it should be a radio button choice between consuming a slot or using your daily free casting.

**Comment by arbron** [comment]
> Leaning in with support, though I'd honestly be satisfied if it kept the same system as it does now, but, if there's available uses, check on Consume Available Uses and check other stuff (like Spell Slots) off by default. I just want to be able to conveniently use Uses for free-casting stuff before using other resources like Spell Slots or Sorcery Points.

That would just cause the opposite problem for spells that have a limited use **and** consume a spell slot, such as some of the warlock invocations (Bewitching Whispers allows you to use a warlock spell slot once per long rest to cast "Compulsion", but you cannot cast it after that). A separate options will give support for both **or** spells and **and** spells.

**Comment by LukasPrism** [comment]
Ideally they would change based on the spell requirements. But I understand your desire to keep things as simple as possible.

**Comment by NeilWhite** [comment]
There's also some sorcerer abilities that let you cast spells with either Sorcery points or spell slots, would this approach allow for that as well? Or is that still better served with multiple items?

> When you reach 3rd level in this class, you learn the darkness spell, which doesn't count against your number of sorcerer spells known. In addition, you can cast it by spending 2 sorcery points or by expending a spell slot. If you cast it with sorcery points, you can see through the darkness created by the spell.

**Comment by Zanderaf** [comment]
I think in part the Darkness here for Shadow Sorcerer and the Shadow Monk stuff can be handled with just added a duplicated spell with a preset UUID consumption, but yea, those are more things to consider I geuss
