### ISSUE TITLE
Tooltips do not work, when using PopOut! module

### ISSUE THREAD

**Issue by Opeey** [foundryvtt/dnd5e#3352]
With 3.0.4 you added support for the PopOut! module, which is really great. Thank you!
Unfortunately though, the tooltips on the character sheet are not working correctly when PopOut! is used.

They only display a loading spinner and no content ever loads.
![image](https://github.com/foundryvtt/dnd5e/assets/7497821/8e29754c-c47c-4c4d-b24c-37480536ead9)

**Comment by arbron** [comment]
Have you brought up this issue on the PopUp! module? Module issues like this are best first brought up with the module developer and then they can bring us specific solutions if they need to be made in the system.

**Comment by Opeey** [comment]
Ah, you‘re right. It seems like the module developer of PopUp! already knows of this issue. I‘m sorry for the inconvenience.
