### ISSUE TITLE
Add a numeric value to DND5E.actorSizes to facilitate size comparison in macros

### ISSUE THREAD

**Issue by pgervais70** [foundryvtt/dnd5e#3353]
By adding a numeric value to CONFIG.DND5E.actorSizes (e.g.: order, value) it would facilitate doing size comparison in macro code. Many features are only available when a target is maximum one size larger or have a different behavior depending on the size difference.

**Comment by pgervais70** [comment]
I looked at the linked PR, but I don’t agree that it should close this request, it only partially closes it. 
The hit dice value only allows to compare with larger or smaller, but not easily how many sizes larger or smaller.
I was thinking more like assigning values like: 0 to 5 or 1 to 6.

**Comment by JPMeehan** [comment]
Doesn't the token size value let you perform comparisons? I guess Medium vs Small isn't quite there

**Comment by pgervais70** [comment]
> Doesn't the token size value let you perform comparisons? I guess Medium vs Small isn't quite there

Like you said, almost, small and medium have the same value
