### ISSUE TITLE
Add attack enricher

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#3355]
In addition to the current damage enricher, it would be good to have an attack enricher in the style of `[[/attack +5]]` which would compose a generic attack roll, taking advantage of the roll dialog and the new targeting features without having to be tied to a specific item.

This should also be usable in the form `[[/attack]]`, which would attempt to automatically determine the attack modifier from the item it is embedded within, and roll using that item's attack rather than a generic attack. When paired with the change suggested in #2568, this would allow for writing generic NPC weapon descriptions that adapt to the NPC's stats:
`Melee Weapon Attack: [[/attack]], reach 5 ft., one target. Hit. [[/damage average]] damage.`
would be turned into:
`Melee Weapon Attack: [+3] to hit, reach 5 ft., one target. Hit 3 ([1d4 + 1]) slashing damage.`

**Comment by Rabulias** [comment]
> which would attempt to automatically determine the attack modifier from the item it is embedded within

You probably already have an idea for this, but don't forget weapons like daggers and handaxes that can be melee or ranged attack?

**Comment by revilowaldow** [comment]
> weapons like daggers and handaxes that can be melee or ranged attack

The ability used doesn't change for these based on the attack type you make, these are both melee weapons with the thrown property.
Ranged weapons always use DEX, and melee weapons always use STR.
The exception is when a melee weapon has the finesse property (not handaxe, yes dagger), where you use your choice (i.e. the higher) of STR and DEX.

I think this is exactly what Jeff is suggesting checking for.

**Comment by Rabulias** [comment]
>The exception is when a melee weapon has the finesse property (not handaxe, yes dagger), where you use your choice (i.e. the higher) of STR and DEX.

You are correct. I was talking about finesse weapons, but just did not phrase it correctly, and misremembered that handaxes are not finesse. Thanks for clarifying my concern.
