### ISSUE TITLE
Active Effects for HP do not work

### ISSUE THREAD

**Issue by nsm91** [foundryvtt/dnd5e#3369]
I have tried:
```
system.attributes.hp.bonuses.level | add | +2
system.attributes.hp.bonuses.overall | add | +2*@details.level
```
but this has no effect, it seems to be a text field and does not affect the actor HP.

I also tried:
```
system.attributes.hp.effectiveMax | add | + (2 * @details.level)
system.attributes.hp.max | add | + (2 * @details.level)
```
and these do affect the sheet total, but the percent continues to show 100 percent and the value cannot go past the old max (i.e. if the old max was 33, using the above makes the new max show as 45, but 33/45 is the highest the HP will go and 33/45 will show as 100%

**Comment by krbz999** [comment]
You have likely overridden the hp max inside the HP config.

**Comment by nsm91** [comment]
I don't really understand what you mean, this is what I currently have that generates the above screenshot:
![image](https://github.com/foundryvtt/dnd5e/assets/20305756/4edf26e2-626e-4d63-9ba1-b49f7ebd2c8f)

**Comment by krbz999** [comment]
Enter edit mode, open the hp config, remove the override in the hp maximum.

(Further troubleshooting should take place on the discord server.)
