### ISSUE TITLE
Add magical to list of armor properties (and, possibly, add armor bonus parameter/sheet field)

### ISSUE THREAD

**Issue by MustBeAlive** [foundryvtt/dnd5e#3382]
Basically, title. None of the equipment type items has that property, so it's sort of inconvenient when it comes to checking if actor has magical armor/shields/clothing/trinkets.

On a side note, it would also be nice to have "armor bonus" parameter (and sheet field) similar to weapon "attack roll bonus" for cases when magical equipment has static +1/+2/+3 bonuses to AC.

**Comment by krbz999** [comment]
![image](https://github.com/foundryvtt/dnd5e/assets/50169243/890f6814-3eea-4415-b43c-c157377c774e)
