### ISSUE TITLE
Option to disable automatic top-level compendium folder

### ISSUE THREAD

**Issue by hjk321** [foundryvtt/dnd5e#3392]
Since v11, Foundry allows folders in the compendium tab. dnd5e auto-creates a folder called "D&D 5e SRD" every time the world is booted up, and moves the SRD compendiums into it. This is in general a good thing, but some users may want to keep the compendiums in a different folder. **The module will create the folder and move the compendiums even if the folder was previously deleted, which can be quite annoying if the user had a good reason to move them.** There should be a configuration option to disable this behavior.

**Comment by Zanderaf** [comment]
Known issue I think, has been around since the SRD was organized into folders, I think v12 Might fix it? Not completly sure tho

**Comment by JPMeehan** [comment]
This is a core foundry issue rather than a system issue.

**Comment by hjk321** [comment]
Tracking at upstream foundryvtt/9902
