### ISSUE TITLE
Store spell level used for casting summoning spell in summoned actor's data/flags

### ISSUE THREAD

**Issue by trioderegion** [foundryvtt/dnd5e#3393]
For summoning spells that scale "non-data" properties such as increasing the number of attacks the creature's "Multiattack" action provides, it would be helpful to have a way to reference the slot level used for use in `[[lookup]]` and other roll formulas.

Feature text at present: 
> The `[[lookup @name lowercase]]` makes a number of attacks equal to half this spell’s level (rounded down).

**Desired Result**
> The `[[lookup @name lowercase]]` makes a number of attacks equal to half this spell’s level (rounded down): `[[floor(@flags.dnd5e.summonLevel / 2)]]`.

Note: I have no strong opinion on the location or naming of this information.

Rendered result:
> The chinchilla makes a number of attacks equal to half this spell’s level (rounded down): 2.

**Comment by arbron** [comment]
I have added the spell's level (if from a spell) and the profile ID to the flags, so now it will have all the info necessary to recreate the summoning conditions too.

```json
{
  "flags.dnd5e.summon": {
    "uuid": "Actor.2vn3o1FZOFXhrh9L.Item.yJgcYzTXBIINBn5H",
    "profile": "CsMlGY5LcjmKzftY",
    "level": 2
  }
}
```
