### ISSUE TITLE
Allow Resource Consumption to consume variable amounts of a resource.

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/dnd5e#3408]
A minor thing, not sure how big this would be but would help out in cases of something like Sorcerer's Twinned Spell

Twinned Spell: When you cast a spell that targets only one creature and doesn't have a range of self, you can spend a number of sorcery points equal to the spell's level

**Comment by Fyorl** [comment]
Should be covered by consumption scaling now, but please correct me if I'm misunderstanding.

**Comment by Zanderaf** [comment]
Should be yea, from what I remember you can just set a scaling consumption on like, a utility activity on Twin Spell to consume 1-X amounts of Sorcery points.
