### ISSUE TITLE
Add distinction between normal & critical results on chat rolls

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#3410]
Before `3.0` there was a distinction between regular and critical successes & failures on chat messages. Regular successes & failures would get a green/red background, and criticals would get a different colored text. The new chat message design in `3.0` did away with this distinction, given both normal successes and critical successes the same styling. This makes it more difficult at a glance to determine what type of success/failure a role is at a glance, and removes some of the specialness that comes with a critical in a chat message.

<img width="280" alt="Normal hit and critical hit" src="https://github.com/foundryvtt/dnd5e/assets/19979839/73831455-71e3-4c3a-9b3c-a646d245920e">

It would be good to add some sort of obvious distinction between the two types of successes and failures so they work better at a glance, rather than having to find a small change to the flavor text indicating that a roll is a critical or opening up the dice tooltip to see what exactly was rolled on the die.

**Comment by krbz999** [comment]
I feel like just *not* making that single change in #3405 would solve this, no?

**Comment by Fyorl** [comment]
Well that change was made to avoid having to expand the (new) targets tray in the most common case of only having one target for the attack, but we could pull it out. We're in no hurry to merge #3405 though, I'm sure we can come up with some crit styling in the meantime.

**Comment by Rabulias** [comment]
It might be too subtle (and may not meet accessibility guidelines), but I would suggest:
Success: Green background with the roll result in black
Critical Success: Green background with the roll result in dark green
Failure: Red background with the roll result in black
Critical Failure: Red background with the roll result in dark red

This would mirror the older D&D5E system behavior that colors the roll result when you roll a max result or min result on the die.
