### ISSUE TITLE
Add configuration & restrictions on enchantments

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#3418]
A data structure will need to be built up to store information for enchantments (see #3305) and how they relate to items:

### Enchantment Itself
- How many items an enchantment can be bound to, if it is limited
- What item type it can be applied to (e.g. weapon, equipment, consumable, loot)
  - Initially based just on item's primary type
  - Future work can include additional restrictions (e.g. requires "Ammunition" property, must be worth at least 100 gp)

### Enchantment Source
(this is an item that provides information about a group of enchantments)
- Period in which enchantments can be changed (short rest, long rest, never, at will, etc)
- How many total enchantments of this type can be in use at a time (e.g. you can only infuse 2 items at a time)
  - This must accept scale values and other formulas so it can increase with time

**Comment by JPMeehan** [comment]
Will the 3.2 implementation differentiate between types of equipment?

**Comment by arbron** [comment]
> Will the 3.2 implementation differentiate between types of equipment?

For the first pass I'll probably just do by item type (weapon, equipment, etc.), but I'd like to add more time permitting.
