### ISSUE TITLE
Add a Race item type which functions similarly to the Class item

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#342]
## Basic Goals

* The **Race** item would contain certain metadata about the racial traits or proficiencies which are granted.
* Characters should be prevented from adding a 2nd race-type item to enforce that only one is chosen.

## Status

This is not a priority in the short term - but something that should be added to the system eventually to provide for better automation in character creation.

## Progress
- [x] #2503 
- [x] #2541 
- [x] #2542 
- [x] #2556 
- [x] #2557 
- [x] #2563
- [x] #2555
- [x] #2559

**Comment by MaxPat931** [comment]
Just want to mention that in addition to Item Grant, Races should also allow for Scale Value advancements, this could be used for Dragonborn Breath Weapons, or as a workaround for any homebrew a DM wants to scale off of total character level instead of class level
