### ISSUE TITLE
Feature request: Legacy sheets view

### ISSUE THREAD

**Issue by the-real-orson** [foundryvtt/dnd5e#3428]
It would be awesome if there was an option for the user to always view all sheets in the old legacy view as opposed to having to change them one by one.

**Comment by unsoluble** [comment]
This is exactly what the Default Sheet control is for.

![CleanShot 2024-04-07 at 17 56 10](https://github.com/foundryvtt/dnd5e/assets/801582/4f8776bb-cf27-4dd6-800d-1c31e304f97a)

**Comment by the-real-orson** [comment]
Awsome...ty!!
