### ISSUE TITLE
damage modification physical bypasses not functioning

### ISSUE THREAD

**Issue by etiquettestartshere** [foundryvtt/dnd5e#3429]
**Steps to reproduce:** give an actor (in my case, Morthos (Tiefling Sorcerer)) -10 Slashing damage modification, and check Magical under physical bypasses. Give an actor (in my case, Aoth (Human Druid)) a magical weapon, in my case a Dancing Longsword from the SRD. After damage with the longsword is rolled, as the GM, apply the damage with the damage application tray to the actor with damage modification: only damage over 10 will apply, meaning the bypass is not functioning.

The same problem seems to exist if the damage modification and related bypass is applied as an active effect (I also tried with adamantine).

![image](https://github.com/foundryvtt/dnd5e/assets/148253744/40e1ac01-768c-422a-94bc-ba2e17252fa9)
![image](https://github.com/foundryvtt/dnd5e/assets/148253744/dc9c739a-aa4d-4cb8-8630-848c1fbb76a4)

**Comment by tposney** [comment]
I noticed this in my game on the weekend.
There should be a test for bypasses when deciding to apply dm. I added this at line in my game and it seems to work.
```js
      // Apply type-specific damage reduction
      if ( !ignore("modification", d.type) && traits.dm?.amount[d.type] && (traits.dm.bypasses?.size === 0 || (traits.dm.bypasses?.intersection(d.properties)?.size ?? 0) === 0)) {
```
