### ISSUE TITLE
Character sheet CSS doesn't respect "routePrefix" options

### ISSUE THREAD

**Issue by Fneuch** [foundryvtt/dnd5e#3441]
Opening a Actor sheet return a 404 because the CSS doesn't respect the routePrefix specified in options.json

file: `dnd5e.css`

Culprit:
```
.dnd5e2.sheet.actor.character.minimized {
  background: url("/ui/denim075.png");
  border: unset;
}
```

**Comment by Hoppyhob** [comment]
I can work on this.
