### ISSUE TITLE
Put back the delete (trash can) button in the chat cards

### ISSUE THREAD

**Issue by ravingdragoon** [foundryvtt/dnd5e#3443]
As a GM I am constantly deleting unneeded/unwanted messages and having to click the dots or right click the messages for the context menu is significantly slower than it was previously when there was a delete button directly on the chat cards. Can you please put back, or make it an option in the settings to put back, the delete button that was there in the DND5e V2.x versions of the chat cards?

**Comment by unsoluble** [comment]
Maybe Shift makes the trash button appear, à la Discord.

**Comment by Fyorl** [comment]
> Maybe Shift makes the trash button appear, à la Discord.

If we add the trash can back in as-is, there's too great a risk of misclicks next to the kebab menu, so we would have to add a deletion prompt, in which case we're back to the same number of clicks as using the context menu option. A keyboard modifier for GMs only is probably the best solution in that case then.

**Comment by Cempres** [comment]
Are there any plans on adding a "shift" modifier to bring the trash icon back? I'm experiencing a headache for the same reasons as the initial requester of this feature.

**Comment by roth-michael** [comment]
Quick comment to be assigned the PR
