### ISSUE TITLE
Feature request actor.calcluateDamage

### ISSUE THREAD

**Issue by tposney** [foundryvtt/dnd5e#3452]
After the call to dnd5e.preCalculateDamage, damage.active is force set to {} / {active: "Immunity", multiplier: 0).
In midi-qol I have occasion to want to configure some of the actives during the preCalculateDamage hook, so that multipliers can be applied prior to damage modification.

Would it be possible to have damage.active initialised to {} prior to the call to dnd5e.preCalculateDamage?

**Comment by arbron** [comment]
Hmm, what is your intention here exactly? Do you want us to not squash any changes made to `active` during `preCalculateDamage`? If you set `active.multiplier` to `2` during `preCalculateDamage`, are you thinking we'll then modify that value (so if you doubled during pre-calc and then halved during our modification it would end up as `1`)?

**Comment by tposney** [comment]
The exact change I would like is that if in calculate damage damage.active is already defined don't initialise it to {}.

The specific example I have is computing damage when the target has saved. According to at least one rules interpretation the correct order of damage calc should be saves -> modifications -> resistance/immunity. Currently if I pass options.multiplier the order will be modifications/resistance/saves. 

There is also an interpretation that says what is currently being done is correct, so I also have the case of simply setting the multiplier in options during precalculate damage (thanks for the change to make that possible by the way).

So I'm looking to implement the changes due to saves in the preCalculateDamage hook.

I have code to set the multiplier/actual damage for each damage item according to the save, but the multiplier per damage item get overwritten (and the active.saves that I set), however the calculated damage is correct.

**Comment by arbron** [comment]
@tposney Let me know if this does what you need: https://github.com/foundryvtt/dnd5e/pull/3491

**Comment by tposney** [comment]
Looks like exactly what I wanted - many thanks.
