### ISSUE TITLE
Tokens are slightly offset on hexgrids when using `TokenPlacement#place`

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3462]
Either a bit too low or a bit too far to the right, depending on the hex grid type.

![image](https://github.com/foundryvtt/dnd5e/assets/50169243/908aab4d-7d18-4460-b720-3e7799d98d0e)

(Probably a core issue fixed in v12 already idk, but logging it anyway to make sure.)

**Comment by arbron** [comment]
Issue persists in V12, but maybe there is some new API that we can use.
<img width="237" alt="Screenshot 2024-04-23 at 13 18 46" src="https://github.com/foundryvtt/dnd5e/assets/19979839/928baeef-8a73-4f87-b11e-21801c53027f">

**Comment by krbz999** [comment]
Just this in `TokenPlacement##onMovePlacement` seems to work for me.

```js
    const center = canvas.grid.getTopLeftPoint(point);
    if (canvas.grid.isGridless) {
      center.x -= Math.round((this.config.tokens[idx].width * canvas.dimensions.size) / 2);
      center.y -= Math.round((this.config.tokens[idx].height * canvas.dimensions.size) / 2);
    }
    preview.updateSource(center);
 ```
