### ISSUE TITLE
Item Choice Advancement Level Prerequisite: Being able to modify past choices with new options once higher levels are achieved

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/dnd5e#3471]
Sorry if the title of this issue is a bit weird. Did a bit of testing with the https://github.com/foundryvtt/dnd5e/pull/3383 and some stuff I saw from Zhell's test with it yesterday and had a bit of a comment.

With the SRD Eldritch Invocations in the 3.2 branch as an example, leveling up to level 2 and selecting "Armor of Shadows" & "Agonizing Blast" to start off.
- Leveling up to say, level 5 and then going back to modify your level 2 choices still only displays the invocations available to a level 2 warlock. 

From what I understand, the last part of the Eldritch Invocation feature mentions:
_"Additionally, when you gain a level in this class, you can choose one of the invocations you know and replace it with another invocation that you could learn at that level."_

Wouldn't that mean you would be able to slowly change out your "lower level" invocations for higher level ones as you level up instead of the item choice options only being restricted to what you could be taking at the level the option was granted instead of the current level.

**Comment by arbron** [comment]
Modify Choices is working as intended, it will always modify choices in the state as if you were the level you originally were when making the choice, so level restrictions will still apply.

There is another PR for handling replacing earlier choices made with `ItemChoiceAdvancement`: https://github.com/foundryvtt/dnd5e/issues/2299
