### ISSUE TITLE
[V12 Build 319] Compendium Content that contain rolls with "Floor" no longer work

### ISSUE THREAD

**Issue by Mushie1** [foundryvtt/dnd5e#3474]
No Modules activated, new world
Foundry version 12.319, dnd5e version 3.1.2

**Description:** - There are items in the compendiums that contain rolls with "Floor" in them. (Possibly other functions as well) that no longer work in V12. 

**Steps to Repeat** - Import "Cult Fanatic" from compendium into Actors tab.  Warning will appear in console.  Try to use "damage" from  spiritual weapon, and an error will appear.  

I suspect it has to do with the new Dice Rolling V3 - Peggy, and I assume it will effect any roll that has floor, ceiling or potentially other types of rolls with functions.

![image](https://github.com/foundryvtt/dnd5e/assets/77275833/8dbcf462-1e63-4e8e-8c85-1029373b5375)
![image](https://github.com/foundryvtt/dnd5e/assets/77275833/b844efa0-160a-4246-adbc-494fea80508d)
![image](https://github.com/foundryvtt/dnd5e/assets/77275833/19253f96-a58c-4b67-913a-45bacf96df72)

**Comment by Mushie1** [comment]
This was suggested by Foyrl on the discord:
![image](https://github.com/foundryvtt/dnd5e/assets/77275833/f59b9144-1540-4018-9672-e4f2bb81caf3)

**Comment by MrPrimate** [comment]
The formula provided in the SRD spiritual weapon don't seem to work, they always roll 1d8+mod
