### ISSUE TITLE
Condition AE descriptions with relative uuids don't resolve properly

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3476]
Eg the conditions pages having a relative uuid like the Grappled condition, which then gets embedded in the Active Effect, leads to issues like the below when or if a module wants to show the text better than having it hidden in the effect's description.

![image](https://github.com/foundryvtt/dnd5e/assets/50169243/654ee3b8-9735-4e11-a7e7-8b5f416b52fc)

**Comment by arbron** [comment]
How are you displaying the active effect description? If I use `@Embed[Compendium.dnd5e.rules.JournalEntry.w7eitkpD7QQTB6j0.JournalEntryPage.gYDAhd02ryUmtwZn inline]` to include the grappled condition inline in journal entry pages or item description the relative link keeps working properly, so I'm wondering if there is something with how that text is being enriched that is causing trouble.

**Comment by krbz999** [comment]
It is simply the `description` of the ActiveEffect enriched (`TextEditor.enrichHTML`) and rendered in a non-popout application.

MWE:
```js
const uuid = "Compendium.dnd5e.rules.JournalEntry.w7eitkpD7QQTB6j0.JournalEntryPage.gYDAhd02ryUmtwZn";
const page = await fromUuid(uuid);
const text = page.text.content;
await ChatMessage.implementation.create({content: await TextEditor.enrichHTML(text, {async: true})});
```

**Comment by arbron** [comment]
> It is simply the `description` of the ActiveEffect enriched (`TextEditor.enrichHTML`) and rendered in a non-popout application.

Aw, that is because you aren't using `relativeTo` when you enrich the content, so it has no idea how to resolve that link:

```javascript
const uuid = "Compendium.dnd5e.rules.JournalEntry.w7eitkpD7QQTB6j0.JournalEntryPage.gYDAhd02ryUmtwZn";
const page = await fromUuid(uuid);
const text = page.text.content;
await ChatMessage.implementation.create({content: await TextEditor.enrichHTML(text, {async: true, relativeTo: page})});
```

**Comment by krbz999** [comment]
It's not a dnd5e module. I can't know what it is relative to.

**Comment by arbron** [comment]
> It's not a dnd5e-specific module. I can't know what it is relative to.

It's always relative to what you are getting the enriched text from. So since you are enriching a journal page, it is relative to that page. If you were enriching an item description, it would be relative to that. All you need to do is pass in `relativeTo: page`.

**Comment by krbz999** [comment]
> So since you are enriching a journal page,

I am enriching an effect's description.
