### ISSUE TITLE
Find Familiar SRD entry is missing the first paragraph.

### ISSUE THREAD

**Issue by TremendoDude** [foundryvtt/dnd5e#3507]
The SRD entry for Find Familiar is missing its entire first paragraph:

> You gain the service of a familiar, a spirit that takes an animal form you choose: bat, cat, crab, frog (toad), hawk, lizard, octopus, owl, poisonous snake, fish (quipper), rat, raven, sea horse, spider, or weasel. Appearing in an unoccupied space within range, the familiar has the statistics of the chosen form, though it is a celestial, fey, or fiend (your choice) instead of a beast.

**Comment by Rabulias** [comment]
It looks like this fixed in 3.2.0:
https://github.com/foundryvtt/dnd5e/issues/3371

**Comment by TremendoDude** [comment]
Apologies, didn't come up in my initial search and skim. Much obliged!
