### ISSUE TITLE
Inline rolls in dark mode character sheet are difficult to read

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3533]
![image](https://github.com/foundryvtt/dnd5e/assets/50169243/be016c40-1e02-423f-a7ff-0c73837a87a1)
![image](https://github.com/foundryvtt/dnd5e/assets/50169243/5bd34339-9ca0-4159-8ecc-41d24e71d815)

**Comment by Hoppyhob** [comment]
I can work on this.
