### ISSUE TITLE
Tooltips don't show in the popout

### ISSUE THREAD

**Issue by jnsimon** [foundryvtt/dnd5e#3539]
When using the character sheet in the main display, the tooltips display like this:
![image](https://github.com/foundryvtt/dnd5e/assets/11030825/4fd713e8-59db-4a14-a923-d9f847095602)

When switching to a pop-out window, the tooltips are missing on everything:
![image](https://github.com/foundryvtt/dnd5e/assets/11030825/ce11bc47-6e13-4ab9-aff2-5b3b2d70f783)

**Comment by krbz999** [comment]
https://github.com/foundryvtt/dnd5e/issues/3352

**Comment by arbron** [comment]
Module issues should be taken up with the module authors.

**Comment by jnsimon** [comment]
What module would this be from? There aren't any modules for this installed and I'm using the built-in button here
![image](https://github.com/foundryvtt/dnd5e/assets/11030825/cdb59df4-dde1-4c39-bc11-dce4cb8040ba)

**Comment by krbz999** [comment]
The module that allows you to popout windows is called "popout".

It's always a good idea to disable *all* modules before making a bug report, that way you know what is causing the issue, and where to report it.

**Comment by jnsimon** [comment]
That module doesn't show as installed. Installing it provides a second option to open a window
![image](https://github.com/foundryvtt/dnd5e/assets/11030825/3fb64c14-1c8d-4f85-82c5-6f08137497c5)

Using that one works.

**Comment by unsoluble** [comment]
The module in question is a copyright-infringing tool, and will not be discussed further here.
