### ISSUE TITLE
Add consume usage/resource button on chat cards

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#3541]
When the "Uses Prompt" checkbox is unchecked, there is current no way to consume item uses after the fact. This makes it difficult for items that have optional uses because you either need to uncheck the "Consume Available Usage" checkbox every time you activate it or uncheck "Uses Prompt" and manually adjust the uses from the actor sheet. It would be nice to have a button  allowing for uses to be consumed from the chat card.

Whether or not usage has been consumed should be tracked by the chat card so this button only appears if no uses were already consumed, which should prevent the chat log from being filled up with unnecessary buttons during normal play and prevent confusion if the button appears even after uses have been consumed.

**Comment by krbz999** [comment]
> which should prevent the chat log from being filled up with unnecessary buttons during normal play

Though this would create a button for those items or features that never consume their own uses, like Channel Divinity, Ki, or magic items that hold charges only for their granted spells. Makes more sense to simply let those alternative actions consume the item's uses somehow.
