### ISSUE TITLE
Tooltips "sticking around" after middle mouse button are finicky

### ISSUE THREAD

**Issue by Krigsmaskine** [foundryvtt/dnd5e#3554]
In the new character sheet, it can be difficult to get "pinned" tooltips to hang around after middle mouse clicking. Particularly an issue with tooltips that exceed the usual hover text limit, like good ol' Krusk here. Here's a short recording to showcase. Blue highlight is middle mouse click, yellow is left.

[please stay.webm](https://github.com/foundryvtt/dnd5e/assets/39592771/589f66d6-28c5-4530-b184-af66ce6a7df2)

**Comment by etiquettestartshere** [comment]
In my testing, it seems if your cursor is far from where the tooltip appears, the tooltip has a higher chance of vanishing instantly when you middle click and then move towards it. The closer your cursor is to where the tooltip appears, the better chance of it remaining open after you middle click and move.

In my testing, in the case of the tooltips in the "pills-lg" class as shown above, reliable tool-tip staying behavior was replicated when the cursor began on the icon or left of it, but could not be replicated anywhere to the right of the icon. The above video also shows this behavior.

**Comment by arbron** [comment]
This is caused by a core bug that has already been fixed for V12.
