### ISSUE TITLE
Missing Maximum uses formula

### ISSUE THREAD

**Issue by DAxBaph** [foundryvtt/dnd5e#3557]
![foundry formula error](https://github.com/foundryvtt/dnd5e/assets/169609065/5b7509a4-ffa0-4b73-a2ab-08e1c36906a0)
I'm new to Foundry and i'm having an issue w/ spell slots and ki formula. When i create a character w/ either i'll get a warning "The Maximum uses formula within (instert spell or Ki) has references to missing data: @classes.(class).levels" tried google but i just got a bunch of people asking for modules about classes. Created through the D&D SRD Content. Everything is up to date and everything was created on the current versions of foundry and dnd5e.

**Comment by unsoluble** [comment]
You’re using class features on actors that don’t have any class levels (NPCs don’t have classes). Hit up the #dnd5e channel on the discord to dig into this further (and for all future general troubleshooting of the game system).
