### ISSUE TITLE
Unable to add a Halfling to a new character

### ISSUE THREAD

**Issue by farling42** [foundryvtt/dnd5e#3571]
Foundry 12.322
dnd5e 3.1.2
No modules

1 - In an empty world, create an actor
2 - Click on the "Add Race" button
3 - Drag "Lightfoot Halfling" onto the Actor sheet
4 - Press the NEXT button on each page of the Advancement dialog that appears.
5 - See an error occur on clicking NEXT on the third step (first error).

![image](https://github.com/foundryvtt/dnd5e/assets/17485384/b89884aa-1642-4246-ae15-27fc2d763c98)

6 - See an error occur on clicking COMPLETE on the fourth step (second error).

![image](https://github.com/foundryvtt/dnd5e/assets/17485384/6637cebb-a9f9-4b48-85bf-e554512182b6)

The second-to-last page of the Advancement dialog does not show any content.

![image](https://github.com/foundryvtt/dnd5e/assets/17485384/f3c54506-f059-4bfe-9abb-8b51ff82b65e)

**Comment by arbron** [comment]
Known and already fixed issue in 3.2, 3.1 is not fully compatible with V12
