### ISSUE TITLE
Add 'Burning' as a pseudo condition

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3582]
Nice to have due to _Alchemist's Fire_.

**Comment by Rabulias** [comment]
Could also be useful for the Fire Elemental entering a creature's space. Though it is odd that _alchemist's fire_ does only 1d4 and requires an action and a DC10 Dexterity check to put out the flames, while the fire elemental does 1d10 and requires only an action to douse the fire.

**Comment by Rymliez** [comment]
I think adding the "Corroding" effect to the DOT caused by Tasha's Caustic Brew spell would be a good idea.

**Comment by Rabulias** [comment]
Perhaps broaden this suggestion to a more generic effect that applies at the start of turn, with variables for:
- Amount of damage
- Type of damage
- Saving throw (None, Save ends, Save for half, etc.), including DC and ability
- Duration

Even further, supporting a successful skill check to end an effect, like Athletics and/or Acrobatics to escape a Grapple?

**Comment by Rabulias** [comment]
Burning is a specific Hazard in the 2024 PHB. It inflicts 1d4 fire damage at the start of the creature's turn until it is extinguished.

I would also note that it clarifies that taking an action to put out the flames on oneself normally requires going Prone. Stop, drop, and roll!
