### ISSUE TITLE
Add setting to allow NPCs to ignore the encumbrance rules

### ISSUE THREAD

**Issue by DrTravisProthro** [foundryvtt/dnd5e#3598]
Currently, the game system allows you to use the encumbrance or variant encumbrance settings, which works great except for the two instances detailed below.

1. NPC characters set to act as vendors and use the normal commoner, noble, or guard with their normal stat block cannot have in their possession more than 1 set of heavy armor or a handful of weapons with it flagging them as encumbered.
2. Even when modifying a player or NPC maximum encumbrance to add +100 or +1,000, they are still flagged as over-encumbered despite their max encumbrance being 5,000 lbs.
 
I believe the encumbrance tracker calculates based on their strength and then passes that score to the checker which happens independent of their max encumbrance score that shows on their sheet and is modified via code. Needless to say unless I am adding +100 to their strength, modifying their max encumbrance does not affect the checker.

Can we get an override for NPCs or potentially have the checker read their max score and not run directly off the str calculation?

**Comment by Rabulias** [comment]
Using the current Actors to represent a vendor or store is a necessary kludge for the time being. IMO, we need a specialized sheet for this. Whether from DND5E core or from a module is up for debate.

In the meantime, you can make a container with zero weight, enormous capacity, and weightless contents. Then name it "Storefront" and put the vendor's goods within it.
