### ISSUE TITLE
Internet link shows it is closed

### ISSUE THREAD

**Issue by Gabemedina86** [foundryvtt/dnd5e#3620]
Foundry Virtual Tabletop: Version 12 Stable, 12.324
Game System: dnd5e, 3.2.0
Active Modules: 11
Performance Mode: 2

OS: Windows 15.0.0 x86 (64-bit)
Client: Not(A:Brand/24.0.0.0
GPU: ANGLE (Intel, Intel(R) Arc(TM) A750 Graphics (0x000056A1) Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 2880 x 2880 | Grid Size: 96 | Padding Percentage: 0.25
Walls: 94 | Ambient Lights: 26 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 7
Largest Texture: 1920 x 2158 "http://localhost:30000/rae-ema-gust5.jpg"

Actors: 190 | Items: 13 | Journal Entries: 6 | Rollable Tables: 1 |
Playlists: 2 | Compendium Packs: 24 | Chat Messages: 0

World Scripts: 

/* -------------------------------------------- */
/*  World Data                                  */
/* -------------------------------------------- */

Actors: 190 | 3 MB
CardStacks: 0 | 675 B
Messages: 0 | 42 kB
CombatEncounters: 2 | 3 kB
FogExplorations: 1 | 671 kB
Folders: 16 | 5 kB
Items5e: 13 | 58 kB
Journal: 6 | 26 kB
Macros: 2 | 4 kB
Playlists: 2 | 9 kB
RollTables: 1 | 2 kB
Scenes: 14 | 175 kB
WorldSettings: 41 | 19 kB
Users: 5 | 5 kB

/* -------------------------------------------- */
/*  Compendium Data                             */
/* -------------------------------------------- */

"world.new-compendium-19": 346 Items | 514 kB
"world.gunslinger-items": 22 Items | 19 kB
"world.race": 0 Actors | 675 B
"world.more-items": 170 Items | 226 kB
"dnd5e.heroes": 12 Actors | 416 kB
"dnd5e.monsters": 331 Actors | 2 MB
"dnd5e.items": 872 Items | 844 kB
"dnd5e.tradegoods": 23 Items | 14 kB
"dnd5e.spells": 319 Items | 411 kB
"dnd5e.backgrounds": 3 Items | 7 kB
"dnd5e.classes": 12 Items | 61 kB
"dnd5e.subclasses": 12 Items | 20 kB
"dnd5e.classfeatures": 235 Items | 202 kB
"dnd5e.races": 34 Items | 48 kB
"dnd5e.monsterfeatures": 252 Items | 173 kB
"dnd5e.rules": 20 Journal Entries | 374 kB
"dnd5e.tables": 31 Rollable Tables | 46 kB
"fa-battlemaps.maps": 159 Scenes | 8 MB
"item-piles.item-piles-merchant-tables": 13 Rollable Tables | 162 kB
"item-piles.item-piles-custom-items": 7 Items | 30 kB
"item-piles.item-piles-macros": 1 Macros | 4 kB
"michaelghelfi.playlists": 2 Playlists | 8 kB
"monks-active-tiles.active-tile-macros": 10 Macros | 9 kB
"music-d20-sampler.playlists": 4 Playlists | 4 kB

/* -------------------------------------------- */
/*  Active Modules                              */
/* -------------------------------------------- */

dice-calculator | 2.1.9 | "Dice Tray" | "https://github.com/mclemente/fvtt-dice-tray/releases/latest/download/module.json"
dice-so-nice | 4.6.10 | "Dice So Nice!" | "https://gitlab.com/riccisi/foundryvtt-dice-so-nice/-/raw/master/module/module.json"
fa-battlemaps | 1.0.59 | "Forgotten Adventures Battlemaps" | "https://raw.githubusercontent.com/Forgotten-Adventures/FA_Battlemaps/main/module.json"
item-piles | 2.9.1 | "Item Piles" | "https://github.com/fantasycalendar/FoundryVTT-ItemPiles/releases/latest/download/module.json"
lib-wrapper | 1.12.13.1 | "libWrapper" | "https://github.com/ruipin/fvtt-lib-wrapper/releases/latest/download/module.json"
michaelghelfi | 1.4 | "Michael Ghelfi Studios Audio Pack" | "https://foundryvtt.s3-us-west-2.amazonaws.com/modules/michaelghelfi/module.json"
monks-active-tiles | 11.27 | "Monk's Active Tile Triggers" | "https://github.com/ironmonk88/monks-active-tiles/releases/latest/download/module.json"
music-d20-sampler | 1.0.1 | "Music d20 Sampler" | "https://foundryvtt.s3-us-west-2.amazonaws.com/modules/music-d20-sampler/module.json"
polyglot | 2.4.11 | "Polyglot" | "https://github.com/mclemente/fvtt-module-polyglot/releases/latest/download/module.json"
socketlib | 1.0.13 | "socketlib" | "https://raw.githubusercontent.com/manuelVo/foundryvtt-socketlib/master/module.json"
tagger | 1.4.5 | "Tagger" | "https://github.com/fantasycalendar/FoundryVTT-Tagger/releases/latest/download/module.json"

**Comment by unsoluble** [comment]
Hi there, this is not the forum for troubleshooting your connection — please head to the #install-and-connection channel on the Foundry discord server.
