### ISSUE TITLE
Vehicles don't track their cargo weight anymore

### ISSUE THREAD

**Issue by flogiston1** [foundryvtt/dnd5e#3623]
Adding items to vehicle cargo doesn't add their weight to the weight bar at the bottom of the vehicle sheet anymore after latest updates (v12 stable and dnd5e 3.2.0). It was still working on fvtt v11.315 with dnd5e 3.1.2

**Comment by arbron** [comment]
Cargo tracking is still working fine, but it doesn't seem to be taking equipment weight into account.

**Comment by arbron** [comment]
It is also massively over-counting the weight of coins, so that will need to be fixed.
