### ISSUE TITLE
Package warnings after v12 update

### ISSUE THREAD

**Issue by Darrkstarr** [foundryvtt/dnd5e#3628]
Almost all my modules and game systems tell me the same thing about the manifest containing unknown keys:

![image](https://github.com/foundryvtt/dnd5e/assets/159729381/9a3eba7b-4a03-4ae8-8980-322640ee591b)

It looks like everything is still working after the update. Any idea whats causing these warnings?

**Comment by unsoluble** [comment]
These modules are simply using an outdated manifest format, and will need to be updated (by their devs) to clear the warning. You can ignore.
