### ISSUE TITLE
Calling `prepareData` on an actor with owned sheet item with max uses causes crash

### ISSUE THREAD

**Issue by TheGiddyLimit** [foundryvtt/dnd5e#3630]
**env:**

- Foundry v12.324
- dnd5e 3.2.0

**expected:**

no crash when calling `.prepareData`; from the docs: "The work done by this method should be idempotent. There are situations in which prepareData may be called more than once." 

**log:**

```log
dnd5e.mjs:10117 Problem preparing the Maximum Uses formula within Test Item. TypeError: formula.replace is not a function
    at replaceFormulaData (dnd5e.mjs:2545:21)
    at FeatData._prepareFinalFormula (dnd5e.mjs:10111:38)
    at FeatData.prepareFinalActivatedEffectData (dnd5e.mjs:10053:10)
    at FeatData.prepareFinalData (dnd5e.mjs:42173:10)
    at Item5e.prepareFinalAttributes (dnd5e.mjs:12251:35)
    at dnd5e.mjs:17534:37
    at EmbeddedCollection.forEach (foundry-esm.js:5020:9)
    at Actor5e.prepareData (dnd5e.mjs:17534:16)
    at <anonymous>:20:12
```

**repro:**

```js
(async () => {
	const act = await Actor.create({
		name: "Test",
		type: "npc",
	});
	await act.createEmbeddedDocuments(
		"Item",
		[
			{
				name: "Test Item",
				type: "feat",
				system: {
					"activation.type": "none",
					"uses.per": "sr",
					"uses.max": 1,
				}
			}
		]
	);

	act.prepareData();
})();
```

For my use-case I can just call `.reset()` instead; reporting just in case there's some underlying issue which could use visibility.

**Comment by arbron** [comment]
You will have to call reset anyway, because despite what the official Foundry documentation says, calling `prepareData` will never be idempotent even in core because it calls `applyActiveEffects`, which if called multiple times will make cumulative changes to actor data.
