### ISSUE TITLE
Druid Wild Shape feature has no max uses

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3637]
This seems invalid in v12

https://github.com/foundryvtt/dnd5e/blob/3.2.x/packs/_source/classfeatures/druid/druid-features/wild-shape.json#L43

**Comment by Fyorl** [comment]
Ternaries are not supported by the new parser, it only supports binary operators. So we either have to convert this to some other function like `2 + floor(min(@classes.druid.levels, 20) / 20) * 97`, or we add something like a `ternary` function to `CONFIG.Dice.functions`. I think Dominate Monster also has a ternary in its duration.
