### ISSUE TITLE
Enchantment not transferring bonus damage to weapon

### ISSUE THREAD

**Issue by Galphanore** [foundryvtt/dnd5e#3645]
![Holy Weapon Effect](https://github.com/foundryvtt/dnd5e/assets/4059786/e4f27c13-ae71-4b0b-aaa5-51e405c77be8)
If you add an effect to a weapon via an enchantment it is not transferring bonus damage properly. In the above effect, if the effect is put directly on a character it adds the 2d8 radiant damage to all melee weapon attacks. If added via an enchantment to a weapon, it does nothing. The "name" and "system.properties" effects update properly, but not the "system.bonuses.mwak.damage" attribute.

**Comment by krbz999** [comment]
If you wish to use `system.bonuses.mwak.damage`, which is an actor property, you will need to create a "rider effect" that applies to the actor.

If you just want the enchanted weapon to deal additional damage, use this instead:
```
system.damage.parts | Add | [["2d8", "radiant"]]
```

**Comment by Galphanore** [comment]
> If you wish to use `system.bonuses.mwak.damage`, which is an actor property, you will need to create a "rider effect" that applies to the actor.
> 
> If you just want the enchanted weapon to deal additional damage, use this instead:
> 
> ```
> system.damage.parts | Add | [["2d8", "radiant"]]
> ```

Thank you, that works perfectly! Is there somewhere I can see a list of what all the attributes are? I checked [Active Effects Guide](https://github.com/foundryvtt/dnd5e/wiki/Active-Effect-Guide) but didn't find anything, it doesn't include the ".parts" bit.

**Comment by krbz999** [comment]
No AE guide for item-specific properties yet.

**Comment by Galphanore** [comment]
Ok, thanks.
