### ISSUE TITLE
Dynamic Token Ring Setting on Prototype Token Doesn't Stay Enabled

### ISSUE THREAD

**Issue by ejwright** [foundryvtt/dnd5e#3646]
The Dynamic Token Ring Setting on Prototype Token Doesn't Stay Enabled, you can set it -- say updated token and save it. When you pull the token onto the canvas the token loads without it being set. You can then enable on the instance of the token on the canvas and it works fine.

**Comment by Fyorl** [comment]
Are you on v12? This might be a core software issue: https://github.com/foundryvtt/foundryvtt/issues/11030

**Comment by ejwright** [comment]
I am, I'll chase it down there
