### ISSUE TITLE
Display enchantment target limit & enchanted item count

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/dnd5e#3647]
It would be useful if a single enchantment could have a limited amount of objects it could enchant. Few things come to mind:
- A spell that lets you enchant one weapon, and an additional weapon for every higher level the spell is cast.
- PHB Eldritch Knight can have up to two bonded weapons.
- Multiple (up to an ammount) Pieces of Ammunition for poisons?

**Comment by arbron** [comment]
> It would be useful if a single enchantment could have a limited amount of objects it could enchant.

You can currently enchant as many items as you'd like. The `target` field on items was modified to take a formula so you can use that to specify how many items can be enchanted. We'll probably add a visible "Enchanted 1/2" thing to the chat card to track how many items can be enchanted, but probably not hard-restrict it.

**Comment by Zanderaf** [comment]
Oh I did not know about that at all! Yea tracking for it on the card would be a nice addition.
