### ISSUE TITLE
Cannot edit items in characters sheets

### ISSUE THREAD

**Issue by VikInks** [foundryvtt/dnd5e#3655]
Since last update of FoundryVTT, I cannot edit items into character sheets

![image](https://github.com/foundryvtt/dnd5e/assets/28891578/2bef5117-b0f9-4cf2-bc19-9a3e02cbc71c)

The edit button doesn't trigger, when clicked, any popup to create or edit a new item or existing item

**Comment by unsoluble** [comment]
Please head to the Foundry discord server for general troubleshooting. (Disable all your modules to test first, as always.)
