### ISSUE TITLE
Wrong default item artwork

### ISSUE THREAD

**Issue by EdwarDDay** [foundryvtt/dnd5e#3657]
I found an issue in DnD5e when used in foundry v12. When I create a new background (or any other item) I just get the white bag as item icon. In v11 I get an icon which shows a path.

V11:
<img width="558" alt="Dnd5e v11 new background" src="https://github.com/foundryvtt/dnd5e/assets/4127904/1f1f95b3-bce5-4247-9287-f782f79c55f6">

V12:
<img width="560" alt="Dnd5e v12 new background" src="https://github.com/foundryvtt/dnd5e/assets/4127904/9e719c66-f754-45ad-80ee-b28723fe4658">

**Comment by Fyorl** [comment]
Seems to be a core bug: foundryvtt/foundryvtt#11074
