### ISSUE TITLE
Update various weapon descriptions and images for accuracy

### ISSUE THREAD

**Issue by CodeMoWerser** [foundryvtt/dnd5e#3669]
### Blowgun
Blowgun icon is a wooden stick, rather than a blowgun (not that we specifically have a blowgun icon, but we have something better).
- Change the icon to use something more appropriate. ex: `icons/commodities/tech/pipe-metal.webp`
### Club
The club uses a heavily spiked icon which doesn't match the bludgeoning damage the weapon does.
- Change the icon to something more appropriate. ex: `icons/weapons/clubs/club-simple-black.webp`
### Flail
The flail is using the morningstar icon, and presents the item as spiked, while the flail actually deals bludgeoning.
- Change icon of the flail to something more appropriate. ex: `icons/weapons/maces/flail-studded-grey.webp`
- Change the description to something more appropriate. ex: "A heavy iron ball attached to a stout wooden shaft with a heavy chain, allowing it to deal devastating damage at the end of wide, sweeping swings."
### Mace
The mace in the system has a description and icon that doesn't match the mechanical nature of the weapon. 
- Change the icon of the Mace to something more appropriate. ex: `icons/weapons/maces/mace-flanged-steel-grey.webp`
- Change the description of the Mace to something more appropriate. ex: "A heavy metal head mounted to the end of a sturdy haft meant to deliver powerful, crushing blows capable of shattering armor and bone alike."
### Pike
The pike has an icon more fitting of a pole-axe, not a long piercing spear.
- Change the icon to something more fitting. Ex: `icons/weapons/polearms/pike-flared-red.webp`
### Trident
The trident has an icon that is three spears, rather than a proper trident, which foundry now has.
- Change the icon to something more fitting. Ex: `icons/weapons/polearms/trident-silver-blue.webp`

**Comment by Padhiver** [comment]
@arbron
Quick comment ! :) Thank you for accepting the PR.
