### ISSUE TITLE
Character sheet - Container image scaling (minor visual issue)

### ISSUE THREAD

**Issue by onesockdocs** [foundryvtt/dnd5e#3670]
The inventory tab on the new character sheet has a minor scaling issue on the container bar at the top (sacks, backpacks, bags of holding, etc.) that causes jaggies/artifacts (see blue bag in pictures below).  

In `<ul class="containers unlist">` the `<li>` enforces an aspect ratio of 1.
Since the nested child `<div>` (bag fullness bar) has a set height of 6px, the `<img>` with `object-fit: cover` will scale to the remaining space and distort (76x70).

Hacking around in the css, removing the `aspect-ratio` on the `<li>` and changing the `max-width` from 78 to 71 will force the correct sizing and keep the containing `<ul>` and the adjacent encumbrance card matching at 77px in height.  This may need a better solution if the structure is more dynamic / causes issues in other portions of the app.

![image](https://github.com/foundryvtt/dnd5e/assets/56654626/2bee7925-38cb-4f37-b608-c0eef127920b)
![image](https://github.com/foundryvtt/dnd5e/assets/56654626/8f4ceb8f-0b67-4416-8e7d-d9e3e510ac28)

Thanks!

**Comment by Fyorl** [comment]
There might be some weird interaction with `aspect-ratio: 1` and `object-fit: cover`, but it looks more like the general case of Chrome's poor downscaling algorithm at work in the first screenshot. `object-fit: cover` should allow the image to retain its inherent aspect ratio regardless of the dimensions of the container, so it's not clear to me how the proposed steps produce a better result. Is it the case across many different images of different sizes?
