### ISSUE TITLE
Allow "Award (Coins)" to Party  if "Track Experience" is turned off

### ISSUE THREAD

**Issue by Shareenx** [foundryvtt/dnd5e#3671]
If you have a party in a group, and track XP is turned off, you cannot award coins. 
I'd love to distribute coins with the new "Group" mechanic AND use milestones

**Comment by arbron** [comment]
That should already be the case in `3.2.0`, what version are you running?

**Comment by Shareenx** [comment]
=D 3.1.2, just noticed that I have an update pending!

Thanks!!!
