### ISSUE TITLE
Toggle Floating Damage/Healing numbers

### ISSUE THREAD

**Issue by DennisNick2026** [foundryvtt/dnd5e#3689]
Please make a setting to toggle this feature.

I understand its usefulness but in my experience, it gets in the way as players just end up counting numbers or figuring out resistances on the spot. It also works to undermine any potential secret abilities or hidden healing values as it will just broadcast this to all who are watching.

**Comment by unsoluble** [comment]
Core settings > Scrolling Status Text.

**Comment by DennisNick2026** [comment]
> Core settings > Scrolling Status Text.

You are a god, I will venerate you for aeons.

**Comment by unsoluble** [comment]
Acceptable.
