### ISSUE TITLE
[BUG] Line Breaks and Paragraphs after embeds do not act as expected

### ISSUE THREAD

**Issue by SLinxTheFox** [foundryvtt/dnd5e#3690]
**_V11 stable 315
DnD 5e 3.1.2
Tested without any modules active_**

---

# Issue
Text and especially other embeds that follow an embed do not act as expected after hitting save in any text area

# Examples
The below pictures show the differences in the text editor vs the saved text document using 3 elven features. the first two features being embedded and the third being not embedded. This is because they react differently to the same formats.

### Same Line

Titles that are on the same line as the embed in edit mode
![1 (same line, edit mode)](https://github.com/foundryvtt/dnd5e/assets/44953602/86d4f257-00d0-45f3-abff-7b2a135013f9)
Produce this line break spacing with the embed while somehow pushing the next line down more, but paragraph like spacing for the text, but pushing down its next line even further
![2 (same line)](https://github.com/foundryvtt/dnd5e/assets/44953602/87b6e895-8588-436b-96cf-f9c15320a641)

### Line Break

Titles that have had "shift+enter" applied for a line break in edit mode
![3 (shift enter, edit mode)](https://github.com/foundryvtt/dnd5e/assets/44953602/031b5d00-3301-4682-8e3f-6e6dbd6ff7cd)
Produce these similar results
![4 (shift enter)](https://github.com/foundryvtt/dnd5e/assets/44953602/6336a432-6bb8-44bb-8df2-6b7438f284a4)

### Paragraph

Titles that have had just "enter" applied for a new paragraph in edit mode
![5 (enter, edit mode)](https://github.com/foundryvtt/dnd5e/assets/44953602/8567ab17-ad05-424a-86be-f90346300189)
Produce more normal results, but "trance" looks line broken instead of a paragraph
![6 (enter)](https://github.com/foundryvtt/dnd5e/assets/44953602/d54cd0f2-64ea-4b96-854c-2cb790ee90c9)

**Comment by Fyorl** [comment]
In v11, embeds are unable to re-parent themselves so we resort to some CSS 'hacks' which may not cover every case. We need to check if the backported embeds are still taking precedence in v12 or not (if they are, we should make a change to prevent that), and then check if the v12 embeds still exhibit this issue. If they do, it would require a core software change.
