### ISSUE TITLE
Summoning right-click behavior

### ISSUE THREAD

**Issue by MaxPat931** [foundryvtt/dnd5e#3691]
Using right-click will temporarily place a token during the summon process, and it will be removed once completed.
This might be working as intended, but either making the RC placed tokens visually different, or totally cancelling further summons might be preferred

Yellow - LC, Blue - RC

https://github.com/foundryvtt/dnd5e/assets/86370342/220420e4-effb-4453-a99f-4280fe8a742b

**Comment by arbron** [comment]
Known bug, already fixed for `3.2.1`: https://github.com/foundryvtt/dnd5e/issues/3659
