### ISSUE TITLE
[Feature request] Different translation keys for damage.

### ISSUE THREAD

**Issue by Padhiver** [foundryvtt/dnd5e#3693]
Hello !
I don't know if it's possible, but it would be cool to have different translation keys for the damage.

As it stands, for example, if I use a fire damage enrichisser (fire=feu in my language), I'm going to have written ‘1d10 feu’, and that's really not very pretty in French. If we could have ‘1d10 dégâts de feu’ it would be much nicer.

And we can't just change the current keys, as they're useful for the simple translation of the word.

**Comment by maxobremer** [comment]
Why not write it as [[/damage 1d10 feu]]{1d10 dégâts de feu}
that way you have the functionality of the enricher as it stands but the text shown is whatever you want. Hell you could even use [[/damage 1d10 feu]]{1d10 potatoes} if you really want, it will just change the text and how it looks to fit your needs while mechanically just rolling the fire damage you want or whichever damage type you need.

**Comment by Padhiver** [comment]
> Why not write it as [[/damage 1d10 feu]]{1d10 dégâts de feu} that way you have the functionality of the enricher as it stands but the text shown is whatever you want. Hell you could even use [[/damage 1d10 feu]]{1d10 potatoes} if you really want, it will just change the text and how it looks to fit your needs while mechanically just rolling the fire damage you want or whichever damage type you need.

Oh I didn't know you could do that with damage enrichiser, it's all good so !

**Comment by arbron** [comment]
I will not, when writing these enrichers you should always use the non-translated keys in the enricher, so it should be `[[/damage 1d10 fire]]` not `[[/damage 1d10 feu]]`. This will still display properly translated, but we need the base damage keys to be the same otherwise it will not be able to properly apply damage resistances/immunity.
