### ISSUE TITLE
Drag spell from spell list journal

### ISSUE THREAD

**Issue by Korghen** [foundryvtt/dnd5e#3694]
I'm not able to drag a spell from the new spell list Journal Entry (Foundry 11.315 and DnD 3.2.0, with no module enabled).
When I try to do it, it selects like text.
![Sans titre-1](https://github.com/foundryvtt/dnd5e/assets/107515698/beeae04e-7185-4bf4-97a1-4760fd2e9515)

**Comment by arbron** [comment]
Known issue, will be resolved in `3.2.1`: https://github.com/foundryvtt/dnd5e/issues/3604
