### ISSUE TITLE
Enchantments not respecting unchecked "Apply to self when item applies to target effects" flag

### ISSUE THREAD

**Issue by Galphanore** [foundryvtt/dnd5e#3697]
If you create an enchantment with a secondary effect, when you use the enchantment the secondary effect is transferred to the actor holding the now enchanted object regardless of whether the "Apply to self when item applies to target effects" flag is checked. 

Once the enchantment is in effect, the flag works properly, but as the enchantment is first cast it should not be applied to the actor. In the below enchantment, it adds psychic damage to the weapon (which works fine) and the secondary effect applies "Fear" on hit. Right now, no matter what I do, as the spell is cast the person holding the weapon gets hit with Fear. After that, the people they attack are ALSO targets of fear.

![ApplyToSelf](https://github.com/foundryvtt/dnd5e/assets/4059786/6c473339-6900-4f4f-8c41-bcd741d014d9)

![Vengeful](https://github.com/foundryvtt/dnd5e/assets/4059786/12fa8299-f851-4337-866e-5130a91ea1cc)

![VengefulFear](https://github.com/foundryvtt/dnd5e/assets/4059786/0ee070cd-4412-406f-a97a-cd46ce2c9f76)

**Comment by pgervais70** [comment]
This checkbox is a DAE checkbox not a dnd5e one.
You should report that on Posney’s Foundry Automation Discord server
