### ISSUE TITLE
Primary spellcasting is not set on characters when adding or changing a class

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#3701]
- make `character` actor
- set their wisdom to 20.
- add a spell with a melee spell attack (see that it has an attack bonus of +1, which is expected)
- add cleric class from SRD
- look at spells tab (see that spell still has only attack bonus of +2 due to PB, wisdom is ignored).

Whether a bug or not, it would be nice if an actor has only a single spellcasting attribute (or a single class) that their primary one is set to that.

**Comment by davidR1974** [comment]
strangely enough it seems to work if the class has Intelligence as primary spellcasting...
