### ISSUE TITLE
Actor Artwork Not Updating / Image Browser Not Opening

### ISSUE THREAD

**Issue by IonPickaxe43** [foundryvtt/dnd5e#3710]
Ran into this issue, running 5e 3.2.0, Foundry version 12 stable 325. 

Up until the last update I've been able to open an NPC (or any other) actor sheet from my sidebar, click their sheet's portrait, and update the token art through the image browser. 

I am now seemingly unable to do so (image browser does not open from the actor sheet portrait anymore) and have yet to find a way to update how the actor's art appears in the sidebar and in their sheet.

![image](https://github.com/foundryvtt/dnd5e/assets/158988444/4ac9735c-23f8-4029-b177-9d3e2f095d2f)
(In the image above, Commandant Neave and Commandant Nadia both have the same appearance in the sidebar and actor sheets despite having different image sources for any art.)

Upon further testing, I am now unable to update any of the sidebar art that appears (nor the art on each actor's sheet). If I adjust the prototype token art source, it shows the tile correct once placed on the table, but before then it is not visually updated. I also tried creating a new actor but was unable to adjust the art on it either. 

I've restarted my hosting computer and Foundry multiple times trying to remedy this issue before I submitted this note.

![image](https://github.com/foundryvtt/dnd5e/assets/158988444/d347af89-2e30-4c0d-8110-7fcf0a67a68b)
(In the image above, Commandant Nadia's placed tile appears correctly while her sidebar image and sheet image are still both incorrect.)

Please advise if I'm doing something wrong, if a process updated, or if this is a true bug. I tried finding another issue with this but was unable to locate any others.

**Comment by unsoluble** [comment]
Please disable all modules, and then head over to the Foundry discord server for general troubleshooting support.

**Comment by IonPickaxe43** [comment]
Thanks @unsoluble, it was definitely one of my modules. Now the fun begins.
