### ISSUE TITLE
Configure Scene tab is not closing

### ISSUE THREAD

**Issue by KeviSoul69** [foundryvtt/dnd5e#3712]
In "Configure Scene:" tab after editing the scene light / dimension / permissions 
click on save it doesn't close 
click on the X it doesn't close 

My only fix for it is to F5 but is driving me insane while editing the scenes.
Foundry v 12.325

**Comment by unsoluble** [comment]
Please disable all modules. If it's still an issue, head over to the #troubleshooting channel on the Foundry discord server, for all general troubleshooting.

**Comment by KeviSoul69** [comment]
I started tinkering with the modules is not from base foundry now i am just activating module by module trying to see with one is at fault
