### ISSUE TITLE
[Bug] Loot chatProperties reference to weight embeds [object Object] instead of the weight value

### ISSUE THREAD

**Issue by kgar** [foundryvtt/dnd5e#3713]
The Loot chatProperties getter in /module/data/item/loot.mjs is using `this.weight` instead of `this.weight.value`, creating the text "[object Object] lbs."

![image](https://github.com/foundryvtt/dnd5e/assets/4632129/4aa30348-1a40-45cd-909f-6b0c9afc03af)

![image](https://github.com/foundryvtt/dnd5e/assets/4632129/0ada92e3-4384-4ca6-a47f-8115bb466dfc)

![image](https://github.com/foundryvtt/dnd5e/assets/4632129/34c9e8f0-a8a3-405a-8351-b306c5622611)

**Comment by imivoltz** [comment]
Hey there! Coming back to this after the latest update (3.2.1) it still shows up as lbs. despite using the metric weight system option.
