### ISSUE TITLE
New character sheet: missing `info` button

### ISSUE THREAD

**Issue by sentientmonkey** [foundryvtt/dnd5e#3731]
I know that the new character sheets have tooltip descriptions, but what's missing is the `info` button that the Legacy Character Sheet has. As a DM, it's handy to be able to share a spell (or feature) description with everyone in chat, especially when the rules are vague and we'd like to review. Without the `info` button, I don't have any quick way of sharing that rule in chat for everyone.

Is there a way we can get to this without having to toggle back to the legacy character sheet?

Example on new character sheet:
<img width="851" alt="Screenshot 2024-06-11 at 9 47 47 PM" src="https://github.com/foundryvtt/dnd5e/assets/9032/c5351717-bf90-40cb-80e8-8fad3637e049">

Example on legacy character sheet:

<img width="851" alt="Screenshot 2024-06-11 at 9 48 19 PM" src="https://github.com/foundryvtt/dnd5e/assets/9032/114827c3-20d7-4899-99c3-2b639b1c9187">

Clicking `info` displays the following in chat:
<img width="273" alt="Screenshot 2024-06-11 at 9 48 45 PM" src="https://github.com/foundryvtt/dnd5e/assets/9032/6fafa0d3-0a05-404a-b3cf-6fc1ad182348">

**Comment by arbron** [comment]
Those three buttons ("Standard Roll", "Damage", and "Info") are from a module. The standard way to share something with chat is to just click its name (and uncheck consumption if necessary)

**Comment by sentientmonkey** [comment]
We use [midi-qol](https://foundryvtt.com/packages/midi-qol) to help automate rolls and saves, so clicking the spell/weapon/feature uses it automatically, which makes clicking to share a bit more awkward.

I'm not sure what other module could be affecting this - I see the same UX when I disable midi-qol and look at Monster or Legacy Character Sheets.

**Comment by unsoluble** [comment]
If a module you're using is making it hard to do a thing that's easy to do in the base game system, probably should take this up on that module's repo.

**Comment by Rabulias** [comment]
They are definitely from Midi QOL.

**Comment by tposney** [comment]
Those buttons are definitely from midi-qol - I know I put them there - and they do not show up with midi disabled. 

I've not added those to the new dnd5e character sheet yet.
Please close the issue as it's not a dnd5e issue.
