### ISSUE TITLE
TokenPlacement.place() expects prototype token to have a parent, but it (probably) won't

### ISSUE THREAD

**Issue by roth-michael** [foundryvtt/dnd5e#3735]
With a change in 3.2.1:
```diff
- if ( placement ) placements.push(placement);
- else obj.clear();
+ if ( placement ) {
+   const actorId = placement.prototypeToken.parent.id;
+   uniqueTokens.set(actorId, (uniqueTokens.get(actorId) ?? -1) + 1);
+   placement.index = { total: total++, unique: uniqueTokens.get(actorId) };
+   placements.push(placement);
+ } else obj.clear();
```
`placement.prototypeToken.parent.id` is expected to return the actor id. I _think_ this can just be `placement.prototypeToken.actorId` - I don't think `placement.prototypeToken` will have a non-null `parent` property if it's created using an `Actor`'s `getTokenDocument()` function.

**Comment by roth-michael** [comment]
Upon further investigation, this may actually be an issue with the `getTokenDocument()` stripping out `parent`, as `actor.prototypeToken` _will_ have a `parent` property, but `actor.getTokenDocument()` won't.

**Comment by roth-michael** [comment]
Which (again, probably _most_ specifically) is in the `toObject()` function of the `PrototypeToken` class - it already has a `data["actorId"] = this.document?.id;` - might make sense (if deemed useful) to add `data["parent"] = this.parent;`

**Comment by arbron** [comment]
> Upon further investigation, this may actually be an issue with the `getTokenDocument()` stripping out `parent`, as `actor.prototypeToken` _will_ have a `parent` property, but `actor.getTokenDocument()` won't.

Config on `TokenPlacement` accepts an array of `PrototypeToken`s, but `getTokenDocument` returns a `TokenDocument`, which has a lot of the similar data but isn't the same. You should just be using `actor.prototypeToken` to get the data sent to token placement not `getTokenDocument`. The expected workflow is to use this system to get the placement, and then used the returned data as an input into `getTokenDocument` (so `actor.getTokenDocument(placement)`) which will return the token document with the correct position and rotation set.

**Comment by roth-michael** [comment]
Gotcha, perfect that makes sense. Thanks for the follow-up!
