### ISSUE TITLE
Cantrips that require concentration should not warn that you have no available spell slots

### ISSUE THREAD

**Issue by bentomhall** [foundryvtt/dnd5e#3741]
**Steps**
1. Create a cantrip that requires concentration. Or use the SRD version of guidance.
2. Add it to a spell-caster.
3. Click on the spell to cast it.

**Expected**
I get the spell popup, but no warnings about spell slots.

**Actual**
I get big warnings about not having the required spell slot...for a cantrip.

![guidance_details](https://github.com/foundryvtt/dnd5e/assets/6842442/5a79a8e9-5f11-41d8-ba85-46649ba67629)

Warnings: 
![image](https://github.com/foundryvtt/dnd5e/assets/6842442/e49d2bac-be88-4729-a97d-6248d834539f)

**Comment by bemdesign-er** [comment]
Additional info:
- This also occurs when a cantrip has an area of effect - e.g. setting the Target to 5 feet cube on a cantrip will also cause this  "You have no available spell slots with which to cast <cantrip name>".
