### ISSUE TITLE
Sheet "Level" display has un-substituted `aria-label`

### ISSUE THREAD

**Issue by TheGiddyLimit** [foundryvtt/dnd5e#3752]
![image](https://github.com/foundryvtt/dnd5e/assets/25264887/34b2c6c6-1398-4af2-b431-7d8bfb3ae50e)

![image](https://github.com/foundryvtt/dnd5e/assets/25264887/316b1d7a-5c39-4cdb-8169-5c7ac0655268)

`"DND5E.LevelNumber"`

**Comment by lovethebomb** [comment]
I'd like to take on this issue, post-completion :)
