### ISSUE TITLE
Add support for Emanation Area Effect

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/dnd5e#3791]
From the [preview article for spells](https://www.dndbeyond.com/posts/1762-4-key-changes-to-spells-in-the-2024-players)

> Emanation is a new area of effect, joining known types like Cone, Line, or Sphere. An Emanation spell extends in a straight line in all directions from a creature or object, and moves with them if the spell duration is longer than Instantaneous. Emanation differs from a Sphere in that the point of origin is not considered part of the area of effect. Known spells such as Thunderclap and Spirit Guardians are now classified as Emanation for their areas of effect.

**Comment by krbz999** [comment]
#1011
