### ISSUE TITLE
Migrating System from 3.2.0 to 3.2.1 gets stuck at "migrating 100%" and does not advance

### ISSUE THREAD

**Issue by sergioamendoeira** [foundryvtt/dnd5e#3797]
Greetings, I'm trying to upgrade the systems version in my Foundry, and i am getting stuck at message "migrating 100%". 

I have uninstalled all Add-ons modules from Foundry, have tried re-installing Foundry from scratch, but still getting an error.

I inlcude the error log from the last time i attempted this migration. 

Can you help me fix this issue?
[error.2024-07-03.log](https://github.com/user-attachments/files/16091001/error.2024-07-03.log)

**Comment by unsoluble** [comment]
Please head over to the #dnd5e channel on the Foundry discord server for all general troubleshooting.
