### ISSUE TITLE
Error while importing various items: Cannot read properties of undefined (reading 'length')  

### ISSUE THREAD

**Issue by vt-tom** [foundryvtt/dnd5e#3822]
Examples: Torch, Rations  

Error:  
Cannot read properties of undefined (reading 'length')  

Versions:  
- Foundry 12.328
- DnD5e 3.2.1

Screenshots:  
![grafik](https://github.com/user-attachments/assets/43b76a20-3f37-4af8-aa78-bd6388e97103)  
![grafik](https://github.com/user-attachments/assets/f6a91633-6a23-44fe-baf6-60dcb1ea3f12)

**Comment by Fyorl** [comment]
Try reinstalling foundry by downloading a fresh copy from the website.

**Comment by vt-tom** [comment]
That worked... strange this was a fresh v12 installation. I only did the update from 12.327 to 12.328 with the ui. But anyways, thanks for the help.
