### ISSUE TITLE
Number of attunement slots increases when leaving edit mode.

### ISSUE THREAD

**Issue by SittingHill** [foundryvtt/dnd5e#3823]
I have an effect that increases max attunement slots:

system.attributes.attunement.max || Add || +1

Every time that edit mode is toggle off on the new default character sheet, the attunement slots on that character sheet permanently increases by one. It starts at 4, and then after edit mode is left the attunement slots go up to 5.  The next time edit mode is toggled on and off it goes up to 6 and so on.

When the effect is removed, the additional attunement slots from this bug stay on the character sheet.

The attunement slots on the character sheet should stay at 4 and not increase each time edit mode is toggled off.

DND Version: 3.2.1
Foundry Version 11 build 315
hosted on Foundryserver.com

**Comment by SlamHammerfist** [comment]
I believe that this is actually working correctly, if you want it to be a static number make it this instead 
system.attributes.attunement.max || Override || 4

**Comment by SittingHill** [comment]
I don't believe so.  If this was correct behavior, that would be like if I had an effect that increased walking speed by 5ft. Then walking speed increased an additional 5ft every time that edit mode was toggled off.  

When the effect was removed the increased walking speed would remain.

**Comment by krbz999** [comment]
> I believe that this is actually working correctly, if you want it to be a static number make it this instead system.attributes.attunement.max || Override || 4

It is not intended. Common interactions with a sheet should not cause effects to apply themselves multiple times.
