### ISSUE TITLE
Diagonal Movement Rule BUG

### ISSUE THREAD

**Issue by javerth1** [foundryvtt/dnd5e#3840]
The optional diagonal movement DMG rule is not working.

**Comment by arbron** [comment]
What is your Foundry & DnD5e version?

**Comment by javerth1** [comment]
> What is your Foundry & DnD5e version?

Foundry V12.329 and DnD5e V3.3.0

**Comment by dev7355608** [comment]
We forgot the hide dnd5e's "Diagonal Movement Rule" setting in V12 (#3851), which doesn't do anything anymore. Now there's the core setting "Square Grid Diagonals". You'll need to set that to "Alternating (1/2/1)" if you want the DMG movement rules.
