### ISSUE TITLE
On the Design Direction for NPC sheets

### ISSUE THREAD

**Issue by Berlinia** [foundryvtt/dnd5e#3845]
Hi, whomever is reading this.

I have a general issue with the way the 5e system is handling NPC sheets (and has for the entirety of the foundry systems existence). In my opinion, NPCs represent the monsters the heroes fight, and should have sheets that represent that. I am curious, how often people actively use the inventory of an NPC, or the biography, rather than use other, more specialized, note taking programs for that. 

The overwhelming majority of enemy combatant sheets are never touched upon again, their entire purpose is to be fought, defeated and that's it. Core 5e "statblocks" display all the information, in a clear, concise manner. If I am running 4 different enemies, I can just glance at their statblocks, and see their features. Meanwhile, if I want to see an (N)PCs feature, they best way to actually do that right now, in the system is either use the feature and see it in the chat (which clogs the chat) or *edit* the feature. As a DM, I didn't care for the PC part, but for the creature part this is a big problem for me.

Furthermore, all monsters that are published by wizards, are already in statblock form. This creates a disconnect in designing monsters within foundry and the monsters readily available by WoTC. It used to be that my woes with the 5e systems NPC sheets, were covered by the module monster blocks. However, I don't think core functionality should be behind modules, and functional, easy to use NPC sheets, fall under core functionality for me. While the current sheet update looks gorgeous, this is done in my opinion at the expense of usability.

![image](https://github.com/user-attachments/assets/20a328a8-2536-4864-bd8b-7f6e6747b46e)
See in the above image for example. There is so much empty space here, and so much tabbing needed to do what you need to do. What spells does the mindflayer know? I don't know, need to go to the spells tab for that. What does magic resistance do (admitedly, nicely named). I need to click and open the feature. In the middle of combat, when you want to make snappy decisions to not waste time, I have found it actually quicker to open the 5e-style statblocks on a seperate screen, and just roll physical dice.

Thank you for reading this. I understand I might be alone with this, but I hope I gave you something to consider.

**Comment by thatlonelybugbear** [comment]
I agree on some of the points, like Spells being visible in one tab, but at least for the Magic Resistance point, hovering over should give you a better solution showing the description than opening the feature.

**Comment by MaxPat931** [comment]
It wasnt called out in the release notes, aside from the linked issue, but you can expand the item description in the sheet again with the square box icon to the right, in addition to viewing the description in the tooltip.

![image](https://github.com/user-attachments/assets/f789dc95-8f31-454c-9185-96e2291fe5ba)

**Comment by Berlinia** [comment]
> It wasnt called out in the release notes, aside from the linked issue, but you can expand the item description in the sheet again with the square box icon to the right, in addition to viewing the description in the tooltip.
> 
That's nice, . While that does fix some of the issues, the core problem I have is still the same. The requirement to expand each feature takes uncessesary time, and makes reading the statblock at a glance harder. That is a big improvement however.

**Comment by Fyorl** [comment]
> The requirement to expand each feature takes uncessesary time, and makes reading the statblock at a glance harder.

You do not need to expand each feature, only the ones that you need to reference 'at a glance'. For example, I already know how Legendary Resistance and Magic Resistance work, so I wouldn't need to expand them. This saves a lot more space compared to the printed stat blocks where every feature has its full text displayed without any option to hide them.

**Comment by TrofimSelbs** [comment]
> > The requirement to expand each feature takes uncessesary time, and makes reading the statblock at a glance harder.
> 
> You do not need to expand each feature, only the ones that you need to reference 'at a glance'. For example, I already know how Legendary Resistance and Magic Resistance work, so I wouldn't need to expand them. This saves a lot more space compared to the printed stat blocks where every feature has its full text displayed without any option to hide them.

Will it remember to stay that way between closing and opening foundry? Coz if yes - sweet! If no - it is more work to open them for each monster (especially for a pack of wolves where you have way too many tokens to expand each)

**Comment by Fyorl** [comment]
> Will it remember to stay that way between closing and opening foundry? Coz if yes - sweet! If no - it is more work to open them for each monster (especially for a pack of wolves where you have way too many tokens to expand each)

It will not. I originally planned for it when initially re-implementing this feature but it did not make the cut. Please feel free to raise a separate issue though so that it does not get lost.

**Comment by Berlinia** [comment]
> > The requirement to expand each feature takes uncessesary time, and makes reading the statblock at a glance harder.
> 
> You do not need to expand each feature, only the ones that you need to reference 'at a glance'. For example, I already know how Legendary Resistance and Magic Resistance work, so I wouldn't need to expand them. This saves a lot more space compared to the printed stat blocks where every feature has its full text displayed without any option to hide them.

The moment you run slighlly more complicated statblocks, this is just not the case anymore. I agree that an option to hide features would be useful, even for normal statblocks, but the default design imo should replicate the published wizards content as closely as possible.

**Comment by nschoenwald** [comment]
I agree completely with your issues and think this feature request would help without the developers having to redesign the whole sheet: https://github.com/foundryvtt/dnd5e/issues/3861

Having the actual text of the monster's features is very important while running them in combat. Hover-over functionality and having to expand every feature individually are no good substitutes because they create friction and make running combat more challenging for the GM. Running combat is already one of the most challenging duties of the GM and Foundry should be designed to help as much as possible.
