### ISSUE TITLE
In the NPC v2 sheet, clicking on an initiative additionally opens the token art.

### ISSUE THREAD

**Issue by Zarkoncheg** [foundryvtt/dnd5e#3856]
Foundry 12 329
DND 3.3.0
Clicking on initiative button causes showing NPC art.
No modules active.
![image](https://github.com/user-attachments/assets/44ac3b85-6053-4c64-9aa7-0802238dca4e)

**Comment by thatlonelybugbear** [comment]
Duplicate of #3850
