### ISSUE TITLE
Cartographer's Tools missing from Tools List

### ISSUE THREAD

**Issue by ctbritt** [foundryvtt/dnd5e#3864]
in DnD5e 3.3.0, cartographer's tools are missing from tools list. I added it back with this worldscript: 
```js
// Adds new Tool Proficiency for Cartographer's Tools
Hooks.once("init", () => {
  CONFIG.DND5E.toolIds.cartographer = "compendium objest uuid here";
});
```

**Comment by krbz999** [comment]
Seems to still be there. Here's the config object with cartographer.
https://github.com/foundryvtt/dnd5e/blob/3.3.x/module/config.mjs#L463

And the item with that id is definitely in the "Items" compendium.
