### ISSUE TITLE
[Feature Request] Allow for a setting when non-proficient skills are visible for a creature in the new NPC sheet

### ISSUE THREAD

**Issue by Vengrath97** [foundryvtt/dnd5e#3865]
Currently, only proficient skills are visible for creatures, but it is very common for creatures to have no proficiency in Athlethics/Acrobatics, and have to roll for these skills (grapple/shove). The same goes for Stealth (!) Perception (!) Insight, Deception, and less often for Sleight of Hands,

**Comment by Zanderaf** [comment]
A setting for this would really be nice

**Comment by krbz999** [comment]
_(Comment for assignment.)_
