### ISSUE TITLE
Bring back trash can (delete) icon in chat log

### ISSUE THREAD

**Issue by devteamplus** [foundryvtt/dnd5e#3867]
In the chat log, having to click into a menu and then select "delete" for each individual message is super tedious.  Please bring back the trash can icon so that we can do "one-click" deletes for individual chate messages.

**Comment by unsoluble** [comment]
Please remember to do a quick search for existing issues before posting one :)

(this is already resolved in PR #3826)

**Comment by devteamplus** [comment]
> Please remember to do a quick search for existing issues before posting one :)
> 
> (this is already resolved in PR #3826)

Hmm... I did a search and that didn't pop up.  Thanks for pointing it out.

**Comment by devteamplus** [comment]
> Please remember to do a quick search for existing issues before posting one :)
> 
> (this is already resolved in PR #3826)

FYI - Holding shift (as the DM) does not show the trashcan icon for me.

**Comment by unsoluble** [comment]
It’s resolved in a pull request, which has not yet been merged with the system and released.

**Comment by Fyorl** [comment]
Duplicate of #3443
