### ISSUE TITLE
[BUG][v3.3.1] New NPC Sheet: Prepared spell filter doesn't work

### ISSUE THREAD

**Issue by TaureHorn** [foundryvtt/dnd5e#3879]
Applying the prepared spell filter on the new NPC sheet doesn't do anything for me. All the spells remain visible, both unprepared and prepared spells. The rest of the spell filters on the new NPC sheet work just fine. Disabling all modules shows the same behaviour.

dnd5e v3.3.1
foundry v.12.327 - 12.329 (felddy docker container)

**Comment by M0nk3yy** [comment]
This bug is still present in dnd5e 4.0.2

![image](https://github.com/user-attachments/assets/fa8ea002-e2bf-4c4e-849f-a0fb7df1fd97)

**Comment by TaureHorn** [comment]
I have found the culprit. 

dnd5e.mjs:40409
```
if ( filters.has("prepared") ) {
          console.log("listing filters", filters)
        if ( alwaysPrepared.includes(item.system.preparation?.mode) ) return true;
>>>>    if ( this.actor.type === "npc" ) return true;
        return item.system.preparation?.
}
```
Commenting that line out made spell the prepared spell filter on npc sheet work as normal.

Finding that line makes it seem more like a feature than a bug. But either way, I'm glad to have preparation filters back.
