### ISSUE TITLE
[Bug] Character Sheet always shows identified description

### ISSUE THREAD

**Issue by TheDying0fLight** [foundryvtt/dnd5e#3890]
When expanding the item description, the identified description is shown even when the item is unidentified (see screenshot which is taken from the a user with player permissions)

![grafik](https://github.com/user-attachments/assets/532f3cd8-6910-4cb3-9a37-0360c23c530b)

**Comment by kylania** [comment]
The other part of this is that Players, even with Limited Permissions, are able to Identify (by Rclick from Inventory > Identify) or by Rclicking from Inventory > Edit.  They will see the Unidentified button to freely ID the Item.  

Here's a video showing GM and Player view of this, including the Rclick from Inventory > Expand displaying the Identified Description):  [Repo Video](https://drive.google.com/file/d/1TAvprisaArfNIbIAek7hWwUD26iUGGGY/view?usp=sharing)

**Comment by Fyorl** [comment]
> The other part of this is that Players, even with Limited Permissions, are able to Identify (by Rclick from Inventory > Identify) or by Rclicking from Inventory > Edit. They will see the Unidentified button to freely ID the Item.
> 
> Here's a video showing GM and Player view of this, including the Rclick from Inventory > Expand displaying the Identified Description): [Repo Video](https://drive.google.com/file/d/1TAvprisaArfNIbIAek7hWwUD26iUGGGY/view?usp=sharing)

This is a misunderstanding of how ownership works in core foundry. The Item that exists on the Actor is not the same as the one in the sidebar, it is a copy. Since the player is an Owner of the Actor, they are also the Owner of all that Actor's Items.

**Comment by MaxPat931** [comment]
> The other part of this is that Players... are able to Identify... the Item.

If you want to prevent Players from Identifying their items, that is tracked in a separate issue, I commented with a world script you can use here https://github.com/foundryvtt/dnd5e/issues/2781#issuecomment-1930550681

**Comment by kylania** [comment]
Ahh, that makes sense, Fyorl, thanks!  It's important to be able to hand an Unidentified Item to a player but leave it unidentified, so MaxPat's WorldScript seems to work great for that.  Thanks!

**Comment by uncleurdnot** [comment]
I wanted to +1 on this one.  The item is unidentified, and even with @MaxPat931 's script preventing players from identifying the item on their own, they can still just click on the description preview and see the description anyways.  I suspect that the preview isn't checking the item's status as identified or not.

![image](https://github.com/user-attachments/assets/1b4c5e11-e132-4891-b9a2-f0f64883c5be)


![image](https://github.com/user-attachments/assets/51a47081-aa57-4fb1-aa25-163e1ea90e85)

**Comment by uncleurdnot** [comment]
In case it ends up helping someone else, I patched this on my V11/3.3.1 installation here: https://github.com/uncleurdnot/foundryVTT-fix-item-5e-unidentified-description/tree/master
