### ISSUE TITLE
Activity Type: Attack

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#3910]
The attack activity will be able to roll attacks and damage. It will contain information on whether it is a melee or ranged attack, weapon or spell attack, and any bonuses to hit. For damage it will be able to take multiple formulas of different damage types and be able to fetch the intrinsic damage from a weapon if it exists on one.

**Comment by krbz999** [comment]
What about items that can attack but do not deal damage?

**Comment by arbron** [comment]
Then you can just not fill in any of the damage parts and no damage button will appear, similar to the current behavior on items.
