### ISSUE TITLE
Activity Type: Saving Throw

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#3911]
The saving throw activity will be able to call for a saving throw on a target and roll damage. It will contain information on setting the save DC and what type of save is required. It will also contain information on how the damage/effects are applied on a successful save (e.g. "No Damage on Save", "Half Damage on Save", "Full Damage on Save", "No Effects on Save", etc.).

**Comment by maxobremer** [comment]
Hey Arbron, will different activities also be able to have different active effects tied to them? Let's say you want to make the item [Staff of Power](https://www.dndbeyond.com/magic-items/4764-staff-of-power) and have the spells on it as activities. Will it be possible to have an active effect for the hold monster and ray of enfeeblement separately?
