### ISSUE TITLE
Request: Option to manualy set the level cap for player characters

### ISSUE THREAD

**Issue by Benji222333** [foundryvtt/dnd5e#3916]
In a earlier version it was possible to level a character with multiclasses beyond level 20. Would be nice, if this would be possible again.

Maybe even a option to manualy set the required xp.

**Comment by JPMeehan** [comment]
This is currently doable with a [world script](https://github.com/foundryvtt/dnd5e/wiki/Modifying-Your-Game-with-Scripts)
