### ISSUE TITLE
Class HP advancements produce unexpected results when used with NPCs

### ISSUE THREAD

**Issue by TheGiddyLimit** [foundryvtt/dnd5e#3922]
env:

- Foundry 12.330
- dnd5e 3.3.1
- no active modules

---

When dropping a character class to an NPC sheet, a d8 is always used as the hit die.

Ex (Sorcerer hit dice is a `d6`):

![image](https://github.com/user-attachments/assets/4dda88d2-6783-4ae9-8f18-782db704d31c)

---

Additionally, HP gained via advancements interacts poorly with the starting 10 HP, resulting in e.g. the following when inputting "6" as the HP rolled:

![image](https://github.com/user-attachments/assets/9039a2d6-129b-49d4-9947-a4390067e071)

**Comment by Fyorl** [comment]
This has been implemented per the DMG rules on adding classes to monsters, where they only receive HD based on their size:

> For each class level you add, the monster gains one Hit Die of its normal type (based on its size), ignoring the class’s Hit Die progression.

Adding to the starting HP is per the rules on Sidekicks from Tasha's.

**Comment by TheGiddyLimit** [comment]
cool, appreciate the explanation
