### ISSUE TITLE
Attack rolls below target AC are highlighted red even if the roll is a critical success

### ISSUE THREAD

**Issue by roth-michael** [foundryvtt/dnd5e#3952]
See below:
![image](https://github.com/user-attachments/assets/af083421-0a74-4a3f-bebb-ca144b46f0ac)

Should just be a matter of changing 
```js
if ( d20Roll.total >= d.options.target ) total.classList.add("success");
```
to
```js
if ( d20Roll.total >= d.options.target || (canCrit && d20Roll.isCritical) ) total.classList.add("success");
```

**Comment by roth-michael** [comment]
Technically both the `fumble` and `success` classes are added in the opposite scenario (a natural 1 but a bonus that lifts it above AC) but that doesn't matter, since it seems `fumble` takes priority over `success`

**Comment by Fyorl** [comment]
That's how it's intended to be handled in the case of this bug as well: `critical` styles should take priority over the `failure` styles.

**Comment by roth-michael** [comment]
Ah gotcha so the ideal solution would be a css one, not a code change as outlined above? (I ask because I'll make a PR if desired)
