### ISSUE TITLE
concentrating statusEffect is keyed to dead

### ISSUE THREAD

**Issue by Krigsmaskine** [foundryvtt/dnd5e#3968]
dnd5e version 3.3.1
FVTT 12.330

The concentrating `statusEffect` seems keyed to dead, enabling concentrating from the right-click status effect menu makes the token dead and looking up concentrating in `CONFIG.statusEffects` returns
`{
    "id": "concentrating",
    "name": "Dead",
    "img": "systems/dnd5e/icons/svg/statuses/dead.svg",
    "_id": "dnd5edead0000000"
}`

**Comment by thatlonelybugbear** [comment]
Are you sure there isn't a module involved?

**Comment by Krigsmaskine** [comment]
ok I now can't repro despite the fact I created an entire new world, so must be cache related
