### ISSUE TITLE
[Feature Request] Allow Additional Saving Throws on Items (possible via Enchantments)

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/dnd5e#3973]
At the moment a weapon can only have 1 saving throw defined, even though there are situations where multiple saving throws are required. An example is hitting a giant with a [Giant Slayer](https://www.dndbeyond.com/magic-items/5388-giant-slayer) weapon while a [Basic Poison](https://www.dndbeyond.com/equipment/68-poison-basic-vial) is coated on the weapon. This requires a DC 15 Strength saving throw from the Giant Slayer weapon and a DC 10 Constitution saving throw from the Basic Poison. I do not immediately know any examples for items or features that have 2 DCs attached to them, but with enough poison most weapons could have multiple.

It would be nice if enchantments could add additional saving throws instead of overriding them. It would also be nice if items in general could have multiple saves, but that's more from a homebrew perspective

**Comment by JPMeehan** [comment]
This is going to be cleanly handled by the new Activities system in 4.0

**Comment by Psygrrl88** [comment]
@JPMeehan Could you please elaborate on how this works? Thank you.

**Comment by krbz999** [comment]
> @JPMeehan Could you please elaborate on how this works? Thank you.

You add multiple activities.
https://github.com/foundryvtt/dnd5e/wiki/Activities
