### ISSUE TITLE
Error when casting find familiar

### ISSUE THREAD

**Issue by dovrosenberg** [foundryvtt/dnd5e#4006]
I'm getting an error when attempting to cast find familiar...  After clicking the space where I want it to appear, I get:
```
TypeError: undefined. Cannot read properties of undefined (reading 'replace')
[Detected 1 package: system:dnd5e(3.3.1)]
    at Roll.replaceFormulaData (foundry-esm.js:64012:22)
    at SummonsData.getChanges (summons-field.mjs:491:36)
    at SummonsData.summon (summons-field.mjs:232:26)
    at async Item5e._onChatCardSummon (item.mjs:2256:7)
    at async Item5e._onChatCardAction (item.mjs:2152:11)
```
It creates the actor of the summons but not the token.  Other summoning spells seem to work fine.

**Comment by Rabulias** [comment]
I just tried this on FVTT 12.331 DND5E 3.3.1 and it worked fine with summoning the Bat. 

What type of familiar are you trying to summon? Are you trying with no other modules installed?

**Comment by dovrosenberg** [comment]
I'm able to reproduce it with all modules off - same versions as you.

Any type of familiar does it (including the bat).

Inside ` SummonsData.getChanges`, `this.bonuses` has `undefined` as the value for all the properties, so on this line: `const attackDamageBonus = Roll.replaceFormulaData(this.bonuses.attackDamage, rollData);` the first parameter is undefined.

**Comment by Rabulias** [comment]
Are you using the Foundry client or hosted?

**Comment by dovrosenberg** [comment]
Hosted and yes

**Comment by Rabulias** [comment]
My test was using the local Foundry client. My Forge-hosted game is still on v11, so I cannot test that out for you.

**Comment by krbz999** [comment]
Probably best to move general troubleshooting to the `#dnd5e` channel on the discord.

**Comment by dovrosenberg** [comment]
Thanks - I only posted it here because it sure seems like a bug.  We can easily work around it, so I don't really need troubleshooting.
