### ISSUE TITLE
Activity Type: Cast a Spell

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#4061]
Activity type that triggers a spell for items like Staffs and Wands.

**Comment by Rabulias** [comment]
Would this also apply to _instruments of the bards_?

**Comment by arbron** [comment]
> Would this also apply to _instruments of the bards_?

This would apply to any item that casts spells.

**Comment by Rabulias** [comment]
Staves and instruments of the bards use the wielder's spell save DC instead of a set DC on the item. I got mixed up thinking wands did the same, and thought this issue was focused on that.

**Comment by Zanderaf** [comment]
Any preview on how the spells are going to be displayed? I feel like having them show up in the spellbook similarly to how modules like Magic Items or Items with Spells does it feels the best imo; just having all the spells in the "same place".

**Comment by roth-michael** [comment]
Noticed in #4474 you have "Currently does nothing to change how these spells appear on the actor sheet, so they will all display in the spell list as if they were normal spells" with "Hide cached spells on actor sheet" as a Todo. Wondering if it'd make sense to make use of that behavior, and maybe have a togglable option (either a system setting or per-cast-activity) on whether to show the spell in the spellbook, perhaps under its own "Granted by item" category. Personally I'd prefer to keep spells granted by items on the item, not have them show up in my spellbook, but I know there are many who feel the opposite.

**Comment by Zanderaf** [comment]
Yea, I would very much appreciate spells granted by items in their own category instead of being mixed in with other spells.
