### ISSUE TITLE
[4.0] Fumble range for attack rolls is missing in `dnd5e.preRollAttackV2`

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#4121]

**Comment by arbron** [comment]
It isn't filled in by default, but setting it works perfectly fine:

```javascript
Hooks.on("dnd5e.preRollAttackV2", (process, dialog, message) => {
  process.rolls.forEach(r => r.options.criticalFailure = 19);
});
```

<img width="299" alt="Screenshot 2024-09-05 at 13 58 24" src="https://github.com/user-attachments/assets/b2be49a2-2763-4345-aa81-1c77fd862f9a">
