### ISSUE TITLE
[4.0 and below] "Submit" button has no localization key.

### ISSUE THREAD

**Issue by Padhiver** [foundryvtt/dnd5e#4140]
The Submit button has no location key available in the en.json.

It does exist, however, and is simply called “Submit”, which is about as precise as it gets. If I translate “Submit”: “Translation”, in my fr.json, I get the translation.

I would have made a PR but I'm not sure how to handle the fact that the key is just called “Submit”.

![image](https://github.com/user-attachments/assets/788a1778-9c96-4620-ad35-e6d850930ab2)
(Edit Source windows)

**Comment by krbz999** [comment]
It is part of core.

**Comment by arbron** [comment]
> ~It is part of core.~ e: nope, it sure ain't!

"Save" is part of core, so maybe that is what we should use instead.

**Comment by krbz999** [comment]
> > ~It is part of core.~ e: nope, it sure ain't!
> 
> "Save" is part of core, so maybe that is what we should use instead.

That or `"Confirm"` .
