### ISSUE TITLE
SRD compendium spell Conjure Animals has wrong formula for upcasting summons

### ISSUE THREAD

**Issue by flogiston1** [foundryvtt/dnd5e#4161]
Conjure Animals caps at 3x the normal amount of summons, but it should cap at 4x when cast at ninth level.
So instead of 
`[normal number of creatures] * min(3, floor((@item.level - 1) / 2))`
the formula should be 
`[normal number of creatures] * min(4, floor((@item.level - 1) / 2))`

or just drop the min altogether I guess.

**Comment by arbron** [comment]
Huh, looks like we are missing the last part of the scaling formula that mentions 9th level in the description.
