### ISSUE TITLE
Parsing @UUID to reference items on enchanted item descriptions doesn't work

### ISSUE THREAD

**Issue by imivoltz** [foundryvtt/dnd5e#4171]
While using the attribute system.description.value on an enchant effect, if you add an item reference that contains @UUID, it will get parsed as a 0 on the actual description once the enchant is applied, breaking the item reference.

![image](https://github.com/user-attachments/assets/7972c2ca-d071-42e2-b8cb-d30597559d31)
Effect Value
![image](https://github.com/user-attachments/assets/b1e5e8d6-c90c-47d5-b617-a4fecd13819f)
Actual description once the enchant is applied, @UUID gets cleaned to 0.

**Comment by arbron** [comment]
Not able to reproduce, have you tested this without module enabled?

**Comment by imivoltz** [comment]
It's actually on Midi's side now that i've tested this further, sorry for the issue.
