### ISSUE TITLE
References to an Embedded Document when using fromUuidSync causes script crash

### ISSUE THREAD

**Issue by ShinyHobo** [foundryvtt/dnd5e#4178]
Title

Foundry: 12.331
dnd5e: 3.3.1
midiQOL: 11.6.14.1

When attempting to utilize the "Add attack/damage buttons to item inventory list" option with NPC sheets specifically, the roll hook crashes:

```Chat message WyM0ZBMYWbhPjwQn failed to render: Error: fromUuidSync was invoked on UUID '[any uuid]' which references an Embedded Document and cannot be retrieved synchronously.)```

I fixed this by making _enrichChatCard async, awaiting it, and changing the relevant "Enriched roll flavor" section from
```const item = fromUuidSync(roll?.itemUuid);```
to 
```const item = await fromUuid(roll?.itemUuid);```

This is a related issue to https://github.com/foundryvtt/dnd5e/issues/3675; this may be an issue elsewhere.

**Comment by arbron** [comment]
This sounds like a module problem. Rolling from compendium items isn't supported and won't be by the system.

**Comment by ShinyHobo** [comment]
You specifically fixed the issue of rolling for items in the compendium in the linked issue I provided. It is literally the exact same issue and fix within a different context. Is there a downside to this change; it seems to me that it would improve module compatibility because of the inherent fallback behavior?

**Comment by arbron** [comment]
The issue linked is for simply opening the sheets when they are in a compendium, not for activating items.
