### ISSUE TITLE
NPC experience points visible to players

### ISSUE THREAD

**Issue by Doshy7** [foundryvtt/dnd5e#4186]
Heya folks! I'm running a 5e campaign and was giving  'Limited' player permission to NPCs they encounter on their journey so there was a record of certain characters. However, I've noticed that that the experience points of said NPC is now visible. 

We don't run exp in my game but I feel it does reveal how 'significant' a seemingly innocuous character might be. I feel like this likely isn't intended behavior - especially on 'Limited' visibilty!  It also showed the page reference number/sourcebook for the NPC but I was able to clear that myself at least manually.

![image](https://github.com/user-attachments/assets/a50abf34-92cf-4108-8181-874a424ef0ba)

**Comment by Rabulias** [comment]
As a temporary workaround in the meantime, you could switch the NPC(s) in question to the Legacy sheet. Or make Journal entries and share those instead.
