### ISSUE TITLE
Allow for different attack/damage when Throwing a weapon

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#4189]
Like versatile changes the formula when the weapon is used with two hands, there are also features that provide bonuses specifically to thrown weapons

**Comment by arbron** [comment]
Initially it would probably just be properly swapping between `bonuses.mwak` and `bonuses.rwak`, but there should probably be an additional set of bonuses based on attack mode (or steal BaB for better bonus handling). In `4.0` we should be able to get this working with damage bonuses, but attack bonuses are blocked by the roll refactor.
