### ISSUE TITLE
Allow for multiple saving throws on a single activity

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/dnd5e#4192]
It would be nice for an activity to ask for multiple saving throws. Grappling and shoving in the new rules allows for a dex or str saving throw (the one being grappled chooses which) so it would be nice if the chat card has both of those saves there.

The module [Roll Groups](https://foundryvtt.com/packages/rollgroups) has this functionality, so maybe it can be used as an example.

**Comment by krbz999** [comment]
I think it would make more sense for the roll configuration dialog to give the choice of ability, rather than presenting multiple buttons in the chatlog. This would also be in line with skills, tools, and (soon) attack rolls.

**Comment by Deyzeria** [comment]
Also allowing to set any several in any ability choice window would be good, like how by default for Finesse weapons it presents (Strength or Dexterity) choice, being able to do similar manually would be great for homebrews and cases like this, could probably reuse something similar to how damage types selection were done- you select, and it just adds them to the currently selected/options.
