### ISSUE TITLE
Allow multiple types of saving throw on a single activity 

### ISSUE THREAD

**Issue by M0nk3yy** [foundryvtt/dnd5e#4194]
The most common use cases for this are Grapples and Shoves. 

In Revised 5e, Grapples and Shoves are now a non-damaging form of Unarmed Strike, and utilize a Saving Throw rather than a contested Ability Check. The defender can make their choice between Strength and Dexterity. 

Whilst it is possible to give the Unarmed Strike multiple activities including separate Strength and Dexterity specific Saving Throw activities, this results in the awkward situation of needing the DM to tell the player which ability the NPC is going to use before the player even performs the action. 

My suggestion is to add the ability to have multiple kinds of Saving Throw on a single activity so that the DM may click whichever they deem appropriate. This avoids delay and revealing information to the player. 

Example screenshots, credit to the `Roll Groups` mod. 

![image](https://github.com/user-attachments/assets/1434e5c5-e4c3-45ae-9ff3-4d9d1500a12b)
Image showing `+` button that can be used to add a second Saving Throw line. 

![image](https://github.com/user-attachments/assets/42013cf8-6201-4577-b8ce-c7e3b5902338)
Example of resultant chat card. 

My understanding from some of the new documentation is that something similar is possible with Ability Check activities (unfortunately I haven't been able to check this out first hand yet), but it would be useful to be able to extend this to Saving Throws.

**Comment by M0nk3yy** [comment]
Duplicate of #4192. My bad, did not see that when writing this up. 

Regarding the comment from @krbz999 - utilizing a drop-down would probably be fine as long as the onus is still on the DM to choose, not the player.

**Comment by krbz999** [comment]
Community out in full force to kill off Roll Groups.

**Comment by M0nk3yy** [comment]
To make sure we don't *lose* any of Roll Groups. 

I'm also not sure how obvious it would be to the defender that they'd have a choice of ability if it's drop-down only. Whatever solution is used should make that at least as clear as the presence of both buttons.
