### ISSUE TITLE
Use Item RollData for resource recovery instead of Actor RollData

### ISSUE THREAD

**Issue by roth-michael** [foundryvtt/dnd5e#4197]
If I understand correctly, the only difference between an Item's rollData and an Actor's is that the item also has access to its own relevant info. It would be nice to be able to put in `@item.uses.max / 2` as a recovery formula - right now it's limited to only Actor rollData.

**Comment by arbron** [comment]
Looks like that is already the case in `3.3`, and will continue to be the case in `4.0`.

```javascript
// 3.3
const roll = new Roll(uses.recovery, item.getRollData());

// 4.0
const rollData = this.activity.getRollData();
```

**Comment by roth-michael** [comment]
Hmm, not seeing it there - where's that 4.0 line? Looking at line 2716 of `actor.mjs`

**Comment by roth-michael** [comment]
(Added a PR to demonstrate what I mean, since it's just a one-liner)

**Comment by arbron** [comment]
Oop, I was looking at consumption not recovery for the `4.0` code :P
