### ISSUE TITLE
Cannot delete activities

### ISSUE THREAD

**Issue by LadyDefile** [foundryvtt/dnd5e#4220]
I seemingly cannot delete activities. I click the button but nothing happens.
![image](https://github.com/user-attachments/assets/d5f6e884-bdbf-4929-b6dd-b85c9507aa69)
This is the button I'm clicking and I'm 99.9% sure it should be removing "Attack" from the list but doesn't.

I tested this on a completely fresh "test" world with no modules activated to ensure it wasn't a module issue.
![image](https://github.com/user-attachments/assets/e2159bc7-16ec-415e-b12d-c9bc7de00c44)

**Comment by refleximage** [comment]
Same issue here.

**Comment by hakr14** [comment]
You can delete activities by right-clicking them and selecting Delete from there. But yes, the trash can in Edit mode should probably work :).
Here's the error thrown when attempting this operation:
```
item-sheet-2.mjs:223 Uncaught TypeError: Cannot read properties of null (reading 'dataset')
    at ItemSheet5e2._onDeleteActivity (item-sheet-2.mjs:223:47)
    at ItemSheet5e2._onSheetAction (item-sheet-2.mjs:269:42)
    at HTMLButtonElement.dispatch (jquery.min.js:2:40035)
```
