### ISSUE TITLE
(bug) Cropped Icons in Title Bar

### ISSUE THREAD

**Issue by DragonHale** [foundryvtt/dnd5e#4235]
Longer item names will crop the title bar icons in half (see picture below. It crops the toggle edit button, the x, the source, etc.)
<img width="374" alt="{7AE47693-B79E-4514-A879-6A3402F12C2C}" src="https://github.com/user-attachments/assets/1b0af94c-6031-48f2-8408-ed96b4be4899">

**Comment by InnilToo** [comment]
I believe this duplicates https://github.com/foundryvtt/dnd5e/issues/4239

**Comment by arbron** [comment]
> I believe this duplicates #4239

Making sheets resizable and fixing the header cropping are two different issues.
