### ISSUE TITLE
Skip dialog ignores previously selected ammunition

### ISSUE THREAD

**Issue by InnilToo** [foundryvtt/dnd5e#4257]
While skipping a dialog with Shift the attack roll always uses the first item on the list (presumably alphabetically) ignoring any previous selections.
If the dialog is not skipped it remembers the last ammunition that was selected.
In my opinion, skipping and not skipping should work the same.
Tested on a fresh world with no modules system version 4.0.0 Foundry version 12 Build 331.

**Comment by krbz999** [comment]
Additionally, the default cannot be set to blank.

Having deselected the ammo previously during an attack roll, I assumed that would be the new default.
