### ISSUE TITLE
SRD Longbow throws error on use

### ISSUE THREAD

**Issue by M0nk3yy** [foundryvtt/dnd5e#4264]
Repro:

1. Add `Longbow` to character from SRD compendium
2. Try to roll item

Error shown in console:

![image](https://github.com/user-attachments/assets/a4a9fcb4-582f-4e2f-980b-505cb2b2f2a6)

Editing the name of the Activity seems to allow it to roll. This includes adding a new name, then deleting it entirely.

Bonus: The Longbow seems to have its Activity Consumption set to Material Uses, which it does not need. When I add the Longbow to Krusk this actually results in the bow trying to consume Javelins in an additional popup which is not necessary.

**Comment by arbron** [comment]
Hmm, the Longbow in the SRD doesn't have material consumption set up and I don't get that error when attempting to use it.
