### ISSUE TITLE
Using the dnd5e.preRollDamage breaks any roll data in the damage formula

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/dnd5e#4285]
This issue was originally reported for my module, kaelad02/adv-reminder#76, but I can reproduce it with a simple macro.

If you have a module that uses the `dnd5e.preRollDamage`, the legacy hook now that v4.0 introduced the new `dnd5e.preRollDamageV2` hook, any part of the damage roll that uses roll data (e.g. `@mod`) resolves to `0`. I added a Dagger to a PC and made an attack with it. When I roll the damage, it shows the damage correctly as `1d4 + 3` since it's correctly adding `@mod` to the damage.

![image](https://github.com/user-attachments/assets/16f1345a-bdad-4ef4-8cf8-6f9d0221c97a)

But if you enable any module that uses the `dnd5e.preRollDamage` hook, the damage formula is `1d4 + 0`. It appears that using the hook breaks something with the roll data and the `@mod` part doesn't work correctly.

![image](https://github.com/user-attachments/assets/e741d068-cb26-4b0a-a73e-82f82d3e96c7)

The reason I believe this is a system issue rather than a module issue is because of 2 things:
1. I can reproduce it with 0 modules, just a simple macro to register a hook: `Hooks.once("dnd5e.preRollDamage", console.log);`
2. I see there's big block of code that only runs if someone's registered that hook: https://github.com/foundryvtt/dnd5e/blob/release-4.0.1/module/documents/activity/mixin.mjs#L920

**Comment by kaelad02** [comment]
Some more info:

- I originally tested this with dnd5e version 4.0.0 but also confirmed it still happens on 4.0.1
- I'm still working on a new version for my module, but I can confirm that using the `dnd5e.preRollDamageV2` instead of the old one works just fine. It only happens when using the older, `dnd5e.preRollDamage` hook
- It's not just the `@mod` roll data that's broken. I had a second activity on the dagger that also added sneak attack damage from the Rogue class's scale value and instead of resolving to `1d6` it was `0`

**Comment by arbron** [comment]
The trouble a missing underscore can cause :(
