### ISSUE TITLE
Make auto-created spell scrolls utilize a scroll icon rather than a spell icon

### ISSUE THREAD

**Issue by M0nk3yy** [foundryvtt/dnd5e#4287]
Currently, when spell scrolls are created by dragging a spell to the inventory, the generated item depicts the icon of the spell. I would suggest instead; getting the icon from the SRD scroll of the appropriate level and using that.

Whilst I can see that the current method does provide some visual indication of what the scroll contains, my expectation when browsing the inventory is to see equipment icons. When looking for scrolls, I expect to see scrolls, rather than magic effects etc. This is the same philosophy I have attempted to implement across other inventory items.

Current:
![image](https://github.com/user-attachments/assets/be75481c-f3c2-4603-bd0b-05433fbf70f3)

Suggested:
![image](https://github.com/user-attachments/assets/f7d3de63-bd51-41a9-b4b9-0ca58a717491)

**Comment by krbz999** [comment]
*Insert witty comment here.*
