### ISSUE TITLE
Enchantment "Apply Effect to Actor" troubles

### ISSUE THREAD

**Issue by LadyDefile** [foundryvtt/dnd5e#4298]
Talked this out with @krbz999 in the Discord and this definitely appears to be a bug, I have a feature with an enchantment activity.
![image](https://github.com/user-attachments/assets/cf6b05c9-d837-4766-bd8b-26af7ae56cb0)

As you can see, it has two effects, one that is an enchantment and one that is a "rider effect". Here is the issue. The effects both transfer successfully but I found a big issue with the way that rider effects work.

If I **disable** "Apply Effect to Actor" in the rider effect on the **feature**, then it is also disabled once enchanted to the piece of equipment. This prevents the rider effect from working properly.

If I **enable** "Apply Effect to Actor" in the rider effect on the **feature**, then it is immediately activated just by the creature possessing the effect, making the effect a permanent buff.

This is two effects that I have.
![image](https://github.com/user-attachments/assets/d75be72a-086f-4eaf-9218-fa08270fc439)

**Comment by LadyDefile** [comment]
To be thorough, I also tried using the "Effect Suspended" option but the result was the same. There needs to be a way enable "Apply Effect to Actor" after it has been transferred to the enchanted item.

**Comment by Fyorl** [comment]
Rider effects are supposed to be given a flag to prevent this from happening, so we've somehow regressed on that.

**Comment by arbron** [comment]
Looks like we just forgot to update how we filter out these effects after we moved the flag location.
