### ISSUE TITLE
DND 5E 4.0 and above not compatible with ready set roll

### ISSUE THREAD

**Issue by Fighterpilot64** [foundryvtt/dnd5e#4301]
I have ready set roll as a module installed on my world and just updates to foundry 12 version and updated to 5E version 4.0.1 and the attributed would roll when clicked on but none of my spells, attacks, or features were rolling or going to the chat. Downgrading to 5E version 3.3.0 fixed the issue so there clearly is some sort of compatibility issue going on there.

**Comment by arbron** [comment]
Should be filed on the RSR repo, not the system repo.
