### ISSUE TITLE
[Bug] Multiple active effects on damage card that shouldnt have an

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/dnd5e#4307]
When I roll the damage for the rogue's cunning strike with the activity Cunning Sneak Attack, it adds both the Cunning Strike: Poisoned and Cunning Strike: Tripped to the damage chat card. Now this could be an issue with the new Player's Handbook, but I think its a DnD5e issue, hence why i post it here
![image](https://github.com/user-attachments/assets/f901baef-8572-42c8-8958-be909c9e83c1)

No modules besides version 1.0.0 of the [Player's Handbook (2024)
](https://foundryvtt.com/packages/dnd-players-handbook)
DnD5e version 4.0.1
Foundry (Node version) 12.331

**Comment by maxobremer** [comment]
I used the rogue character from the phb and only levelled her up to 5 to check the ability

**Comment by maxobremer** [comment]
Also happens btw when you roll for the damage of the Bonus Hex Damage activity on the hex spell. also from the new phb
![image](https://github.com/user-attachments/assets/0844eeab-a477-4d37-a1c0-c35f0fa5d2aa)

**Comment by arbron** [comment]
Closed by https://github.com/foundryvtt/dnd5e/pull/4306
