### ISSUE TITLE
Players can see the 'refund resource' button despite permissions

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#4308]

**Comment by arbron** [comment]
Could you clarify what you mean? In my testing the "Refund Resource" button will only appear for the GM or player who used the item:
<img width="609" alt="Screenshot 2024-09-18 at 13 10 46" src="https://github.com/user-attachments/assets/5fed8078-9946-4b8f-8e8a-39f7394237d4">

**Comment by krbz999** [comment]
Was not able to reproduce more than once.
