### ISSUE TITLE
[Bug] Concentration is hexed when you use an activity that doesnt use concentration

### ISSUE THREAD

**Issue by maxobremer** [foundryvtt/dnd5e#4309]
When you use the hex spell, the timer for concentration is applied or reset when you use the Bonus Hex Damage activity even though it shouldnt and doesnt have the concentration check box enabled.

in the image I only used the Bonus Hex Damage activity and still got concentration. 
![image](https://github.com/user-attachments/assets/9e439a41-8695-4315-9803-d4437668ad93)
 

Using the Bonus Hex Damage activity while i was concentrating on the Place Curse activity made the timer reset for concentration btw

No modules besides version 1.0.0 of the [Player's Handbook (2024)](https://foundryvtt.com/packages/dnd-players-handbook)
DnD5e version 4.0.1
Foundry (Node version) 12.331

**Comment by arbron** [comment]
Known issue, will be resolved in `4.0.2`
