### ISSUE TITLE
Effect-modified "Uses" not showing on Character Sheet when item's base uses is null

### ISSUE THREAD

**Issue by MythicPalette** [foundryvtt/dnd5e#4313]
As you can see, the effect sets the `system.uses.max` property and does function properly, but it doesn't show the modified use count under the `Charges` column on the character sheet. Manually setting the value in the item itself shows the charges though.
![image](https://github.com/user-attachments/assets/5667e2a5-3c02-4156-b520-e16b0fbfd8c2)

Now, I did notice that setting the value to anything that is ***not null*** will make it show the correct number of Charges.
![image](https://github.com/user-attachments/assets/dcf73549-0ea0-4580-b6f6-efc9621476e9)

You can see here, I set it to 0 in Max and it shows the correct number the effect gives, 6, on the character sheet.

**Comment by LadyDefile** [comment]
@arbron nobody has commented or tagged this bug. Did it get overlooked?
