### ISSUE TITLE
Request: Adjust character sheet so appearance of scroll bar does not shift page contents

### ISSUE THREAD

**Issue by alaustin0** [foundryvtt/dnd5e#4324]
Currently, when a page on the character sheet is not long enough to warrant a scrollbar - which is common for many level 1 characters - expanding a feature can lengthen the page and cause the scrollbar to appear, shifting all page content over enough that the cursor is no longer over the same button.

https://github.com/user-attachments/assets/d2af4e20-56d3-44b5-96f5-3aab83939988

While this is admittedly a rather minor issue, it is frequently encountered especially at low level play when certain pages don't have a ton of features on them.

I'n not sure what the best way to alleviate this issue would be, but it would be a nice quality of life change for people who expand and collapse features often.

**Comment by arbron** [comment]
Should be pretty simple, we just need to add `scrollbar-gutter: stable` and adjust the padding on the right.
