### ISSUE TITLE
Feature Request: Add section to the character sheet to showcase Weapon Masteries and allow them to be swapped

### ISSUE THREAD

**Issue by alaustin0** [foundryvtt/dnd5e#4327]
While weapon masteries can be selected during Class Advancement, they cannot be easily viewed or changed after the fact. It would be helpful if there was a section on the sheet for viewing the current masteries as well as being able to change them out easily.

**Comment by arbron** [comment]
They display in the "Weapons" proficiency list on the sheet and can be modified using the weapons config application:

<img width="922" alt="Screenshot 2024-09-18 at 14 31 14" src="https://github.com/user-attachments/assets/f5113922-8e03-4054-b088-01b13766cfd0">

**Comment by alaustin0** [comment]
Of course you guys were already on it. Thanks Jeff!
