### ISSUE TITLE
[4.0.2] - Cannot close activity setup when viewing a compendium Item, unless you hit Escape.

### ISSUE THREAD

**Issue by thatlonelybugbear** [foundryvtt/dnd5e#4330]
[activityCompendiumCloseNope.webm](https://github.com/user-attachments/assets/a8957b05-3b41-4124-9534-9d5f150fdd7d)

**Comment by krbz999** [comment]
I think there are several issues here. It ain't supposed to look like that.

**Comment by thatlonelybugbear** [comment]
The skinny and tall window might be a secondary issue,  not present when
testing before making the video, so not sure if it's an actual issue.

Another such issue I noticed is that if you minimize the non closing
window, there is a way to *make* it behave like you are dragging it around,
when in fact you are not.  It seems like it moves along with the mouse
movement.
If I manage to find a way to reproduce I will create another issue.
