### ISSUE TITLE
Editing damage type stuck (Eldritch Blast tested)

### ISSUE THREAD

**Issue by itteerde** [foundryvtt/dnd5e#4356]
This is not about it being the wrong Type in Compendium!

I did change the Damage Type in the Item on an Actor, but it does not work. The ChatMessage created remains displaying the wrong type.

> why is my Eldritch Blast dealing Necrotic?
![image](https://github.com/user-attachments/assets/502a925b-b5a1-4a67-8a97-37b512c9602a)

- [my initial question](https://discord.com/channels/170995199584108546/670336046164213761/1286365741003706389)
- [being reproduced (and for other Spells)](https://discord.com/channels/170995199584108546/670336046164213761/1286370866409509015)

**Comment by maxobremer** [comment]
This is part of the json file of a warlock who'se eldritch blast damage was necrotic, then changed to force, used with damage rolls in chat and then back to necrotic.
![image](https://github.com/user-attachments/assets/9da8355c-999a-44a9-96c4-b63585ede740)
*both left and right are the same json i just copied everything to a new window so i could see both clearly at the same time

**Comment by itteerde** [comment]
Importing the item into SideBar, fixing there, dropping on Actor works. Has to be something caching or referencing?

**Comment by arbron** [comment]
Looks like this is caused by saving the last damage type, but not checking to ensure that the saved damage type is actually available in the possible damage types list.
