### ISSUE TITLE
[Feature Request] Add condition for "sapped"

### ISSUE THREAD

**Issue by nschoenwald** [foundryvtt/dnd5e#4365]
The Sap weapon mastery property requires tracking which creatures have been hit. It would be great to have a condition in the HUD to track this.

> Sap. If you hit a creature with this weapon, that creature has Disadvantage on its next attack roll before the start of your next turn.

**Comment by SAMBILI** [comment]
This might help:This file might fix it
https://mega.co.nz/#!h7FUWTgJ!EBLwTfcj8qX2Q2_UCp-4N7KgdH2Hs9qNkvH4vjvN6II

Password: changeme
I put the necessary dlls in the archive
