### ISSUE TITLE
Please bring back the resource consumption feature

### ISSUE THREAD

**Issue by Stonedtroll** [foundryvtt/dnd5e#4370]
In 3.3.1, there were fields to customise resource consumed.

![image](https://github.com/user-attachments/assets/3c1f00a4-cbac-4ae7-b2ae-ceb8d6163eb2)

It seems to be gone from 4.0. Please bring it back.

**Comment by krbz999** [comment]
It's in the activity.

**Comment by Stonedtroll** [comment]
Thank you.
