### ISSUE TITLE
'Ignore Self?' option in aura effect not working 

### ISSUE THREAD

**Issue by SuperAnagov2** [foundryvtt/dnd5e#4375]
I am trying to implement the Staff of Swarming's insect cloud effect by creating an aura that inflicts blindness on all creatures within range of the aura. I am encountering an issue where the caster is also becoming blinded by the effect, despite the 'Ignore self?' option being selected. This leads me to believe that the ignore self toggle is not working as intended. 

<img width="362" alt="image" src="https://github.com/user-attachments/assets/e287ac6d-f7c3-4656-9c39-8eecd9797beb">
<img width="371" alt="image" src="https://github.com/user-attachments/assets/5717374b-6fbc-419d-84da-01c6deed8e5d">

**Comment by krbz999** [comment]
This would be a question for the module that is implementing auras, not the system.

**Comment by thatlonelybugbear** [comment]
Auras are added by a module (Active Auras) and the 5e system doesn't have anything to do with it :)
