### ISSUE TITLE
Pluralize `Target` display of features that target multiple entities

### ISSUE THREAD

**Issue by M0nk3yy** [foundryvtt/dnd5e#4384]
The `Target` of a feature targeting 2 creatures shows as `2 Creature`.

![image](https://github.com/user-attachments/assets/7dff016f-db4d-4647-902e-114b5e3613c6)

![image](https://github.com/user-attachments/assets/8aabc6bd-e064-49a7-864f-ead88ec7be4d)

It would be nice if this could check if>1 and convert to `2 Creatures`.

This would also affect `Ally`, `Enemy`, `Object`, `Space`, `Creature or Object`, and `Willing Creature`. Most of these would append an `s` but   `2 Ally` would become `2 Allies` and `2 Enemy` would become `2 Enemies`, etc.

**Comment by arbron** [comment]
Related to https://github.com/foundryvtt/dnd5e/issues/1355 & https://github.com/foundryvtt/dnd5e/issues/3958
