### ISSUE TITLE
Bug or Feature Removed: Unable to swap ammunition type in new system 4.0.2

### ISSUE THREAD

**Issue by Kregoras** [foundryvtt/dnd5e#4402]
In the old system ammo could be chosen among the ones available so a player could choose normal arrow, +1, etc. Now there is no option to select the ammunition used on weapons with ammunition.

**Comment by krbz999** [comment]
This is done during the attack roll now.

![image](https://github.com/user-attachments/assets/064faa29-de29-43cd-8ab1-653866fa1c67)
