### ISSUE TITLE
Natural Melee attacks are defaulting to use dexterity instead of strength

### ISSUE THREAD

**Issue by DragonHale** [foundryvtt/dnd5e#4404]
I have checked in other types of weapons but I think only natural attacks do it. I'm using legacy rules in v4.0.2. Shouldn't they use strength by default? or strength or dexterity for the ones that are finesse? Dexterity only as a default should be only for ranged weapons.

I saw a similar open issue here already (https://github.com/foundryvtt/dnd5e/issues/2735), but that one was marked with compendium content tag...I am not in the compendium (although the monsters in the compendium have the same issue). I am trying to set up my own attacks and I am having to override the ability to use with them with strength even though they are melee.
<img width="375" alt="{D0DE8717-5A68-4294-8038-8CA308F1C538}" src="https://github.com/user-attachments/assets/13bc1f96-88a7-47ca-bf1a-7ddcb7937477">
<img width="373" alt="{332274A9-7097-4213-A954-04D0D924E04C}" src="https://github.com/user-attachments/assets/eb260524-2e4a-46bb-9afb-7b48913c9ca4">
<img width="375" alt="{F9F1D216-04A1-4938-AF4A-B524F0F28F12}" src="https://github.com/user-attachments/assets/806fc1e3-e120-423c-aa60-5b41dc2a3473">

**Comment by M0nk3yy** [comment]
I imagine most creatures with natural attacks use whichever stat is higher. I believe Default is looking at which stat is higher on the actor in this case.

**Comment by lholden** [comment]
I can confirm that Natural is always choosing dex regardless of str being higher.

**Comment by krbz999** [comment]
Seems to be all over the place.

If making an item with a spell attack, despite the activity saying "Default (Spellcasting)", it is still using DEX.

**Comment by Silentdarkness12** [comment]
+1 on this, and it's not just(for me at least) limited to Natural weapons.
All the weapons in a module i'm working on, save for Finesse-tagged weapons, are defaulting to dexterity over strength.
