### ISSUE TITLE
Enchanting with a destroyed item does not put the enchanted items in the chat message list

### ISSUE THREAD

**Issue by InnilToo** [foundryvtt/dnd5e#4407]
~~Currently when enchanting an item, dragging an item onto the chat message, the only feedback that the enchantment happened is a short pop up message about the actor's token which is easily missed.~~

~~I propose keeping the information in the chat messgae itself. A list of items (if multiple were enchanted) along with an indicator of the actor who own's the item.~~

![image](https://github.com/user-attachments/assets/861d7da0-2716-4452-b65f-1ef18cfefe98)
---
I would propose to have a limit of how many items can be enchanted (probably deserves a separate issue).
And also adding which actors owns the enchanted item.

**Comment by InnilToo** [comment]
Some more testing with help from @MaxPat931 shows that the issue occurs when the item that is doing the enchanting ("New Item" in this case) is se to "Destroy on empty" and it's last use was consumed.

**Comment by krbz999** [comment]
> I would propose to have a limit of how many items can be enchanted (probably deserves a separate issue).

This should already appear if the activity has Targets set (e.g. 5 Objects)

**Comment by MaxPat931** [comment]
Repro steps for enchanting with a Destroy on Empty enchantment item:
Use Item, consume use, drag item to enchant to chat card
Results:
Item is enchanted? Yes
Can enchant multiple items? Yes
Chat card is updated? No
Pop out message shows enchanted items? No

Workaround
Use Item, do not consume use, drag item to enchant to chat card, consume use from chat card
Results:
Item is enchanted? Yes
Can enchant multiple items? Only before use is consumed
Chat card is updated? Yes
Pop out message shows enchanted items? Only if popped out before use is consumed 

sample item [fvtt-Item-basic-poison-2V5m5crXrFfwqYNI.json](https://github.com/user-attachments/files/17104913/fvtt-Item-basic-poison-2V5m5crXrFfwqYNI.json)
