### ISSUE TITLE
A subclass that adds spellcasting is not tracking prepared spells

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/dnd5e#4423]
If you have a subclass that adds spellcasting, like the Rogue's Arcane Trickster, it's not tracking their prepared spells on the spellcasting tab. You prepare their spells and the number of prepared spells stays at `0`. You can see in this screenshot I have two spells prepared (and they're marked as Rogue spells) but the counter in the pill at the top stays at `0/3`.

![image](https://github.com/user-attachments/assets/462d0d55-9c82-4bce-90e7-b088abcaa467)

Steps to reproduce:

1. Create a new PC actor
2. Add the Rogue class to the actor
3. Create a subclass directly on the sheet to make the Arcane Trickster, in the Spellcasting section:
  a. Spell Progression => Third Caster
  b. Spellcasting Ability => Intelligence
  c. Preparation Formula => `3`
4. Drag over a couple of 1st-level spells from the Spells SRD compendium
5. Confirm that the spells have the Source Class set to Rogue
6. Prepare the spells and see the Prepared counter stay at `0`

And a related question... why does it use the class name for Source Class on the spells if it's the subclass that has spellcasting? Shouldn't it show the subclass name like it uses the subclass name in the screenshot above?

**Comment by kaelad02** [comment]
Actually, now that I think about it, I think that "related question" may actually be the cause of the issue. If the spells are tagged as Rogue spells, but the Prepared counter is looking for Arcane Trickster spells, that's probably why it's not working.

**Comment by asherett** [comment]
Can only confirm that I see the same.

This is only an issue for 2 subclasses as far as I can see: Arcane Trickster and Eldritch Knight. These are the only 2 core subclasses that add Spellcasting to a non-caster class.

However, in a separate bug, Eldritch Knight is completely missing a spells preparation formula:
![image](https://github.com/user-attachments/assets/224ddbd7-88d8-4438-b54f-7bc457f63271)

So we can't really test if this issue is present there or not.

**Comment by kaelad02** [comment]
@asherett Did you get Eldritch Knight from the new PHB module? If so, I'd file a separate issue for the missing Preparation Formula here to get that fixed: https://github.com/foundryvtt/foundryvtt-premium-content/issues

**Comment by asherett** [comment]
> @asherett Did you get Eldritch Knight from the new PHB module? If so, I'd file a separate issue for the missing Preparation Formula here to get that fixed: https://github.com/foundryvtt/foundryvtt-premium-content/issues

Yes. Just wanted to bring it up here since the same issue will be relevant for EK when prepared progression is added. I'll file a new issue.
