### ISSUE TITLE
[BUG] Spell Attack Bonuses from Enchantment Activity are not Applied

### ISSUE THREAD

**Issue by Hopelite** [foundryvtt/dnd5e#4429]
I try to apply effect with `system.bonuses.msak.attack` and `system.bonuses.rsak.attack` increases via Enchantment Activity (I'm implementing Artificer's "Enhanced Arcane Focus" infusion). However, enchanted this way items with this effect do not change the spell rolls, unlike to items with the same effect, but set manually.

## Steps to reproduce
1. Create a Feature with an Enchantment Activity.
   1.  In the Effects tab Add any value to `system.bonuses.msak.attack` attribute.
   2. The same for `system.bonuses.rsak.attack` attribute.
   3. Do not apply any restrictions to the Activity.
![image](https://github.com/user-attachments/assets/55011e2a-2649-4a3d-8e62-a5c23b638390)
2. Grant this Feature to an Actor.
3. Use this feature and drag any item into the chat template (like Staff):
![image](https://github.com/user-attachments/assets/7dab0c38-b3de-44bc-9dd4-81d474a9e74e)
4. Equip the item for the Actor.
5. Use any spell with either "Ranged Spell Attack" or "Melee Spell Attack" attack type Activity.

**Expected result**: the attack roll is increased by the `system.bonuses.msak.attack` or `system.bonuses.rsak.attack` value of the created effect.
**Actual result**: both melee and ranged spell attacks do not have the `system.bonuses.msak.attack` or `system.bonuses.rsak.attack` value applied:
![image](https://github.com/user-attachments/assets/9c8face5-eee1-4e9f-a5cd-c24ca8e89be5)

## Additional Info
**System version**: 4.0.3
**Foundry VTT version**: 12 Build 331

If the same effect was added manually to an item, not granted by an Enchantment Activity:
![image](https://github.com/user-attachments/assets/7b29d0b0-896c-435e-b846-a983b2c9aee9)

All bonuses are applied correctly:
![image](https://github.com/user-attachments/assets/09594356-5011-41aa-af66-d6046a74bb89)

**Comment by hakr14** [comment]
Effects to be added to the item like this need to be added as Additional Effects (or "Rider Effects") in the enchantment:
![image](https://github.com/user-attachments/assets/c405e690-cf1f-4f4e-ad19-f7fec6ed6aec)

**Comment by Hopelite** [comment]
Thank you for the quick answer! I definitely overlooked this field's purpose somewhere in the docs. Closing the issue.
