### ISSUE TITLE
Spells do not include any metadata or tags in chat card

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/dnd5e#4454]
This is especially a problem for spells with scaling targets or duration, because the scaled info is not available anywhere.

Note: I believe older versions of the system included this info as tags in the bottom, so it's possibly a bug?

**Comment by krbz999** [comment]
![image](https://github.com/user-attachments/assets/c19acd3a-755e-4b74-9521-ec37e5e1bdbc)

Seems to be all over the place.

**Comment by JPMeehan** [comment]
Might be related to a bad merge of spell tags & properties?
