### ISSUE TITLE
Fails to execute concentration spells

### ISSUE THREAD

**Issue by matsbierwirth** [foundryvtt/dnd5e#4468]
The new 4.0.4 seems to have broken the execution of concentration spells. Trying to cast one yields:
![image](https://github.com/user-attachments/assets/49073752-c305-4c3a-9d86-5ad3c4417e3b)

Probably introduced in [#4446]

**Comment by arbron** [comment]
Can't reproduce this issue. Is this a new spell you are concentrating on, or an existing spell that was being concentrated on before the new version?
