### ISSUE TITLE
D&D5e 3.3.1 - If Grid-Aligned Square Templates is disabled, it makes any template supposed to be a cube get created as a ray.

### ISSUE THREAD

**Issue by Silvestrae** [foundryvtt/dnd5e#4479]
D&D5e 3.3.1
**Simple steps to reproduce the bug**: Disable "Grid-Aligned Square Templates" in system settings, use a cube spell, check template's type and it'll say "Ray"

**Screenshots and/or console errors**:
This setting...
![image](https://github.com/user-attachments/assets/2aa8a395-fb6d-4f19-9c98-d522c99a43bc) - 

New/any spell set as a 5ft cube...
![image](https://github.com/user-attachments/assets/607ef48b-a9e2-4f2d-91fe-f9a873fd23d4) - 

produces this template as a 5ft Ray
![image](https://github.com/user-attachments/assets/42b61a20-29c6-4f25-a888-fd62db91c32b) -

**Comment by unsoluble** [comment]
This is intentional, as only a Ray can be rotated (in the way end users expect a rotation).

**Comment by Silvestrae** [comment]
I see. 
It has been creating havoc for images/animations assigned to the ray upon cast via other modules, such as this bonfire, of the entangle spell, or anything thinking its going to be attached to a cube.
![image](https://github.com/user-attachments/assets/16701a99-de25-44f2-a2fe-6408ed488391)

However I believe if it's intentional, then that would come down to being a module dev problem.

**Comment by unsoluble** [comment]
Yup :)

**Comment by Silvestrae** [comment]
Thank you for your quick replies.
