### ISSUE TITLE
Actor's `_onUpdate` HP-Related Code Triggers on Non-HP Update

### ISSUE THREAD

**Issue by Larkinabout** [foundryvtt/dnd5e#4485]
I've noticed I'm getting the scrolling text displayed multiple times with my module code where it sets an actor flag within the `updateActor` hook. It seems to be because my module's `setFlag` actor update triggers the `_onUpdate` before the HP-related update has fully resolved and therefore `curr.value` has not yet changed. All that's included in the `data` for my actor update is the `flags` object.

I think this might be avoidable by only executing the HP-related code if the update is HP-related, i.e., `data` contains `system.attributes.hp`.

**Comment by Larkinabout** [comment]
Additionally, it also seems to cause the creation or deletion of the Bloodied effect twice causing an error about the effect already, or not, existing. A quick fix for most instances might be to also check for a HP change to trigger `updateBloodied`. But, it doesn't really solve the issue of multiple updates happening in quick succession causing the same code to repeat in `_onUpdate`.

**Comment by arbron** [comment]
Can you pose a concrete reproduction example? Preferable without requiring your module.
