### ISSUE TITLE
[Feature Request] Add Active Effects to Half and Three-Quarters Cover

### ISSUE THREAD

**Issue by Tex1090** [foundryvtt/dnd5e#4489]
Currently applying the 'Half Cover' and 'Three-Quarters Cover' only applies a status icon but still requires manual input of -2/-5 to an attack or manual adjustment of the AC.

It would be nice for those two statuses to apply the AC bonuses automatically while the status is applied to an actor, which will help avoid players and GMs forgetting to add a situational bonus of -2/-5 to the roll dialog and keeping the visuals for hits/miss in the chat cards consistent to the AC of an actor.

**Comment by krbz999** [comment]
*Insert witty comment here.*
