### ISSUE TITLE
[Feature Request] Add Pact Slot as selectable consumption target under Spell Slots

### ISSUE THREAD

**Issue by jennis0** [foundryvtt/dnd5e#4494]
When configuring an activity which consumes spell slots, only standard levelled spells are available as possible targets. Ideally it should be possible to target Pact Slots as well. It would be valuable to be able to create activities which consume (or restore) pact slots. Currently (as far as I can tell) the only way to do this is to assign Pact Slot as a standard attribute once the item has already been attached to an entity which isn't ideal when creating compendium content.

![image](https://github.com/user-attachments/assets/e2a0580b-e547-416d-93be-c58885a1f04d)

**Comment by arbron** [comment]
You'll have to use attribute consumption and just type the key path in manually: `spells.pact.value`

The "Spell Slots" consumption is different because it requires the ability to scale by spell slot level, which isn't necessary for pact slots.
