### ISSUE TITLE
Character sheet not opening correctly due to item validation errors

### ISSUE THREAD

**Issue by penumbraldragon** [foundryvtt/dnd5e#4501]
[fvtt-Actor-yojimbo-nzGuolCUJmkILMEJ.json](https://github.com/user-attachments/files/17249229/fvtt-Actor-yojimbo-nzGuolCUJmkILMEJ.json)

This is the sheet in question. I tried checking in the foundry discord for assistance, they said to submit a ticket. The character sheet appears to fail to open because the character has both resistance and immunity to force damage. I have no idea what I'm doing, but I can provide any information that could help.

**Comment by JPMeehan** [comment]
To add in I popped open the debugger and found it breaking here
![image](https://github.com/user-attachments/assets/8f31a85f-7be5-4d1c-afdc-9842d373cf28)

**Comment by JPMeehan** [comment]
Stepped through the debugger in a more thorough fashion; I was mistaken it's not about force damage it seems to be related to concentration

![image](https://github.com/user-attachments/assets/e4acbe47-e2f6-44f8-9fc5-8e5b8e5e7ab1)

**Comment by JPMeehan** [comment]
This seems to suggest there's a bad migration for concentration effects

**Comment by krbz999** [comment]
That would explain why disabling the effects had no effect. There was a related change here in v4.0.4.

**Comment by krbz999** [comment]
The repro steps are pretty simple.
- Be on 4.0.3.
- Concentrate on a spell. (Might need to be a scroll that is then deleted.
- Update to 4.0.4.
- Attempt to render actor sheet.

This was probably caused by #4446.

**Comment by krbz999** [comment]
The temporary fix here is to delete all effects on the actor that are for tracking concentration.

```js
const actor = game.actors.getName("<actor name>");

for (const effect of actor.effects) 
  if (effect.statuses.has("concentrating"))
    await effect.delete();
```
