### ISSUE TITLE
[Feature] Journal Type - Creature/Actor list.

### ISSUE THREAD

**Issue by robgrahamau** [foundryvtt/dnd5e#4509]
It would be really nice to have a Creature/Actor list journal type that worked similar to how the spell-list journal entry does. 
It would allow you to drag over actors and then do a short on them suggestions:
Type, CR, Name, Size, Alignment.

This would allow for a lot easier look up rather then having to go through  mass amounts of entries each time.

**Comment by JPMeehan** [comment]
Shouldn't this just be an improvement of the compendium browser? The reason for spell lists is so the class info doesn't have to go on the spell item itself

**Comment by robgrahamau** [comment]
Both? There are times when you need monster lists for either encounter
sections on book or modules etc that allow for dm's except painfully by
hand.

**Comment by JPMeehan** [comment]
Wouldn't that be a Group actor, then?

**Comment by robgrahamau** [comment]
Groups don't allow you just to list and sorry there full groups.
I'll give a few examples lets say you have say a module like the older
undermountain rather then the newer one were you want to go encounters can
include these monsters based on what cr you need just grab something.

Currently you have zip way to just list and sort the monsters ir actors.

A group is designed for just that a group or party not for sorting
individual actors etc.

Compendium would work for getting lists across all modules so example I
want to see all beasts sorted by cr or all beasts of cr2 etc

But lets say your trying to produce something like just the monster manuals
cr lists? You have to manually enter ever item into a journal and can not
easily sort them. A list format like the spell list I can just drag every
entry over and ask it to sort by cr or by type etc.

And woth foundry handling more and more full sourcebooks the need to be
able to create entries for sorting across multiple encounter levels or just
to quickly look is needed more.
