### ISSUE TITLE
Updating to v4 breaks weapons with multiple damage types

### ISSUE THREAD

**Issue by flogiston1** [foundryvtt/dnd5e#4511]
Updating to version 4 (from version 3.3.1 to 4.0.4 specifically for me) doesn't migrate weapons with two damage types correctly. Problem is that only the first row of damage gets migrated to the new weapon (both base item, and attack activity), and second row disappears. This seems to affect weapons only, or at least on features it works as should.

I tested this with custom copies (not from srd compendium) of flame tongue and a death knight, of which flame tongue deals slashing and fire damage, and death knight has two features dealing dual damage: his sword and hellfire orb. Hellfire orb gets migrated correctly, but his sword loses it's necrotic damage. Flame tongue also deals only slashing after migration, and fire damage has disappeared.

Gave named examples so I don't have to explain as much, tested it on some other stuff too with similar results. These were tested as imported to a world, and this does seem to affect both things in world and in compendiums (after running migration scripts on those).

**Comment by flogiston1** [comment]
Just to add, I don't know if this only affects weapons, but at least doesn't seem to affect features. I did not do extensive testing though.

**Comment by JPMeehan** [comment]
Given that the MIDI-verse folks still haven't migrated to 4.0 yet, it seems like there's still going to be a lot of people who could use help with this migration.

**Comment by gatesvp** [comment]
This isn't just a migration problem. It looks like the Flametongue in the SRD Items Compendium is just broken and not clearly fixable. Here's a screenshot highlighting the problem. It looks like you can add damage types, but it doesn't really work.

![image](https://github.com/user-attachments/assets/f4e30966-b95e-4b73-b670-ee69983ef59b)

**Comment by krbz999** [comment]
Well the flametongue weapons were never set up correctly in the SRD before v4 either. They are fixed on the 4.1 branch.

Not sure what you suggest does not really work here, as adding additional damage parts in an Attack activity is easy enough to do by clicking that "+" button.

**Comment by gatesvp** [comment]
> Well the flametongue weapons were never set up correctly in the SRD before v4 either...

OK, so this is definitely what I was seeing. My "reference weapon" was basically broken.

> as adding additional damage parts in an Attack activity is easy enough to do by clicking that "+" button...

This was not working for me on certain items. Like the "+" button was simply not adding a section. I can't repro this right now, so I'll let it be.
