### ISSUE TITLE
Summoning Mage Hand Causes an Error

### ISSUE THREAD

**Issue by Stonedtroll** [foundryvtt/dnd5e#4519]
Placing Mage Hand fails with the following error.

![image](https://github.com/user-attachments/assets/769c9960-6258-43c3-bf15-9bd9794fcea5)

Fresh install with no other modules except:

Foundry: 12.331
DND5e: 4.0.4
PHB 2024: 1.2.0

**Comment by arbron** [comment]
Can't reproduce this myself with the SRD or PHB version of Mage Hand, but I can see what might be causing it. You should be able to edit the "Summon" activity on the Mage Hand spell and ensure that the Attack, Save, and Healing bonus fields all have `0` in them.

**Comment by Stonedtroll** [comment]
Thank you!
