### ISSUE TITLE
Can't edit some items and spells DND 4.0.4

### ISSUE THREAD

**Issue by Chikubi-ai** [foundryvtt/dnd5e#4523]
I can't edit many of items and spells. No modules active
Next message in console
![image](https://github.com/user-attachments/assets/1dcc58d4-7920-47e4-9be8-a80ed4fe0fd7)

**Comment by roth-michael** [comment]
Looks like you at least have libWrapper enabled. I'd double check that you _actually_ have no modules active.

**Comment by Chikubi-ai** [comment]
> Looks like you at least have libWrapper enabled. I'd double check that you _actually_ have no modules active.

Even in world without modules and using SRD, still the same problem

**Comment by roth-michael** [comment]
Can you show the console error in a module-less world?

**Comment by unsoluble** [comment]
Can you please bring this one to the [Discord server](https://discord.gg/foundryvtt) for investigation? Otherwise we're going to need you to provide a _lot_ more context: Host setup, client browser (and version), core build, specific items involved, where you're trying to edit them, to start.

**Comment by Chikubi-ai** [comment]
> Can you show the console error in a module-less world?

![image](https://github.com/user-attachments/assets/412eeec9-6f82-42d1-b663-306b0a97390a)
