### ISSUE TITLE
Changing situational bonus on damage roll input programmatically fails unexplicably

### ISSUE THREAD

**Issue by theripper93** [foundryvtt/dnd5e#4528]
DND: 4.0.4
FVTT: 331

Steps:
- Start any damage roll to get the dialog
- Run `document.querySelector(`[name="roll.0.situational"]`).value = 25` as a macro or in the console
- Confirm the input has the actual value
- Roll damage
- The bonus is not added

Calling `.closest("form").dispatchEvent(new Event("change"))` will fix the issue, but it's kinda odd

**Comment by krbz999** [comment]
The rolls are rebuilt when the inputs change, as you saw by dispatching a change event listener. I believe this is working as intended.

**Comment by theripper93** [comment]
I guess if this should be taken up to core. Dispatching a change event to the input itself seems to not propagate it to the form, which i find odd. In any case ye, after some investigation it's not a dnd issue, i should have opened this in core but this was an easy repro example.

**Comment by arbron** [comment]
> I guess if this should be taken up to core. Dispatching a change event to the input itself seems to not propagate it to the form, which i find odd. In any case ye, after some investigation it's not a dnd issue, i should have opened this in core but this was an easy repro example.

Note that change events aren't triggered by programmatic changes to inputs, only direct user interaction, so this seems to be working as expected.

**Comment by theripper93** [comment]
> > I guess if this should be taken up to core. Dispatching a change event to the input itself seems to not propagate it to the form, which i find odd. In any case ye, after some investigation it's not a dnd issue, i should have opened this in core but this was an easy repro example.
> 
> Note that change events aren't triggered by programmatic changes to inputs, only direct user interaction, so this seems to be working as expected.

Ye, i'm aware, i tested by dispatching a change on the input itself
