### ISSUE TITLE
can not add map

### ISSUE THREAD

**Issue by JanusTrush** [foundryvtt/dnd5e#4530]
the size of the image is 1296 x 1392

https://cdn.discordapp.com/attachments/494726439263010826/1294348024641753170/IMG_4572.jpg?ex=670aaf08&is=67095d88&hm=1adb3166981ea58ca6a076cfadae793da717dbeceecc87fe36e409cc1b31ee86&

**Comment by arbron** [comment]
Not related to dnd5e, I suggest taking this up on Discord for troubleshooting and if a issue is found file it on the core repo: https://github.com/foundryvtt/foundryvtt/issues
