### ISSUE TITLE
Spellmod no longer usable in item uses

### ISSUE THREAD

**Issue by SylisCloud** [foundryvtt/dnd5e#4538]
@attributes.spellmod does not seem to work when put into Limited Uses. I made sure Spellcasting ability is set accurately. It does work for damage rolls though. I tested this on a world with modules and one without, and had a friend test it too on their machine with no modules, all had the same result. It says the data is missing.

Recreate:
1) put spellcasting class onto a character sheet with stats set to any number other than 10
2) Created a new feature and plugged in @attributes.spellmod  into Limited Uses

![image](https://github.com/user-attachments/assets/c2736250-aed3-48b8-ab2c-ff953bb2f194)
![image](https://github.com/user-attachments/assets/006d9151-9151-4e2c-963c-61204e7cd882)

**Comment by arbron** [comment]
Looks like we moved spellcasting preparation until after item data preparation to fix a different issue in the previous version. We should be able to move just the `spellmod` part earlier in the process to fix this issue.
