### ISSUE TITLE
Feature Request: Add an option to limit Attribute Score Improvement Advancement to only specific attributes

### ISSUE THREAD

**Issue by BlackOtter9** [foundryvtt/dnd5e#4552]
Certain features, such as 2024 backgrounds, allow point allocation to specific sets of 3 or more attributes instead of all 6. 
With the current implementation there is only one way to prevent a non-designated attribute from being increased, which is by giving it a fixed value: 

> "If there is a fixed improvement then a lock symbol will display next to the change and they player won't be able to modify it using the controls". 

This doesn't support the value of 0, so it is impossible to make an attribute non-increasable.

**Comment by arbron** [comment]
That is entirely possible, and how the backgrounds in the PHB are implemented. Just hit the "Locked" checkboxes:

<img width="423" alt="Screenshot 2024-10-18 at 08 39 28" src="https://github.com/user-attachments/assets/da66ac21-f553-40b7-b3b8-7477c582afcb">
