### ISSUE TITLE
Starting a drag-and-drop on an item's icon to the macro hotbar does not create a macro

### ISSUE THREAD

**Issue by Krigsmaskine** [foundryvtt/dnd5e#4559]
If you start your drag-and-drop on an item's icon, to drag it to the macro hotbar to create a quick `dnd5e.documents.macro.rollItem` macro, it fails. Starting it on the title of the item makes it work as usual. 

fvtt 12.331
dnd5e 4.0.4
no modules

**Comment by arbron** [comment]
Seems like dragging from the image doesn't result in any of the correct drag data from being stored, so drops anywhere that would normally work for items don't.

**Comment by arbron** [comment]
Also, only happens for the actor sheet inventory, not container inventories.

**Comment by arbron** [comment]
Okay, looks like this is happening because images default to `draggable="true"` in browsers, causing it to trigger a drag event even though the system sheet hasn't defined it as a draggable element.
