### ISSUE TITLE
Item behaves erratically after drag-and-dropping from an actor sheet onto the macro hotbar

### ISSUE THREAD

**Issue by Krigsmaskine** [foundryvtt/dnd5e#4560]
After drag-and-dropping an item from an actor sheet onto the macro hotbar, you can no longer use the expand button and the item itself can start behaving oddly regarding rollData; I've had Rage lose its' scale value and be basically unable to be used.
![image](https://github.com/user-attachments/assets/584baf2b-ef1f-4536-88cf-1be285f8a512)

Tested with multiple SRD heroes on no module world
fvtt 12.331
dnd5e 4.0.4

repro:
1. create new world
2. import srd hero
3. open srd hero and drag a feature onto the macro hotbar

it should start behaving oddly after

**Comment by arbron** [comment]
Seems like it the same issue as this, just in a different spot: https://github.com/foundryvtt/dnd5e/issues/4428
