### ISSUE TITLE
Forcing AttackActivity.rollDamage to crit?

### ISSUE THREAD

**Issue by crash1115** [foundryvtt/dnd5e#4571]
I'm not sure if this is just me failing to read documentation or a very minor oversight since activities were such a massive undertaking, but how do you programmatically force `AttackActivity.rollDamage` to crit?

I can see that `rollConfig.rolls` (which gets set up in the first line of the `rollDamage` method) is what houses the data for if a roll is a crit or not, but there doesn't seem to be a way to override that. (Maybe you could do it with hooks, but that doesn't help for macros.) Is there a way to do this that I'm missing?

 If not, can such a thing get added? Something like this would do the trick:
```js
const sword = myActor.items.getName("Longsword");
const activity = sword.system.activities.getByType("attack")[0];
await activity.rollDamage({isCritical: true});
```

Thanks!

**Comment by krbz999** [comment]
Tried several variations myself and wasn't successful. I don't believe this is possible any longer.
