### ISSUE TITLE
Items with long range only show the short range in the chat card

### ISSUE THREAD

**Issue by kaelad02** [foundryvtt/dnd5e#4582]
With the 4.0 update, there is a bug where weapons that have a short and long range only show the short range on the chat card or if you expand the item in the character sheet. I'm guessing there's a bug in when generating the `labels.range` property. And as an example, here is the bottom of a Longbow's chat card, only showing the range of "150 ft" instead of "150/600 ft" or whatever the formatting used to be.

![image](https://github.com/user-attachments/assets/bdd19b4b-2568-4306-965a-e69c35e985c5)

**Comment by JPMeehan** [comment]
Related #4454
