### ISSUE TITLE
Active Effect Bug: Modifiers cant be added to scale values

### ISSUE THREAD

**Issue by Zanderaf** [foundryvtt/dnd5e#4585]
When trying to modify a scale value via an active effect
system.scale.blood-hunter.vital.modifiers / add / kl 
(the scale value just being a simple 1d4 going to 1d10), it errors out. This happens with every other dice modifier as well, such as xo, x, kh, etc.
![image](https://github.com/user-attachments/assets/eaf05a3a-b38a-42a7-9608-10df8156508a)

**Comment by krbz999** [comment]
Seems like it's bludgeoning `ScaleValueTypeDice#modifiers` into a string despite explicit support for adding a string to a set.
