### ISSUE TITLE
In "Cast" activity, set "Material" as an ignored property by default

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#4588]
Seems like a sensible default.

from the Basic Rules on DDB:
_"Some magic items allow the user to cast a spell from the item. The spell is cast at the lowest possible spell and caster level, doesn't expend any of the user's spell slots, and **requires no components**, unless the item's description says otherwise."_

Emphasis mine. Whether that includes Verbal and Somatic, I am not entirely sure.

**Comment by krbz999** [comment]
I suppose this default should only apply if the parent item is a physical item. A _feat_ that allows you to cast Misty Step for example shouldn't necessarily remove components.

**Comment by arbron** [comment]
> I suppose this default should only apply if the parent item is a physical item. A _feat_ that allows you to cast Misty Step for example shouldn't necessarily remove components.

Much harder to do defaults that only apply for only one item type since they would have to be handled outside data models. Probably simpler for now to just fill those by default and let people delete them if it isn't on a physical item.
