### ISSUE TITLE
Bug: Second wind is not righ

### ISSUE THREAD

**Issue by thystra** [foundryvtt/dnd5e#4606]
Second wind should be 1D10+fighter level, instead does a fixed roll of 4+10. 2024 character.

**Comment by arbron** [comment]
Not seeing that issue, both the versions in the SRD and the Player's Handbook module contain the correct healing formula:

<img width="1076" alt="Screenshot 2024-10-28 at 13 14 02" src="https://github.com/user-attachments/assets/20463e1c-1973-4eea-bed1-b98f04051812">
