### ISSUE TITLE
Bug: Synaptic static does not apply attack roll penalty

### ISSUE THREAD

**Issue by thystra** [foundryvtt/dnd5e#4608]
Monsters that fail Synaptic Static saving throw should have a 1d6 penalty to attack rolls until (if) they pass the saving throw.

**Comment by JPMeehan** [comment]
Synaptic Static is not part of the SRD. Did you mean to report to https://github.com/foundryvtt/foundryvtt-premium-content ?

**Comment by arbron** [comment]
Synaptic Static also does have an effect in the PHB, so it seems like it should work like stated.
