### ISSUE TITLE
Consider allowing fractions in the CR input field

### ISSUE THREAD

**Issue by JPMeehan** [foundryvtt/dnd5e#4625]
The v2 NPC sheet uses a `number` input for the CR field, which doesn't accept a `/` as a valid character. This means all fractional challenge ratings must be entered as decimals, an unintuitive requirement.

One alternative would be to add a data list that just provides the 0.125, 0.25, and 0.5 values.

**Comment by arbron** [comment]
The old code for converting fractions back to decimals still exists in the system, so it looks like this is just because it uses a number input rather than a text input.
