### ISSUE TITLE
Item._stats.compendiumSource Not Added with Advancements

### ISSUE THREAD

**Issue by aldenparker** [foundryvtt/dnd5e#4631]
**Bug:**
When adding a class, subclass, race, or background and going through the advancements, no compendiumSource value is added to the items _stats field. compendiumSource is also not added to the class, subclass, race, or background when clicking on "Add ______" in the character sheet and choosing the respective item. 

**Versions Details:**
Foundry Version: 12.331
DND5E Version: 4.0.4
Hosting: Local

**Steps to Reproduce:**
1. Create a new world with the DND5E game system.
2. Create a new Player Actor named TestActor.
3. Add one of the SRD class, subclass, race, or background to the Actor and click through the advancements.
4. Open the javascript console and type ```game.actors.getName("TestActor").items```.
5. Hit enter and explore the items of the character.
6. Opening the _stats field of any item will show that it's compendiumSource field is null.

**Other Notes:**
This bug was found when trying to create a macro that updates items on a world actor based on the items in their original compendiums. I noticed that the sorcedItems field does contain the items and their full UUIDs, however upon using those and updating the items via .updateEmbeddedDocuments(), the sorcedItems map no longer contains the updated items. Is this intended?

**Comment by krbz999** [comment]
The reason is probably the same as https://github.com/foundryvtt/dnd5e/issues/4569
