### ISSUE TITLE
Avoid column break inside fieldsets on 4.1 tool config

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#4643]
Currently on the 4.1 branch:

![image](https://github.com/user-attachments/assets/15954079-442c-48ac-8cf3-21457303ad3e)

**Comment by arbron** [comment]
Chrome *shakes fist*

Unfortunately using `break-inside: avoid` on the fieldsets in Chrome causes them all to fall into a single column:

<img width="606" alt="Screenshot 2024-11-05 at 10 10 57" src="https://github.com/user-attachments/assets/9d53265b-23c3-4b14-9cc6-25a05aa3770e">

Works perfectly in Firefox even without that property, but I haven't been able to find a solid solution to prevent this in Chrome.

**Comment by Fyorl** [comment]
@bertolinimarco Looks like that does the trick, thank you
