### ISSUE TITLE
[4.1] Spells from a Cast activity on a Feature item do not appear on the spellbook tab

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#4666]
![image](https://github.com/user-attachments/assets/2d5d25e4-6ec9-42ea-ac0d-d54aa8ce9cc7)

**Comment by Fyorl** [comment]
We should probably change the name of the heading on the spells tab to something more generic, like 'Additional Spells'.

**Comment by arbron** [comment]
> We should probably change the name of the heading on the spells tab to something more generic, like 'Additional Spells'. I also noticed that items that do not require attunement, like the Wand of Magic Missiles, do not show their spells under 'Item Spells' even if they are equipped.

I am seeing Wand of Magic Missiles spell displaying properly.

<img width="475" alt="Screenshot 2024-11-08 at 10 03 05" src="https://github.com/user-attachments/assets/7842d2ff-c851-4e02-ba2e-17622661dcd0">
<img width="770" alt="Screenshot 2024-11-08 at 10 02 54" src="https://github.com/user-attachments/assets/17c58660-ce2d-4dd7-b428-1b139259d668">
