### ISSUE TITLE
Character sheet cannot display appropriately 

### ISSUE THREAD

**Issue by ChenQTYF** [foundryvtt/dnd5e#4668]
![Screenshot_20241109-004755](https://github.com/user-attachments/assets/20b03b4c-98f4-4294-ba5f-046815f9c045)
![Screenshot_20241109-004812](https://github.com/user-attachments/assets/1fb75327-7df0-43d8-b8b6-bc1a306a66cf)
In 4.0.4 Character Sheet cannot display appropriately in pad and mobile device. 
In older version use Legacy 5e Character Sheet in pad and mobile device would be like following.
<img width="600" alt="Snipaste_2024-11-09_01-12-30" src="https://github.com/user-attachments/assets/f443fa88-bc8e-4cef-97f1-23a29f8134da">
In older version use Tidy 5e Character Sheet in pad and mobile device would be like following.
<img width="600" alt="Snipaste_2024-11-09_01-11-33" src="https://github.com/user-attachments/assets/2638106f-38aa-420c-a5de-30f11ae8f74e">

**Comment by arbron** [comment]
Looks like you have some module preventing the system's from loading properly, head over to the Discord for troubleshooting.

**Comment by ChenQTYF** [comment]
On first and second images, I didn't use any module. It's a new world running without any module.
