### ISSUE TITLE
[4.1] @item.level not being parsed in summoned creatures hit points

### ISSUE THREAD

**Issue by ctbritt** [foundryvtt/dnd5e#4682]
When using the summon activity that alters the summoned creatures HP based on spell level, @item.level is not computed properly. 

For instance, in Summon Aberration, the HP of the summoned creatures is 40 + 10 per each level of the spell above 4. So a 5th level summon should result in 50 HP. 

Here's the set up in the summon activity. 
<img width="483" alt="image" src="https://github.com/user-attachments/assets/3f90e2b0-e152-4fda-aacf-0422bc5306da">

Here's the HP set up for the pre-summoned creature
<img width="809" alt="image" src="https://github.com/user-attachments/assets/a9f61aec-9cac-4c50-b6cb-6dfb350bcead">

And here's what happens when you summon it at 5th level:
<img width="418" alt="image" src="https://github.com/user-attachments/assets/541ec840-0667-4365-9457-6375b13a5dff">

It's setting the HP to what the additional HP would be (10 extra in this case) instead of the base 40 + the summoned bonus.

**Comment by arbron** [comment]
Not able to reproduce this the current release, here is the 4th level & 5th level summons using the copy of the spell from Tasha's & the PHB:

<img width="785" alt="Screenshot 2024-11-10 at 16 14 44" src="https://github.com/user-attachments/assets/b63828f5-56c6-41eb-99c0-0bf8f9558137">

<img width="703" alt="Screenshot 2024-11-10 at 16 17 29" src="https://github.com/user-attachments/assets/ed161a02-943c-433c-a218-67fa733583c6">

Any modules installed?

**Comment by ctbritt** [comment]
found the issue; module conflict.
