### ISSUE TITLE
[4.1] Bug: Alert Feat (2024) Incorrectly applied for initiative

### ISSUE THREAD

**Issue by thystra** [foundryvtt/dnd5e#4684]
- 2024 Alert Feat applies Prof Bonus in addition to Dex Mod ~~, and rolls at advantage.~~
- DND 4.1.0 seems to indicate that, but incorrectly display initiative bonus in character sheet, and only rolls D20+Dex Mod, Not D20+dex+Prof. 

Screen Cap of interaction:
https://www.dropbox.com/scl/fi/79luelec072b8cbrmg8th/Screencast-From-2024-11-09-20-40-15.webm?rlkey=lm5ac2izgyqicgipqy7s7ll9n&dl=0

Foundry Initiative:
![Screenshot From 2024-11-09 20-28-48](https://github.com/user-attachments/assets/38be8d20-90e6-4493-8181-906e2d57eb80)
Chat log after rolling:
![Screenshot From 2024-11-09 20-25-24](https://github.com/user-attachments/assets/1e5a5966-d33e-4889-a4bb-13573229d73a)

DND Beyond Character:
![Screenshot From 2024-11-09 20-26-15](https://github.com/user-attachments/assets/1c5bd2ce-08cb-4544-a574-3f4014b17271)

**Comment by SDoehren** [comment]
Alert in 4.0.4 and 4.1.0 is incorrect.  
It is adding a flat +5.  
It should be +Prof (in addition to d20+dex).

But alert does not give advantage.

Your Barbarian is getting advantage from Feral Instinct, which is a level 7 feature.


> Initiative Proficiency. When you roll Initiative, you can add your Proficiency Bonus to the roll.

> Feral Instinct. Your instincts are so honed that you have Advantage rolls.

**Comment by thystra** [comment]
Ok, thanks for the correction. 

However Foundry was not properly rolling with advantage nonetheless. It would show the 2d20kh but only roll/show results of 1 die.
