### ISSUE TITLE
System Migration to 4.1 never ends

### ISSUE THREAD

**Issue by JPolycarp** [foundryvtt/dnd5e#4694]
Hello, 

I use the Forge as my server.

I updated to 4.1 and I got this:
![Screenshot 2024-11-10 235314](https://github.com/user-attachments/assets/3e9084e2-2780-4e99-a254-0cad566e41c8)

I went to discord and was told to launch in safe mode.

So I did, I'm getting similar results
![Screenshot 2024-11-11 003811](https://github.com/user-attachments/assets/f6764e39-07eb-49f5-bd4a-f1c91c3977ea)

Any direction would be appreciated.

**Comment by unsoluble** [comment]
Please let the migration finish (you will see a similar blue banner when it’s done), and then return to the discord for further troubleshooting of the issues with your item data.

**Comment by JPolycarp** [comment]
Dude, you're everywhere!
I used the link for issues for the Game System.
I'll leave it up all night and see what happens in the morning.

**Comment by JPolycarp** [comment]
It finished and is working (mostly) fine.  I have to figure out why my HUD doesn't work.  I appreciate your help and patience.
I imagine your profile pic is for having to answer questions like mine all the time.
:)
