### ISSUE TITLE
Chat buttons after issuing Barracks enlarge order throw errors

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#4714]
repro:
- add Barracks facility to actor
- click Barracks facility
- issue Enlarge order
- click any resulting button in chat

![image](https://github.com/user-attachments/assets/e4db5ba0-2480-4c99-84a1-dd887355ba0f)

**Comment by arbron** [comment]
Looks like this is happening because the synthetic activity we use for the Enlarge order is no longer available on the item because it has been fully enlarged.
