### ISSUE TITLE
Unidentified names not display properly

### ISSUE THREAD

**Issue by lholden** [foundryvtt/dnd5e#4730]
Right now if you mark an item as unidentified, the name shows up as blank when viewing the item card, but it has the original name when in an Actor's inventory.

It would be really nice if the system could automatically generate a default obfuscated name for the item using the equipment type.

For example, an unidentified Wand could be called "Unidentified Wand" when a custom unidentified name hasn't been provided for its unidentified form.

![image](https://github.com/user-attachments/assets/7439a42f-bfea-4ef3-b962-aff9a49e3650)

**Comment by arbron** [comment]
The system does this already, but it looks like there is a bug in the current version causing problems.
