### ISSUE TITLE
Spells - Available Classes

### ISSUE THREAD

**Issue by Artromix** [foundryvtt/dnd5e#4733]
When creating spells, it would be valuable to have a list of classes that spell is available to - which is shown on the spell description. When making/editing spells on the details tab, you can quickly select the core 5e classes + open text for homebrew/unofficial classes.

I.e.,

**Casting Time:**
**Range:**
**Components:**
**Duration:**
**Classes:**

**Comment by krbz999** [comment]
This would be done with a Spell List page.
