### ISSUE TITLE
[BUG] A feature is placed in the Other Features category even though the Type is specified as Species Feature

### ISSUE THREAD

**Issue by Stonedtroll** [foundryvtt/dnd5e#4753]
A feature is placed in the Other Features category even though the Type is specified as Species Feature.

![image](https://github.com/user-attachments/assets/d639552e-908a-4c90-ac91-3b7103506b7e)

![image](https://github.com/user-attachments/assets/37c1485d-fc50-49a8-9d3b-833e1005e58c)

Version 4.1.1

**Comment by JPMeehan** [comment]
Not technically a bug, the sorting is based on the advancements system rather than feature type.

**Comment by Stonedtroll** [comment]
Could you expand or point me to where I can read up on this? I do not understand what an "advancements system" is. Thanks.

**Comment by JPMeehan** [comment]
https://github.com/foundryvtt/dnd5e/wiki/Advancement

**Comment by Stonedtroll** [comment]
Thanks. So to have it grouped correctly, I would have to modify the species item.
