### ISSUE TITLE
Monk - Unarmored Movement - Movement bonus is not applied after level 2

### ISSUE THREAD

**Issue by alandsidel** [foundryvtt/dnd5e#4754]
Honestly don't know if this is a dnd module bug or a core FoundryVTT but, or a usual, if I'm just doing something wrong on my side.

When leveling up a Monk, they receive a +10 to movement at level 2, and an additional +5 at levels 6, 10, 14, and 18.  Similarly there is a martial arts die which starts at 1d4 at level 1 and increases at various levels, and advances to 1d6 at level 5.  Both of these are correctly reflected in the included class from the SRD and use scale tables for the advancement.

When advancing to level 5 the martial arts die correctly changes from 1d4 to 1d6 as expected.

When advancing to level 6 however, for some reason, the unarmored movement bonus does not increase from +10 to +15 as the scale chart indicates it should and still shows "monk 2" when being hovered over on the effects tab of the character sheet.

**Comment by krbz999** [comment]
Related: https://github.com/foundryvtt/dnd5e/issues/3505

**Comment by alandsidel** [comment]
> Related: #3505

Same bug entirely.  I did search but somehow missed that result.  The responses over there aren't making much sense to me though.  I don't know what "DAE" is and this scale table is a core feature that ships with the world module.  Why go through all the effort of adding in the scale table if it doesn't actually work?  Why does it work the first time @ lvl 2 and just never again?
