### ISSUE TITLE
Actor's sourcedItems not properly cleared during delete update from consumption of destroy-on-empty item

### ISSUE THREAD

**Issue by roth-michael** [foundryvtt/dnd5e#4764]
Can easily be replicated with a healing potion; use its final charge/quantity on a sheet, then immediately try to drag another of the same item onto the sheet. Causes a problem with this function in `module/applications/actor/sheet-mixin.mjs`:
```js
_onDropStackConsumables(itemData, { container=null }={}) {
  const droppedSourceId = itemData._stats?.compendiumSource ?? itemData.flags.core?.sourceId;
  if ( itemData.type !== "consumable" || !droppedSourceId ) return null;
  const similarItem = this.actor.sourcedItems.get(droppedSourceId, { legacy: false }) // <-- this.actor.sourcedItems still has the now-deleted item
    ?.filter(i => (i.system.container === container) && (i.name === itemData.name))?.first();
  if ( !similarItem ) return null;
  return similarItem.update({
    "system.quantity": similarItem.system.quantity + Math.max(itemData.system.quantity, 1)
  });
}
```
I wasn't able to determine _why_ `sourcedItems` isn't properly updated, though.

**Comment by arbron** [comment]
Looks like the system isn't checking whether an item is real or temporary, so when we revive items to roll damage they are being added to `sourcedItems` even though they don't actually exist on the actor.
