### ISSUE TITLE
Problem with Spell List in Journal (Permission)

### ISSUE THREAD

**Issue by ZeroLul** [foundryvtt/dnd5e#4801]
![image](https://github.com/user-attachments/assets/2325d1a4-7f9d-411a-9594-2b3793a6bb07)

Hi, just posted in Discord and someone said I should put it here.

The problem is I as a Master can drag and drop spells in this, but my player can't. If I give him Master or Auxiliar GM permit he can drag and drop spells, but not as a player.

**Comment by arbron** [comment]
Probably the same issue we had with item sheets awhile ago, where the default `canDragDrop` method just checks for if the user is GM, not whether the sheet is editable.
