### ISSUE TITLE
Wiki legend and system.attributes.hp.bonuses.level entry says it can be populated with any dice formula, it cannot

### ISSUE THREAD

**Issue by Krigsmaskine** [foundryvtt/dnd5e#4811]
legend says 

> [formula] - When formula is mentioned in this document it means this value can be populated with any dice formula. For example, Bless adds several effects with the Effect Value of 1d4. These fields always allow for the use of roll data.

but this entry does not accept dice formula

https://github.com/foundryvtt/dnd5e/wiki/Active-Effect-Guide#bonus-hp-for-each-character-level

**Comment by krbz999** [comment]
poke.
