### ISSUE TITLE
Integration with sw5e module

### ISSUE THREAD

**Issue by BSonPosh** [foundryvtt/dnd5e#4825]
Sorry if this isn't the correct place to reach out but I was hoping for some help. I am one of the developers on the sw5e module based on your dnd5e system. We are so happy with all you have done and really want adopt all the work you've done.

I was able to add a new bar for force points on the main sheet but cannot figure out for the life of me how to allow it update like the "Hit Points" bar.  

Is there anyone that can help? Below is a photo of the new bar. I would like to add the temp section and the ability to update the value.

![image](https://github.com/user-attachments/assets/5ccccf25-5b92-4ba3-abd0-abfc9a8ba093)

**Comment by JPMeehan** [comment]
The system implements it via a change listener

**Comment by BSonPosh** [comment]
I've got very little web dev experience. Can you elaborate a little or give me somewhere to start?

**Comment by unsoluble** [comment]
Sorry, we can't provide dev support in a ticket comment thread regardless, but definitely can't assist with the sw5e project in particular, for licensing reasons.

**Comment by BSonPosh** [comment]
I'm just looking for guidance but you can only do what you can do. Do you have a discord or anything?

**Comment by unsoluble** [comment]
Afraid we cannot assist with this in any capacity.

**Comment by BSonPosh** [comment]
Its a sad day when one open source project can't help another open source project because of a license but it is what is and its not your fault. Ticket closed.
