### ISSUE TITLE
Failed data preparation for `null` items property

### ISSUE THREAD

**Issue by MrVauxs** [foundryvtt/dnd5e#4837]
When opening an adventure (which has been made back in v10), a lot of errors may appear relating to 
```Failed data preparation for [UUID]. Cannot read properties of null (reading 'items')```

This is happening in 
```
Caused by: TypeError: Cannot read properties of null (reading 'items')
    at FeatData.prepareBaseData (abstract.mjs:470:54)
```

<img width="523" alt="NVIDIA_Overlay_VzjEzr3rkT" src="https://github.com/user-attachments/assets/e7d837de-48a3-42e1-8ac1-43ffda6d20f1">

Contact @vauxs on Discord for an example module, as this is being encountered in a premium module.

**Comment by Fyorl** [comment]
Does the adventure content need to be migrated then re-packed?

**Comment by MrVauxs** [comment]
Re-packing it does not remove the error, I will see if manually migrating them through the button will do anything.

**Comment by krbz999** [comment]
Just had a look at a different adventure module (Dungeons of Drakkenheim) and got a few thousand of these errors. This is a fully migrated adventure. Not sure if the error impacts anything, though. The uuids in the error are *inside* the adventure document.

**Comment by arbron** [comment]
Looks like this error is caused because the item's parent actor is a `BaseActor` instance at this point, rather than `Actor`, causing `item.actor` to return `null`. Some weirdness is going on in core with document preparation order in adventures.

**Comment by arbron** [comment]
Hmm, this is probably because the adventure document has embedded data fields containing `BaseActor` instances, but when they are loaded they initialize all of their embedded items as actual `Item` instances, causing all of the data preparation to be called on the items even when the actors themselves aren't properly prepared.
