### ISSUE TITLE
Reintroduce a way to roll item attacks with advantage and disadvantage through the API

### ISSUE THREAD

**Issue by MaterialFoundry** [foundryvtt/dnd5e#4843]
In previous versions it was possible to roll an item attack with advantage using:
```js
item.rollAttack({
  options: {
    advantage: true
  }
})
```
Maybe I'm missing something, but this no longer seems to be possible with the new activity system.

I've found a solution, I'm not sure if it's the best way, but it seems to work fine:
In `AttackActivity.rollAttack` change
```js
rollConfig.rolls = [{
  options: {
    ammunition: rollConfig.ammunition,
    attackMode: rollConfig.attackMode,
    criticalSuccess: this.criticalThreshold,
    mastery: rollConfig.mastery
  }
}].concat(config.rolls ?? []);
```
to
```js
rollConfig.rolls = [{
  options: {
    advantage: rollConfig.advantage,
    disadvantage: rollConfig.disadvantage,
    ammunition: rollConfig.ammunition,
    attackMode: rollConfig.attackMode,
    criticalSuccess: this.criticalThreshold,
    mastery: rollConfig.mastery
  }
}].concat(config.rolls ?? []);
```

**Comment by MaterialFoundry** [comment]
I don't want to create separate issues for each of these, but it looks like this also applies to ability checks, saves, tool checks, and possibly other rolls.

**Comment by arbron** [comment]
You can do this currently by passing advantage to the interior roll options object:

`rollSkill({ skill: "acr", rolls: [{ options: { "advantage": true }}] })`
