### ISSUE TITLE
Add option to override spellcasting ability on CastActivity

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#4851]
Currently the cast activity allows for overriding the spell's DC & attack bonus to a fixed value, or using the user's default spellcasting ability. There are certain places where a spell might be cast through an item using a specific ability, but without a fixed DC. The cast activity should be able to specify this.

**Comment by roth-michael** [comment]
Not sure whether this fits on this issue or would earn an issue of its own, but it would be nice if, in addition to selecting a custom Ability to use for the modifier, you could specify a specific _value_ to be used in place of `@mod` in any of the formulae. For instance, the Ring of Spell Storing "saves" the actual spellmod of the original caster to be used when the spell is re-cast from the ring.
