### ISSUE TITLE
Errors when opening Adventure Importer

### ISSUE THREAD

**Issue by Greatshock** [foundryvtt/dnd5e#4854]
## Issue description
Whenever adventure importer is opened, it logs a lot of errors like the ones shown in the screenshot. This happens with all the adventure modules I've tried, including like Phandelver and Below: The Shattered Obelisk (latest 1.2.1 version).
<img width="1385" alt="Screenshot 2024-12-09 at 9 52 31 PM" src="https://github.com/user-attachments/assets/983a4e61-a369-43b5-96d0-0476c6ea06fe">
## Report
Foundry Virtual Tabletop: Version 12 Stable, 12.331
Game System: dnd5e, 4.1.2
Active Modules: 1
Performance Mode: 2

OS: macOS 13.5.0 arm (64-bit)
Client: Google Chrome/131.0.6778.109
GPU: ANGLE (Apple, ANGLE Metal Renderer: Apple M1 Pro, Unspecified Version)
Max Texture Size: 16384

Scene: 9776.272108187935 x 12915 | Grid Size: 287 | Padding Percentage: 0.25
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 1
Largest Texture: 6300.439453125 x 8100 

Actors: 163 | Items: 252 | Journal Entries: 61 | Rollable Tables: 12 |
Playlists: 0 | Compendium Packs: 18 | Chat Messages: 2

World Scripts: 

/* -------------------------------------------- */
/*  World Data                                  */
/* -------------------------------------------- */

Actors: 163 | 4 MB
CardStacks: 0 | 120 B
Messages: 2 | 4 kB
CombatEncounters: 0 | 120 B
FogExplorations: 0 | 120 B
Folders: 76 | 29 kB
Items5e: 252 | 397 kB
Journal: 61 | 1 MB
Macros: 10 | 12 kB
Playlists: 0 | 120 B
RollTables: 12 | 37 kB
Scenes: 35 | 4 MB
WorldSettings: 7 | 6 kB
Users: 1 | 751 B

/* -------------------------------------------- */
/*  Compendium Data                             */
/* -------------------------------------------- */

"dnd5e.heroes": 12 Actors | 456 kB
"dnd5e.monsters": 331 Actors | 3 MB
"dnd5e.items": 872 Items | 1 MB
"dnd5e.tradegoods": 23 Items | 13 kB
"dnd5e.spells": 319 Items | 471 kB
"dnd5e.backgrounds": 3 Items | 6 kB
"dnd5e.classes": 12 Items | 61 kB
"dnd5e.subclasses": 12 Items | 19 kB
"dnd5e.classfeatures": 235 Items | 203 kB
"dnd5e.races": 34 Items | 49 kB
"dnd5e.monsterfeatures": 252 Items | 187 kB
"dnd5e.rules": 20 Journal Entries | 360 kB
"dnd5e.tables": 31 Rollable Tables | 44 kB
"dnd-phandelver-below.pbso-adventures": 1 Adventures | 2 MB
"dnd-phandelver-below.pbso-bestiary": 148 Actors | 1 MB
"dnd-phandelver-below.pbso-items": 164 Items | 139 kB
"dnd-phandelver-below.pbso-player-options": 40 Items | 50 kB
"dnd-phandelver-below.pbso-player-tables": 53 Rollable Tables | 60 kB

/* -------------------------------------------- */
/*  Active Modules                              */
/* -------------------------------------------- */

dnd-phandelver-below | 1.2.1 | "Phandelver & Below: The Shattered Obelisk" | "https://r2.foundryvtt.com/packages-public/dnd-phandelver-below/module.json"

**Comment by krbz999** [comment]
related: #4837
