### ISSUE TITLE
Adding Action to a Monster Adds Feature Instead

### ISSUE THREAD

**Issue by SudsyMcGee** [foundryvtt/dnd5e#4865]
![image](https://github.com/user-attachments/assets/e38f69ad-6ea4-44de-99a8-0bc85c61ee4a)

When add action button is clicked (red) it shouldnt create a feature it should create an action instead it creates a feature. See below

![image](https://github.com/user-attachments/assets/799a1441-f1e3-4bca-ade2-9704ab0eae4b)

**Comment by krbz999** [comment]
That's an issue with the sheet module you are using.

**Comment by kgar** [comment]
Tidy 5e Sheets developer here, confirming what krbz999 said--this is an issue with the sheet module.

Activities make it so it's no longer feasible to add active features without also adding an activity on your behalf. This is not something Tidy will be doing, so until the UI is updated, it will function as above.

Tidy will be moving to a One Add Button setup like the default sheets, which is intended to solve this problem by presenting options to add Class / Subclass / Feature, where Features start as passive until they are given activities. Github issue here: https://github.com/kgar/foundry-vtt-tidy-5e-sheets/issues/763

In fact, this reported behavior is mentioned in the cross-post link above.

I recommend closing the issue on this repo; the issue on the Tidy repo will now have a cross-post reference to this report so we can review these details while working on the fix.
