### ISSUE TITLE
Allow for the DC of a passive skill enricher to be optional

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#4866]
Use case being the ability to make an enricher for text such as "the party member with the highest passive Perception". When using an enricher without a DC (`[[/skill perception passive]]`), it displays as "DC undefined passive Wisdom (Perception)".

It would be nice to be able to use an enricher to simply display a passive skill without a need for a DC.

**Comment by roth-michael** [comment]
Comment
