### ISSUE TITLE
Link to item with activity does not work if activity name has more than 1 word

### ISSUE THREAD

**Issue by Greatshock** [foundryvtt/dnd5e#4872]
The bug can be reproduced with Rogue's Improved Cunning Strike in PHB 2024 official module. In the Foundry Note section there's a link to a specific activity called Cunning Sneak attack:

```html
<section class="secret" id="secret-8yelsP7k8fXkEA5W">
    <p><strong>Foundry Note</strong></p>
    <p>After using Cunning Strike effects use the [[/item Cunning Strike activity=Cunning Sneak Attack]]{Cunning Sneak Attack} activity. It will prompt you to select how many dice you expended on effects and deduct them from your Sneak Attack roll automatically.</p>
    <p>You can control the damage type in the damage roll dialog box.</p>
</section>
```

However, when link is clicked, warning is shown saying there is not such item:
<img width="853" alt="Screenshot 2024-12-12 at 11 08 12 PM" src="https://github.com/user-attachments/assets/961b3530-85b0-4d0f-9863-98d51a189b08" />

I believe the reason for that is that only first word from activity name is taken as value for `data-roll-activity-name` attribute:
<img width="1188" alt="Screenshot 2024-12-12 at 11 11 25 PM" src="https://github.com/user-attachments/assets/9f16480f-495c-4ca2-86c8-1c5fdb419221" />

**Comment by arbron** [comment]
You have to use quotes around it: `[[/item Cunning Strike activity="Cunning Sneak Attack"]]`, multiple words without quotes generally only works for unlabeled properties such as the item name.

**Comment by Greatshock** [comment]
> You have to use quotes around it: `[[/item Cunning Strike activity="Cunning Sneak Attack"]]`, multiple words without quotes generally only works for unlabeled properties such as the item name.

Oh... So, that's an issue in the PHB module itself then. Thanks

I think we can close this issue then and file the one on player's handbook content module.
