### ISSUE TITLE
When using an array-form for additional damage parts in an enchantment, allow for multiple damage types

### ISSUE THREAD

**Issue by krbz999** [foundryvtt/dnd5e#4880]
While possible when using `system.damage.parts | Add | {types: [...], number: 1, denomination: 6}`, it would be good if multiple damage types could also be allowed in the array form such as:
```
system.damage.parts | Add | [["1d6", ["acid", "cold", "fire"]]]
```

**Comment by arbron** [comment]
I doubt we will be adding improvements to the array form since it is only there for backwards compatibility.

**Comment by krbz999** [comment]
> I doubt we will be adding improvements to the array form since it is only there for backwards compatibility.

Based tbh.
