### ISSUE TITLE
Errors when exporting Actors to an Adventure

### ISSUE THREAD

**Issue by boss-loot** [foundryvtt/dnd5e#4905]
How to reproduce:

Create a new world with D&D 5e system.
Create a new module, "Test Module" with an **Adventure Compendium** having dnd5e as system requirement.
Import a new Actor from Monsters (SRD) dnd5e Compendium.
Create a new Adventure and add the Actor to the Adventure.

In my test I have added the Acolyte and these are the console errors:
![console-error-foundry](https://github.com/user-attachments/assets/122cd606-8202-450d-aa22-73b89c650ee8)

If it helps I can upload the test module used.

**Comment by boss-loot** [comment]
Foundry v12.331
DnD v4.1.2

**Comment by thatlonelybugbear** [comment]
to be fixed: https://github.com/foundryvtt/dnd5e/issues/4837
