### ISSUE TITLE
HTML Options and dark mode

### ISSUE THREAD

**Issue by DragonHale** [foundryvtt/dnd5e#4939]
Hello
The HTML options mentioned in the wiki (https://github.com/foundryvtt/dnd5e/wiki/System-HTML), have a very bad contrast when it comes to the dark mode. It is borderline unreadable. I was wondering if it can be fixed at all, or if a new option compatible with dark mode can be added?
![{498A273C-69A1-447F-AECD-F4B85774FD55}](https://github.com/user-attachments/assets/2ea50522-08cc-404a-9fce-b03dcf85e9b5)

**Comment by arbron** [comment]
Seems like it is only a problem with the "Narrative" option, the other two styles work fine in dark mode.
