### ISSUE TITLE
Item icons with parens in their image filename don't display in certain cases

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#681]
Originally in GitLab by @unsoluble1

(0.6.6 / 0.96)

This might actually be a core Foundry thing, but I figure you can sort that out. :)

If an item's image has parentheses in its filename, the image won't display when in lists on the character sheet (like in `Weapons` or `Features` etc.). It'll show fine in the item's own app window though.

![image](https://gitlab.com/foundrynet/dnd5e/uploads/702b12b5d4b20a22b9fa0fecd0b35303/Races-1.jpg)

(Screenshot has a module in effect, but it doesn't matter in this case. Also note that it's the _filename_ that breaks things here, not the item name.)

**Comment by unsoluble** [comment]
@aaclayton Looks like this one is back, but in a slightly different form — now it's _apostrophes_ anywhere in the filepath that cause the sheet icon to fail to render (and perhaps other special characters, haven't had a chance to test more).

Looks like it's affecting any game system that was (I'm guessing) originally forked from dnd5e — same results in `pf2e` and `ose`, but things render fine in `pf1e`. No console errors.

`dnd5e`:
<img width="588" alt="CleanShot 2022-09-21 at 23 33 44@2x" src="https://user-images.githubusercontent.com/801582/191675765-9a33c438-c06a-4fa9-b56f-814570e4940e.png">

`pf2e`:
<img width="634" alt="CleanShot 2022-09-21 at 23 32 52@2x" src="https://user-images.githubusercontent.com/801582/191675763-55b957e0-ed08-4096-b04f-4ad0cd3109f3.png">

`pf1e`:
<img width="603" alt="CleanShot 2022-09-21 at 23 34 42@2x" src="https://user-images.githubusercontent.com/801582/191675761-65a80717-f8c6-4294-adb7-2f2b4a60ff0b.png">

**Comment by aaclayton** [comment]
I'm guessing the same issue as https://github.com/foundryvtt/foundryvtt/issues/8222

**Comment by Fyorl** [comment]
This seems to have been addressed by core changes now in v10 which urlencode apostrophe characters in filenames.
