### ISSUE TITLE
Native item container support

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#729]
Originally in GitLab by @saethone

Native support for item containers such as backpacks and belt pouches, with weight tracking and visibility of items from the item tab (including collapsing and expanding to view inside, instead of opening a separate item sheet as is the case currently through the support of another module)

(example of a backpack in pathfinder 2e system)
![image](https://gitlab.com/foundrynet/dnd5e/uploads/b0ff62d0681486e2b273276733f21ac7/image.png)

**Comment by Ikaguia** [comment]
@arbron is this still in progress? Last update seems to be from july 2023. If you are busy with other stuff, I could try and see if I can do it

**Comment by Fyorl** [comment]
> @arbron is this still in progress? Last update seems to be from july 2023. If you are busy with other stuff, I could try and see if I can do it

It is still in progress, and should be ready for 2.5, but thank you for the offer
