### ISSUE TITLE
Allow reverse transformation option for Unlinked Tokens

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#761]
Originally in GitLab by @Kandashi

Currently only Linked Tokens can have a polymorph/wildshape reversed, which can be very frustrating trying to remember hp/item uses/recharges/initiative for an unlinked token if "offensivley polymorphed" by a PC.

Possibly store the actorData of the original token seperatly from the actorData of the new polymorph form?

**Comment by Fyorl** [comment]
I believe this was implemented in #1840
