### ISSUE TITLE
Compendium items missing Active Effects

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#797]
Imported from Gitlab

**Comment by MotoMoto1234** [comment]
The following items need either entire effects or an edit to them:

Belt of Cloud Giant Strength: system.abilities.str.value | Upgrade | 27    (Needs the ae)
Belt of Fire Giant Strength: system.abilities.str.value | Upgrade | 25    (Needs the ae)
Belt of Frost Giant Strength: system.abilities.str.value | Upgrade | 23    (Needs the ae)
Belt of Hill Giant Strength: system.abilities.str.value | Upgrade | 21    (Needs the ae)
Belt of Storm Giant Strength: system.abilities.str.value | Upgrade | 29    (Needs the ae)
Boots of Striding and Springing: system.attributes.movement.walk | Upgrade | 30    (Needs the ae)
Boots of Winterlands: system.traits.dr.value | ADD | cold    (Needs the ae)
Bracers of Archery: system.traits.weaponProf.custom | ADD | Longbow; Shortbow    (Needs the ae)
Ioun Stone of Agility: system.abilities.dex.value | ADD | +2    (Needs the ae)
Ioun Stone of Fortitude: system.abilities.con.value | ADD | +2    (Needs the ae)
Ioun Stone of Insight: system.abilities.wis.value | ADD | +2    (Needs the ae)
Ioun Stone of Intellect: system.abilities.int.value | ADD | +2    (Needs the ae)
Ioun Stone of Leadership: system.abilities.cha.value | ADD | +2    (Needs the ae)
Ioun Stone of Mastery: system.attributes.prof | ADD | +1    (Needs the ae)
Ioun Stone of Protection: system.attributes.ac.bonus | Add | +1    (Needs the AE)
Ioun Stone of Strength: system.abilities.str.value | ADD | +2    (Needs the ae)
Ring of Protection needs:  system.bonuses.abilities.save | Add | +1    (Missing this key in ae)
Stone of Good Luck needs: system.bonuses.abilities.save | Add | +1    (Missing this key in ae)
