### ISSUE TITLE
Agree upon a schema for tracking effects which provide advantage or disadvantage to a certain type of roll.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#809]
I don’t think that the core dnd5e system will ever automate the choice of advantage/disadvantage to a dice roll. However, we can have a discussion about how to store/record that data so that modules can use it to perform that type of automation.

**Tentative Proposal**

Step 1 - agree on a taxonomy of roll types which are tracked in an object like:

```js
advantages: {
  "check:skill:ath": 1, // 1 = advantage
  "check:skill:ste": -1, // -1 = disadvantage
  "attack:mwak": 1,
  "check:save:str": 1,
  "check:test:str": 1
};
```

Step 2 - Which could then be configured on an active effect as:

![image](https://gitlab.com/foundrynet/dnd5e/uploads/3aaf2d26b47996676ca5d28496fac23e/image.png)

**Comment by Ikaguia** [comment]
Was this ever agreed upon or was is just abandoned?

**Comment by revilowaldow** [comment]
Would love to see this support labels on the new character sheet in a similar style to D&D beyond

**Comment by Fyorl** [comment]
The schema is now in place with the implementation of the `RollConfigField`.
