### ISSUE TITLE
Support an option so that an action can designate a spell slot as its target for automatic resource consumtion.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#818]
Originally in GitLab by @Angor-de-Redjak

Hello!

I play in an AU/system using D&D5 SRD.

In this game there is a ranger's action which allow to spend a spell slot to make an arrow shot magical and inflicts more damage.
I would like to automatize this action but I can't choose a spell slot as a consumable resource for the time being.

Would it be possible to implement this?

While I'm at it, do you think it would be possible to do like "damage formula", a + button adding a new line, for the consumption of resources?
I could set this way spell slot and arrow consumption.

Thanks for reading me!

**Comment by arbron** [comment]
Been possible for awhile.
