### ISSUE TITLE
Items cannot be sorted on the Default 5e NPC Sheet

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#824]
Originally in GitLab by @joseph.spandrusyszyn

Moving Features or Spells around in the NPC sheet to reorder them doesn't work. They also cannot be moved through macros/modules directly changing the underlying sort value.

Sorting works fine on the Default Character Sheet.

```
Foundry: 0.7.7
DnD5e: 1.1.1
Active Modules: None
```

**Comment by Fyorl** [comment]
I cannot reproduce this anymore. Since it's a very old issue, I'm assuming it's been fixed since.
