### ISSUE TITLE
Allow action recharge property for equipment and weapons, not just features

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#826]
Originally in GitLab by @MS-PBS

I don't think there's any good reason why weapons and other items couldn't have a d6 recharge property. Most of the time, when I'm preparing an NPC, I add a breath weapon as a weapon and after filling everything out I realise there is no recharge property for weapons, so I have to remove it and remake it as a feature. Another example: I gave one of my players a sword that can do area damage on a d6 recharge, and we have to keep track of that manually.

**Comment by hakr14** [comment]
I believe this should now be closed? Possible is 4.0.
