### ISSUE TITLE
Visual highlight on sheet item hover does not match clickable region

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#829]
Originally in GitLab by @TheGiddyLimit

See below:

![image](https://gitlab.com/foundrynet/dnd5e/uploads/3abe152e3bc8e533bfe09fb438285e15/region.webm)

(Although masked by the yellow blob from my recorder, ) the item name gains a highlight on hover, and the icon on the left turns to the "rollable" dice, despite the mouse not yet hovering over the clickable region. The clickable region should be expanded to match the height of the item row, to avoid the feeling of a "stuck" item where clicks appear to have no effect.

**Comment by Fyorl** [comment]
With some help I was able to reproduce this so I've implemented a proper fix.
