### ISSUE TITLE
The Avatar of Death monster has incorrect CR and XP

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#861]
Originally in GitLab by @captain-yoshi

The Monster `Avatar of Death` has incorrect CR (should be an En or EM dash —) and have 0 XP per DMG pg. 164.

Is this monster really in the SRD? It is not in the SRD (Basic Rules) of DnD Beyond (It comes with the DMG). And I cannot see this monster in any website that talks about DnD5e SRD.

**Comment by Rabulias** [comment]
I think the DMG made a mistake making the Avatar of Death's CR as a dash. The point is the Avatar of Death is worth 0 XP. The SRD, the Monster Manual (p.9) and even the DMG itself (p.275) all state that a CR 0 creature is worth 0 or 10 XP. So maybe we need two different CR 0 entries?
CR 0 (0 XP) (a new entry, used for the Avatar of Death, and maybe others)
CR 0 (10 XP) (a relabel of the existing entry)

**Comment by krbz999** [comment]
> So maybe we need two different CR 0 entries?

Alternatively, allow for overriding the XP value of a creature such that it is not necessarily derived from its CR. It could work identically to how Hit Point maximum of a `character` is derived (if `null`) but can be overridden.

**Comment by Fyorl** [comment]
Now that NPC CR is a `nullable` field, this creature should probably have a CR of `null`.
