### ISSUE TITLE
Feature request: Display actor resources on NPC sheets dynamically

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#868]
Originally in GitLab by @stwlam

Currently the NPC sheet template is hard-coded with their legendary/lair resources. One can have additional resources displayed with a `renderSheet` hook and some DOM tinkering, but doing so causes handlebars to go haywire when the user edits the cloned input fields. If the NPC sheet displayed resources in the same way as skills (perhaps prioritizing the legendary resources in the ordering so they always appear first), a module could add a resource to an NPC actor and see it reflected in the sheet automatically.

In my case the solution was to override the NPC sheet and serve out a custom template, which for a module is a bit far-reaching for such a limited purpose.

**Comment by Rabulias** [comment]
In light of DND5E 3.X, is this still needed? Maybe I misunderstand the request.
