### ISSUE TITLE
Reliable Talent is not presently working with Thieves' Tools

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#900]
Originally in GitLab by @taelnia

Rogues gain automatic proficiency with thieves' tools (and are able to choose them for expertise as well).

PHB-96: Reliable Talent is applicable:
Whenever you make an ability check that lets you add your proficiency bonus

PHB-154: Thieves' tools:
Proficiency with these tools lets you add your proficiency bonus to any ability checks you make to disarm traps or open locks.

We recently set up a foundryvtt game using the dnd5e system and noticed during testing that this ability was not calculating correctly.

**Comment by nicolaslandoni** [comment]
This looks like it should be as simple as adding a line around here:
https://github.com/foundryvtt/dnd5e/blob/dcdb5894a98f9a54d613e4e63adb96de6ea94654/module/documents/actor/actor.mjs#L1149

      _reliableTalent: this.getFlag("dnd5e", "reliableTalent"),_
