### ISSUE TITLE
Separate healing and temporary healing "damage" types into a separate definition construct which can be contextually shown depending on the nature of the ability in question.

### ISSUE THREAD

**Issue by zeel01** [foundryvtt/dnd5e#904]
Originally in GitLab by @zeel01

When an item has the "Action Type" of "Healing" under the "Healing Formula" there is still a <select> with all *damage* types available which includes healing and temporary healing. For other action types, the "Damage Formula" has all damage types available which also includes both healing options.

Damage types and healing types should be separated into different lists, with only healing types available for the healing action type, and only damage types available for non-healing action types.

**Comment by arbron** [comment]
Type lists in activities work this way now.
