### ISSUE TITLE
Provide a helper method which can clean/scrub an existing Actor or Item, only keeping the valid properties which should exist in its defined data model.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#942]
Originally in GitLab by @tposney

I have a number of actors (player characters) that have been around for more than a year (yes I don't kill player characters often enough) and their actor._data is a bit of a mess. They have all of the derived fields that used to be stored in data before the _data split.
Of course the derived fields are no longer updated and can be confusing at times. I wonder if it is a good idea as part of a dnd5e update to remove the old derived fields from the _data so that things can be nice and clean.

**Comment by arbron** [comment]
With the new data models the `dnd5e.migrations.refreshCompendium` and `dnd5e.migrations.refreshAllCompendiums` methods perform this job for compendiums, but a third method should probably be added for world documents.
