### ISSUE TITLE
Make Skill Checks for Features and Items Act Like Saving Throws

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#947]
Originally in GitLab by @Matsozetex

Currently in this system you either have to save against a DC or attack against an AC. However in the newly released Tasha's Cauldron of Everything and probably other examples there are instances where you have to use a skill against a DC to save. I would request that under the Saving Throw section of an item/feature there be a Skill Check line that includes which skill can it prompt vs DC.
![image](https://gitlab.com/foundrynet/dnd5e/uploads/7afac76df304ae78f9ebe5d31daa46c6/Examples.png)

**Comment by arbron** [comment]
Handled by `CheckActivity`.
