### ISSUE TITLE
Provide an option for rolling initiative with advantage or disadvantage, as well as potentially including additional circumstantial bonuses in the initiative roll.

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#950]
Originally in GitLab by @tagnullde1

Right now there doesn't seem to be a way to roll initiative with Advantage or Disadvantage via the Charactersheet.
Maybe consider this to be added in a future release. 

Please also refer to this conversation: https://github.com/Moerill/fvtt-mars-5e/issues/65

Foundry: 0.7.9
DnD5e: 1.2.2
Tidy5e: 0.4.8

**Comment by krbz999** [comment]
Related: #1994
