### ISSUE TITLE
In character sheet, split special senses with semi-colon

### ISSUE THREAD

**Issue by aaclayton** [foundryvtt/dnd5e#968]
Originally in GitLab by @CDeenen

On the attributes page of the character sheet you can add custom attributes with the 'special' field such as for languages, damage immunities, etc. 
For pretty much all of these, you can split multiple attributes with a semi-colon, however, this does not work for 'Senses'. Could this be added?

**Comment by Hoppyhob** [comment]
Hey I can work on this issue.
